#!/bin/sh
NAME="ncurses"
VERSION="6.3"
SOURCES="https://ftp.gnu.org/gnu/ncurses/ncurses-$VERSION.tar.gz"
SHA256SUM="97fc51ac2b085d4cde31ef4d2c3122c21abc217e9090a43a30fc5ec21684e059  ncurses-6.3.tar.gz"
DESCRIPTION="ncurses library allows you to make TUI applications."

build() {
    [ ! -d "ncurses-$VERSION" ] && tar -xvf ncurses-$VERSION.tar.gz
    cd ncurses-$VERSION || exit 1
    sed -i s/mawk// configure
    mkdir build
    cd build || exit 1
        ../configure
        make -C include
        make -C progs tic
    cd ..
    ./configure --prefix=/usr                \
                --build=$(./config.guess)    \
                --host=x86_64-pc-linux-gnu   \
                --mandir=/usr/share/man      \
                --with-manpage-format=normal \
                --with-shared                \
                --without-debug              \
                --with-termlib               \
                --without-ada                \
                --without-normal             \
                --disable-stripping          \
                --enable-widec               \
                --with-versioned-syms 
    make
    make DESTDIR=$ROOT TIC_PATH=$(pwd)/build/progs/tic install
    echo "INPUT(-lncursesw)" > $ROOT/usr/lib/libncurses.so
    cd $ROOT/usr/lib || exit 1
    ln -s libncursesw.so.6 libtinfo.so.6
    ln -s libncursesw.so.6 libtinfo.so
}
