#!/bin/sh
NAME="ncurses"
RELEASE="1"
VERSION="6.3"
SOURCES="https://ftp.gnu.org/gnu/ncurses/ncurses-$VERSION.tar.gz"
SHA256SUM="97fc51ac2b085d4cde31ef4d2c3122c21abc217e9090a43a30fc5ec21684e059  ncurses-6.3.tar.gz"
DESCRIPTION="ncurses library allows you to make TUI applications."

build() {
    [ ! -d "ncurses-$VERSION" ] && tar -xvf ncurses-$VERSION.tar.gz
    cd ncurses-$VERSION || exit 1
    # Taken from KISS Linux, LICENSE here https://github.com/kisslinux/repo/blob/master/LICENSE 
   ./configure \
    --prefix=/usr \
    --mandir=/usr/share/man \
    --enable-pc-files \
    --disable-rpath-hack \
    --with-pkg-config-libdir=/usr/lib/pkgconfig \
    --with-shared \
    --enable-widec \
    --without-ada \
    --without-tests \
    --without-debug \
    --without-cxx-binding

    make
    make install
    for lib in ncurses form panel menu; do
    	rm -f "$ROOT/usr/lib/lib${lib}.so"
   	printf '%s\n' "INPUT(-l${lib}w)" > "$ROOT/usr/lib/lib${lib}.so"
    	chmod 755 "$ROOT/usr/lib/lib${lib}.so"
    	ln -sf "lib${lib}w.a" "$ROOT/usr/lib/lib${lib}.a"
     done

	# Some packages look for libcurses instead of libncurses when building.
	printf '%s\n' "INPUT(-lncursesw)" > "$ROOT/usr/lib/libcursesw.so"
	ln -s libncurses.so "$ROOT/usr/lib/libcurses.so"

}
