#!/bin/sh
NAME="llvm"
RELEASE="2"
VERSION="19.1.6"
SOURCES="https://github.com/llvm/llvm-project/releases/download/llvmorg-$VERSION/llvm-project-$VERSION.src.tar.xz"
DEPENDS_LLVM="gcc"
BUILD_DEPENDS="cmake ninja"
BUILD_DEPENDS_LLVM+="binutils"
B2SUM="b35ab0c754f28c850ac6fd4ee584e963b1d5cf06885c59827ee4ac11f93cde5b8e0268fbed560839137de2c495c9da2b889331cd12a8a02958d8e0cbdbed2607"
DESCRIPTION="The LLVM Project is a collection of modular and reusable compiler and toolchain technologies."


build() {
    cmake -S llvm -B build -DCMAKE_BUILD_TYPE=Release \
        -DBUILD_SHARED_LIBS=1 \
        -DLLVM_ENABLE_RTTI=ON \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DLLVM_INSTALL_UTILS=ON \
        -DLLVM_INCLUDE_BENCHMARKS=OFF \
        -DLLVM_BINUTILS_INCDIR=/usr/include \
        -DLLVM_ENABLE_PROJECTS="lld;clang;libclc" \
        -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;compiler-rt;libunwind" \
        -G Ninja
    ninja -C build -j$(nproc)
}

package() {    
    DESTDIR="$ROOT" ninja -C build install
}


