#!/bin/sh
NAME="llvm"
RELEASE="2"
VERSION="19.1.1"
SOURCES="https://github.com/llvm/llvm-project/releases/download/llvmorg-$VERSION/llvm-project-$VERSION.src.tar.xz"
DEPENDS_LLVM="gcc"
BUILD_DEPENDS="cmake ninja"
BUILD_DEPENDS_LLVM+="binutils"
B2SUM="7c9250f99c8e5ae2097e89269ebf5bfdfb0fba8f67ab934377d24030c985013fe5475d0c9bd6d60a679e169772ad1723bc6e44ff9e4c7aed5627b9f1f1a2477a"
DESCRIPTION="The LLVM Project is a collection of modular and reusable compiler and toolchain technologies."


build() {
    cmake -S llvm -B build -DCMAKE_BUILD_TYPE=Release \
        -DBUILD_SHARED_LIBS=1 \
        -DLLVM_ENABLE_RTTI=ON \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DLLVM_INSTALL_UTILS=ON \
        -DLLVM_INCLUDE_BENCHMARKS=OFF \
        -DLLVM_BINUTILS_INCDIR=/usr/include \
        -DLLVM_ENABLE_PROJECTS="lld;clang;libclc" \
        -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;compiler-rt;libunwind" \
        -G Ninja
    ninja -C build -j$(nproc)
}

package() {    
    DESTDIR="$ROOT" ninja -C build install
}


