#!/bin/sh
NAME="micro"
RELEASE="1"
VERSION="2.0.14"
SOURCES="https://github.com/zyedidia/micro/archive/refs/tags/v$VERSION.tar.gz"
BUILD_DEPENDS="go gmake"
DEPENDS=""
SHA256SUM="40177579beb3846461036387b649c629395584a4bbe970f61ba7591bd9c0185a"
DESCRIPTION="micro is a terminal-based text editor that aims to be easy to use and intuitive"
build() {
	make build
}

package() {
    env install -vD micro "$ROOT/usr/bin/micro"
}
