#!/bin/sh
NAME="xdg-desktop-portal-gnome"
RELEASE="1"
VERSION="49.0"
SOURCES="https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/archive/$VERSION/xdg-desktop-portal-gnome-$VERSION.tar.gz"
DEPENDS="gnome-desktop gnome-keyring libadwaita xdg-desktop-portal-gtk xdg-desktop-portal"
BUILD_DEPENDS="meson"
SHA256SUM="98b772b94a39eaef4cc2555ed2fd80839a42817fe1d1c8c1e06091f09c4146b3"
DESCRIPTION="GNOME backend for xdg-desktop-portal"

build() {
    
    if ! command -v systemctl > /dev/null; then
        extraArgs="-Dsystemduserunitdir=/opt/deleteme"
    fi

    meson setup $extraArgs \
    --prefix=/usr \
    --buildtype=release \
    build

    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
    if ! command -v systemctl > /dev/null; then
        rm -rf "$DESTDIR/opt/deleteme"
    fi
}
