#!/bin/sh
NAME="glibc"
RELEASE="5"
VERSION="2.41"
BUILD_DEPENDS="gmake"
SOURCES="https://ftp.gnu.org/gnu/glibc/glibc-$VERSION.tar.xz"
DEPENDS="grep bash gawk bison m4"
BUILD_DEPENDS="perl texinfo"
DEPENDS_AARCH64_LINUX_GNU_GLIBC+="aarch64-linux-gnu-linux-headers"
B2SUM="4da62f489ba7a95bb069c2cfea8cf78e4d37e3a5f7e1736239670ba1dca12b69aa77bd00ced078c27d91b1e622c58cbd70258161a9d18c5b3bcc95863b8d744d"
DESCRIPTION="The GNU C library"

common_build() {
    export LD_LIBRARY_PATH=$(echo $LD_LIBRARY_PATH | sed 's/^://;s/:$//;s/:://g')
    export CC=$1-gcc
    export CXX=$1-g++
    
    echo "==OLD ENVIRONMENT=="
    env
    echo "==END OLD ENVIRONMENT=="

    mkdir -v build
    cd build || exit

    if [ "$1" != "$(uname -m)-linux-gnu" ]; then
	target="--target=$1"
	host="--host=$1"
	build="--build=$(uname -m)-linux-gnu"
	headers="/usr/$1/include"
	# taken from arch https://gitlab.archlinux.org/archlinux/packaging/packages/aarch64-linux-gnu-glibc/-/blob/main/PKGBUILD?ref_type=heads
	extraArgs="--includedir=/include --libdir=/lib --libexecdir=/lib"
   else
	host="--host=$(uname -m)-linux-gnu"
	build="--build=$(uname -m)-linux-gnu"
	headers="/usr/include"
    fi

    ../configure $extraArgs \
      --prefix=/usr \
      $host \
      $build \
      $target \
      --enable-kernel=4.14 \
      --enable-stack-protector=strong \
      --with-headers=$headers \
      --disable-crypt
    
    if [ "$1" != "$(uname -m)-linux-gnu" ]; then
	echo 'build-programs=no' >> configparms
    fi

    make || exit 1
    ls

    echo "==AFTERBUILD ENVIRONMENT=="
    env
    echo "==END AFTERBUILD ENVIRONMENT=="
}

build_aarch64_linux_gnu_glibc() {
    common_build "aarch64-linux-gnu"
}

package_aarch64_linux_gnu_glibc() {
     cd build
     ls
     make install_root="$ROOT/usr/aarch64-linux-gnu" install
     rm -rf "$ROOT/usr/share/info/dir"
     rm -f "$ROOT/etc/ld.so.cache"
     for file in tzselect zdump zic; do
         rm -f "$ROOT/usr/bin/$file"
     done
      
}

build() {
    common_build "$KPKG_TARGET"
}

package() {
    echo "==PACKAGE ENVIRONMENT=="
    env
    echo "==END PACKAGE ENVIRONMENT=="
    ls
    make DESTDIR=$ROOT install || exit 1
    rm -rf "$ROOT/usr/share/info/dir"
    rm -f "$ROOT/etc/ld.so.cache"
    for file in tzselect zdump zic; do
        # to make sure we delete from every directory
        rm -f "$ROOT/usr/bin/$file"
        rm -f "$ROOT/usr/sbin/$file"
        rm -f "$ROOT/bin/$file"
        rm -f "$ROOT/sbin/$file"
    done
}

postinstall() {
    mkdir -p $ROOT/usr/lib/locale
    localedef --prefix=$ROOT -i C -f UTF-8 C
}
