#!/bin/sh
NAME="glibc"
RELEASE="1"
VERSION=2.37
SOURCES="https://ftp.gnu.org/gnu/glibc/glibc-$VERSION.tar.xz"
SHA256SUM="2257eff111a1815d74f46856daaf40b019c1e553156c69d48ba0cbfc1bb91a43  glibc-2.37.tar.xz"
DESCRIPTION="The GNU C library"

build() {
    mkdir -v build
    cd build || exit
    ../configure --prefix=/usr --disable-sanity-checks --host=x86_64-pc-linux-gnu --enable-kernel=3.2 --disable-crypt \
        libc_sv_slibdir=/usr/lib
    make || exit
}

install() {
    make DESTDIR=$ROOT install
}
