#!/bin/sh
NAME="glibc"
RELEASE="2"
VERSION="2.38"
SOURCES="https://ftp.gnu.org/gnu/glibc/glibc-$VERSION.tar.xz"
BUILD_DEPENDS="gcc"
DEPENDS="grep gawk bison m4"
SHA256SUM="fb82998998b2b29965467bc1b69d152e9c307d2cf301c9eafb4555b770ef3fd2"
DESCRIPTION="The GNU C library"

build() {
    export CC=gcc
    export CXX=g++
    mkdir -v build
    cd build || exit
    ../configure \
      --prefix=/usr \
      --host=x86_64-pc-linux-gnu \
      --enable-kernel=4.14 \
      --enable-stack-protector=strong \
      --with-headers=/usr/include \
      --disable-crypt \
        libc_sv_slibdir=/usr/lib
    make || exit
}

package() {
    cd build
    make DESTDIR=$ROOT install
}
