#!/bin/sh
NAME="ibus"
RELEASE="1"
VERSION="1.5.33"
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/ibus/ibus/releases/download/$VERSION/ibus-$VERSION.tar.gz"
DEPENDS="dconf gobject-introspection libnotify iso-codes vala gtk3 gtk4 libnotify"
SHA256SUM="58941c9b8285891c776b67fb2039eebe0d61d63a51578519febfc5481b91e831"
DESCRIPTION="ibus"

build() {
    
    if ! command -v systemd > /dev/null; then
      extraArgs="--disable-systemd-services"
    fi
    
    # From BLFS
    kpkgConfigure $extraArgs --prefix=/usr \
                --sysconfdir=/etc \
                --disable-python2 \
                --disable-gtk2 \
                --disable-emoji-dict \
                --disable-unicode-dict
                
    rm -f tools/main.c
    make
}

package() {
    make DESTDIR=$ROOT install
}
