#!/bin/sh
NAME="gjs"
RELEASE="1"
VERSION="1.77.90"
SOURCES="https://gitlab.gnome.org/GNOME/gjs/-/archive/$VERSION/gjs-$VERSION.tar.gz"
DEPENDS="glib js115 libffi cairo dbus gobject-introspection readline dconf"
BUILD_DEPENDS="meson"
SHA256SUM="2c159cffa2d2deac47b502de7b60865340d12d4db9dc85c3582945c004169b4e  gjs-1.77.90.tar.gz"
DESCRIPTION="Javascript bindings for GNOME"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    --wrap-mode=nofallback \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
