#!/bin/sh
NAME="gjs"
RELEASE="1"
VERSION="1.86.0"
SOURCES="https://gitlab.gnome.org/GNOME/gjs/-/archive/$VERSION/gjs-$VERSION.tar.gz"
DEPENDS="glib js115 libffi cairo dbus gobject-introspection readline dconf"
BUILD_DEPENDS="meson"
SHA256SUM="c854ed3c76127361b2c6fa3c4e0199a6d687b5e47cdac3be837c6017c305d686"
DESCRIPTION="Javascript bindings for GNOME"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    --wrap-mode=nofallback \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
