#!/bin/sh
NAME="gjs"
RELEASE="1"
VERSION="1.78.3"
SOURCES="https://gitlab.gnome.org/GNOME/gjs/-/archive/$VERSION/gjs-$VERSION.tar.gz"
DEPENDS="glib js115 libffi cairo dbus gobject-introspection readline dconf"
BUILD_DEPENDS="meson"
SHA256SUM="e22e5f18085b1c4cc96e527882dd693f1fabdcd3a1d5152edd8c91cc0d17e2b3"
DESCRIPTION="Javascript bindings for GNOME"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    --wrap-mode=nofallback \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
