#!/bin/sh
NAME="nim"
RELEASE="1"
VERSION="1.6.14"
SOURCES="https://nim-lang.org/download/nim-$VERSION.tar.xz"
SHA256SUM="d070d2f28ae2400df7fe4a49eceb9f45cd539906b107481856a0af7a8fa82dc9  nim-1.6.14.tar.xz"
DESCRIPTION="The Nim programming language"

build() {
        sh build.sh
        bin/nim c --nimcache=/tmp/kpkg/srcdir/cache koch
        ./koch boot -d:release --nimcache=/tmp/kpkg/srcdir/cache
        ./koch tools --nimcache=/tmp/kpkg/srcdir/cache
        ./koch nimble --nimcache=/tmp/kpkg/srcdir/cache
}

install() {
  mkdir -p "$ROOT/usr/include" "$ROOT/usr/bin" "$ROOT/etc/nim" "$ROOT/usr/lib"
  cp -r lib/ "$ROOT/usr/lib/nim"
  cp -r compiler/ "$ROOT/usr/lib/nim"
  cp -rf config/* -t "$ROOT/etc/nim"
  cp -rf bin/* -t "$ROOT/usr/bin"
  cp -rf "$ROOT/usr/lib/nim/"*.h "$ROOT/usr/include"
  rm -rf "$ROOT/nim"
}
