#!/bin/sh
NAME="nim"
RELEASE="1"
VERSION="2.0.0"
SOURCES="https://nim-lang.org/download/nim-$VERSION.tar.xz"
SHA256SUM="bd6101d840036fb78e93a69df6cf3f9fd0c21cd754b695ff84a3b4add8ed0af7  nim-2.0.0.tar.xz"
DESCRIPTION="The Nim programming language"

build() {
        sh build.sh
        bin/nim c --nimcache=/tmp/kpkg/srcdir/cache koch
        ./koch boot -d:release --nimcache=/tmp/kpkg/srcdir/cache
        ./koch tools --nimcache=/tmp/kpkg/srcdir/cache
        ./koch nimble --nimcache=/tmp/kpkg/srcdir/cache
}

install() {
  mkdir -p "$ROOT/usr/include" "$ROOT/usr/bin" "$ROOT/etc/nim" "$ROOT/usr/lib"
  cp -r lib/ "$ROOT/usr/lib/nim"
  cp -r compiler/ "$ROOT/usr/lib/nim"
  cp -rf config/* -t "$ROOT/etc/nim"
  cp -rf bin/* -t "$ROOT/usr/bin"
  cp -rf "$ROOT/usr/lib/nim/"*.h "$ROOT/usr/include"
  rm -rf "$ROOT/nim"
}
