#!/bin/sh
NAME="geoclue"
RELEASE="2"
VERSION="2.7.2"
SOURCES="https://gitlab.freedesktop.org/geoclue/geoclue/-/archive/$VERSION/geoclue-$VERSION.tar.gz" 
BUILD_DEPENDS="meson"
DEPENDS="libnotify libsoup json-glib glib"
SHA256SUM="9c2f3626e3131abc037955cb38a8c0f28a29b4d6cc9992a067fe04be46e37fbe"
DESCRIPTION="A D-Bus geoinformation service"

build() {
    meson setup \
    --prefix=/usr \
    --sysconfdir=/etc \
    --buildtype=release \
    -Dmodem-gps-source=false \
    -D3g-source=false \
    -Dcdma-source=false \
    -Dgtk-doc=false \
    -Dnmea-source=false \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
