#!/bin/sh
NAME="telepathy-mission-control"
RELEASE="1"
VERSION="5.16.6"
SOURCES="https://telepathy.freedesktop.org/releases/telepathy-mission-control/telepathy-mission-control-$VERSION.tar.gz"
DEPENDS="telepathy-glib networkmanager"
SHA256SUM="2df8ae3995e919a7670e01aa3568215ef0777e34961ace1cac1c6477cb297a45  telepathy-mission-control-5.16.6.tar.gz"
DESCRIPTION="telepathy-mission-control"

build() {
    ./configure --prefix=/usr --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
