#!/bin/sh
NAME="wayland"
RELEASE="1"
VERSION="1.22.0"
SOURCES="https://gitlab.freedesktop.org/wayland/wayland/-/archive/$VERSION/wayland-$VERSION.tar.gz"
SHA256SUM="bbca9c906a8fb8992409ebf51812f19e2a784b2c169d4b784cdd753b4bb448ef  wayland-1.22.0.tar.gz"
DESCRIPTION="Wayland is a project to define a protocol for a compositor to talk to its clients as well as a library implementation of the protocol."

build() {
    mkdir build
    cd build
    meson --prefix=/usr       \
          --buildtype=release \
          -Ddocumentation=false
    ninja
}

install() {
    DESTDIR="$ROOT" ninja install
}
