#!/bin/sh
NAME="wayland"
VERSION="1.20.0"
SOURCES="https://wayland.freedesktop.org/releases/wayland-$VERSION.tar.xz"
SHA256SUM="b8a034154c7059772e0fdbd27dbfcda6c732df29cae56a82274f6ec5d7cd8725  wayland-1.20.0.tar.xz"
DESCRIPTION="Wayland is a project to define a protocol for a compositor to talk to its clients as well as a library implementation of the protocol."

build() {
    wget https://wayland.freedesktop.org/releases/wayland-$VERSION.tar.xz
    tar -xvf wayland-$VERSION.tar.xz
    cd wayland-$VERSION || exit 1
    mkdir build
    cd build
    meson --prefix=/usr       \
          --buildtype=release \
          -Ddocumentation=false
    ninja
    DESTDIR="$ROOT" ninja install
}
