#!/bin/sh
NAME="sway"
RELEASE="1"
VERSION="1.8"
SOURCES="https://github.com/swaywm/sway/releases/download/$VERSION/sway-$VERSION.tar.gz"
SHA256SUM="033be1d9f0784cf09fb3931850894fc70a1af54ee04ae52a968e4beba7bc1d0c  sway-1.8.tar.gz"
DESCRIPTION="Wayland tiling window manager"
build() {
    meson --prefix=/usr -D werror=false build/
    ninja -C build/
}

install() {
    DESTDIR=$ROOT ninja -C build/ install
}
