#!/bin/sh
NAME="sway"
RELEASE="1"
VERSION="1.11"
SOURCES="https://github.com/swaywm/sway/releases/download/$VERSION/sway-$VERSION.tar.gz"
DEPENDS="pcre wlroots cairo git libevdev wayland libinput wayland-protocols pango json-c jetbrains-mono"
BUILD_DEPENDS="meson"
SHA256SUM="0e37a55b7c3379230e97e1ad982542b75016a0c7d6676198604e557f9b373dae"
DESCRIPTION="Wayland tiling window manager"

build() {
    meson --prefix=/usr -D werror=false build/
    ninja -C build/
}

package() {
    DESTDIR=$ROOT ninja -C build/ install
}
