#!/bin/sh
NAME="xorg-server"
RELEASE="1"
VERSION="21.1.21"
SOURCES="https://www.x.org/releases/individual/xserver/xorg-server-$VERSION.tar.gz"
SHA256SUM="952444a35ce6a720c3e978d3bad2b683bacb648cceedc03e3600f6fb170071d2"
DEPENDS="libdrm libtirpc xorg-setxkbmap xorg-font-util libx11 libxrender libxshmfence libepoxy dbus libglvnd libpciaccess libxcvt libxfont2 libxshmfence libnettle pixman"
BUILD_DEPENDS="meson"
DESCRIPTION="Open source display server for the X Window System"

build() {
    meson setup \
      --prefix=/usr \
      --buildtype=release \
      build
    ninja -C build
}

package() {
    DESTDIR=$ROOT ninja -C build install
}
