#!/bin/sh
NAME="exiv2"
RELEASE="1"
VERSION="0.28.7"
SOURCES="https://github.com/Exiv2/exiv2/archive/refs/tags/v$VERSION.tar.gz"
DEPENDS="gettext curl expat zlib"
BUILD_DEPENDS="cmake ninja"
SHA256SUM="5e292b02614dbc0cee40fe1116db2f42f63ef6b2ba430c77b614e17b8d61a638"
DESCRIPTION="Image metadata library and tools"

build() {
    cmake -B build -G Ninja \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DEXIV2_ENABLE_CURL=ON      \
      -DEXIV2_ENABLE_NLS=ON       \
      -DEXIV2_ENABLE_BMFF=ON      \
      -DEXIV2_ENABLE_VIDEO=ON      \
      -DEXIV2_ENABLE_PNG=ON       \
      -DEXIV2_ENABLE_INIH=OFF     \
      -DEXIV2_ENABLE_BROTLI=OFF
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
