#!/bin/sh
NAME="exiv2"
RELEASE="1"
VERSION="0.28.3"
SOURCES="https://github.com/Exiv2/exiv2/archive/refs/tags/v$VERSION.tar.gz"
DEPENDS="gettext curl expat zlib"
BUILD_DEPENDS="cmake ninja"
SHA256SUM="1315e17d454bf4da3cc0edb857b1d2c143670f3485b537d0f946d9ed31d87b70"
DESCRIPTION="Image metadata library and tools"

build() {
    cmake -B build -G Ninja \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DEXIV2_ENABLE_CURL=ON      \
      -DEXIV2_ENABLE_NLS=ON       \
      -DEXIV2_ENABLE_BMFF=ON      \
      -DEXIV2_ENABLE_VIDEO=ON      \
      -DEXIV2_ENABLE_PNG=ON       \
      -DEXIV2_ENABLE_INIH=OFF     \
      -DEXIV2_ENABLE_BROTLI=OFF
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
