#!/bin/sh
NAME="gdk-pixbuf"
RELEASE="2"
VERSION="2.42.12"
SOURCES="https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/archive/$VERSION/gdk-pixbuf-$VERSION.tar.gz"
DEPENDS="glib libpng libjpeg-turbo libtiff shared-mime-info"
BUILD_DEPENDS="meson gobject-introspection"
OPTDEPENDS="webp-pixbuf-loader: For webp support (runtime)"
SHA256SUM="d41966831b3d291fcdfe31f683bea4b3f03241d591ddbe550b5db873af3da364"
DESCRIPTION="GdkPixbuf is a library that loads image data in various formats and stores it as linear buffers in memory"
build() {
    meson setup \
        --prefix=/usr \
        -Dman=false \
        -Dgtk_doc=false \
        --wrap-mode=nofallback \
        -Dbuiltin_loaders=all \
        build/
    export XDG_DATA_DIRS=/usr/local/share:/usr/share
    meson compile -C build/
}

package() {
    DESTDIR=$ROOT meson install -C build/
}

postinstall() {
  gdk-pixbuf-query-loaders --update-cache
}
