#!/bin/sh
NAME="gdk-pixbuf"
RELEASE="2"
VERSION="2.42.9"
SOURCES="https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/archive/$VERSION/gdk-pixbuf-$VERSION.tar.gz"
DEPENDS="glib libpng libjpeg-turbo libtiff shared-mime-info"
BUILD_DEPENDS="meson gobject-introspection"
SHA256SUM="226d950375907857b23c5946ae6d30128f08cd75f65f14b14334c7a9fb686e36  gdk-pixbuf-2.42.9.tar.gz"
DESCRIPTION="GdkPixbuf is a library that loads image data in various formats and stores it as linear buffers in memory"
build() {
    meson setup \
        --prefix=/usr \
        -Dman=false \
        -Dgtk_doc=false \
        -Dtests=false \
        build/
    ninja -C build/
}

package() {
    DESTDIR=$ROOT ninja -C build/ install
}

postinstall() {
  gdk-pixbuf-query-loaders --update-cache
}
