#!/bin/sh
NAME="pipewire"
RELEASE="2"
VERSION="1.0.1"
SOURCES="https://github.com/PipeWire/pipewire/archive/$VERSION/pipewire-$VERSION.tar.gz"
DEPENDS="glib"
OPTDEPENDS="dbus: for D-Bus support"
BUILD_DEPENDS="meson"
SHA256SUM="23f7a3c1227e0dbc6c859d2ae56e0f3866749e4bc2e6193e3b6cadf5a037bd8e"
DESCRIPTION="Sound server"

build() {
    dbusEnable="disabled"
    if [ -d "/var/cache/kpkg/installed/dbus" ]; then
	dbusEnable="enabled"
    fi
   
    # Fix for https://github.com/kreatolinux/kpkg-repo/actions/runs/7372713578/job/20061318876
    export CFLAGS="$CFLAGS -ltinfow"

    meson setup \
      --prefix=/usr \
      --buildtype=release   \
      -Dsession-managers=[] \
      -Ddbus=$dbusEnable   \
      build  
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install  
}
