#!/bin/sh
NAME="pipewire"
RELEASE="1"
VERSION="0.3.73"
SOURCES="https://github.com/PipeWire/pipewire/archive/$VERSION/pipewire-$VERSION.tar.gz"
SHA256SUM="a4f8ee0577ef1ef72e0b4f1612fd99db3163541d4c36361cb938d5a62fa6d82b  pipewire-0.3.73.tar.gz"
DESCRIPTION="Sound server"

build() {
    mkdir build 
    cd    build 
    meson --prefix=/usr \
      --buildtype=release   \
      -Dsession-managers=[] \
      -Ddbus=disabled   \
    ..                    
    ninja
}

install() {
    DESTDIR="$ROOT" ninja -C build install  
}
