#!/bin/sh
NAME="libpsl"
RELEASE="1"
VERSION="0.21.5"
SOURCES="https://github.com/rockdaboot/libpsl/releases/download/$VERSION/libpsl-$VERSION.tar.gz"
BUILD_DEPENDS="meson"
DEPENDS="libidn2 libunistring"
SHA256SUM="1dcc9ceae8b128f3c0b3f654decd0e1e891afc6ff81098f227ef260449dae208"
DESCRIPTION="libpsl"

build() {
    meson setup --prefix=/usr      \
            --buildtype=release    \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
