#!/bin/sh
NAME="groff"
RELEASE="1"
VERSION="1.23.0"
SOURCES="https://ftp.gnu.org/gnu/groff/groff-$VERSION.tar.gz"
DEPENDS="bison perl"
BUILD_DEPENDS="gmake"
SHA256SUM="6b9757f592b7518b4902eb6af7e54570bdccba37a871fddb2d30ae3863511c13"
DESCRIPTION="GNU implementation of the traditional Unix document formatting tools"

build() {
    kpkgConfigure 
    make
}

package() {
    make DESTDIR=$ROOT install
    rm -rf "$ROOT/usr/share/info/dir"
}
