#!/bin/sh
NAME="samba"
RELEASE="1"
VERSION="4.19.1"
SOURCES="https://download.samba.org/pub/samba/stable/samba-$VERSION.tar.gz"
DEPENDS="gnutls jansson dbus fuse gpgme icu libtasn linux-pam"
BUILD_DEPENDS="perl-parse-yapp rpcsvc-proto libtirpc perl-json"
SHA256SUM="ce3b7f0d18bf91aa5fd646e8bb385a3b35375b703c6e5123b02b85a1abc81879"
DESCRIPTION="samba"

build() {

    if ! command -v systemctl > /dev/null; then
      extraArgs="--disable-systemd"
    fi
    
    # Some of these are taken from BLFS
    ./configure $extraArgs --sysconfdir=/etc \
      --localstatedir=/var \
      --with-pammodulesdir=/usr/lib/security \
      --enable-fhs \
      --without-acl-support \
      --without-ad-dc \
      --without-ldap \
      --without-ads \
      --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
