#!/bin/sh
NAME="samba"
RELEASE="1"
VERSION="4.22.6"
SOURCES="https://download.samba.org/pub/samba/stable/samba-$VERSION.tar.gz"
DEPENDS="gnutls jansson dbus fuse gpgme icu libtasn linux-pam"
BUILD_DEPENDS="perl-parse-yapp rpcsvc-proto libtirpc perl-json gmake"
SHA256SUM="8e6beb0cce87fb3c763af94c2dc21fd47b8fd02d46b3cb1deb2a72df9259c425"
DESCRIPTION="samba"

build() {

    if ! command -v systemctl > /dev/null; then
      extraArgs="--disable-systemd"
    fi
    
    # Some of these are taken from BLFS
    kpkgConfigure $extraArgs --sysconfdir=/etc \
      --localstatedir=/var \
      --with-pammodulesdir=/usr/lib/security \
      --enable-fhs \
      --without-acl-support \
      --without-ad-dc \
      --without-ldap \
      --without-ads \
      --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
