#!/bin/sh
NAME="lzip"
RELEASE="1"
VERSION="1.24"
SOURCES="https://download.savannah.gnu.org/releases/lzip/lzip-$VERSION.tar.gz"
SHA256SUM="d42659229b10e066eeb6e81eb673cdd893b672e512d26719c2d95975556ca56c"
DESCRIPTION="A lossless data compressor"

build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make install 
}
