#!/bin/sh
NAME="lzip"
RELEASE="1"
VERSION="1.24.1"
BUILD_DEPENDS="gmake"
SOURCES="https://download.savannah.gnu.org/releases/lzip/lzip-$VERSION.tar.gz"
SHA256SUM="30c9cb6a0605f479c496c376eb629a48b0a1696d167e3c1e090c5defa481b162"
DESCRIPTION="A lossless data compressor"

build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make install 
}
