#!/bin/sh
NAME="lzip"
RELEASE="1"
VERSION="1.23"
SOURCES="https://download.savannah.gnu.org/releases/lzip/lzip-$VERSION.tar.gz"
SHA256SUM="4792c047ddf15ef29d55ba8e68a1a21e0cb7692d87ecdf7204419864582f280d"
DESCRIPTION="A lossless data compressor"

build() {
    ./configure --prefix=/usr
    make
}

package() {
    make install 
}
