#!/bin/sh
NAME="ruby"
RELEASE="1"
VERSION="3.2.2"
SOURCES="https://cache.ruby-lang.org/pub/ruby/3.2/ruby-$VERSION.tar.xz"
DEPENDS="libyaml"
SHA256SUM="4b352d0f7ec384e332e3e44cdbfdcd5ff2d594af3c8296b5636c710975149e23  ruby-3.2.2.tar.xz"
DESCRIPTION="The Ruby language"

build() {
    ./configure --prefix=/usr \
                --enable-shared \
                --without-baseruby \
                --without-valgrind 
    make
}

package() {
    make DESTDIR=$ROOT install
}
