#!/bin/sh
NAME="ruby"
RELEASE="1"
VERSION="3.4.7"
BUILD_DEPENDS="gmake"
SOURCES="https://cache.ruby-lang.org/pub/ruby/3.2/ruby-$VERSION.tar.xz"
DEPENDS="libyaml"
SHA256SUM="SKIP"
DESCRIPTION="The Ruby language"

build() {
    kpkgConfigure --prefix=/usr \
                --enable-shared \
                --without-baseruby \
                --without-valgrind 
    make
}

package() {
    make DESTDIR=$ROOT install
}
