#!/bin/sh
NAME="libevdev"
RELEASE="1"
VERSION=1.13.3
BUILD_DEPENDS="gmake"
SOURCES="https://www.freedesktop.org/software/libevdev/libevdev-$VERSION.tar.xz"
DEPENDS=""
SHA256SUM="abf1aace86208eebdd5d3550ffded4c8d73bb405b796d51c389c9d0604cbcfbf"
DESCRIPTION="Common functions for Xorg input drivers"

build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR="$ROOT" install
}
