#!/bin/sh
NAME="libevdev"
RELEASE="1"
VERSION=1.13.0
SOURCES="https://www.freedesktop.org/software/libevdev/libevdev-$VERSION.tar.xz"
SHA256SUM="9edf2006cc86a5055279647c38ec923d11a821ee4dc2c3033e8d20e8ee237cd9  libevdev-1.13.0.tar.xz"
DESCRIPTION="Common functions for Xorg input drivers"

build() {
    ./configure --prefix=/usr
}

install() {
    make DESTDIR="$ROOT" install
}
