#!/bin/sh
NAME="gtar"
RELEASE="1"
VERSION="1.34"
SOURCES="https://ftp.gnu.org/gnu/tar/tar-$VERSION.tar.gz"
SHA256SUM="03d908cf5768cfe6b7ad588c921c6ed21acabfb2b79b788d1330453507647aed  tar-1.34.tar.gz"
DESCRIPTION="GNU tar"
build() {
    ./configure --prefix=/usr
    make
}

install() {
    make DESTDIR=$ROOT install
}
