#!/bin/sh
NAME="gnome-tweaks"
RELEASE="1"
VERSION="49.0"
SOURCES="https://github.com/GNOME/gnome-tweaks/archive/refs/tags/$VERSION.tar.gz"
BUILD_DEPENDS="meson"
DEPENDS="pygobject python gnome-settings-daemon glib gtk3 gnome-desktop libhandy pango gsettings-desktop-schemas gnome-shell mutter"
SHA256SUM="a9ca755f5bc1540c8970f02dfcaf7782e2efb31314ae19e8d6667dde2548d1a5"
DESCRIPTION="GNOME Tweaks app"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}

postinstall() {
    echo "Installing new Schemas"
    glib-compile-schemas /usr/share/glib-2.0/schemas || exit 1
    echo "Updating icon cache..."
    gtk-update-icon-cache -qtf /usr/share/icons/hicolor || exit 1
}
