#!/bin/sh
NAME="gnome-tweaks"
RELEASE="1"
VERSION="45.0"
SOURCES="https://github.com/GNOME/gnome-tweaks/archive/refs/tags/$VERSION.tar.gz"
BUILD_DEPENDS="meson"
DEPENDS="pygobject python gnome-settings-daemon glib gtk3 gnome-desktop libhandy pango gsettings-desktop-schemas gnome-shell mutter"
SHA256SUM="8bfa7dc1b4d4a7988269fd9424414cd1a630f4f6c7634c653efc32c6226c47c2"
DESCRIPTION="GNOME Tweaks app"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}

postinstall() {
    echo "Installing new Schemas"
    glib-compile-schemas /usr/share/glib-2.0/schemas || exit 1
    echo "Updating icon cache..."
    gtk-update-icon-cache -qtf /usr/share/icons/hicolor || exit 1
}
