#!/bin/sh
NAME="cups"
RELEASE="1"
VERSION="2.4.13"
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/OpenPrinting/cups/releases/download/v$VERSION/cups-$VERSION-source.tar.gz"
DEPENDS="colord dbus libusb linux-pam"
SHA256SUM="8255ecf037be72660de24a73bcada042fc5bf509fc87bc8ad16cd0675735c1a8"
DESCRIPTION="The Common Unix Printing System"
build() {

    # from BLFS, temporary
    sed -i 's#@CUPS_HTMLVIEW@#firefox#' desktop/cups.desktop.in
    
    if ! command -v systemctl > /dev/null; then
      extraArgs="--disable-systemd"
    fi
    
    kpkgConfigure $extraArgs --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
