#!/bin/sh
NAME="cups"
RELEASE="1"
VERSION="2.4.6"
SOURCES="https://github.com/OpenPrinting/cups/releases/download/v$VERSION/cups-$VERSION-source.tar.gz"
DEPENDS="colord dbus libusb linux-pam"
SHA256SUM="58e970cf1955e1cc87d0847c32526d9c2ccee335e5f0e3882b283138ba0e7262  cups-2.4.6-source.tar.gz"
DESCRIPTION="The Common Unix Printing System"
build() {

    # from BLFS, temporary
    sed -i 's#@CUPS_HTMLVIEW@#firefox#' desktop/cups.desktop.in
    
    if ! command -v systemctl > /dev/null; then
      extraArgs="--disable-systemd"
    fi
    
    ./configure $extraArgs --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
