#!/bin/sh
NAME="libical"
RELEASE="1"
VERSION="3.0.17"
SOURCES="https://github.com/libical/libical/releases/download/v$VERSION/libical-$VERSION.tar.gz"
DEPENDS="glib"
BUILD_DEPENDS="cmake gobject-introspection vala"
SHA256SUM="bcda9a6db6870240328752854d1ea475af9bbc6356e6771018200e475e5f781b"
DESCRIPTION="An implementation of iCalendar protocols and data formats"

build() {
    cmake -DCMAKE_INSTALL_PREFIX=/usr \
	  -DCMAKE_BUILD_TYPE=Release  \
	  -DSHARED_ONLY=yes            \
    -DGOBJECT_INTROSPECTION=true \
    -DICAL_GLIB_VAPI=true        \
    -DENABLE_GTK_DOC=OFF \
	  -B build
    cmake --build build
 }

package() {
    DESTDIR="$ROOT" cmake --install build
}
