#!/bin/sh
NAME="libical"
RELEASE="1"
VERSION="3.0.20"
SOURCES="https://github.com/libical/libical/releases/download/v$VERSION/libical-$VERSION.tar.gz"
DEPENDS="glib"
BUILD_DEPENDS="cmake gobject-introspection vala"
SHA256SUM="72b7dc1a5937533aee5a2baefc990983b66b141dd80d43b51f80aced4aae219c"
DESCRIPTION="An implementation of iCalendar protocols and data formats"

build() {
    cmake -DCMAKE_INSTALL_PREFIX=/usr \
	  -DCMAKE_BUILD_TYPE=Release  \
	  -DSHARED_ONLY=yes            \
    -DGOBJECT_INTROSPECTION=true \
    -DICAL_GLIB_VAPI=true        \
    -DENABLE_GTK_DOC=OFF \
	  -B build
    cmake --build build
 }

package() {
    DESTDIR="$ROOT" cmake --install build
}
