#!/bin/sh
NAME="vte"
RELEASE="1"
VERSION="0.74.1"
SOURCES="https://gitlab.gnome.org/GNOME/vte/-/archive/$VERSION/vte-$VERSION.tar.gz"
DEPENDS="gtk3 pcre fribidi gtk4 gnutls"
BUILD_DEPENDS="meson gobject-introspection vala"
SHA256SUM="8160ed2c9962f3b559bb73f8e4b51f62eff3221722d964a7955b097272d4c996"
DESCRIPTION="Visual Terminal Emulator widget"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Ddocs=false \
    -Dgtk4=true \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
