#!/bin/sh
NAME="libxkbcommon"
RELEASE="1"
VERSION=1.4.1
SOURCES="https://xkbcommon.org/download/libxkbcommon-$VERSION.tar.xz"
SHA256SUM="943c07a1e2198026d8102b17270a1f406e4d3d6bbc4ae105b9e1b82d7d136b39  libxkbcommon-1.4.1.tar.xz;"
DESCRIPTION="Keyboard compiler and support library"

build() {
    tar -xvf libxkbcommon-$VERSION.tar.xz
    cd libxkbcommon-$VERSION || exit 1
    mkdir build 
    cd    build 
    meson --prefix=/usr \
      --buildtype=release   \
      -Denable-x11=false    \
      -Dxkb-config-root=/usr/share/X11/xkb \
      -Dx-locale-root=/usr/share/X11/locale \
      -Denable-docs=false
      ..                    
    ninja
    DESTDIR="$ROOT" ninja install  
}
