#!/bin/sh
NAME="libxkbcommon"
RELEASE="2"
VERSION="1.7.0"
SOURCES="https://xkbcommon.org/download/libxkbcommon-$VERSION.tar.xz"
DEPENDS="wayland wayland-protocols libxcb libxml2 xkeyboard-config"
BUILD_DEPENDS="meson"
SHA256SUM="65782f0a10a4b455af9c6baab7040e2f537520caa2ec2092805cdfd36863b247"
DESCRIPTION="Keyboard compiler and support library"

build() {
    mkdir build 
    cd    build 
    meson --prefix=/usr \
      --buildtype=release   \
      -Denable-x11=true    \
      -Dxkb-config-root=/usr/share/X11/xkb \
      -Dx-locale-root=/usr/share/X11/locale \
      -Denable-docs=false
      ..                    
    ninja
}

package() {
    DESTDIR="$ROOT" ninja -C build install  
}
