#!/bin/sh
NAME="libnettle"
RELEASE="1"
VERSION="3.8.1"
BUILD_DEPENDS="gmake"
SOURCES="https://ftp.gnu.org/gnu/nettle/nettle-$VERSION.tar.gz"
DEPENDS=""
SHA256SUM="SKIP"
DESCRIPTION="low-level cryptographic library"

build() {
    kpkgConfigure --prefix=/usr
    make -j$(nproc)
}

package() {
    make DESTDIR="$ROOT" install
}
