#!/bin/sh
NAME="libnettle"
RELEASE="1"
VERSION="3.8.1"
SOURCES="https://ftp.gnu.org/gnu/nettle/nettle-$VERSION.tar.gz"
DEPENDS=""
SHA256SUM="364f3e2b77cd7dcde83fd7c45219c834e54b0c75e428b6f894a23d12dd41cbfe"
DESCRIPTION="low-level cryptographic library"

build() {
    kpkgConfigure --prefix=/usr
    make -j$(nproc)
}

package() {
    make DESTDIR="$ROOT" install
}
