#!/bin/sh
NAME="libndp"
RELEASE="1"
VERSION="1.9"
SOURCES="https://github.com/jpirko/libndp/archive/refs/tags/v$VERSION.tar.gz"
SHA256SUM="e564f5914a6b1b799c3afa64c258824a801c1b79a29e2fe6525b682249c65261"
BUILD_DEPENDS="autoconf automake libtool gmake"
DESCRIPTION="Neighbor Discovery library"

build() {
    autoreconf -v -f -i
    kpkgConfigure --prefix=/usr                   \
                --sysconfdir=/etc \
                --localstatedir=/var \
                --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
