#!/bin/sh
NAME="xkeyboard-config"
RELEASE="1"
VERSION="2.40"
SOURCES="https://www.x.org/archive//individual/data/xkeyboard-config/xkeyboard-config-$VERSION.tar.xz"
SHA256SUM="7a3dba1bec7dc7191432da021242d17c9cf6c89690e6c57b0de048ff8c9d2ae3"
DESCRIPTION="XKB data description files"

build() {
    mkdir build 
    cd    build 
    meson --prefix=/usr \
      --buildtype=release \
      ..                    
    ninja
}

package() {
    DESTDIR="$ROOT" ninja -C build install  
}
