#!/bin/sh
NAME="evolution-data-server"
RELEASE="1"
VERSION="3.58.2"
SOURCES="https://download.gnome.org/sources/evolution-data-server/3.50/evolution-data-server-$VERSION.tar.xz"
BUILD_DEPENDS="cmake ninja gobject-introspection vala"
DEPENDS="libical libsecret nss sqlite libgweather gtk3 libcanberra gnome-online-accounts webkitgtk3"
NO_CHKUPD="y"
OPTDEPENDS="webkitgtk4: for built-in OAuth2 authentications ;; gtk4: for gtk4 support"
SHA256SUM="SKIP"
DESCRIPTION="evolution-data-server"

build() {
    
    if ! command -v systemctl > /dev/null; then
      extraArgs="-DWITH_SYSTEMDUSERUNITDIR=no"
    fi 

    if ! kpkg info webkitgtk4 > /dev/null; then
      extraArgs="$extraArgs -DENABLE_OAUTH2_WEBKITGTK4=OFF"
    fi

    if ! kpkg info gtk4 > /dev/null; then
      extraArgs="$extraArgs -DENABLE_GTK4=OFF"
    fi

    # Flags taken from BLFS
    cmake -B build $extraArgs -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DWITH_KRB5=OFF                \
        -DENABLE_VALA_BINDINGS=ON \
        -DWITH_OPENLDAP=OFF \
        -DENABLE_INTROSPECTION=ON \
        -DENABLE_GTK_DOC=OFF \
        -DWITH_LIBDB=OFF \
        -DENABLE_INSTALLED_TESTS=OFF \
        -DSYSCONF_INSTALL_DIR=/etc \
        -G Ninja
    ninja -C build -j$(nproc)
}

package() {    
    DESTDIR="$ROOT" ninja -C build install
}
