#!/bin/sh
NAME="icu"
RELEASE="1"
VERSION="74.1"
SOURCES="https://github.com/unicode-org/icu/releases/download/release-73-2/icu4c-73_2-src.tgz"
SHA256SUM="818a80712ed3caacd9b652305e01afc7fa167e6f2e94996da44b90c2ab604ce1"
DESCRIPTION="Unicode stuff"

build() {
    cd source
    kpkgConfigure --prefix=/usr
    make
}

package() {
    cd source
    make DESTDIR=$ROOT install
}
