#!/bin/sh
NAME="m4"
VERSION="1.4.19"
SOURCES="https://ftp.gnu.org/gnu/m4/m4-$VERSION.tar.gz"
SHA256SUM="3be4a26d825ffdfda52a56fc43246456989a3630093cced3fbddf4771ee58a70  m4-1.4.19.tar.gz"
DESCRIPTION="GNU m4"

build() {
    tar -xf m4-$VERSION.tar.gz
    cd m4-$VERSION
    ./configure --prefix=/usr
    make -j$(nproc)
    make DESTDIR=$ROOT install
}

