#!/bin/sh
NAME="m4"
RELEASE="1"
VERSION="1.4.20"
BUILD_DEPENDS="gmake"
SOURCES="https://ftp.gnu.org/gnu/m4/m4-$VERSION.tar.gz"
DEPENDS=""
SHA256SUM="3be4a26d825ffdfda52a56fc43246456989a3630093cced3fbddf4771ee58a70"
DESCRIPTION="GNU m4"

build() {
    kpkgConfigure
    make -j$(nproc)
}

package() {
    make DESTDIR=$ROOT install
    rm -rf "$ROOT/usr/share/info/dir"
}

