#!/bin/sh
NAME="patch"
RELEASE="1"
VERSION="2.8"
SOURCES="https://ftp.gnu.org/gnu/patch/patch-$VERSION.tar.gz"
BUILD_DEPENDS="gmake"
DEPENDS=""
SHA256SUM="SKIP"
DESCRIPTION="GNU patch"

build() {
    mkdir -v build
    cd       build
    KPKG_CONFIGURE_PATH="../configure" kpkgConfigure                  \
        --prefix=/usr              \
        --disable-nls              \
        --enable-shared            \
        --disable-werror           \
        --enable-64-bit-bfd
    make
}

package() {
    cd build
    make DESTDIR=$ROOT install -j1
}
