#!/bin/sh
NAME="python-pip"
RELEASE="1"
VERSION="25.2"
SOURCES="https://github.com/pypa/pip/archive/refs/tags/$VERSION.tar.gz"
DEPENDS="python python-setuptools"
B2SUM="3bfe61d6d0d6f3a79c3fd801f5cb40b203fd12085d925ae7cde53adca3c5ee523fdfd9449546e1bc8ca719b3e8766cfef3162919e13a77f7adc0d20a951d11c7"
DESCRIPTION="Easily download, build, install, upgrade, and uninstall Python packages"

package() {
    
    if ! command -v pip || ! pip --version; then
        # Install pip using ensurepip if it is not available or not working
        python3 -m ensurepip 
    fi

    pip install . --no-dependencies --ignore-installed --prefix=/usr --root="$ROOT"
    find "$ROOT" -type d -name "__pycache__" -exec rm -rf {} +
    find "$ROOT" -type f -name "*.pyc" -exec rm -f {} +
}
