#!/bin/sh
NAME="python-pip"
RELEASE="1"
VERSION="25.3"
SOURCES="https://github.com/pypa/pip/archive/refs/tags/$VERSION.tar.gz"
DEPENDS="python python-setuptools"
B2SUM="87d848c497163a45ee3de8f6f75c80b5051b07062c5a15450ae98b59a6cebc6bf03ca8525d57929493f2cfeb28d5623401eba69f0bdfc734389efbb84eafdf53"
DESCRIPTION="Easily download, build, install, upgrade, and uninstall Python packages"

package() {
    
    if ! command -v pip || ! pip --version; then
        # Install pip using ensurepip if it is not available or not working
        python3 -m ensurepip 
    fi

    pip install . --no-dependencies --ignore-installed --prefix=/usr --root="$ROOT"
    find "$ROOT" -type d -name "__pycache__" | xargs rm -rf
    find "$ROOT" -type f -name "*.pyc" | xargs rm -f
}
