#!/bin/sh
NAME="e2fsprogs"
RELEASE="2"
VERSION="1.47.2"
BUILD_DEPENDS="gmake"
SOURCES="https://mirrors.edge.kernel.org/pub/linux/kernel/people/tytso/e2fsprogs/v$VERSION/e2fsprogs-$VERSION.tar.gz"
SHA256SUM="7a959221c1b1cc6e28b7d7a4e204a2ffd8ec6d8a2de4461c482b64c5f4463cca"
DESCRIPTION="Provides the filesystem utilities for use with the ext2,ext3 and ext4 filesystem"

build() {
    kpkgConfigure --prefix=/usr --enable-elf-shlibs --with-root-prefix="" 
    make
}

package() {
    make install install-libs
}
