#!/bin/sh
NAME="conmon"
RELEASE="1"
VERSION="2.1.12"
SOURCES="https://github.com/containers/conmon/archive/refs/tags/v$VERSION.tar.gz"
BUILD_DEPENDS="go gmake"
DEPENDS="glib"
SHA256SUM="842f0b5614281f7e35eec2a4e35f9f7b9834819aa58ecdad8d0ff6a84f6796a6"
DESCRIPTION="An OCI container runtime monitor"

build() {
    make -j$(nproc)
}

package() {
    make install
}
