#!/bin/sh
NAME="conmon"
RELEASE="1"
VERSION="2.1.13"
SOURCES="https://github.com/containers/conmon/archive/refs/tags/v$VERSION.tar.gz"
BUILD_DEPENDS="go gmake"
DEPENDS="glib"
SHA256SUM="350992cb2fe4a69c0caddcade67be20462b21b4078dae00750e8da1774926d60"
DESCRIPTION="An OCI container runtime monitor"

build() {
    make -j$(nproc)
}

package() {
    make install
}
