#!/bin/sh
NAME="conmon"
RELEASE="1"
VERSION="2.1.9"
SOURCES="https://github.com/containers/conmon/archive/refs/tags/v$VERSION.tar.gz"
BUILD_DEPENDS="go"
DEPENDS="glib"
SHA256SUM="15a41e78f5e86dba429cc78ef4836f44ba927b6c69f1cd1721118a08ca0fd1f5"
DESCRIPTION="An OCI container runtime monitor"

build() {
    make -j$(nproc)
}

package() {
    make install
}
