#!/bin/sh
NAME="pkgconf"
RELEASE="1"
VERSION=1.8.0
SOURCES="https://distfiles.dereferenced.org/pkgconf/pkgconf-$VERSION.tar.xz"
SHA256SUM="ef9c7e61822b7cb8356e6e9e1dca58d9556f3200d78acab35e4347e9d4c2bbaf  pkgconf-1.8.0.tar.xz"
DESCRIPTION="pkgconf is a program which helps to configure compiler and linker flags for development frameworks."

build() {
    ./configure --prefix=/usr
}

install() {
    make DESTDIR="$ROOT" install
    [ ! -d "$ROOT/usr/bin" ] && mkdir -p "$ROOT/usr/bin"
    ln -s pkgconf "$ROOT/usr/bin/pkg-config"
}
