#!/bin/sh
NAME="pkgconf"
RELEASE="1"
VERSION=2.0.1
SOURCES="https://distfiles.dereferenced.org/pkgconf/pkgconf-$VERSION.tar.xz"
DEPENDS=""
SHA256SUM="3238af7473740844e5159dd8fb6540603e3fbcebf60beb3c8a426cdca2e29c51  pkgconf-2.0.1.tar.xz"
DESCRIPTION="pkgconf is a program which helps to configure compiler and linker flags for development frameworks."

build() {
    ./configure --prefix=/usr
    make
}

package() {
    make DESTDIR="$ROOT" install
    [ ! -d "$ROOT/usr/bin" ] && mkdir -p "$ROOT/usr/bin"
    ln -s pkgconf "$ROOT/usr/bin/pkg-config"
}
