#!/bin/sh
NAME="git"
RELEASE="1"
VERSION=2.40.1
DESCRIPTION="Version control tool"
SOURCES="https://mirrors.edge.kernel.org/pub/software/scm/git/git-$VERSION.tar.xz"
SHA256SUM="4893b8b98eefc9fdc4b0e7ca249e340004faa7804a433d17429e311e1fef21d2  git-2.40.1.tar.xz"
build() {
./configure --prefix=/usr
# Taken from kiss linux, license is https://github.com/kisslinux/repo/blob/master/LICENSE
cat > config.mak <<EOF
NO_GETTEXT=YesPlease
NO_SVN_TESTS=YesPlease
NO_TCLTK=YesPlease
NO_EXPAT=YesPlease
NO_NSEC=YesPlease
NO_PYTHON=YesPlease
NO_PERL=YesPlease
NO_SYS_POLL_H=1
NO_CROSS_DIRECTORY_HARDLINKS=1
NO_INSTALL_HARDLINKS=1
EOF
make -j$(nproc)
}

install() {
make DESTDIR=$ROOT install
}
