#!/bin/sh
NAME="git"
RELEASE="1"
VERSION="2.52.0"
BUILD_DEPENDS="gmake gsed"
DESCRIPTION="Version control tool"
SOURCES="https://mirrors.edge.kernel.org/pub/software/scm/git/git-$VERSION.tar.xz"
DEPENDS="curl openssl zlib"
SHA256SUM="3cd8fee86f69a949cb610fee8cd9264e6873d07fa58411f6060b3d62729ed7c5"
build() {
kpkgConfigure --prefix=/usr
# Taken from kiss linux, license is https://github.com/kisslinux/repo/blob/master/LICENSE
cat > config.mak <<EOF
NO_GETTEXT=YesPlease
NO_SVN_TESTS=YesPlease
NO_TCLTK=YesPlease
NO_EXPAT=YesPlease
NO_NSEC=YesPlease
NO_PYTHON=YesPlease
NO_PERL=YesPlease
NO_PERL_CPAN_FALLBACKS=YesPlease
NO_ARCHIMPORT=YesPlease
NO_SYS_POLL_H=1
NO_CROSS_DIRECTORY_HARDLINKS=1
NO_INSTALL_HARDLINKS=1
EOF
make -j$(nproc)
}

package() {
make DESTDIR=$ROOT install
}
