#!/bin/sh
NAME="xf86-input-libinput"
RELEASE="1"
VERSION="1.4.0"
SOURCES="https://xorg.freedesktop.org/releases/individual/driver/xf86-input-libinput-$VERSION.tar.xz"
SHA256SUM="3a3d14cd895dc75b59ae2783b888031956a0bac7a1eff16d240dbb9d5df3e398  xf86-input-libinput-1.4.0.tar.xz"
DEPENDS="libinput"
BUILD_DEPENDS="libxi libx11 xorgproto xorg-util-macros xorg-server"
DESCRIPTION="xf86-input-libinput"

build() {
    ./configure \
        --prefix=/usr \
        --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
