#!/bin/sh
NAME="xf86-input-libinput"
RELEASE="1"
VERSION="1.5.0"
SOURCES="https://xorg.freedesktop.org/releases/individual/driver/xf86-input-libinput-$VERSION.tar.xz"
SHA256SUM="2524c35f196554ea11aef3bba1cf324759454e1d49f98ac026ace2f6003580e6"
DEPENDS="libinput"
BUILD_DEPENDS="libxi libx11 xorgproto xorg-util-macros xorg-server gmake"
DESCRIPTION="xf86-input-libinput"

build() {
    kpkgConfigure \
        --prefix=/usr \
        --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
