#!/bin/sh
NAME="chkupd"
RELEASE="1"
VERSION="1.2"
SOURCES="https://github.com/kreatolinux/chkupd/archive/refs/tags/v$VERSION.tar.gz"
SHA256SUM="76051d18e8d90fe84912d2d0e3d59f68002158de690e5cb301d9887777571f92  v1.2.tar.gz"
DESCRIPTION="nyaa package update checker"
build() {
    mkdir -p $ROOT/usr/bin
}

install() {
    cp chkupd $ROOT/usr/bin
}
