#!/bin/sh
NAME="glib"
RELEASE="1"
VERSION="2.76.1"
SOURCES="https://download.gnome.org/sources/glib/2.76/glib-$VERSION.tar.xz" 
SHA256SUM="43dc0f6a126958f5b454136c4398eab420249c16171a769784486e25f2fda19f  glib-2.76.1.tar.xz"
DESCRIPTION="glib"

build() {
    meson \
    --prefix=/usr \
    -Dman=false \
    build
    ninja -C build
}

install() {
    DESTDIR="$ROOT" ninja -C build install
}
