#!/bin/sh
NAME="glib"
RELEASE="1"
VERSION="2.76.2"
SOURCES="https://download.gnome.org/sources/glib/2.76/glib-$VERSION.tar.xz" 
SHA256SUM="24f3847857b1d8674cdb0389a36edec0f13c666cd3ce727ecd340eb9da8aca9e  glib-2.76.2.tar.xz"
DESCRIPTION="glib"

build() {
    meson \
    --prefix=/usr \
    -Dman=false \
    build
    ninja -C build
}

install() {
    DESTDIR="$ROOT" ninja -C build install
}
