#!/bin/sh
NAME="libgcrypt"
RELEASE="1"
VERSION="1.11.0"
BUILD_DEPENDS="gmake"
SOURCES="https://gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-$VERSION.tar.bz2"
DEPENDS="libgpg-error"
SHA256SUM="09120c9867ce7f2081d6aaa1775386b98c2f2f246135761aae47d81f58685b9c"
DESCRIPTION="A general purpose cryptographic library"

build() {
    kpkgConfigure --prefix=/usr
    make -j$(nproc)
}

package() {
    make install
}
