#!/bin/sh
NAME="gnome-shell"
RELEASE="1"
VERSION="49.1"
SOURCES="https://gitlab.gnome.org/GNOME/gnome-shell/-/archive/$VERSION/gnome-shell-$VERSION.tar.gz"
BUILD_DEPENDS="meson"
DEPENDS="dconf gnome-autoar elogind adwaita-icon-theme dconf gdm gnome-backgrounds gnome-control-center libgweather telepathy-mission-control evolution-data-server gnome-bluetooth networkmanager desktop-file-utils gcr-4 gjs gnome-desktop ibus mutter polkit sassc startup-notification pipewire"
SHA256SUM="ae70da39d4cb8d505c83def33e8941a470bfb0706d4ee3eaaa75dca19d6c86c0"
DESCRIPTION="The GNOME shell"

build() {
    
    if ! command -v systemctl > /dev/null; then
      # Credits to https://www.linuxfromscratch.org/blfs/view/svn/gnome/gnome-shell.html
      extraArgs="-Dsystemd=false"
    fi

    rm -r subprojects/gvc
    git clone https://gitlab.gnome.org/GNOME/libgnome-volume-control subprojects/gvc
    cd subprojects/gvc
    git checkout 000046e88714de77db320b0711af3baacb2813a2
    cd ../.. 

    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Dtests=false \
    -Dman=false \
    -Dgtk_doc=false \
    $extraArgs build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}

postinstall() {
  glib-compile-schemas /usr/share/glib-2.0/schemas
}
