#!/bin/sh
NAME="eudev"
RELEASE="1"
VERSION="3.2.12"
SOURCES="https://github.com/eudev-project/eudev/releases/download/v$VERSION/eudev-$VERSION.tar.gz"
DEPENDS="gperf kmod"
SHA256SUM="ccdd64ec3c381d3c3ed0e99d2e70d1f62988c7763de89ca7bdffafa5eacb9ad8  eudev-3.2.12.tar.gz"
REPLACES="systemd libudev"
DESCRIPTION="Fork of systemd with the aim of making udev init-independent"
build() {
    ./configure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
