#!/bin/sh
NAME="docbook-xml"
RELEASE="1"
VERSION="4.5"
NO_CHKUPD="true"
SOURCES="https://www.docbook.org/xml/$VERSION/docbook-xml-4.5.zip"
SHA256SUM="4e4e037a2b83c98c6c94818390d4bdd3f6e10f6ec62dd79188594e26190dc7b4"
DESCRIPTION="A widely used XML scheme for writing documentation and help"

prepare() {
    bsdtar -xf docbook-xml-$VERSION.zip
}

# Huge thanks to BLFS for having this batshit crazy installation process figured out

package() {
    install -v -d -m755 $DESTDIR/usr/share/xml/docbook/xml-dtd-$VERSION
    install -v -d -m755 $DESTDIR/etc/xml
    chown -R root:root . 
    cp -v -af docbook.cat *.dtd ent/ *.mod \
        $DESTDIR/usr/share/xml/docbook/xml-dtd-$VERSION

    if [ ! -e $DESTDIR/etc/xml/docbook ]; then
        xmlcatalog --noout --create $DESTDIR/etc/xml/docbook
    fi

    xmlcatalog --noout --add "public" \
        "-//OASIS//DTD DocBook XML V$VERSION//EN" \
        "http://www.oasis-open.org/docbook/xml/$VERSION/docbookx.dtd" \
        $DESTDIR/etc/xml/docbook
    xmlcatalog --noout --add "public" \
        "-//OASIS//DTD DocBook XML CALS Table Model V$VERSION//EN" \
        "file:///usr/share/xml/docbook/xml-dtd-$VERSION/calstblx.dtd" \
        $DESTDIR/etc/xml/docbook
    xmlcatalog --noout --add "public" \
        "-//OASIS//DTD XML Exchange Table Model 19990315//EN" \
        "file:///usr/share/xml/docbook/xml-dtd-$VERSION/soextblx.dtd" \
        $DESTDIR/etc/xml/docbook
    xmlcatalog --noout --add "public" \
        "-//OASIS//ELEMENTS DocBook XML Information Pool V$VERSION//EN" \
        "file:///usr/share/xml/docbook/xml-dtd-$VERSION/dbpoolx.mod" \
        $DESTDIR/etc/xml/docbook
    xmlcatalog --noout --add "public" \
        "-//OASIS//ELEMENTS DocBook XML Document Hierarchy V$VERSION//EN" \
        "file:///usr/share/xml/docbook/xml-dtd-$VERSION/dbhierx.mod" \
        $DESTDIR/etc/xml/docbook
    xmlcatalog --noout --add "public" \
        "-//OASIS//ELEMENTS DocBook XML HTML Tables V$VERSION//EN" \
        "file:///usr/share/xml/docbook/xml-dtd-$VERSION/htmltblx.mod" \
        $DESTDIR/etc/xml/docbook
    xmlcatalog --noout --add "public" \
        "-//OASIS//ENTITIES DocBook XML Notations V$VERSION//EN" \
        "file:///usr/share/xml/docbook/xml-dtd-$VERSION/dbnotnx.mod" \
        $DESTDIR/etc/xml/docbook
    xmlcatalog --noout --add "public" \
        "-//OASIS//ENTITIES DocBook XML Character Entities V$VERSION//EN" \
        "file:///usr/share/xml/docbook/xml-dtd-$VERSION/dbcentx.mod" \
        $DESTDIR/etc/xml/docbook
    xmlcatalog --noout --add "public" \
        "-//OASIS//ENTITIES DocBook XML Additional General Entities V$VERSION//EN" \
        "file:///usr/share/xml/docbook/xml-dtd-$VERSION/dbgenent.mod" \
        $DESTDIR/etc/xml/docbook 
    xmlcatalog --noout --add "rewriteSystem" \
        "http://www.oasis-open.org/docbook/xml/$VERSION" \
        "file:///usr/share/xml/docbook/xml-dtd-$VERSION" \
        $DESTDIR/etc/xml/docbook
    xmlcatalog --noout --add "rewriteURI" \
        "http://www.oasis-open.org/docbook/xml/$VERSION" \
        "file:///usr/share/xml/docbook/xml-dtd-$VERSION" \
        $DESTDIR/etc/xml/docbook

    cd ..
}

postinstall() {
    
    if [ ! -e /etc/xml/catalog ]; then
        xmlcatalog --noout --create /etc/xml/catalog
    fi

    xmlcatalog --noout --add "delegatePublic" \
        "-//OASIS//ENTITIES DocBook XML" \
        "file:///etc/xml/docbook" \
        /etc/xml/catalog
    xmlcatalog --noout --add "delegatePublic" \
        "-//OASIS//DTD DocBook XML" \
        "file:///etc/xml/docbook" \
        /etc/xml/catalog
    xmlcatalog --noout --add "delegateSystem" \
        "http://www.oasis-open.org/docbook/" \
        "file:///etc/xml/docbook" \
        /etc/xml/catalog
    xmlcatalog --noout --add "delegateURI" \
        "http://www.oasis-open.org/docbook/" \
        "file:///etc/xml/docbook" \
        /etc/xml/catalog

    for DTDVERSION in 4.1.2 4.2 4.3 4.4
do
  xmlcatalog --noout --add "public" \
    "-//OASIS//DTD DocBook XML V$DTDVERSION//EN" \
    "http://www.oasis-open.org/docbook/xml/$DTDVERSION/docbookx.dtd" \
    /etc/xml/docbook
  xmlcatalog --noout --add "rewriteSystem" \
    "http://www.oasis-open.org/docbook/xml/$DTDVERSION" \
    "file:///usr/share/xml/docbook/xml-dtd-4.5" \
    /etc/xml/docbook
  xmlcatalog --noout --add "rewriteURI" \
    "http://www.oasis-open.org/docbook/xml/$DTDVERSION" \
    "file:///usr/share/xml/docbook/xml-dtd-4.5" \
    /etc/xml/docbook
  xmlcatalog --noout --add "delegateSystem" \
    "http://www.oasis-open.org/docbook/xml/$DTDVERSION/" \
    "file:///etc/xml/docbook" \
    /etc/xml/catalog
  xmlcatalog --noout --add "delegateURI" \
    "http://www.oasis-open.org/docbook/xml/$DTDVERSION/" \
    "file:///etc/xml/docbook" \
    /etc/xml/catalog
done
}

postremove() {
    :
}
