#!/bin/sh
NAME="pango"
MAINVERSION="1.50"
VERSION="$MAINVERSION.7"
SOURCES="https://download.gnome.org/sources/pango/$MAINVERSION/pango-$VERSION.tar.xz" 
SHA256SUM="0477f369a3d4c695df7299a6989dc004756a7f4de27eecac405c6790b7e3ad33  pango-1.50.7.tar.xz"
DESCRIPTION="Text (i.e. glyph) layout engine library"

build() {
    tar -xvf pango-$VERSION.tar.xz
    cd pango-$VERSION || exit 1
    rm -rf subprojects
    meson \
    --prefix=/usr \
    -Dgtk_doc=false \
    -Dxft=disabled \
    -Dintrospection=disabled \
    . build
    ninja -C build
    DESTDIR="$ROOT" ninja -C build install
}
