#!/bin/sh
NAME="pango"
MAINVERSION="1.50"
VERSION="$MAINVERSION.10"
SOURCES="https://download.gnome.org/sources/pango/$MAINVERSION/pango-$VERSION.tar.xz" 
SHA256SUM=";caef96d27bbe792a6be92727c73468d832b13da57c8071ef79b9df69ee058fe3  pango-1.50.12.tar.xz"
DESCRIPTION="Text (i.e. glyph) layout engine library"

build() {
    tar -xvf pango-$VERSION.tar.xz
    cd pango-$VERSION || exit 1
    rm -rf subprojects
    meson \
    --prefix=/usr \
    -Dgtk_doc=false \
    -Dxft=disabled \
    build
    ninja -C build
    DESTDIR="$ROOT" ninja -C build install
}
