#!/bin/sh
NAME="jumpstart"
RELEASE="1"
VERSION="5.0.1"
SOURCES="https://github.com/kreatolinux/src/archive/refs/tags/v$VERSION.tar.gz"
BUILD_DEPENDS="nim"
DEPENDS="libarchive shadow openssl git"
SHA256SUM="43f06b73e27542cc0eab46f9651d25049898f8777e4b79aea9be6167dd49acbc  v5.0.1.tar.gz"
DESCRIPTION="Kreato Linux's Init system/Service manager"

build() {
        nimble install cligen fusion -y
        nim c -d:release --threads:on -o="out/jumpstart" "jumpstart/jumpstart.nim"
        nim c -d:release --threads:on -o="out/jumpctl" "jumpstart/jumpctl.nim"
}

package() {
        mkdir -p "$ROOT/bin"
        cp out/jumpctl "$ROOT/bin/"
        cp out/jumpstart "$ROOT/bin"
}
