#!/bin/sh
NAME="jumpstart"
RELEASE="1"
VERSION="4.1.2"
SOURCES="https://github.com/kreatolinux/src/archive/refs/tags/v$VERSION.tar.gz"
SHA256SUM="3f14a4639e4139d7205c274115ef4ee41ff0ef34f4457be904fc147a10a654b6  v4.1.2.tar.gz"
DESCRIPTION="Kreato Linux's Init system/Service manager"

build() {
        nimble install cligen fusion -y --nimbleDir=/tmp/kpkg/srcdir/deps
        nim c -d:release --threads:on -o="out/jumpstart" --NimblePath=/tmp/kpkg/srcdir/deps/pkgs --nimcache=/tmp/kpkg/srcdir/cache "src/jumpstart/jumpstart.nim"
        nim c -d:release --threads:on -o="out/jumpctl" --NimblePath=/tmp/kpkg/srcdir/deps/pkgs --nimcache=/tmp/kpkg/srcdir/cache "src/jumpstart/jumpctl.nim"
}

install() {
        mkdir -p "$ROOT/bin"
        cp out/jumpctl "$ROOT/bin/"
        cp out/jumpstart "$ROOT/bin"
}
