#!/bin/sh
NAME="jumpstart"
RELEASE="1"
VERSION="5.0.0"
SOURCES="https://github.com/kreatolinux/src/archive/refs/tags/v$VERSION.tar.gz"
BUILD_DEPENDS="nim"
DEPENDS="libarchive shadow openssl git"
SHA256SUM="ce96dcdf03970c45005e10c8a7e2036277438a511cbd8f29916449a2b6bbd1c5  v5.0.0.tar.gz"
DESCRIPTION="Kreato Linux's Init system/Service manager"

build() {
        nimble install cligen fusion -y
        nim c -d:release --threads:on -o="out/jumpstart" "jumpstart/jumpstart.nim"
        nim c -d:release --threads:on -o="out/jumpctl" "jumpstart/jumpctl.nim"
}

package() {
        mkdir -p "$ROOT/bin"
        cp out/jumpctl "$ROOT/bin/"
        cp out/jumpstart "$ROOT/bin"
}
