#!/bin/sh
NAME="webp-pixbuf-loader"
RELEASE="2"
VERSION="0.2.7"
SOURCES="https://github.com/aruiz/webp-pixbuf-loader/archive/refs/tags/$VERSION.tar.gz"
DEPENDS="libwebp gdk-pixbuf"
BUILD_DEPENDS="meson"
SHA256SUM="54f448383d1c384409bd1690cdde9b44535c346855902e29bd37a18a7237c547"
DESCRIPTION="Library that allows gdk-pixbuf to load WebP images"

build() {
    meson setup \
        --prefix=/usr \
	--buildtype=release \
        build/
    ninja -C build/
}

package() {
    DESTDIR=$ROOT ninja -C build/ install
}

postinstall() {
  gdk-pixbuf-query-loaders --update-cache
}
