#!/bin/sh
NAME="webp-pixbuf-loader"
RELEASE="2"
VERSION="0.2.7"
SOURCES="https://github.com/aruiz/webp-pixbuf-loader/archive/refs/tags/$VERSION.tar.gz"
DEPENDS="libwebp gdk-pixbuf"
BUILD_DEPENDS="meson"
SHA256SUM="61ce5e8e036043f9d0e78c1596a621788e879c52aedf72ab5e78a8c44849411a"
DESCRIPTION="Library that allows gdk-pixbuf to load WebP images"

build() {
    meson setup \
        --prefix=/usr \
	--buildtype=release \
        build/
    ninja -C build/
}

package() {
    DESTDIR=$ROOT ninja -C build/ install
}

postinstall() {
  gdk-pixbuf-query-loaders --update-cache
}
