#!/bin/sh
NAME="webp-pixbuf-loader"
RELEASE="2"
VERSION="0.2.5"
SOURCES="https://github.com/aruiz/webp-pixbuf-loader/archive/refs/tags/$VERSION.tar.gz"
DEPENDS="libwebp gdk-pixbuf"
BUILD_DEPENDS="meson"
SHA256SUM="e1b76c538a1d3b3fc41323d044c7c84365ab9bd5ab3dcc8de7efb0c7dc2f206b"
DESCRIPTION="Library that allows gdk-pixbuf to load WebP images"

build() {
    meson setup \
        --prefix=/usr \
	--buildtype=release \
        build/
    ninja -C build/
}

package() {
    DESTDIR=$ROOT ninja -C build/ install
}

postinstall() {
  gdk-pixbuf-query-loaders --update-cache
}
