#!/bin/sh
NAME="xdg-desktop-portal-gtk"
RELEASE="1"
VERSION="1.15.3"
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/flatpak/xdg-desktop-portal-gtk/releases/download/$VERSION/xdg-desktop-portal-gtk-$VERSION.tar.xz"
DEPENDS="xdg-desktop-portal gtk3"
SHA256SUM="47a3743d2419a8601e691db37e85bb5fac5ae4b26842177065cd5f22ada23b37"
DESCRIPTION="GTK backend for xdg-desktop-portal"

build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
