#!/bin/sh
NAME="xdg-desktop-portal-gtk"
RELEASE="1"
VERSION="1.15.1"
SOURCES="https://github.com/flatpak/xdg-desktop-portal-gtk/releases/download/$VERSION/xdg-desktop-portal-gtk-$VERSION.tar.xz"
DEPENDS="xdg-desktop-portal gtk3"
SHA256SUM="425551ca5f36451d386d53599d95a3a05b94020f1a4927c5111a2c3ba3a0fe4c"
DESCRIPTION="GTK backend for xdg-desktop-portal"

build() {
    ./configure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
