#!/bin/sh
NAME="xdg-utils"
RELEASE="1"
VERSION="1.1.3"
SOURCES="https://portland.freedesktop.org/download/xdg-utils-$VERSION.tar.gz"
BUILD_DEPENDS="xmlto"
SHA256SUM="d798b08af8a8e2063ddde6c9fa3398ca81484f27dec642c5627ffcaa0d4051d9  xdg-utils-1.1.3.tar.gz"
DESCRIPTION="A set of tools that allows applications to easily integrate with the desktop environment of the user"

build() {
    ./configure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
