#!/bin/sh
NAME="libzstd"
RELEASE="1"
VERSION="1.5.1"
SOURCES="https://github.com/facebook/zstd/releases/download/v$VERSION/zstd-$VERSION.tar.gz"
DEPENDS=""
SHA256SUM="e28b2f2ed5710ea0d3a1ecac3f6a947a016b972b9dd30242369010e5f53d7002"
DESCRIPTION="Facebook's zstd library"

build() {
    make
}

package() {
    make DESTDIR=$ROOT prefix=/usr install
}
