#!/bin/sh
NAME="gobject-introspection"
RELEASE="4"
VERSION="1.86.0"
SOURCES="https://gitlab.gnome.org/GNOME/gobject-introspection/-/archive/$VERSION/gobject-introspection-$VERSION.tar.gz"
BUILD_DEPENDS="meson ninja python-setuptools python-packaging"
DEPENDS="python glib"
SHA256SUM="eadae02135e96ad40221b4a9eb5e168f8c70ef3f697485c38345a3638adf51a2"
DESCRIPTION="Introspection system for GObject-based libraries"

build() {
    meson setup \
    --prefix=/usr \
    -D tests=false \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}

postinstall() {
    [ -d /usr/share/glib-2.0/schemas ] && glib-compile-schemas /usr/share/glib-2.0/schemas || true
}
