#!/bin/sh
NAME="gobject-introspection"
RELEASE="1"
VERSION="1.75.2"
SOURCES="https://gitlab.gnome.org/GNOME/gobject-introspection/-/archive/$VERSION/gobject-introspection-$VERSION.tar.gz" 
BUILD_DEPENDS="meson ninja"
DEPENDS="python cairo glib"
SHA256SUM="8d71eb79564f2758ae09b935e277a911cf902c0bea25ef3766b93b755e17aac3  gobject-introspection-1.75.2.tar.gz"
DESCRIPTION="gobject-introspection"

build() {
    meson \
    --prefix=/usr \
    -Dman=false \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
