#!/bin/sh
NAME="OpenJPEG"
RELEASE="1"
VERSION="2.5.0"
SOURCES="https://github.com/uclouvain/openjpeg/archive/v$VERSION/openjpeg-$VERSION.tar.gz"
BUILD_DEPENDS="cmake ninja"
SHA256SUM="0333806d6adecc6f7a91243b2b839ff4d2053823634d4f6ed7a59bc87409122a"
DESCRIPTION="Implementation of JPEG-2000"

build() {
    cmake -B build \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DBUILD_STATIC_LIBS=OFF \
      -G Ninja
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
