#!/bin/sh
NAME="btrfs-progs"
RELEASE="1"
VERSION="6.1.2"
SOURCES="https://mirrors.edge.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v$VERSION.tar.xz"
SHA256SUM="58cb8efab367458e1d0306bc58fc7164d2ab4f3f59c7ffd40bddee4bad1d88a8  btrfs-progs-v6.1.2.tar.gz"
DESCRIPTION="BTRFS filesystem utilities"

build() {
    cd btrfs-progs-v$VERSION
    ./configure --disable-documentation --prefix=/usr
    make -j$(nproc)
    make install
}
