#!/bin/sh
NAME="wlroots"
RELEASE="1"
VERSION="0.17.0"
SOURCES="https://gitlab.freedesktop.org/wlroots/wlroots/-/archive/$VERSION/wlroots-$VERSION.tar.gz"
BUILD_DEPENDS="meson samurai"
DEPENDS="wayland wayland-protocols libdrm libxkbcommon libinput hwdata seatd pixman libudev mesa"
SHA256SUM="0db3bd4854c233409f881fa1ccd7936eee2f3633454a1dbdcaf834f49e231149"
DESCRIPTION="Modules for building a Wayland compositor"
build() {
    meson --prefix=/usr build/
    ninja -C build/
}

package() {
    DESTDIR=$ROOT ninja -C build/ install
}
