#!/bin/sh
NAME="wlroots"
RELEASE="1"
VERSION="0.16.2"
SOURCES="https://gitlab.freedesktop.org/wlroots/wlroots/-/archive/$VERSION/wlroots-$VERSION.tar.gz"
BUILD_DEPENDS="meson samurai"
DEPENDS="wayland wayland-protocols libdrm libxkbcommon libinput hwdata seatd pixman libudev mesa"
SHA256SUM="f502959db8bc029e32f10a837b37257bb8c5ed269bceddf9492f0bb381bebf76"
DESCRIPTION="Modules for building a Wayland compositor"
build() {
    meson --prefix=/usr build/
    ninja -C build/
}

package() {
    DESTDIR=$ROOT ninja -C build/ install
}
