#!/bin/sh
NAME="wlroots"
RELEASE="1"
VERSION="0.16.1"
SOURCES="https://gitlab.freedesktop.org/wlroots/wlroots/-/releases/$VERSION/downloads/wlroots-$VERSION.tar.gz"
SHA256SUM="130a1a86f6f8c4fa162ba4db82aaa70850273c5d01313b242baa0144e3d6d253  wlroots-0.16.1.tar.gz"
DESCRIPTION="Modules for building a Wayland compositor"
build() {
    meson --prefix=/usr build/
    ninja -C build/
}

install() {
    DESTDIR=$ROOT ninja -C build/ install
}
