#!/bin/sh
NAME="btop"
RELEASE="1"
VERSION="1.4.5"
SOURCES="https://github.com/aristocratos/btop/archive/refs/tags/v$VERSION.tar.gz"
BUILD_DEPENDS="gmake"
SHA256SUM="0ffe03d3e26a3e9bbfd5375adf34934137757994f297d6b699a46edd43c3fc02"
DESCRIPTION="htop alternative"

build() {
    make
}

package() {
    make DESTDIR=$ROOT PREFIX=/usr install 
}
