#!/bin/sh
NAME="kbd"
RELEASE="1"
VERSION="2.8.0"
SOURCES="https://git.kernel.org/pub/scm/linux/kernel/git/legion/kbd.git/snapshot/kbd-$VERSION.tar.gz"
BUILD_DEPENDS="autoconf automake gettext libtool gmake"
SHA256SUM="f5c7be3fd5365bd5150a3293cff58f836acc2b5914515c1ca91540a7f9be50f7"
DESCRIPTION="Linux keyboard tools"

build() {
    autoreconf -v -f -i
    kpkgConfigure --prefix=/usr --disable-vlock --bindir=/usr/bin
    make
}

package() {
    make DESTDIR=$ROOT install
}
