#!/bin/sh
NAME="kbd"
RELEASE="1"
VERSION="2.8.0"
SOURCES="https://git.kernel.org/pub/scm/linux/kernel/git/legion/kbd.git/snapshot/kbd-$VERSION.tar.gz"
BUILD_DEPENDS="autoconf automake gettext libtool gmake"
SHA256SUM="001ebe04b336406207e35fb513ba4fc329c11fb6fc18ac3da854fa49e74225e5"
DESCRIPTION="Linux keyboard tools"

build() {
    autoreconf -v -f -i
    kpkgConfigure --prefix=/usr --disable-vlock --bindir=/usr/bin
    make
}

package() {
    make DESTDIR=$ROOT install
}
