#!/bin/sh
NAME="polkit"
RELEASE="1"
VERSION="126"
SOURCES="https://gitlab.freedesktop.org/polkit/polkit/-/archive/$VERSION/polkit-$VERSION.tar.gz"
DEPENDS="elogind linux-pam glib gobject-introspection expat dbus duktape"
BUILD_DEPENDS="meson"
SHA256SUM="SKIP"
DESCRIPTION="A toolkit for defining and handling authorizations"

build() {
    
    if command -v systemctl > /dev/null; then
      extraArgs="-Dsession_tracking=libsystemd-login"
    fi

    meson setup $extraArgs \
    --prefix=/usr \
    --buildtype=release \
    -Dman=false \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}

postinstall() {
  # From BLFS
  groupadd -fg 27 polkitd &&
  if ! id -u "polkitd" >/dev/null 2>&1; then
  	useradd -c "PolicyKit Daemon Owner" -d /etc/polkit-1 -u 27 \
        	-g polkitd -s /bin/false polkitd
  fi
}
