#!/bin/sh
NAME="msgpack-c"
RELEASE="1"
VERSION="6.0.2"
DESCRIPTION="MessagePack for C"
SOURCES="https://github.com/msgpack/msgpack-c/releases/download/c-6.0.2/msgpack-c-6.0.2.tar.gz"
BUILD_DEPENDS="cmake gmake"
DEPENDS=""
SHA256SUM="5e90943f6f5b6ff6f4bda9146ada46e7e455af3a77568f6d503f35618c1b2a12"

build() {
    cmake -DCMAKE_INSTALL_PREFIX=/usr .
    make
}

package() {
    make DESTDIR=$ROOT install
}
