#!/bin/sh
NAME="msgpack-c"
RELEASE="1"
VERSION="6.0.1"
DESCRIPTION="MessagePack for C"
SOURCES="https://github.com/msgpack/msgpack-c/releases/download/c-6.0.1/msgpack-c-6.0.1.tar.gz"
BUILD_DEPENDS="cmake gmake"
DEPENDS=""
SHA256SUM="a349cd9af28add2334c7009e331335af4a5b97d8558b2e9804d05f3b33d97925"

build() {
    cmake -DCMAKE_INSTALL_PREFIX=/usr .
    make
}

package() {
    make DESTDIR=$ROOT install
}
