#!/bin/sh
NAME="msgpack-c"
RELEASE="1"
VERSION="5.0.0"
DESCRIPTION="MessagePack for C"
SOURCES="https://github.com/msgpack/msgpack-c/releases/download/c-5.0.0/msgpack-c-5.0.0.tar.gz"
BUILD_DEPENDS="cmake"
DEPENDS=""
SHA256SUM="eb6d77f32dbaaae9174d96cacfe02af30bf1ea329c45018074cd95ac6e6fa6e5  msgpack-c-5.0.0.tar.gz"

build() {
    cmake -DCMAKE_INSTALL_PREFIX=/usr .
    make
}

package() {
    make DESTDIR=$ROOT install
}
