#!/bin/sh
NAME="dconf"
RELEASE="1"
VERSION="0.49.0"
SOURCES="https://gitlab.gnome.org/GNOME/dconf/-/archive/$VERSION/dconf-$VERSION.tar.gz"
DEPENDS="dbus glib vala"
BUILD_DEPENDS="meson python-setuptools"
SHA256SUM="5269517a1aa4edf0f7a728e0dde8c9b0facd58cefbdae851eb96434459b91495"
DESCRIPTION="A simple key/value storage system that is heavily optimised for reading"

build() {
    meson setup \
    --prefix=/usr \
    -Dbash_completion=false \
    --buildtype=release \
    -Dman=false \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
