#!/bin/sh
NAME="dconf"
RELEASE="1"
VERSION="0.40.0"
SOURCES="https://gitlab.gnome.org/GNOME/dconf/-/archive/$VERSION/dconf-$VERSION.tar.gz"
DEPENDS="dbus glib"
BUILD_DEPENDS="meson"
SHA256SUM="c144c314a5ab1b0e2c2e5cb381658d19b9577511b62db5df3fac463028b61bca  dconf-0.40.0.tar.gz"
DESCRIPTION="A simple key/value storage system that is heavily optimised for reading"

build() {
    meson setup \
    --prefix=/usr \
    -Dbash_completion=false \
    --buildtype=release \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
