#!/bin/sh
NAME="dbus"
RELEASE="6"
VERSION="1.16.2"
SOURCES="https://dbus.freedesktop.org/releases/dbus/dbus-$VERSION.tar.xz"
DEPENDS="expat"
BUILD_DEPENDS="python-setuptools gmake"
SHA256SUM="0ba2a1a4b16afe7bceb2c07e9ce99a8c2c3508e5dec290dbb643384bd6beb7e2"
DESCRIPTION="Message bus system"

build() {

    if command -v systemctl > /dev/null; then
      extraArgs="--enable-systemd"
    fi 

    kpkgConfigure $extraArgs --disable-static \
                --prefix=/usr    \
                --runstatedir=/run \
                --sysconfdir=/etc \
                --enable-user-session
    make
}

package() {
    make DESTDIR="$ROOT" install
}
