#!/bin/sh
NAME="dbus"
RELEASE="6"
VERSION="1.16.2"
SOURCES="https://dbus.freedesktop.org/releases/dbus/dbus-$VERSION.tar.xz"
DEPENDS="expat"
BUILD_DEPENDS="python-setuptools gmake"
SHA256SUM="ba1f21d2bd9d339da2d4aa8780c09df32fea87998b73da24f49ab9df1e36a50f"
DESCRIPTION="Message bus system"

build() {

    if command -v systemctl > /dev/null; then
      extraArgs="--enable-systemd"
    fi 

    kpkgConfigure $extraArgs --disable-static \
                --prefix=/usr    \
                --runstatedir=/run \
                --sysconfdir=/etc \
                --enable-user-session
    make
}

package() {
    make DESTDIR="$ROOT" install
}
