#!/bin/sh
NAME="geocode-glib"
RELEASE="1"
VERSION="3.26.4"
SOURCES="https://github.com/GNOME/geocode-glib/archive/refs/tags/$VERSION.tar.gz"
DEPENDS="glib libsoup json-glib"
BUILD_DEPENDS="meson"
SHA256SUM="cd4464f74add58584f04e6a7f16347f07caf271509e0b7ef067a4170b74518c9  3.26.4.tar.gz"
DESCRIPTION="geocode-glib"

build() {
    meson setup --prefix /usr --buildtype=release -Denable-gtk-doc=false -Dsoup2=false build/
    meson compile -C build 
}

package() {
    meson install --destdir "$ROOT" -C build/
}
