#!/bin/sh
NAME="json-glib"
RELEASE="1"
VERSION="1.10.8"
SOURCES="https://download.gnome.org/sources/json-glib/1.10/json-glib-$VERSION.tar.xz" 
BUILD_DEPENDS="meson ninja gobject-introspection"
DEPENDS="glib"
SHA256SUM="55c5c141a564245b8f8fbe7698663c87a45a7333c2a2c56f06f811ab73b212dd"
DESCRIPTION="A full JSON parser and generator using GLib and GObject, and integrates JSON with GLib data types"

build() {
    meson \
    --prefix=/usr \
    -Dman=false \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}

postinstall() {
    glib-compile-schemas /usr/share/glib-2.0/schemas
}
