#!/bin/sh
NAME="pulseaudio"
RELEASE="1"
VERSION="17.0"
SOURCES="https://www.freedesktop.org/software/pulseaudio/releases/pulseaudio-$VERSION.tar.xz"
BUILD_DEPENDS="meson"
DEPENDS="libsndfile libtool gdbm alsa-lib dbus elogind glib"
OPTDEPENDS="bluez: for Bluetooth support"
SHA256SUM="053794d6671a3e397d849e478a80b82a63cb9d8ca296bd35b73317bb5ceb87b5"
DESCRIPTION="Sound system"

build() {

    if command -v bluetoothctl > /dev/null; then
      bluez5="enabled"
    else
      bluez5="disabled"
    fi
    
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Dman=false \
    -Ddoxygen=false \
    -Dtests=false \
    -Ddatabase=gdbm     \
    -Dbluez5=$bluez5 \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
