#!/bin/sh
NAME="libtextstyle"
RELEASE="1"
VERSION="0.22"
SOURCES="https://ftp.gnu.org/gnu/gettext/gettext-$VERSION.tar.xz"
SHA256SUM="0e60393a47061567b46875b249b7d2788b092d6457d656145bb0e7e6a3e26d93  gettext-0.22.tar.xz"
DESCRIPTION="A part of gettext."

build() {
    cd libtextstyle
    ./configure --prefix=/usr
    make -j$(nproc)
}

install() {
    cd libtextstyle
    make DESTDIR=$ROOT install
}
