#!/bin/sh
NAME="ninja"
RELEASE="1"
VERSION="1.12.1"
SOURCES="https://github.com/ninja-build/ninja/archive/refs/tags/v$VERSION.tar.gz"
SHA256SUM="821bdff48a3f683bc4bb3b6f0b5fe7b2d647cf65d52aeb63328c91a6c6df285a"
REPLACES="samurai"
BUILD_DEPENDS="python"
DESCRIPTION="a small build tool with a focus on speed"

build() {
    python configure.py --bootstrap
}

package() {
    mkdir -p "$ROOT/usr/bin"
    mv ninja "$ROOT/usr/bin"
    ln -s /usr/bin/ninja "$ROOT/usr/bin/samu"
}
