#!/bin/sh
NAME="ninja"
RELEASE="1"
VERSION="1.11.1"
SOURCES="https://github.com/ninja-build/ninja/archive/refs/tags/v$VERSION.tar.gz"
SHA256SUM="31747ae633213f1eda3842686f83c2aa1412e0f5691d1c14dbbcc67fe7400cea  v1.11.1.tar.gz"
REPLACES="samurai"
BUILD_DEPENDS="python"
DESCRIPTION="a small build tool with a focus on speed"

build() {
    python configure.py --bootstrap
}

package() {
    mkdir -p "$ROOT/usr/bin"
    mv ninja "$ROOT/usr/bin"
    ln -s /usr/bin/ninja "$ROOT/usr/bin/samu"
}
