#!/bin/sh
NAME="ninja"
RELEASE="1"
VERSION="1.12.0"
SOURCES="https://github.com/ninja-build/ninja/archive/refs/tags/v$VERSION.tar.gz"
SHA256SUM="8b2c86cd483dc7fcb7975c5ec7329135d210099a89bc7db0590a07b0bbfe49a5"
REPLACES="samurai"
BUILD_DEPENDS="python"
DESCRIPTION="a small build tool with a focus on speed"

build() {
    python configure.py --bootstrap
}

package() {
    mkdir -p "$ROOT/usr/bin"
    mv ninja "$ROOT/usr/bin"
    ln -s /usr/bin/ninja "$ROOT/usr/bin/samu"
}
