#!/bin/sh
NAME="libffi"
RELEASE="1"
VERSION=3.5.2
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/libffi/libffi/releases/download/v$VERSION/libffi-$VERSION.tar.gz"
SHA256SUM="f3a3082a23b37c293a4fcd1053147b371f2ff91fa7ea1b2a52e335676bac82dc"
DESCRIPTION="A portable foreign-function interface library."

build() {
    export CFLAGS="$CFLAGS -Wno-implicit-function-declaration"
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT prefix=/usr install
    rm -rf "$ROOT/usr/share/info/dir"
}
