#!/bin/sh
NAME="libffi"
VERSION="3.4.2"
SOURCES="https://github.com/libffi/libffi/releases/download/v$VERSION/libffi-$VERSION.tar.gz"
SHA256SUM="540fb721619a6aba3bdeef7d940d8e9e0e6d2c193595bc243241b77ff9e93620  libffi-3.4.2.tar.gz"
DESCRIPTION=""

build() {
    tar -xvf libffi-$VERSION.tar.gz
    cd libffi-$VERSION || exit 1
    ./configure
    make
    make DESTDIR=$ROOT prefix=/usr install
}
