#!/bin/sh
NAME="colord-gtk"
RELEASE="1"
VERSION="0.3.1"
SOURCES="https://www.freedesktop.org/software/colord/releases/colord-gtk-$VERSION.tar.xz"
BUILD_DEPENDS="meson lcms2 gtk3 gobject-introspection"
DEPENDS="gtk4 colord"
SHA256SUM="c176b889b75630a17f4e3d7ef24c09a3e12368e633496087459c8b53ac3a122d"
DESCRIPTION="GTK stuff for colord"

build() {
    
    meson setup \
    --buildtype=release \
    --prefix=/usr \
    -Dgtk4=true \
    -Dvapi=true \
    -Ddocs=false \
    -Dman=false \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
