#!/bin/sh
NAME="libxfont2"
RELEASE="1"
VERSION="2.0.6"
SOURCES="https://www.x.org/releases/individual/lib/libXfont2-$VERSION.tar.xz"
SHA256SUM="74ca20017eb0fb3f56d8d5e60685f560fc85e5ff3d84c61c4cb891e40c27aef4  libXfont2-2.0.6.tar.xz"
DEPENDS="freetype xorgproto"
BUILD_DEPENDS="xtrans"
DESCRIPTION="X11 font rasterisation library"

build() {
    ./configure \
        --prefix=/usr \
        --sysconfdir=/etc \
        --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
