#!/bin/sh
NAME="libxfont2"
RELEASE="1"
VERSION="2.0.7"
SOURCES="https://www.x.org/releases/individual/lib/libXfont2-$VERSION.tar.xz"
SHA256SUM="8b7b82fdeba48769b69433e8e3fbb984a5f6bf368b0d5f47abeec49de3e58efb"
DEPENDS="libfontenc freetype xorgproto"
BUILD_DEPENDS="xtrans gmake"
DESCRIPTION="X11 font rasterisation library"

build() {
    kpkgConfigure \
        --prefix=/usr \
        --sysconfdir=/etc \
        --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
