#!/bin/sh
NAME="libsoup"
RELEASE="1"
VERSION="3.4.3"
SOURCES="https://download.gnome.org/sources/libsoup/3.4/libsoup-$VERSION.tar.xz"
BUILD_DEPENDS="meson"
DEPENDS="glib glib-networking libxml2 nghttp2 sqlite gobject-introspection vala libpsl"
SHA256SUM="b7f1bbaeeb43f5812daba3ee258a72e1b4b14c2fd91f4a1a75d4eea10dcf288f  libsoup-3.4.3.tar.xz"
DESCRIPTION="libsoup"

build() {
    # Got options from https://www.linuxfromscratch.org/blfs/view/svn/basicnet/libsoup3.html
    meson setup --prefix=/usr          \
            --buildtype=release    \
            -Dvapi=enabled         \
            -Dgssapi=disabled      \
            -Dsysprof=disabled     \
            --wrap-mode=nofallback \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
