#!/bin/sh
NAME="libsoup"
RELEASE="1"
VERSION="3.4.4"
SOURCES="https://download.gnome.org/sources/libsoup/3.4/libsoup-$VERSION.tar.xz"
BUILD_DEPENDS="meson"
DEPENDS="glib glib-networking libxml2 nghttp2 sqlite gobject-introspection vala libpsl"
SHA256SUM="291c67725f36ed90ea43efff25064b69c5a2d1981488477c05c481a3b4b0c5aa"
DESCRIPTION="libsoup"

build() {
    # Got options from https://www.linuxfromscratch.org/blfs/view/svn/basicnet/libsoup3.html
    meson setup --prefix=/usr          \
            --buildtype=release    \
            -Dvapi=enabled         \
            -Dgssapi=disabled      \
            -Dsysprof=disabled     \
            --wrap-mode=nofallback \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
