#!/bin/sh
NAME="expat"
RELEASE="1"
VERSION="2.7.3"
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/libexpat/libexpat/releases/download/R_2_5_0/expat-$VERSION.tar.xz"
DEPENDS=""
SHA256SUM="SKIP"
DESCRIPTION="a stream oriented C library for parsing XML"

build() {
    kpkgConfigure --prefix=/usr --disable-static
    make -j$(nproc)
}

package() {
    make DESTDIR=$ROOT install
}

