#!/bin/sh
NAME="expat"
RELEASE="1"
VERSION="2.5.0"
SOURCES="https://github.com/libexpat/libexpat/releases/download/R_2_5_0/expat-$VERSION.tar.xz"
SHA256SUM="ef2420f0232c087801abf705e89ae65f6257df6b7931d37846a193ef2e8cdcbe  expat-2.5.0.tar.xz"
DESCRIPTION="a stream oriented C library for parsing XML"

build() {
    ./configure --prefix=/usr --disable-static
    make -j$(nproc)
}

install() {
    make DESTDIR=$ROOT install
}

