#!/bin/sh
NAME="libogg"
RELEASE="1"
VERSION="1.3.6"
BUILD_DEPENDS="gmake"
SOURCES="https://downloads.xiph.org/releases/ogg/libogg-$VERSION.tar.xz"
SHA256SUM="5c8253428e181840cd20d41f3ca16557a9cc04bad4a3d04cce84808677fa1061"
DESCRIPTION="Ogg container format libraries"

build() {
    kpkgConfigure --prefix=/usr \
                --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
