#!/bin/sh
NAME="cpio"
RELEASE="1"
VERSION="2.15"
BUILD_DEPENDS="gmake"
SOURCES="https://ftp.gnu.org/gnu/cpio/cpio-$VERSION.tar.gz"
DEPENDS=""
SHA256SUM="efa50ef983137eefc0a02fdb51509d624b5e3295c980aa127ceee4183455499e"
DESCRIPTION="GNU cpio"
REPO_DIR="/etc/kpkg/repos/main"
build() {
    patch -p1 < $REPO_DIR/$NAME/patches/0001-src-global.c-drop-duplicate-definition-of-program_na.patch
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
