#!/bin/sh
NAME="cpio"
VERSION="2.13"
SOURCES="https://ftp.gnu.org/gnu/cpio/cpio-$VERSION.tar.gz"
SHA256SUM="e87470d9c984317f658567c03bfefb6b0c829ff17dbf6b0de48d71a4c8f3db88  cpio-2.13.tar.gz"
DESCRIPTION="GNU cpio"
build() {
    [ ! -d "cpio-$VERSION" ] && tar -xvf cpio-$VERSION.tar.gz
    cd cpio-$VERSION || exit  1
    ./configure --prefix=/usr
    make
    make DESTDIR=$ROOT install
}
