#!/bin/sh
NAME="limine"
RELEASE="1"
VERSION="5.20230709.0"
SOURCES="https://github.com/limine-bootloader/limine/releases/download/v$VERSION/limine-$VERSION.tar.xz"
SHA256SUM="36a5f3977adfea274e410f4fcfff00de77ef43631d2176baaf2a8b232f5fd59d  limine-5.20230709.0.tar.xz"
DESCRIPTION="Modern, advanced, portable, multiprotocol bootloader."

build() {
    ./configure --prefix=/usr --enable-bios --enable-uefi-x86-64
    make
}

install() {
    make DESTDIR="$ROOT" install
}
