#!/bin/sh
NAME="limine"
RELEASE="1"
VERSION="7.7.1"
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/limine-bootloader/limine/releases/download/v$VERSION/limine-$VERSION.tar.xz"
DEPENDS="efibootmgr nasm"
SHA256SUM="ab6814d36c890cd6843716b83da5467290dadd13d96df03fc2610d0afc466e5e"
DESCRIPTION="Modern, advanced, portable, multiprotocol bootloader."

build() {
    kpkgConfigure --prefix=/usr --enable-bios --enable-uefi-x86-64
    make
}

package() {
    make DESTDIR="$ROOT" install
}
