#!/bin/sh
NAME="limine"
RELEASE="1"
VERSION="5.20230801.0"
SOURCES="https://github.com/limine-bootloader/limine/releases/download/v$VERSION/limine-$VERSION.tar.xz"
SHA256SUM="d7bd6389491ec63303dbcf77e32e77250f62bd10839278957681c1d6613d8ca6  limine-5.20230801.0.tar.xz"
DESCRIPTION="Modern, advanced, portable, multiprotocol bootloader."

build() {
    ./configure --prefix=/usr --enable-bios --enable-uefi-x86-64
    make
}

install() {
    make DESTDIR="$ROOT" install
}
