#!/bin/sh
NAME="nano"
RELEASE="1"
VERSION="7.1"
SOURCES="https://nano-editor.org/dist/v7/nano-7.1.tar.gz"
SHA256SUM="d03f2fcf536e709edcfc7db882f4b60f198726585df5f1c48f7f7097f3622322  nano-7.1.tar.gz"
DESCRIPTION="Text editor with a TUI and intuitive keybinds"
build() {
    cd nano-$VERSION || exit  1
    ./configure
    make
    make DESTDIR=$ROOT PREFIX=/usr install 
}

