#!/bin/sh
NAME="booster"
RELEASE="1"
VERSION="0.12"
SOURCES="https://github.com/anatol/booster/archive/refs/tags/$VERSION.tar.gz"
BUILD_DEPENDS="go"
DEPENDS=""
SHA256SUM="a2515923e919c99b69ce50f7828aa5df6e7ff80ea145c93c5a8c981d015d8bd4"
DESCRIPTION="fast and secure initramfs generator"

build() {
    cd init
    go build
    cd ../generator
    go build
}

package() {
    # Taken from https://github.com/anatol/booster/blob/master/packaging/arch/PKGBUILD
    env install -Dp -m755 generator/generator "$DESTDIR/usr/bin/booster"
    env install -Dp -m755 init/init "$DESTDIR/usr/lib/booster/init"
}
