#!/bin/sh
NAME="libxcrypt"
RELEASE="1"
VERSION="4.4.33"
SOURCES="https://github.com/besser82/libxcrypt/releases/download/v$VERSION/libxcrypt-$VERSION.tar.xz"
SHA256SUM="e87acf9c652c573a4713d5582159f98f305d56ed5f754ce64f57d4194d6b3a6f  libxcrypt-4.4.33.tar.xz"
DESCRIPTION="Extended crypt library"

build() {
    ./configure --disable-obsolete-api --prefix=/usr
    /usr/lib/libcrypt.so.2
    make
}

install() {
    make DESTDIR="$ROOT" install
    mkdir -p "$ROOT/usr/lib"
}
