#!/bin/sh
NAME="libxcrypt"
RELEASE="1"
VERSION="4.4.36"
SOURCES="https://github.com/besser82/libxcrypt/releases/download/v$VERSION/libxcrypt-$VERSION.tar.xz"
DEPENDS=""
SHA256SUM="e5e1f4caee0a01de2aee26e3138807d6d3ca2b8e67287966d1fefd65e1fd8943"
DESCRIPTION="Extended crypt library"

build() {
    ./configure --disable-obsolete-api --prefix=/usr
    /usr/lib/libcrypt.so.2
    make
}

package() {
    make DESTDIR="$ROOT" install
    mkdir -p "$ROOT/usr/lib"
}
