#!/bin/sh
NAME="libidn2"
RELEASE="1"
VERSION="2.3.7"
SOURCES="https://ftp.gnu.org/gnu/libidn/libidn2-$VERSION.tar.gz"
DEPENDS="libunistring"
SHA256SUM="4c21a791b610b9519b9d0e12b8097bf2f359b12f8dd92647611a929e6bfd7d64"
DESCRIPTION="libidn2"
build() {
    kpkgConfigure --prefix=/usr \
	    	--disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
