#!/bin/sh
NAME="libidn2"
RELEASE="1"
VERSION="2.3.8"
BUILD_DEPENDS="gmake"
SOURCES="https://ftp.gnu.org/gnu/libidn/libidn2-$VERSION.tar.gz"
DEPENDS="libunistring"
SHA256SUM="f557911bf6171621e1f72ff35f5b1825bb35b52ed45325dcdee931e5d3c0787a"
DESCRIPTION="libidn2"
build() {
    kpkgConfigure --prefix=/usr \
	    	--disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
