#!/bin/sh
NAME="adwaita-icon-theme"
RELEASE="1"
VERSION="49.0"
SOURCES="https://download.gnome.org/sources/adwaita-icon-theme/49/adwaita-icon-theme-$VERSION.tar.xz"
BUILD_DEPENDS="meson"
DEPENDS="librsvg gtk3 hicolor-icon-theme"
SHA256SUM="65166461d1b278aa942f59aa8d0fccf1108d71c65f372c6266e172449791755c"
DESCRIPTION="adwaita-icon-theme"

build() {
    meson setup --prefix=/usr build
    ninja -C build
}

package() {
    DESTDIR=$ROOT ninja -C build install
}
