#!/bin/sh
NAME="iso-codes"
RELEASE="1"
VERSION="4.16.0"
SOURCES="https://ftp.debian.org/debian/pool/main/i/iso-codes/iso-codes_$VERSION.orig.tar.xz"
BUILD_DEPENDS="python"
SHA256SUM="d37ff1b2b76e63926e8043b42e0ff806bb4e41e2a57d93c9d4ec99c06b409530"
DESCRIPTION="Provides lists of various ISO standards (countries, languages, language scripts, and currency names) in one place"

build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
