#!/bin/sh
NAME="iso-codes"
RELEASE="1"
VERSION="4.15.0"
SOURCES="https://ftp.debian.org/debian/pool/main/i/iso-codes/iso-codes_$VERSION.orig.tar.xz"
BUILD_DEPENDS="python"
SHA256SUM="3d50750bf1d62d83b6085f5815ceb8392df34266a15f16bcf8d4cf7eb15d245c"
DESCRIPTION="Provides lists of various ISO standards (countries, languages, language scripts, and currency names) in one place"

build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
