#!/bin/sh
NAME="iso-codes"
RELEASE="1"
VERSION="4.16.0"
SOURCES="https://ftp.debian.org/debian/pool/main/i/iso-codes/iso-codes_$VERSION.orig.tar.xz"
BUILD_DEPENDS="python gmake"
SHA256SUM="SKIP"
DESCRIPTION="Provides lists of various ISO standards (countries, languages, language scripts, and currency names) in one place"

build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
