#!/bin/sh
NAME="libhandy"
RELEASE="1"
VERSION="1.8.3"
SOURCES="https://gitlab.gnome.org/GNOME/libhandy/-/archive/$VERSION/libhandy-$VERSION.tar.gz"
DEPENDS="glib gtk3"
BUILD_DEPENDS="meson vala gobject-introspection"
SHA256SUM="7e7670f5d0a6d0adc24b888da44dab938a6f52472b8944d6dd4e31b6d3569a5f"
DESCRIPTION="Building blocks for modern adaptive GNOME apps"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
