#!/bin/sh
NAME="yajl"
RELEASE="1"
VERSION="2.1.0"
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/lloyd/yajl/archive/refs/tags/$VERSION.tar.gz"
DEPENDS="cmake"
SHA256SUM="3fb73364a5a30efe615046d07e6db9d09fd2b41c763c5f7d3bfb121cd5c5ac5a"
DESCRIPTION="Yet Another JSON Library"

build() {
    mkdir build
    cd build
    cmake -DCMAKE_INSTALL_PREFIX="/usr" ..
    make -j$(nproc)
}

package() {
    cd build
    DESTDIR="$ROOT" make install
}
