#!/bin/sh
NAME="bzip2"
RELEASE="1"
VERSION="1.0.8"
SOURCES="https://sourceware.org/pub/bzip2/bzip2-$VERSION.tar.gz"
SHA256SUM="ab5a03176ee106d3f0fa90e381da478ddae405918153cca248e682cd0c4a2269  bzip2-1.0.8.tar.gz"
DESCRIPTION="A freely available, patent free, high-quality data compressor"
build() {
    make
}

install() {
    make PREFIX=/usr install
}