#!/bin/sh
NAME="bzip2"
RELEASE="3"
VERSION="1.0.8"
SOURCES="https://sourceware.org/pub/bzip2/bzip2-$VERSION.tar.gz"
BUILD_DEPENDS="gmake"
DEPENDS=""
SHA256SUM="ab5a03176ee106d3f0fa90e381da478ddae405918153cca248e682cd0c4a2269"
DESCRIPTION="A freely available, patent free, high-quality data compressor"

build() {
    make -f Makefile-libbz2_so
    make clean
    make
}

package() {
    make PREFIX=$ROOT/usr install
    cp bzip2-shared $ROOT/usr/bin/bzip2
    cp -a libbz2.so* $ROOT/usr/lib
    ln -s libbz2.so.1.0 $ROOT/usr/lib/libbz2.so
}
