#!/bin/sh
NAME="bzip2"
RELEASE="3"
VERSION="1.0.8"
SOURCES="https://sourceware.org/pub/bzip2/bzip2-$VERSION.tar.gz"
BUILD_DEPENDS="gmake"
DEPENDS=""
SHA256SUM="ab5a03176ee106d3f0fa90e381da478ddae405918153cca248e682cd0c4a2269"
DESCRIPTION="A freely available, patent free, high-quality data compressor"

build() {
    make -f Makefile-libbz2_so
    make clean
    make
}

package() {
    # From https://gitlab.archlinux.org/archlinux/packaging/packages/bzip2/-/blob/ee417df2064c7ff4ec317e123d074c6e3213b340/PKGBUILD
    install -dm755 "$DESTDIR"/usr/bin "$DESTDIR"/usr/lib "$DESTDIR"/usr/include "$DESTDIR"/usr/share/man/man1

    install -m755 bzip2-shared "$DESTDIR"/usr/bin/bzip2
    install -m755 bzip2recover bzdiff bzgrep bzmore "$DESTDIR"/usr/bin
    ln -sf bzip2 "$DESTDIR"/usr/bin/bunzip2
    ln -sf bzip2 "$DESTDIR"/usr/bin/bzcat

    cp -a libbz2.so* "$DESTDIR"/usr/lib
    ln -s libbz2.so.$VERSION "$DESTDIR"/usr/lib/libbz2.so
    ln -s libbz2.so.$VERSION "$DESTDIR"/usr/lib/libbz2.so.1 # For compatibility with some other distros

    install -m644 bzlib.h "$DESTDIR"/usr/include/

    install -m644 bzip2.1 "$DESTDIR"/usr/share/man/man1/
    ln -sf bzip2.1 "$DESTDIR"/usr/share/man/man1/bunzip2.1
    ln -sf bzip2.1 "$DESTDIR"/usr/share/man/man1/bzcat.1
    ln -sf bzip2.1 "$DESTDIR"/usr/share/man/man1/bzip2recover.1

    install -Dm644 LICENSE "$DESTDIR"/usr/share/licenses/"$NAME"/LICENSE

}
