#!/bin/sh
NAME="libxshmfence"
RELEASE="1"
VERSION="1.3.3"
SOURCES="https://www.x.org/releases/individual/lib/libxshmfence-$VERSION.tar.gz"
SHA256SUM="6233ccd9fa80198835efc3039cdf8086ab2b218b17e77ebdb0a19913fcee58d3"
BUILD_DEPENDS="xorgproto gmake"
DESCRIPTION="libxshmfence"

build() {
    kpkgConfigure \
        --prefix=/usr \
        --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
