#!/bin/sh
NAME="automake"
RELEASE="1"
VERSION="1.18.1"
BUILD_DEPENDS="gmake"
SOURCES="https://ftp.gnu.org/gnu/automake/automake-$VERSION.tar.gz"
DEPENDS="perl autoconf"
SHA256SUM="63e585246d0fc8772dffdee0724f2f988146d1a3f1c756a3dc5cfbefa3c01915"
DESCRIPTION="GNU Automake"
build() {
    kpkgConfigure --prefix=/usr 
    make
}

package() {
    make DESTDIR=$ROOT install
}
