#!/bin/sh
NAME="automake"
RELEASE="1"
VERSION="1.18.1"
BUILD_DEPENDS="gmake"
SOURCES="https://ftp.gnu.org/gnu/automake/automake-$VERSION.tar.gz"
DEPENDS="perl autoconf"
SHA256SUM="397767d4db3018dd4440825b60c64258b636eaf6bf99ac8b0897f06c89310acd"
DESCRIPTION="GNU Automake"
build() {
    kpkgConfigure --prefix=/usr 
    make
}

package() {
    make DESTDIR=$ROOT install
}
