#!/bin/sh
NAME="automake"
RELEASE="1"
VERSION="1.17"
BUILD_DEPENDS="gmake"
SOURCES="https://ftp.gnu.org/gnu/automake/automake-$VERSION.tar.gz"
DEPENDS="perl autoconf"
SHA256SUM="SKIP"
DESCRIPTION="GNU Automake"
build() {
    kpkgConfigure --prefix=/usr 
    make
}

package() {
    make DESTDIR=$ROOT install
}
