#!/bin/sh
NAME="gsettings-desktop-schemas"
RELEASE="2"
VERSION="46.0"
SOURCES="https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas/-/archive/$VERSION/gsettings-desktop-schemas-$VERSION.tar.gz"
BUILD_DEPENDS="meson ninja"
DEPENDS="cantarell-fonts gobject-introspection"
SHA256SUM="7e61db80e827d0648f58499f505353b319fee2173628afd27c930e1608e15f17"
DESCRIPTION="Contains a collection of GSettings schemas for
settings shared by various components of a desktop"

build() {
    sed -i -r 's:"(/system):"/org/gnome\1:g' schemas/*.in
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}

postinstall() {
  glib-compile-schemas /usr/share/glib-2.0/schemas
}
