#!/bin/sh
NAME="gsettings-desktop-schemas"
RELEASE="2"
VERSION="49.1"
SOURCES="https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas/-/archive/$VERSION/gsettings-desktop-schemas-$VERSION.tar.gz"
BUILD_DEPENDS="meson ninja"
DEPENDS="cantarell-fonts gobject-introspection"
SHA256SUM="97b802b1ce4cda8ce129a36fb675d6f1e4ef8da566e7ba1e8c2e8a97fbc1f213"
DESCRIPTION="Contains a collection of GSettings schemas for
settings shared by various components of a desktop"

build() {
    sed -i -r 's:"(/system):"/org/gnome\1:g' schemas/*.in
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}

postinstall() {
  glib-compile-schemas /usr/share/glib-2.0/schemas
}
