#!/bin/sh
NAME="gsettings-desktop-schemas"
RELEASE="2"
VERSION="49.1"
SOURCES="https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas/-/archive/$VERSION/gsettings-desktop-schemas-$VERSION.tar.gz"
BUILD_DEPENDS="meson ninja"
DEPENDS="cantarell-fonts gobject-introspection"
SHA256SUM="77cbca64af31e243c1bb387f939175f47b6776001fb2f6232f4d2bb1f71bbb71"
DESCRIPTION="Contains a collection of GSettings schemas for
settings shared by various components of a desktop"

build() {
    sed -i -r 's:"(/system):"/org/gnome\1:g' schemas/*.in
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}

postinstall() {
  glib-compile-schemas /usr/share/glib-2.0/schemas
}
