#!/bin/sh
NAME="gnome-desktop"
RELEASE="1"
VERSION="44.0"
SOURCES="https://download.gnome.org/sources/gnome-desktop/44/gnome-desktop-$VERSION.tar.xz" 
BUILD_DEPENDS="meson"
DEPENDS="gsettings-desktop-schemas gtk3 gtk4 iso-codes itstool libseccomp libxml2 xkeyboard-config gobject-introspection"
SHA256SUM="42c773745d84ba14bc1cf1c4c6f4606148803a5cd337941c63964795f3c59d42"
DESCRIPTION="Libraries for GNOME desktop"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
