#!/bin/sh
NAME="gnome-desktop"
RELEASE="1"
VERSION="44.4"
SOURCES="https://download.gnome.org/sources/gnome-desktop/44/gnome-desktop-$VERSION.tar.xz" 
BUILD_DEPENDS="meson python-setuptools"
DEPENDS="gsettings-desktop-schemas gtk3 gtk4 iso-codes itstool libseccomp libxml2 xkeyboard-config gobject-introspection"
SHA256SUM="1d8cb9c6a328eb689b0c1269cf53834cc84d851d7e71970cdabba82706b44984"
DESCRIPTION="Libraries for GNOME desktop"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
