#!/bin/sh
NAME="json-c"
RELEASE="1"
VERSION="0.17"
SOURCES="https://s3.amazonaws.com/json-c_releases/releases/json-c-$VERSION.tar.gz"
DEPENDS="cmake"
SHA256SUM="7550914d58fb63b2c3546f3ccfbe11f1c094147bd31a69dcd23714d7956159e6  json-c-0.17.tar.gz"
DESCRIPTION="Construct JSON objects in C"

build() {
    mkdir build 
    cd    build 
    cmake -DCMAKE_INSTALL_PREFIX=/usr \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_STATIC_LIBS=OFF    \
          ..
    make 
}

package() {
    cd build
    make DESTDIR="$ROOT" install
}
