#!/bin/sh
NAME="json-c"
RELEASE="1"
VERSION="0.18"
BUILD_DEPENDS="gmake"
SOURCES="https://s3.amazonaws.com/json-c_releases/releases/json-c-$VERSION.tar.gz"
DEPENDS="cmake"
SHA256SUM="876ab046479166b869afc6896d288183bbc0e5843f141200c677b3e8dfb11724"
DESCRIPTION="Construct JSON objects in C"

build() {
    mkdir build 
    cd    build 
    cmake -DCMAKE_INSTALL_PREFIX=/usr \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_STATIC_LIBS=OFF    \
          ..
    make 
}

package() {
    cd build
    make DESTDIR="$ROOT" install
}
