#!/bin/sh
NAME="vim"
RELEASE="1"
VERSION="9.1.0776"
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/vim/vim/archive/refs/tags/v$VERSION.tar.gz"
DEPENDS="ncurses"
SHA256SUM="124a9b41d94c60bc6238594ba060ccab86d18ce5229ff2ec35fcb4ad9ca9cfcb"
DESCRIPTION="Vi Improved"

build() {
    kpkgConfigure \
    	--with-local-dir \
    	--prefix=/usr
    make -j$(nproc)
}

package() {
    make install
}
