#!/bin/sh
NAME="vim"
RELEASE="1"
VERSION="9.1.0309"
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/vim/vim/archive/refs/tags/v$VERSION.tar.gz"
DEPENDS="ncurses"
SHA256SUM="4cfeceeb69cd2b1d1f45a744003e9f7a7c06c9bddd59634df8e97424cbeffa32"
DESCRIPTION="Vi Improved"

build() {
    kpkgConfigure \
    	--with-local-dir \
    	--prefix=/usr
    make -j$(nproc)
}

package() {
    make install
}
