#!/bin/sh
NAME="vim"
RELEASE="1"
VERSION="9.1.0847"
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/vim/vim/archive/refs/tags/v$VERSION.tar.gz"
DEPENDS="ncurses"
SHA256SUM="7e6983b48815e8502b7898124324d83d71721d4a0f9b2ce7cc084a94bd65de7f"
DESCRIPTION="Vi Improved"

build() {
    kpkgConfigure \
    	--with-local-dir \
    	--prefix=/usr
    make -j$(nproc)
}

package() {
    make install
}
