#!/bin/sh
NAME="sassc"
RELEASE="1"
VERSION="3.6.2"
SOURCES="https://github.com/sass/sassc/archive/refs/tags/$VERSION.tar.gz"
DEPENDS="libsass"
BUILD_DEPENDS="autoconf automake gmake"
SHA256SUM="608dc9002b45a91d11ed59e352469ecc05e4f58fc1259fc9a9f5b8f0f8348a03"
DESCRIPTION="sass command-line tool"

build() {
    autoreconf -v -f -i
    kpkgConfigure --prefix=/usr --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
