#!/bin/sh
NAME="libfontenc"
RELEASE="1"
VERSION="1.1.8"
SOURCES="https://www.x.org/releases/individual/lib/libfontenc-$VERSION.tar.xz"
SHA256SUM="7b02c3d405236e0d86806b1de9d6868fe60c313628b38350b032914aa4fd14c6"
DEPENDS="zlib"
BUILD_DEPENDS="xorgproto gmake"
DESCRIPTION="libfontenc"

build() {
    kpkgConfigure \
        --prefix=/usr \
        --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
