#!/bin/sh
NAME="libfontenc"
RELEASE="1"
VERSION="1.1.7"
SOURCES="https://www.x.org/releases/individual/lib/libfontenc-$VERSION.tar.xz"
SHA256SUM="c0d36991faee06551ddbaf5d99266e97becdc05edfae87a833c3ff7bf73cfec2  libfontenc-1.1.7.tar.xz"
DEPENDS="zlib"
BUILD_DEPENDS="xorgproto"
DESCRIPTION="libfontenc"

build() {
    ./configure \
        --prefix=/usr \
        --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
