#!/bin/sh
NAME="libnvme"
RELEASE="1"
VERSION="1.16.1"
SOURCES="https://github.com/linux-nvme/libnvme/archive/refs/tags/v$VERSION.tar.gz"
BUILD_DEPENDS="meson"
DEPENDS="dbus"
SHA256SUM="ce1d9d393feb84c4e82ca096db2bdb7dd4a5fd1997d711cc1904796944f2c579"
DESCRIPTION="libnvme"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Dlibdbus=auto \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
