#!/bin/sh
NAME="libnvme"
RELEASE="1"
VERSION="1.5"
SOURCES="https://github.com/linux-nvme/libnvme/archive/refs/tags/v$VERSION.tar.gz"
BUILD_DEPENDS="meson"
SHA256SUM="f73ba1edde059b2d5e7c1048ad4f895e6047bff241c94b34a7aff5894779d086  v1.5.tar.gz"
DESCRIPTION="libnvme"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Dlibdbus=auto \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
