#!/bin/sh
NAME="gnome-autoar"
RELEASE="1"
VERSION="0.4.5"
SOURCES="https://download.gnome.org/sources/gnome-autoar/0.4/gnome-autoar-$VERSION.tar.xz"
BUILD_DEPENDS="meson vala"
DEPENDS="libarchive gtk3"
SHA256SUM="838c5306fc38bfaa2f23abe24262f4bf15771e3303fb5dcb74f5b9c7a615dabe"
DESCRIPTION="gnome-autoar"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Dvapi=true \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
