#!/bin/sh
NAME="gstreamer"
RELEASE="1"
VERSION="1.22.8"
SOURCES="https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-$VERSION.tar.xz"
BUILD_DEPENDS="meson gobject-introspection"
DEPENDS="glib"
SHA256SUM="ad4e3db1771139b1db17b1afa7c05db083ae0100bd4da244b71f162dcce41bfc"
DESCRIPTION="gstreamer"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
