#!/bin/sh
NAME="gstreamer"
RELEASE="1"
VERSION="1.22.6"
SOURCES="https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-$VERSION.tar.xz"
BUILD_DEPENDS="meson gobject-introspection"
DEPENDS="glib"
SHA256SUM="f500e6cfddff55908f937711fc26a0840de28a1e9ec49621c0b6f1adbd8f818e"
DESCRIPTION="gstreamer"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
