#!/bin/sh
NAME="gstreamer"
RELEASE="1"
VERSION="1.26.8"
SOURCES="https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-$VERSION.tar.xz"
BUILD_DEPENDS="meson gobject-introspection python-setuptools"
DEPENDS="glib"
SHA256SUM="2348e837464c3cb7423b79fc1cc8c4c994c74603443bd97d14edc6cd5ca7db13"
DESCRIPTION="gstreamer"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
