#!/bin/sh
NAME="xorg-xkbcomp"
RELEASE="1"
VERSION="1.4.7"
SOURCES="https://www.x.org/archive/individual/app/xkbcomp-$VERSION.tar.xz"
SHA256SUM="0a288114e5f44e31987042c79aecff1ffad53a8154b8ec971c24a69a80f81f77"
DEPENDS="libxkbfile"
BUILD_DEPENDS="xorg-util-macros"
DESCRIPTION="X11 client-side library"

build() {
    kpkgConfigure \
        --prefix=/usr \
        --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
