#!/bin/sh
NAME="klinstaller"
RELEASE="1"
VERSION="0.0.1"
SOURCES="git::https://github.com/kreatolinux/src::master"
BUILD_DEPENDS="gmake"
DEPENDS="kpkg"
SHA256SUM="SKIP"
DESCRIPTION="Kreato Linux's Installer"

package() {
	make install_klinstaller
}
