#!/bin/sh
NAME="gnome-terminal"
RELEASE="1"
VERSION="3.50.0"
SOURCES="https://gitlab.gnome.org/GNOME/gnome-terminal/-/archive/$VERSION/gnome-terminal-$VERSION.tar.gz"
BUILD_DEPENDS="meson"
DEPENDS="vte jetbrains-mono gtk3 glib libhandy"
OPTDEPENDS="nautilus: For nautilus integration"
SHA256SUM="7c8df4f7987fbd73dc784904bb3dd7e3271cfeb21daddb81ea4800d2d840f1ff  gnome-terminal-3.50.0.tar.gz"
DESCRIPTION="GNOME Terminal"

build() {
    
    if kpkg info nautilus; then
      nautilusEnabled="true"
    else
      nautilusEnabled="false"
    fi
   
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Ddocs=false \
    -Dnautilus_extension=$nautilusEnabled \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
