#!/bin/sh
NAME="gnome-terminal"
RELEASE="1"
VERSION="3.58.0"
SOURCES="https://gitlab.gnome.org/GNOME/gnome-terminal/-/archive/$VERSION/gnome-terminal-$VERSION.tar.gz"
BUILD_DEPENDS="meson"
DEPENDS="vte util-linux jetbrains-mono gtk3 glib libhandy gsettings-desktop-schemas libxslt"
OPTDEPENDS="nautilus: For nautilus integration"
SHA256SUM="6c9f577dfe0679dd736674117ab827b4fddc2224728753a0079124b979b8fdf8"
DESCRIPTION="GNOME Terminal"

build() {
    
    if kpkg info nautilus; then
      nautilusEnabled="true"
    else
      nautilusEnabled="false"
    fi
   
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Ddocs=false \
    -Dnautilus_extension=$nautilusEnabled \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
