#!/bin/sh
NAME="gnome-bluetooth"
RELEASE="1"
VERSION="42.7"
SOURCES="https://download.gnome.org/sources/gnome-bluetooth/42/gnome-bluetooth-$VERSION.tar.xz"
BUILD_DEPENDS="meson gobject-introspection"
DEPENDS="bluez gtk4 libadwaita libnotify upower gsound"
SHA256SUM="94df1729dbec3bb105e588eaf5312bbbaa05c49ea733202a10dc3f7532bdf869"
DESCRIPTION="Bluetooth tools for GNOME"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
