#!/bin/sh
NAME="libsixel"
RELEASE="1"
VERSION="1.10.5"
SOURCES="https://github.com/libsixel/libsixel/archive/refs/tags/v$VERSION.tar.gz"
DEPENDS="libpng"
BUILD_DEPENDS="meson"
SHA256SUM="b6654928bd423f92e6da39eb1f40f10000ae2cc6247247fc1882dcff6acbdfc8"
DESCRIPTION="encoder/decoder implementation for DEC SIXEL graphics"
build() {
    meson --prefix=/usr build/
    ninja -C build/
}

package() {
    ninja -C build/ install
}
