#!/bin/sh
NAME="opendoas"
RELEASE="1"
VERSION="6.8.2"
SOURCES="https://github.com/Duncaen/OpenDoas/releases/download/v$VERSION/opendoas-$VERSION.tar.gz"
DEPENDS="linux-pam shadow"
SHA256SUM="28dca29adec5f4336465812d9e2243f599e62a78903de71c24f0cd6fe667edac  opendoas-6.8.2.tar.gz"
DESCRIPTION="Utility to execute a command as another user, sudo alternative"

build() {
    ./configure --prefix=/usr
    make
}

package() {
    make install
    # From BLFS
    mkdir -p $ROOT/etc/pam.d
    cat > $ROOT/etc/pam.d/doas << "EOF"
# Begin /etc/pam.d/doas

# include the default auth settings
auth      include     system-auth

# include the default account settings
account   include     system-account

# Set default environment variables for the service user
session   required    pam_env.so

# include system session defaults
session   include     system-session

# End /etc/pam.d/doas
EOF
chmod 644 $ROOT/etc/pam.d/doas

}
