#!/bin/sh
NAME="libusb"
RELEASE="1"
VERSION="1.0.29"
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/libusb/libusb/releases/download/v$VERSION/libusb-$VERSION.tar.bz2"
DEPENDS="eudev"
SHA256SUM="5977fc950f8d1395ccea9bd48c06b3f808fd3c2c961b44b0c2e6e29fc3a70a85"
DESCRIPTION="A cross-platform library to access USB devices"

build() {
    kpkgConfigure --prefix=/usr                   \
    		--disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
