#!/bin/sh
NAME="libusb"
RELEASE="1"
VERSION="1.0.27"
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/libusb/libusb/releases/download/v$VERSION/libusb-$VERSION.tar.bz2"
DEPENDS="eudev"
SHA256SUM="ffaa41d741a8a3bee244ac8e54a72ea05bf2879663c098c82fc5757853441575"
DESCRIPTION="A cross-platform library to access USB devices"

build() {
    kpkgConfigure --prefix=/usr                   \
    		--disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
