#!/bin/sh
NAME="libusb"
RELEASE="1"
VERSION="1.0.26"
SOURCES="https://github.com/libusb/libusb/releases/download/v$VERSION/libusb-$VERSION.tar.bz2"
DEPENDS="libudev"
SHA256SUM="12ce7a61fc9854d1d2a1ffe095f7b5fac19ddba095c259e6067a46500381b5a5"
DESCRIPTION="A cross-platform library to access USB devices"

build() {
    kpkgConfigure --prefix=/usr                   \
    		--disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
