#!/bin/sh
NAME="colord"
RELEASE="1"
VERSION="1.4.6"
SOURCES="https://www.freedesktop.org/software/colord/releases/colord-$VERSION.tar.xz"
BUILD_DEPENDS="meson vala gobject-introspection"
DEPENDS="glib libudev eudev libgusb lcms2 elogind libgudev polkit dbus sqlite"
SHA256SUM="7407631a27bfe5d1b672e7ae42777001c105d860b7b7392283c8c6300de88e6f  colord-1.4.6.tar.xz"
DESCRIPTION="A system service that makes it easy to manage, install and generate color profiles"

build() {
    
    # Check if systemd exists so we can enable/disable systemd support accordingly.
    if command -v systemctl > /dev/null; then
      systemd="true"
    else
      systemd="false"
    fi
    
    meson setup \
    --buildtype=release \
    --prefix=/usr \
    -Dman=false \
    -Dsystemd=$systemd \
    -Dbash_completion=false \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
