#!/bin/sh
NAME="colord"
RELEASE="2"
VERSION="1.4.8"
SOURCES="https://www.freedesktop.org/software/colord/releases/colord-$VERSION.tar.xz"
BUILD_DEPENDS="meson vala gobject-introspection"
DEPENDS="glib eudev libgusb lcms2 elogind libgudev polkit dbus sqlite"
SHA256SUM="de02d9910634ae159547585cec414e450f711c27235453b4f9b38a9f2361a653"
DESCRIPTION="A system service that makes it easy to manage, install and generate color profiles"

build() {
    
    # Check if systemd exists so we can enable/disable systemd support accordingly.
    if command -v systemctl > /dev/null; then
      systemd="true"
    else
      systemd="false"
    fi
    
    meson setup \
    --buildtype=release \
    --prefix=/usr \
    -Dman=false \
    -Dvapi=true \
    -Dsystemd=$systemd \
    -Dbash_completion=false \
    -Ddocs=false \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
