#!/bin/sh
NAME="libunistring"
RELEASE="1"
VERSION="1.2"
BUILD_DEPENDS="gmake"
SOURCES="https://ftp.gnu.org/gnu/libunistring/libunistring-$VERSION.tar.xz"
SHA256SUM="632bd65ed74a881ca8a0309a1001c428bd1cbd5cd7ddbf8cedcd2e65f4dcdc44"
DESCRIPTION="libunistring"

build() {
    kpkgConfigure --prefix=/usr \
	    	--disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
