#!/bin/sh
NAME="libunistring"
RELEASE="1"
VERSION="1.1"
SOURCES="https://ftp.gnu.org/gnu/libunistring/libunistring-$VERSION.tar.xz"
SHA256SUM="827c1eb9cb6e7c738b171745dac0888aa58c5924df2e59239318383de0729b98"
DESCRIPTION="libunistring"

build() {
    ./configure --prefix=/usr \
	    	--disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
