#!/bin/sh
NAME="js102"
RELEASE="1"
VERSION="102.15.0"
SOURCES="https://archive.mozilla.org/pub/firefox/releases/$VERSIONesr/source/firefox-$VERSIONesr.source.tar.xz" 
DEPENDS="readline zlib icu"
BUILD_DEPENDS="rust python llvm which"
SHA256SUM="81fa590408f5a3af8f004d839ac47fb4121e05fe717334445cec9ca55d8746af  firefox-102.15.0esr.source.tar.xz"
DESCRIPTION="Spidermonkey JavaScript and WebAssembly Engine"

build() {
  # Thanks to BLFS for configure arguments: https://www.linuxfromscratch.org/blfs/view/svn/general/js102.html
  # Add CC=clang so it overrides the cc set by the user in the configuration file as it may cause problems.
  CC=clang sh js/src/configure.in --prefix=/usr \
                          --with-intl-api          \
                          --with-system-zlib       \
                          --with-system-icu        \
                          --disable-jemalloc       \
                          --disable-debug-symbols  \
                          --enable-readline
  make -j$(nproc)
}

package() {
  make install
}
