#!/bin/sh
NAME="gperf"
RELEASE="1"
VERSION="3.1"
SOURCES="https://ftp.gnu.org/pub/gnu/gperf/gperf-$VERSION.tar.gz"
SHA256SUM="588546b945bba4b70b6a3a616e80b4ab466e3f33024a352fc2198112cdbb3ae2  gperf-3.1.tar.gz"
DESCRIPTION="gperf"
build() {
    ./configure --prefix=/usr
    make
}

install() {
    make DESTDIR=$ROOT install
}
