#!/bin/sh
NAME="libassuan"
RELEASE="1"
VERSION="3.0.2"
BUILD_DEPENDS="gmake"
SOURCES="https://gnupg.org/ftp/gcrypt/libassuan/libassuan-$VERSION.tar.bz2"
DEPENDS="libgpg-error"
SHA256SUM="d2931cdad266e633510f9970e1a2f346055e351bb19f9b78912475b8074c36f6"
DESCRIPTION="Small library implementing Assuan protocol"

build() {
    kpkgConfigure --prefix=/usr
    make -j$(nproc)
}

package() {
    make DESTDIR="$ROOT" install
}
