#!/bin/sh
NAME="libassuan"
RELEASE="1"
VERSION="2.5.6"
SOURCES="https://gnupg.org/ftp/gcrypt/libassuan/libassuan-$VERSION.tar.bz2"
SHA256SUM="e9fd27218d5394904e4e39788f9b1742711c3e6b41689a31aa3380bd5aa4f426  libassuan-2.5.6.tar.bz2"
DESCRIPTION="Small library implementing Assuan protocol"

build() {
    ./configure --prefix=/usr
    make -j$(nproc)
}

install() {
    make DESTDIR="$ROOT" install
}
