#!/bin/sh
NAME="freetype-harfbuzz"
RELEASE="1"
VERSION="2.12.1-5.3.1"
SOURCES="https://download-mirror.savannah.gnu.org/releases/freetype/freetype-2.12.1.tar.gz;https://github.com/harfbuzz/harfbuzz/releases/download/5.3.1/harfbuzz-5.3.1.tar.xz" 
SHA256SUM="efe71fd4b8246f1b0b1b9bfca13cfff1c9ad85930340c27df469733bbb620938  freetype-2.12.1.tar.gz;4a6ce097b75a8121facc4ba83b5b083bfec657f45b003cd5a3424f2ae6b4434d  harfbuzz-5.3.1.tar.xz"
DESCRIPTION="FriBidi is an implementation of Unicode Bidirectional Algorithm"

# Taken from KISS Linux
build_freetype() (
    cd freetype-2.12.1

    meson \
        --prefix=/usr \
        -Ddefault_library=both \
        -Dbzip2=disabled \
        -Dzlib=disabled \
        "$@" \
        . output

    DESTDIR=$ROOT ninja -C output
    DESTDIR=$ROOT ninja -C output install
)

build_harfbuzz() (
    cd harfbuzz-5.3.1

    meson \
        --prefix=/usr \
        -Dpkg_config_path="$DESTDIR/usr/lib/pkgconfig" \
        -Ddefault_library=both \
        -Dglib=disabled \
        -Dfreetype=enabled \
        -Dgobject=disabled \
        -Dcairo=disabled \
        -Dicu=disabled \
        -Dbenchmark=disabled \
        -Dtests=disabled \
        . output

    DESTDIR=$ROOT ninja -C output
    DESTDIR=$ROOT ninja -C output install
)


build() {
    # Point Freetype to the Harfbuzz files.
    export CFLAGS="$CFLAGS -I$DESTDIR/usr/include/harfbuzz"
    export CFLAGS="$CFLAGS -L$DESTDIR/usr/lib "
    export PKG_CONFIG_PATH=$DESTDIR/usr/lib/pkgconfig

    # Point Harfbuzz to the Freetype files.
    export CXXFLAGS="$CXXFLAGS -I$DESTDIR/usr/include/freetype2"
    export CXXFLAGS="$CXXFLAGS -L$DESTDIR/usr/lib"
    
    build_freetype -Dharfbuzz=disabled
    build_harfbuzz
    build_freetype -Dharfbuzz=enabled --reconfigure
}
