#!/bin/sh
NAME="xwayland"
RELEASE="1"
VERSION="24.1.9"
SOURCES="https://www.x.org/releases/individual/xserver/xwayland-$VERSION.tar.xz"
SHA256SUM="f297af27a84508db9b80d1cbbcc69c3801da38eb64c72f3b5b50f582459afdd0"
DEPENDS="xorg-xkbcomp libnettle libepoxy libxfont2 pixman xorg-server libxcvt mesa libglvnd libxau wayland libdrm libtirpc libxshmfence"
BUILD_DEPENDS="meson"
DESCRIPTION="Run X11 applications in Wayland"

build() {
    meson setup \
      --prefix=/usr \
      --buildtype=release \
      build
    ninja -C build
}

package() {
    DESTDIR=$ROOT ninja -C build install
}
