#!/bin/sh
NAME="xwayland"
RELEASE="1"
VERSION="23.2.1"
SOURCES="https://www.x.org/releases/individual/xserver/xwayland-$VERSION.tar.xz"
SHA256SUM="eebc2692c3aa80617d78428bc6ec7b91b254a98214d2a70e997098503cd6ef90"
DEPENDS="xorg-xkbcomp libnettle libepoxy libxfont2 pixman xorg-server libxcvt mesa libglvnd libxau wayland libdrm libtirpc libxshmfence"
DESCRIPTION="Run X11 applications in Wayland"

build() {
    meson setup \
      --prefix=/usr \
      --buildtype=release \
      build
    ninja -C build
}

package() {
    DESTDIR=$ROOT ninja -C build install
}
