#!/bin/sh
NAME="mpc"
RELEASE="1"
VERSION="1.2.1"
SOURCES="https://ftp.gnu.org/gnu/mpc/mpc-$VERSION.tar.gz"
DEPENDS=""
SHA256SUM="17503d2c395dfcf106b622dc142683c1199431d095367c6aacba6eec30340459"
DESCRIPTION="GNU MPC"

build() {
    kpkgConfigure --prefix=/usr
    make -j$(nproc)
}

package() {
    make DESTDIR=$ROOT install
}
