#!/bin/sh
NAME="xorgproto"
RELEASE="1"
VERSION="2024.1"
SOURCES="https://www.x.org/releases/individual/proto/xorgproto-$VERSION.tar.xz"
SHA256SUM="372225fd40815b8423547f5d890c5debc72e88b91088fbfb13158c20495ccb59"
BUILD_DEPENDS="meson"
DESCRIPTION="X Window System Unified Protocol"

build() {
    meson setup --prefix=/usr build
    meson compile -C build
}

package() {
    meson install -C build --destdir "$ROOT"
}
