#!/bin/sh
NAME="alsa-lib"
RELEASE="1"
VERSION="1.2.9"
BUILD_DEPENDS="gmake"
SOURCES="https://www.alsa-project.org/files/pub/lib/alsa-lib-$VERSION.tar.bz2"
SHA256SUM="dc9c643fdc4ccfd0572cc685858dd41e08afb583f30460b317e4188275f615b2"
DESCRIPTION="Libraries for ALSA"

build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
