#!/bin/sh
NAME="alsa-lib"
RELEASE="1"
VERSION="1.2.15"
BUILD_DEPENDS="gmake"
SOURCES="https://www.alsa-project.org/files/pub/lib/alsa-lib-$VERSION.tar.bz2"
SHA256SUM="83770841585e766a60c99fd23f8c574c22643ae0cb1f2d20b793c3d84eb95a8d"
DESCRIPTION="Libraries for ALSA"

build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
