#!/bin/sh
NAME="libgudev"
RELEASE="1"
VERSION="237"
SOURCES="https://download.gnome.org/sources/libgudev/$VERSION/libgudev-$VERSION.tar.xz"
BUILD_DEPENDS="meson"
DEPENDS="libudev>=1.0.3 glib gobject-introspection"
SHA256SUM=""
DESCRIPTION="GObject bindings for libudev"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
