#!/bin/sh
NAME="libgudev"
RELEASE="1"
VERSION="238"
SOURCES="https://download.gnome.org/sources/libgudev/$VERSION/libgudev-$VERSION.tar.xz"
BUILD_DEPENDS="meson"
DEPENDS="libudev>=1.0.3 glib gobject-introspection"
SHA256SUM="61266ab1afc9d73dbc60a8b2af73e99d2fdff47d99544d085760e4fa667b5dd1"
DESCRIPTION="GObject bindings for libudev"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
