#!/bin/sh
NAME="gst-plugins-bad"
RELEASE="1"
VERSION="1.26.8"
SOURCES="https://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-$VERSION.tar.xz"
BUILD_DEPENDS="meson"
DEPENDS="gst-plugins-base"
SHA256SUM="e64e75cdafd7ff2fc7fc34e855b06b1e3ed227cc06fa378d17bbcd76780c338c"
DESCRIPTION="gst-plugins-bad"

build() {
    # -Dgpl flag taken from BLFS
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Dgpl=enabled \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
