#!/bin/sh
NAME="gst-plugins-bad"
RELEASE="1"
VERSION="1.26.8"
SOURCES="https://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-$VERSION.tar.xz"
BUILD_DEPENDS="meson"
DEPENDS="gst-plugins-base"
SHA256SUM="25c05be5eb0694bde3ecd3317516f5d0d6e4ad21125a5ebcf6fb644a4c92439f"
DESCRIPTION="gst-plugins-bad"

build() {
    # -Dgpl flag taken from BLFS
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Dgpl=enabled \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
