#!/bin/sh
NAME="libxi"
RELEASE="1"
VERSION="1.8.2"
SOURCES="https://xorg.freedesktop.org/releases/individual/lib/libXi-$VERSION.tar.gz"
SHA256SUM="5542daec66febfeb6f51d57abfa915826efe2e3af57534f4105b82240ea3188d"
DEPENDS="libxext libxfixes"
BUILD_DEPENDS="xorgproto gmake"
DESCRIPTION="libxi"

build() {
    kpkgConfigure \
        --sysconfdir=/etc \
        --prefix=/usr \
        --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
