#!/bin/sh
NAME="libxkbfile"
RELEASE="1"
VERSION="1.1.3"
BUILD_DEPENDS="gmake"
SOURCES="https://www.x.org/releases/individual/lib/libxkbfile-$VERSION.tar.gz"
SHA256SUM="c4c2687729d1f920f165ebb96557a1ead2ef655809ab5eaa66a1ad36dc31050d"
DEPENDS="libx11"
DESCRIPTION="libxkbfile"

build() {
    kpkgConfigure \
        --prefix=/usr \
        --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
