#!/bin/sh
NAME="gnu-grep"
RELEASE="1"
VERSION="3.12"
BUILD_DEPENDS="gmake"
SOURCES="https://ftp.gnu.org/gnu/grep/grep-$VERSION.tar.xz"
DEPENDS="pcre"
SHA256SUM="2649b27c0e90e632eadcd757be06c6e9a4f48d941de51e7c0f83ff76408a07b9"
DESCRIPTION="GNU grep"

build() {
    kpkgConfigure --prefix=/usr
}

package() {
    make DESTDIR=$ROOT install
    rm -rf "$ROOT/usr/share/info/dir"
}
