#!/bin/sh
NAME="gnu-grep"
RELEASE="1"
VERSION="3.8"
SOURCES="https://ftp.gnu.org/gnu/grep/grep-$VERSION.tar.xz"
DEPENDS="pcre"
SHA256SUM="498d7cc1b4fb081904d87343febb73475cf771e424fb7e6141aff66013abc382"
DESCRIPTION="GNU grep"

build() {
    kpkgConfigure --prefix=/usr
}

package() {
    make DESTDIR=$ROOT install
    rm -rf "$ROOT/usr/share/info/dir"
}
