#!/bin/sh
NAME="gnu-grep"
VERSION="3.7"
SOURCES="https://ftp.gnu.org/gnu/grep/grep-$VERSION.tar.xz"
SHA256SUM="5c10da312460aec721984d5d83246d24520ec438dd48d7ab5a05dbc0d6d6823c  grep-3.7.tar.xz"
DESCRIPTION="GNU grep"

build() {
    tar -xvf grep-$VERSION.tar.xz
    cd grep-$VERSION
    ./configure
    make DESTDIR=$ROOT install
}
