#!/bin/sh
NAME="networkmanager"
RELEASE="1"
VERSION="1.54.2"
SOURCES="https://download.gnome.org/sources/NetworkManager/1.45/NetworkManager-$VERSION.tar.xz"
DEPENDS="jansson libndp curl dhcpcd newt gnutls polkit pygobject elogind vala wpa_supplicant"
BUILD_DEPENDS="meson gobject-introspection libxslt python-setuptools"
SHA256SUM="SKIP"
DESCRIPTION="networkmanager"

build() {
    
    # Thanks for BLFS for the args https://www.linuxfromscratch.org/blfs/view/svn/basicnet/networkmanager.html
    if ! command -v systemctl > /dev/null; then
      extraArgs="-Dsystemd_journal=false -Dsystemdsystemunitdir=no -Dsession_tracking=elogind"
    fi

    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Dnmtui=true \
    -Ddocs=false \
    -Dcrypto=gnutls \
    -Dqt=false \
    -Dppp=false \
    -Dlibaudit=no \
    -Dselinux=false \
    -Dlibpsl=false \
    -Dovs=false \
    -Dmodem_manager=false \
    $extraArgs build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
