#!/bin/sh
NAME="libglvnd"
RELEASE="1"
VERSION="1.7.0"
SOURCES="https://gitlab.freedesktop.org/glvnd/libglvnd/-/archive/v$VERSION/libglvnd-v$VERSION.tar.gz"
BUILD_DEPENDS="meson"
SHA256SUM="2b6e15b06aafb4c0b6e2348124808cbd9b291c647299eaaba2e3202f51ff2f3d"
DESCRIPTION="The GL Vendor-Neutral Dispatch library"

build() {
    meson --buildtype=release  --prefix=/usr   \
      build/
    ninja -C build/
}

package() {
    DESTDIR=$ROOT ninja -C build/ install
}
