#!/bin/sh
NAME="rdfind"
RELEASE="1"
VERSION="1.7.0"
SOURCES="https://github.com/pauldreik/rdfind/archive/refs/tags/releases/$VERSION.tar.gz"
BUILD_DEPENDS="automake gmake"
DEPENDS="libnettle"
SHA256SUM="bd17dbd9c6c9fc0c0b016b3e77ecf5cd718eee428172c767f429ba30405816d8"
DESCRIPTION="find duplicate files utility"

build() {
    ./bootstrap.sh
    kpkgConfigure
    make
}

package() {
    make DESTDIR=$ROOT install
}
