#!/bin/sh
NAME="fakeroot"
RELEASE="1"
VERSION="1.35"
BUILD_DEPENDS="gmake"
SOURCES="https://deb.debian.org/debian/pool/main/f/fakeroot/fakeroot_$VERSION.orig.tar.gz"
DEPENDS="libcap"
SHA256SUM="e5a427b4ab1eb4a2158b3312547a4155aede58735cd5c2910421988834b440a4"
DESCRIPTION="Tool for simulating superuser privileges"

build() {
    export CFLAGS="$CFLAGS -Wno-incompatible-pointer-types" 
    kpkgConfigure --prefix=/usr --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}

install() {
    make DESTDIR=$ROOT install
}
