#!/bin/sh
NAME="fakeroot"
RELEASE="1"
VERSION="1.34"
BUILD_DEPENDS="gmake"
SOURCES="https://deb.debian.org/debian/pool/main/f/fakeroot/fakeroot_$VERSION.orig.tar.gz"
DEPENDS="libcap"
SHA256SUM="5727f16d8903792588efa7a9f8ef8ce71f8756e746b62e45162e7735662e56bb"
DESCRIPTION="Tool for simulating superuser privileges"

build() {
    kpkgConfigure --prefix=/usr --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}

install() {
    make DESTDIR=$ROOT install
}
