#!/bin/sh
NAME="gpgme"
RELEASE="1"
VERSION="1.23.2"
SOURCES="https://gnupg.org/ftp/gcrypt/gpgme/gpgme-1.23.2.tar.bz2"
DEPENDS="gnupg"
SHA256SUM="9499e8b1f33cccb6815527a1bc16049d35a6198a6c5fae0185f2bd561bce5224"
DESCRIPTION="GNU Privacy Guard Made Easy"

build() {
    kpkgConfigure --prefix=/usr
    make -j$(nproc)
}

package() {
    make DESTDIR="$ROOT" install
}
