#!/bin/sh
NAME="gpgme"
RELEASE="1"
VERSION="1.22.0"
SOURCES="https://gnupg.org/ftp/gcrypt/gpgme/gpgme-1.22.0.tar.bz2"
DEPENDS="gnupg"
SHA256SUM="9551e37081ad3bde81018a0d24f245c3f8206990549598fb31a97a68380a7b71  gpgme-1.22.0.tar.bz2"
DESCRIPTION="GNU Privacy Guard Made Easy"

build() {
    ./configure --prefix=/usr
    make -j$(nproc)
}

package() {
    make DESTDIR="$ROOT" install
}
