#!/bin/sh
NAME="libxcvt"
RELEASE="1"
VERSION="0.1.3"
SOURCES="https://www.x.org/releases/individual/lib/libxcvt-$VERSION.tar.xz"
BUILD_DEPENDS="meson"
SHA256SUM="a929998a8767de7dfa36d6da4751cdbeef34ed630714f2f4a767b351f2442e01"
DESCRIPTION="libxcvt"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
