#!/bin/sh
NAME="libtiff"
RELEASE="1"
VERSION="4.5.1"
SOURCES="https://download.osgeo.org/libtiff/tiff-$VERSION.tar.gz"
BUILD_DEPENDS="cmake ninja"
DEPENDS="libjpeg-turbo"
SHA256SUM="d7f38b6788e4a8f5da7940c5ac9424f494d8a79eba53d555f4a507167dca5e2b"
DESCRIPTION="Library to read TIFF files"

build() {
    cmake -B build -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -G Ninja
    ninja -C build -j$(nproc)
}

package() {    
    DESTDIR="$ROOT" ninja -C build install
}
