#!/bin/sh
NAME="libtiff"
RELEASE="1"
VERSION="4.6.0"
SOURCES="https://download.osgeo.org/libtiff/tiff-$VERSION.tar.gz"
BUILD_DEPENDS="cmake ninja"
DEPENDS="libjpeg-turbo"
SHA256SUM="88b3979e6d5c7e32b50d7ec72fb15af724f6ab2cbf7e10880c360a77e4b5d99a"
DESCRIPTION="Library to read TIFF files"

build() {
    cmake -B build -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -G Ninja
    ninja -C build -j$(nproc)
}

package() {    
    DESTDIR="$ROOT" ninja -C build install
}
