#!/bin/sh
NAME="wayland-protocols"
VERSION="1.26"
SOURCES="https://wayland.freedesktop.org/releases/wayland-protocols-$VERSION.tar.xz"
SHA256SUM="c553384c1c68afd762fa537a2569cc9074fe7600da12d3472761e77a2ba56f13  wayland-protocols-1.26.tar.xz"
DESCRIPTION="Additional Wayland protocols that add functionality outside of protocols already in the Wayland core"

build() {
    tar -xvf wayland-protocols-$VERSION.tar.xz
    cd wayland-protocols-$VERSION || exit 1
    mkdir build 
    cd    build 
    meson --prefix=/usr --buildtype=release
    ninja
    DESTDIR="$ROOT" ninja install
}
