#!/bin/sh
NAME="wayland-protocols"
RELEASE="1"
VERSION="1.31"
SOURCES="https://gitlab.freedesktop.org/wayland/wayland-protocols/-/releases/$VERSION/downloads/wayland-protocols-$VERSION.tar.xz"
SHA256SUM="a07fa722ed87676ec020d867714bc9a2f24c464da73912f39706eeef5219e238  wayland-protocols-1.31.tar.xz"
DESCRIPTION="Additional Wayland protocols that add functionality outside of protocols already in the Wayland core"

build() {
    mkdir build 
    cd    build 
    meson --prefix=/usr --buildtype=release
    ninja
}

install() {
    DESTDIR="$ROOT" ninja install
}
