#!/bin/sh
NAME="bc"
RELEASE="1"
VERSION="1.08.2"
SOURCES="https://ftp.gnu.org/gnu/bc/bc-$VERSION.tar.gz"
DEPENDS="readline"
BUILD_DEPENDS="ed texinfo"
SHA256SUM="ae470fec429775653e042015edc928d07c8c3b2fc59765172a330d3d87785f86"
DESCRIPTION="An arbitrary precision calculator language"

build() {
    kpkgConfigure --prefix=/usr
    make MAKEINFO=true
}

package() {
    make MAKEINFO=true install 
}
