#!/bin/sh
NAME="bc"
RELEASE="1"
VERSION="1.07.1"
SOURCES="https://ftp.gnu.org/gnu/bc/bc-$VERSION.tar.gz"
DEPENDS="readline"
BUILD_DEPENDS="ed"
SHA256SUM="62adfca89b0a1c0164c2cdca59ca210c1d44c3ffc46daf9931cf4942664cb02a"
DESCRIPTION="An arbitrary precision calculator language"

build() {
    ./configure --prefix=/usr
    make
}

package() {
    make install 
}
