#!/bin/sh
NAME="libbsd"
RELEASE="1"
VERSION="0.12.2"
BUILD_DEPENDS="gmake"
SOURCES="https://libbsd.freedesktop.org/releases/libbsd-$VERSION.tar.xz"
DEPENDS="libmd"
SHA256SUM="b88cc9163d0c652aaf39a99991d974ddba1c3a9711db8f1b5838af2a14731014"
DESCRIPTION="Useful functions commonly found on BSD systems, and lacking on others like GNU systems"

build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
