#!/bin/sh
NAME="ryzenadj"
RELEASE="1"
VERSION="0.13"
SOURCES="https://github.com/FlyGoat/RyzenAdj/archive/refs/tags/v0.13.0.tar.gz"
SHA256SUM="083d929031521c40308d62a0167b6d8e5035699233be2452ae694ac85d66cdcf  v0.13.0.tar.gz"
DESCRIPTION="Tool to adjust power management of Ryzen CPU's"

build() {
    mkdir build && cd build
    cmake -DCMAKE_BUILD_TYPE=Release ..
    make
}

install() {
     install -vD ryzenadj /usr/bin/ryzenadj
}
