#!/bin/sh
NAME="telepathy-glib"
RELEASE="1"
VERSION="0.24.1"
SOURCES="http://telepathy.freedesktop.org/releases/telepathy-glib/telepathy-glib-$VERSION.tar.gz"
BUILD_DEPENDS="gobject-introspection"
SHA256SUM="9e0df1d8f857e0270cf0b32e2d1ca5a24aa7282873361785d573f72ad7f7d5eb  telepathy-glib-0.24.1.tar.gz"
DESCRIPTION="glib bindings for telepathy"

build() {
    ./configure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
