#!/bin/sh
NAME="telepathy-glib"
RELEASE="1"
VERSION="0.24.2"
SOURCES="https://telepathy.freedesktop.org/releases/telepathy-glib/telepathy-glib-$VERSION.tar.gz"
DEPENDS="dbus-glib"
BUILD_DEPENDS="gobject-introspection"
SHA256SUM="b0a374d771cdd081125f38c3abd079657642301c71a543d555e2bf21919273f0"
DESCRIPTION="glib bindings for telepathy"

build() {
    ./configure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
