#!/bin/sh
NAME="fontconfig"
VERSION="2.14.1"
SOURCES="https://www.freedesktop.org/software/fontconfig/release/fontconfig-$VERSION.tar.gz"
SHA256SUM=";ae480e9ca34382790312ff062c625ec70df94d6d9a9366e2b2b3d525f7f90387  fontconfig-2.14.1.tar.gz"
DESCRIPTION="fontconfig"
build() {
    [ ! -d "$NAME-$VERSION" ] && tar -xvf $NAME-$VERSION.tar.gz
    cd $NAME-$VERSION || exit  1
    ./configure --prefix=/usr
    make
    make DESTDIR=$ROOT install
}
