#!/bin/sh
NAME="dracut"
RELEASE="1"
VERSION="057"
SOURCES="https://github.com/dracutdevs/dracut/archive/refs/tags/$VERSION.tar.gz"
DESCRIPTION="dracut the event driven initramfs infrastructure"
build() {
    [ ! -d "dracut-$VERSION" ] && tar -xvf $VERSION.tar.gz
    cd dracut-$VERSION || exit  1
    ./configure --disable-documentation --prefix=/usr
    make
    make DESTDIR=$ROOT install
}
