#!/bin/sh
NAME="dracut"
RELEASE="1"
VERSION="057"
SOURCES="https://github.com/dracutdevs/dracut/archive/refs/tags/$VERSION.tar.gz"
SHA256SUM="24f149d683d188c0d25756529b7d1e5cd6be8028e0c1043110f303d0d706757d  057.tar.gz"
DESCRIPTION="dracut the event driven initramfs infrastructure"
build() {
    cd dracut-$VERSION || exit  1
    ./configure --disable-documentation --prefix=/usr
    make
    make DESTDIR=$ROOT install
}
