#!/bin/sh
NAME="recvtty"
RELEASE="1"
VERSION="1.1.10"
SOURCES="https://github.com/opencontainers/runc/archive/refs/tags/v$VERSION.tar.gz"
BUILD_DEPENDS="go"
SHA256SUM="e26ae522d09b253b64a30b4e4d233988c988f7588178308b51da7aec927df47b"
DESCRIPTION="Reference implementation of a consumer of runC's --console-socket API."

build() {
    make recvtty
}

package() {
    mkdir -p "$ROOT/usr/bin"
    cp ./contrib/cmd/recvtty/recvtty "$ROOT/usr/bin/recvtty"
}
