#!/bin/sh
NAME="wl-clipboard"
RELEASE="1"
VERSION="2.2.0"
SOURCES="https://github.com/bugaevc/wl-clipboard/archive/refs/tags/v$VERSION.tar.gz"
DEPENDS="wayland wayland-protocols" 
BUILD_DEPENDS="meson"
SHA256SUM="414005cfa229d0e54f89a0d9a8473938e4c29adc21a9e556847a4d44ad508874  v2.2.0.tar.gz"
DESCRIPTION="Command-line copy/paste utilities for Wayland"
build() {
    meson --prefix=/usr build/
    ninja -C build/                      
}

package() {
    DESTDIR=$ROOT ninja -C build/ install
}
