#!/bin/sh
NAME="wl-clipboard"
RELEASE="1"
VERSION="2.1.0" 
SOURCES="https://github.com/bugaevc/wl-clipboard/archive/refs/tags/v$VERSION.tar.gz"                                   
SHA256SUM="72dab9a7d3835c76d6ff2089f15ffec9e064a321e5f3cbbe961a8fa81aff5573  v2.1.0.tar.gz"                                                                                       
DESCRIPTION="Command-line copy/paste utilities for Wayland"
build() {                                                          
    meson --prefix=/usr build/
    ninja -C build/                      
}

install() {
    DESTDIR=$ROOT ninja -C build/ install
}
