#!/bin/sh
NAME="gst-plugins-base"
RELEASE="1"
VERSION="1.22.7"
SOURCES="https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-$VERSION.tar.xz"
BUILD_DEPENDS="meson gobject-introspection"
DEPENDS="alsa-lib gdk-pixbuf gtk3 gstreamer iso-codes libgudev libjpeg-turbo libpng libogg libvorbis mesa pango wayland-protocols libx11"
SHA256SUM="62519e0d8f969ebf62a9a7996f2d23efdda330217a635f4a32c0bf1c71577468"
DESCRIPTION="gst-plugins-base"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    --wrap-mode=nodownload \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
