#!/bin/sh
NAME="gst-plugins-base"
RELEASE="1"
VERSION="1.26.8"
SOURCES="https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-$VERSION.tar.xz"
BUILD_DEPENDS="meson gobject-introspection"
DEPENDS="alsa-lib gdk-pixbuf gtk3 gstreamer iso-codes libgudev libjpeg-turbo libpng libogg libvorbis mesa pango wayland-protocols libx11"
SHA256SUM="513cace4b02cb183ee47665d64bb2a25088abb6678c4cc57bb100b841add746b"
DESCRIPTION="gst-plugins-base"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    --wrap-mode=nodownload \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
