#!/bin/sh
NAME="gst-plugins-base"
RELEASE="1"
VERSION="1.22.5"
SOURCES="https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-$VERSION.tar.xz"
BUILD_DEPENDS="meson gobject-introspection"
DEPENDS="alsa-lib gdk-pixbuf gtk3 gstreamer iso-codes libgudev libjpeg-turbo libpng libogg libvorbis mesa pango wayland-protocols libx11"
SHA256SUM="edd4338b45c26a9af28c0d35aab964a024c3884ba6f520d8428df04212c8c93a"
DESCRIPTION="gst-plugins-base"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    --wrap-mode=nodownload \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
