#!/bin/sh
NAME="flatpak"
RELEASE="2"
VERSION="1.14.5"
SOURCES="https://github.com/flatpak/flatpak/releases/download/$VERSION/flatpak-$VERSION.tar.xz"
BUILD_DEPENDS="meson"
NO_CHKUPD="true"
DEPENDS="appstream libseccomp polkit libxau xdg-dbus-proxy bubblewrap json-glib ostree gdk-pixbuf python-pyparsing fuse libxml2 glib gpgme"
SHA256SUM="5b70c64ce7ac134e1ea08011256e423ae5c54f277297441583f77d013f27ffac"
DESCRIPTION="Linux application sandboxing and distribution framework"

build() {
    meson setup --prefix=/usr \
	-Ddocbook_docs=disabled \
  -Dsystem_bubblewrap=bwrap \
  -Dsystem_dbus_proxy=xdg-dbus-proxy \
	-Dtests=false	\
	build

    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
