#!/bin/sh
NAME="flatpak"
RELEASE="2"
VERSION="1.15.6"
SOURCES="https://github.com/flatpak/flatpak/releases/download/$VERSION/flatpak-$VERSION.tar.xz"
BUILD_DEPENDS="meson"
DEPENDS="appstream libseccomp polkit libxau xdg-dbus-proxy bubblewrap json-glib ostree gdk-pixbuf python-pyparsing fuse libxml2 glib gpgme"
SHA256SUM="8eb68189eb4850a34752feb29827cc2cc744c1981b8915e280ec1cf5bc387962"
DESCRIPTION="Linux application sandboxing and distribution framework"

build() {
    meson setup --prefix=/usr \
	-Ddocbook_docs=disabled \
  -Dsystem_bubblewrap=bwrap \
  -Dsystem_dbus_proxy=xdg-dbus-proxy \
	-Dtests=false	\
	build

    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
