#!/bin/sh
NAME="gnu-core"
RELEASE="1"
VERSION="0.1"
NO_CHKUPD="y"
DEPENDS="gnu-coreutils pigz xz-uils bash gsed bzip2 pach diffuils findutils util-linux bc cpio which"
DESCRIPTION="GNU core group"
IS_GROUP="y"
