#!/bin/sh
NAME="texinfo"
RELEASE="1"
VERSION="7.1.1"
BUILD_DEPENDS="gmake"
SOURCES="https://ftp.gnu.org/gnu/texinfo/texinfo-$VERSION.tar.xz"
DEPENDS="gettext perl"
SHA256SUM="31ae37e46283529432b61bee1ce01ed0090d599e606fc6a29dca1f77c76a6c82"
DESCRIPTION="GNU texinfo"

build() {
    sed -e 's/__attribute_nonnull__/__nonnull/' \
    -i gnulib/lib/malloc/dynarray-skeleton.c
    kpkgConfigure --prefix=/usr
}

package() {
    make DESTDIR=$ROOT install
    rm -rf "$ROOT/usr/share/info/dir"
}
