#!/bin/sh
NAME="texinfo"
RELEASE="1"
VERSION="7.0.1"
SOURCES="https://ftp.gnu.org/gnu/texinfo/texinfo-$VERSION.tar.xz"
SHA256SUM="bcd221fdb2d807a8a09938a0f8d5e010ebd2b58fca16075483d6fcb78db2c6b2  texinfo-7.0.1.tar.xz"
DESCRIPTION="GNU texinfo"

build() {
    sed -e 's/__attribute_nonnull__/__nonnull/' \
    -i gnulib/lib/malloc/dynarray-skeleton.c
    ./configure --prefix=/usr
}

install() {
    make DESTDIR=$ROOT install
}
