#!/bin/sh
NAME="slang"
RELEASE="1"
VERSION="2.3.3"
SOURCES="https://www.jedsoft.org/releases/slang/slang-$VERSION.tar.bz2"
SHA256SUM="f9145054ae131973c61208ea82486d5dd10e3c5cdad23b7c4a0617743c8f5a18  slang-2.3.3.tar.bz2"
DESCRIPTION="slang"

build() {
    ./configure --prefix=/usr                   \
                --sysconfdir=/etc               \
                --build=$(uname -m) \
                --host=$(uname -m) \
                --target=$(uname -m)
    make
}

package() {
    make DESTDIR=$ROOT install
}
