#!/bin/sh
NAME="slang"
RELEASE="1"
VERSION="2.3.3"
BUILD_DEPENDS="gmake"
SOURCES="https://www.jedsoft.org/releases/slang/slang-$VERSION.tar.bz2"
SHA256SUM="SKIP"
DESCRIPTION="slang"

build() {
    kpkgConfigure --prefix=/usr                   \
                --sysconfdir=/etc               \
                --build=$(uname -m) \
                --host=$(uname -m) \
                --target=$(uname -m)
    make
}

package() {
    make DESTDIR=$ROOT install
}
