#!/bin/sh
NAME="util-linux"
RELEASE="1"
VERSION="2.39"
SOURCES="https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v$VERSION/util-linux-$VERSION.tar.xz"
DEPENDS=""
SHA256SUM="32b30a336cda903182ed61feb3e9b908b762a5e66fe14e43efb88d37162075cb  util-linux-2.39.tar.xz"
BUILD_AS_ROOT="true"
DESCRIPTION="Linux Utilities"

build() {
    ./configure --prefix=/usr
    make
}

package() {
    cat /etc/group | grep tty || addgroup tty
    make DESTDIR=$ROOT install -j1
}
