#!/bin/sh
NAME="util-linux"
RELEASE="1"
VERSION="2.39.2"
SOURCES="https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.39/util-linux-$VERSION.tar.xz"
SHA256SUM="87abdfaa8e490f8be6dde976f7c80b9b5ff9f301e1b67e3899e1f05a59a1531f"
DESCRIPTION="Linux Utilities"

build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install -j1
}

postinstall() {
    cat /etc/group | grep tty || addgroup tty
}
