#!/bin/sh
NAME="util-linux"
RELEASE="1"
VERSION="2.41.2"
BUILD_DEPENDS="gmake"
SOURCES="https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.39/util-linux-$VERSION.tar.xz"
SHA256SUM="7b6605e48d1a49f43cc4b4cfc59f313d0dd5402fa40b96810bd572e167dfed0f"
DESCRIPTION="Linux Utilities"

build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install -j1
}

postinstall() {
    cat /etc/group | grep tty || addgroup tty
}
