#!/bin/sh
NAME="python-six"
RELEASE="1"
VERSION="1.16.0"
SOURCES="https://pypi.io/packages/source/s/six/six-$VERSION.tar.gz"
DEPENDS="python"
BUILD_DEPENDS="python-setuptools"
SHA256SUM="1e61c37477a1626458e36f7b1d82aa5c9b094fa4802892072e49de9c60c4c926"
DESCRIPTION="Python 2 and 3 compatibility utilities"

package() {
    python setup.py install --optimize=1 --prefix=/usr --root="$ROOT"
}
