#!/bin/sh
NAME="rsync"
RELEASE="1"
VERSION="3.3.0pre1"
SOURCES="https://download.samba.org/pub/rsync/src-previews/rsync-$VERSION.tar.gz"
SHA256SUM="30a18c6654cc09f6c6e5edb6738f196b20a1f2341dac5282693d69db2eac54e1"
DESCRIPTION="Open source utility that provides fast incremental file transfer"

build() {
    kpkgConfigure --disable-lz4 --disable-xxhash
    make
}

package() {
    make DESTDIR=$ROOT install
}
