#!/bin/sh
NAME="rsync"
RELEASE="1"
VERSION="3.4.1"
SOURCES="https://download.samba.org/pub/rsync/src-previews/rsync-$VERSION.tar.gz"
BUILD_DEPENDS="gmake"
SHA256SUM="SKIP"
DESCRIPTION="Open source utility that provides fast incremental file transfer"

build() {
    kpkgConfigure --disable-lz4 --disable-xxhash
    make
}

package() {
    make DESTDIR=$ROOT install
}
