#!/bin/sh
NAME="libsm"
RELEASE="1"
VERSION="1.2.6"
SOURCES="https://www.x.org/releases/individual/lib/libSM-$VERSION.tar.xz"
SHA256SUM="be7c0abdb15cbfd29ac62573c1c82e877f9d4047ad15321e7ea97d1e43d835be"
DEPENDS="libice util-linux"
BUILD_DEPENDS="xorgproto xtrans gmake"
DESCRIPTION="X11 Session Management Library"

build() {
    kpkgConfigure \
        --prefix=/usr \
        --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
