#!/bin/sh
NAME="xorriso"
RELEASE="1"
VERSION="1.5.6.pl02"
SOURCES="https://www.gnu.org/software/xorriso/xorriso-$VERSION.tar.gz"
DEPENDS="readline"
SHA256SUM="786f9f5df9865cc5b0c1fecee3d2c0f5e04cab8c9a859bd1c9c7ccd4964fdae1  xorriso-1.5.6.pl02.tar.gz"
DESCRIPTION="GNU xorriso"

build() {
    ./configure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
