#!/bin/sh
NAME="xorriso"
RELEASE="1"
VERSION="1.5.7"
SOURCES="https://www.gnu.org/software/xorriso/xorriso-$VERSION.tar.gz"
DEPENDS="readline"
SHA256SUM="867577c387f6b4a9a3224eb441ded8fb1638df6cbc060f8d1a1e5d00f318f502  xorriso-1.5.7.tar.gz"
DESCRIPTION="GNU xorriso"

build() {
    ./configure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
