#!/bin/sh
NAME="gettext-runtime"
RELEASE="1"
VERSION="0.21.1"
SOURCES="https://ftp.gnu.org/gnu/gettext/gettext-$VERSION.tar.xz"
SHA256SUM="50dbc8f39797950aa2c98e939947c527e5ac9ebd2c1b99dd7b06ba33a6767ae6  gettext-0.21.1.tar.xz"
DESCRIPTION="A part of gettext."

build() {
    cd gettext-runtime
    ./configure --prefix=/usr
    make -j$(nproc)
}

install() {
    cd gettext-runtime
    make DESTDIR=$ROOT install
}
