#!/bin/sh
NAME="links"
RELEASE="1"
VERSION="2.30"
BUILD_DEPENDS="gmake"
SOURCES="http://links.twibright.com/download/links-$VERSION.tar.bz2"
SHA256SUM="c4631c6b5a11527cdc3cb7872fc23b7f2b25c2b021d596be410dadb40315f166"
DESCRIPTION="A text WWW browser, similar to Lynx"

build() {
    kpkgConfigure --disable-javascript
    make
}

package() {
    make DESTDIR=$ROOT install
}
