#!/bin/sh
NAME="libxfixes"
RELEASE="1"
VERSION="6.0.1"
SOURCES="https://www.x.org/releases/individual/lib/libXfixes-$VERSION.tar.gz"
SHA256SUM="e69eaa321173c748ba6e2f15c7cf8da87f911d3ea1b6af4b547974aef6366bec"
DEPENDS="libx11"
BUILD_DEPENDS="xorgproto"
DESCRIPTION="libxfixes"

build() {
    kpkgConfigure \
        --sysconfdir=/etc \
        --prefix=/usr \
        --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
