#!/bin/sh
NAME="libxfixes"
RELEASE="1"
VERSION="6.0.2"
SOURCES="https://www.x.org/releases/individual/lib/libXfixes-$VERSION.tar.gz"
SHA256SUM="041331b8e6e36038b3bf836785b6b175ec8515f964c9e4e3316b3bfed0f53ac7"
DEPENDS="libx11"
BUILD_DEPENDS="xorgproto gmake"
DESCRIPTION="libxfixes"

build() {
    kpkgConfigure \
        --sysconfdir=/etc \
        --prefix=/usr \
        --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
