#!/bin/sh
NAME="libxtst"
RELEASE="1"
VERSION="1.2.4"
SOURCES="https://www.x.org/releases/individual/lib/libXtst-$VERSION.tar.xz"
SHA256SUM="84f5f30b9254b4ffee14b5b0940e2622153b0d3aed8286a3c5b7eeb340ca33c8"
DEPENDS="libxext libxfixes libxi"
BUILD_DEPENDS="xorgproto"
DESCRIPTION="libxtst"

build() {
    ./configure \
        --prefix=/usr \
        --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
