#!/bin/sh
NAME="libxtst"
RELEASE="1"
VERSION="1.2.5"
SOURCES="https://www.x.org/releases/individual/lib/libXtst-$VERSION.tar.xz"
SHA256SUM="b50d4c25b97009a744706c1039c598f4d8e64910c9fde381994e1cae235d9242"
DEPENDS="libxext libxfixes libxi"
BUILD_DEPENDS="xorgproto gmake"
DESCRIPTION="libxtst"

build() {
    kpkgConfigure \
        --prefix=/usr \
        --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
