#!/bin/sh
NAME="ed"
RELEASE="1"
VERSION="1.20.1"
SOURCES="https://ftp.gnu.org/gnu/ed/ed-$VERSION.tar.lz"
BUILD_DEPENDS="lzip gmake"
SHA256SUM="b1a463b297a141f9876c4b1fcd01477f645cded92168090e9a35db2af4babbca"
DESCRIPTION="A line-oriented text editor"

build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make install 
}
