#!/bin/sh
NAME="ed"
RELEASE="1"
VERSION="1.22.2"
SOURCES="https://ftp.gnu.org/gnu/ed/ed-$VERSION.tar.lz"
BUILD_DEPENDS="lzip gmake"
SHA256SUM="f58d15242056e15af76f13f34c60d890fa2a2d5cb0abef91c115e4d83794ffe3"
DESCRIPTION="A line-oriented text editor"

build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make install 
}
