#!/bin/sh
NAME="ed"
RELEASE="1"
VERSION="1.20"
SOURCES="https://ftp.gnu.org/gnu/ed/ed-$VERSION.tar.lz"
BUILD_DEPENDS="lzip gmake"
SHA256SUM="c6030defe6ae172f1687906d7354054c75a6a9130af319d4e73c50a91959c5a6"
DESCRIPTION="A line-oriented text editor"

build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make install 
}
