#!/bin/sh
NAME="neofetch"
VERSION="7.1.0"
SOURCES="https://github.com/dylanaraps/neofetch/archive/refs/tags/$VERSION.tar.gz"
SHA256SUM="58a95e6b714e41efc804eca389a223309169b2def35e57fa934482a6b47c27e7  7.1.0.tar.gz"
DESCRIPTION="A command-line system information tool written in bash 3.2+"

build() {
    tar -xvf $VERSION.tar.gz
    cd $VERSION
	mkdir -p $ROOT/usr/bin
	cp -rf   neofetch $ROOT/usr/bin
	chmod +x $ROOT/usr/bin/neofetch
}
