#!/bin/sh
NAME="libxft"
RELEASE="1"
VERSION="2.3.9"
SOURCES="https://www.x.org/releases/individual/lib/libXft-$VERSION.tar.xz"
SHA256SUM="60a25b78945ed6932635b3bb1899a517d31df7456e69867ffba27f89ff3976f5"
DEPENDS="libx11 libxext libxrender fontconfig freetype"
BUILD_DEPENDS="xtrans gmake"
DESCRIPTION="X11 client-side font rendering library"

build() {
    kpkgConfigure \
        --prefix=/usr \
        --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
