#!/bin/sh
NAME="libxft"
RELEASE="1"
VERSION="2.3.8"
SOURCES="https://www.x.org/releases/individual/lib/libXft-$VERSION.tar.xz"
SHA256SUM="5e8c3c4bc2d4c0a40aef6b4b38ed2fb74301640da29f6528154b5009b1c6dd49  libXft-2.3.8.tar.xz"
DEPENDS="libx11 libxext libxrender fontconfig freetype"
BUILD_DEPENDS="xtrans"
DESCRIPTION="X11 client-side font rendering library"

build() {
    ./configure \
        --prefix=/usr \
        --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
