#!/bin/sh
NAME="libxml2"
RELEASE="1"
VERSION="2.11.5"
SOURCES="https://download.gnome.org/sources/libxml2/2.11/libxml2-$VERSION.tar.xz"
DEPENDS="python xz-utils"
SHA256SUM="3727b078c360ec69fa869de14bd6f75d7ee8d36987b071e6928d4720a28df3a6"
DESCRIPTION="Libraries and utilities for parsing XML files"

build() {
    ./configure --prefix=/usr    \
            --disable-static \
            --with-history   \
            --with-python=/usr/bin/python3
    make
}

package() {
    make DESTDIR=$ROOT install
}
