#!/bin/sh
NAME="libxml2"
RELEASE="1"
VERSION="2.10.4"
SOURCES="https://download.gnome.org/sources/libxml2/2.10/libxml2-$VERSION.tar.xz"
SHA256SUM="ed0c91c5845008f1936739e4eee2035531c1c94742c6541f44ee66d885948d45  libxml2-2.10.4.tar.xz"
DESCRIPTION="Libraries and utilities for parsing XML files"

build() {
    ./configure --prefix=/usr    \
            --disable-static \
            --with-history   \
            --with-python=/usr/bin/python3
    make
}

install() {
    make DESTDIR=$ROOT install
}
