#!/bin/sh
NAME="libxml2"
VER1="2.9"
VERSION="$VER1.13"
DESCRIPTION="Libraries and utilities for parsing XML files"

build() {
    wget https://download.gnome.org/sources/libxml2/$VER1/libxml2-$VERSION.tar.xz
    tar -xvf libxml2-$VERSION.tar.xz
    cd libxml2-$VERSION || exit 1
    ./configure --prefix=/usr    \
            --disable-static \
            --with-history   \
            --host=
            --with-python=/usr/bin/python3 \
    make
    make DESTDIR=$ROOT install
}
