#!/bin/sh
NAME="gnome-backgrounds"
RELEASE="1"
VERSION="49.0"
SOURCES="https://gitlab.gnome.org/GNOME/gnome-backgrounds/-/archive/$VERSION/gnome-backgrounds-$VERSION.tar.gz"
BUILD_DEPENDS="meson"
SHA256SUM="d143242e10e48747a74dc61a29976bd9d4ce5327aff8e7bf8342ec603bf2155b"
DESCRIPTION="Backgrounds for GNOME"

build() {
    meson setup \
    --prefix=/usr \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
