#!/bin/sh
NAME="gnome-backgrounds"
RELEASE="1"
VERSION="49.0"
SOURCES="https://gitlab.gnome.org/GNOME/gnome-backgrounds/-/archive/$VERSION/gnome-backgrounds-$VERSION.tar.gz"
BUILD_DEPENDS="meson"
SHA256SUM="67f8c020249a83daf5d9b9f71ec62d910d542fa8cf9deba837f4ca2669735996"
DESCRIPTION="Backgrounds for GNOME"

build() {
    meson setup \
    --prefix=/usr \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
