#!/bin/sh
NAME="gnome-backgrounds"
RELEASE="1"
VERSION="49.0"
SOURCES="https://gitlab.gnome.org/GNOME/gnome-backgrounds/-/archive/$VERSION/gnome-backgrounds-$VERSION.tar.gz"
BUILD_DEPENDS="meson"
SHA256SUM="d1eb89736609bba2dc79f1bdbc3529e5d6888b7369ab10d11dd79653fbf085a3"
DESCRIPTION="Backgrounds for GNOME"

build() {
    meson setup \
    --prefix=/usr \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
