#!/bin/sh
NAME="libsecret"
RELEASE="1"
VERSION="0.21.1"
SOURCES="https://download.gnome.org/sources/libsecret/0.21/libsecret-$VERSION.tar.xz"
DEPENDS="glib libgcrypt gobject-introspection vala"
BUILD_DEPENDS="meson"
SHA256SUM="674f51323a5f74e4cb7e3277da68b5afddd333eca25bc9fd2d820a92972f90b1"
DESCRIPTION="A GObject-based library for accessing the Secret Service API"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Dgtk_doc=false \
    -Dmanpage=false	\
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
