#!/bin/sh
NAME="libsecret"
RELEASE="1"
VERSION="0.21.7"
SOURCES="https://download.gnome.org/sources/libsecret/0.21/libsecret-$VERSION.tar.xz"
DEPENDS="glib libgcrypt gobject-introspection vala"
BUILD_DEPENDS="meson"
SHA256SUM="e4a341496a0815e64c8d3b8fabab33d7bae7efdeab77b843669731d5b181dcee"
DESCRIPTION="A GObject-based library for accessing the Secret Service API"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Dgtk_doc=false \
    -Dmanpage=false	\
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
