#!/bin/sh
NAME="libsecret"
RELEASE="1"
VERSION="0.21.0"
SOURCES="https://download.gnome.org/sources/libsecret/0.21/libsecret-$VERSION.tar.xz"
DEPENDS="glib gobject-introspection vala"
BUILD_DEPENDS="meson"
SHA256SUM="2735b29d1cc0e5b12ba90bee88bd21774ac8db4ae1a4b716f46c409c19a14613  libsecret-0.21.0.tar.xz"
DESCRIPTION="A GObject-based library for accessing the Secret Service API"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Dgtk_doc=false \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
