#!/bin/sh
NAME="gnome-online-accounts"
RELEASE="2"
VERSION="3.56.2"
SOURCES="https://gitlab.gnome.org/GNOME/gnome-online-accounts/-/archive/$VERSION/gnome-online-accounts-$VERSION.tar.gz"
BUILD_DEPENDS="meson vala gobject-introspection webkitgtk3"
DEPENDS="json-glib rest"
SHA256SUM="879dc862648b6017a0817a15840a71e36d373e918364d0d24da28ddb69932011"
DESCRIPTION="The GNOME online account manager"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Dkerberos=false \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
