#!/bin/sh
NAME="gnome-online-accounts"
RELEASE="2"
VERSION="3.56.2"
SOURCES="https://gitlab.gnome.org/GNOME/gnome-online-accounts/-/archive/$VERSION/gnome-online-accounts-$VERSION.tar.gz"
BUILD_DEPENDS="meson vala gobject-introspection webkitgtk3"
DEPENDS="json-glib rest"
SHA256SUM="5f0fa722b7a551298c7ff67f4e7ebb1a4cdcc8ca88a6a7ee630c513203760af5"
DESCRIPTION="The GNOME online account manager"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Dkerberos=false \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
