#!/bin/sh
NAME="gnome-online-accounts"
RELEASE="1"
VERSION="3.48.0"
SOURCES="https://gitlab.gnome.org/GNOME/gnome-online-accounts/-/archive/$VERSION/gnome-online-accounts-$VERSION.tar.gz"
BUILD_DEPENDS="meson vala gobject-introspection"
DEPENDS="json-glib rest"
SHA256SUM="2a24734ab3f8dc4f846c961a15f133b90d209b34598c396f2014dff53540e8c3  gnome-online-accounts-3.48.0.tar.gz"
DESCRIPTION="The GNOME online account manager"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Dkerberos=false \
    -Dgoabackend=false \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
