#!/bin/sh
NAME="libxxf86vm"
RELEASE="1"
VERSION="1.1.6"
BUILD_DEPENDS="gmake"
SOURCES="https://www.x.org/releases/individual/lib/libXxf86vm-$VERSION.tar.xz"
SHA256SUM="96af414c73ce1d5449ad04be7f9f27fa8330f844b6dda843ef22e3e1befb3ee3"
DEPENDS="libxext xorgproto"
DESCRIPTION="X11 library"

build() {
    kpkgConfigure \
        --prefix=/usr \
        --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
