#!/bin/sh
NAME="krb5"
RELEASE="1"
VERSION="1.22.1"
SOURCES="https://kerberos.org/dist/krb5/1.22/krb5-$VERSION.tar.gz"
DEPENDS="e2fsprogs"
BUILD_DEPENDS="perl gmake"
SHA256SUM="1a8832b8cad923ebbf1394f67e2efcf41e3a49f460285a66e35adec8fa0053af"
DESCRIPTION="kerberos"

build() {
    
    cd src

    # Got flags from BLFS
    kpkgConfigure --prefix=/usr            \
            --sysconfdir=/etc        \
            --localstatedir=/var/lib \
            --runstatedir=/run       \
            --with-system-et         \
            --with-system-ss         \
            --with-system-verto=no   \
            --enable-dns-for-realm
    make
}

package() {
    cd src
    make DESTDIR=$ROOT install
}
