#!/bin/sh
NAME="krb5"
RELEASE="1"
VERSION="1.21.2"
SOURCES="https://kerberos.org/dist/krb5/1.21/krb5-$VERSION.tar.gz"
DEPENDS="e2fsprogs"
BUILD_DEPENDS="perl"
SHA256SUM="9560941a9d843c0243a71b17a7ac6fe31c7cebb5bce3983db79e52ae7e850491  krb5-1.21.2.tar.gz"
DESCRIPTION="kerberos"

build() {
    
    cd src

    # Got flags from BLFS
    ./configure --prefix=/usr            \
            --sysconfdir=/etc        \
            --localstatedir=/var/lib \
            --runstatedir=/run       \
            --with-system-et         \
            --with-system-ss         \
            --with-system-verto=no   \
            --enable-dns-for-realm
    make
}

package() {
    cd src
    make DESTDIR=$ROOT install
}
