#!/bin/sh
NAME="libisl"
VERSION="0.24"
DESCRIPTION="isl is a library for manipulating sets and relations of integer points bounded by linear constraints."

build() {
    [ ! -f "isl.tar.xz" ] && wget https://libisl.sourceforge.io/isl-$VERSION.tar.xz -O isl.tar.xz
    tar -xvf isl.tar.xz
    cd isl-$VERSION || exit 1
    ./configure --prefix=/usr
    make -j$(nproc)
    make DESTDIR=$ROOT install
    mkdir -pv $ROOT/usr/share/gdb/auto-load/usr/lib
    mv -v $ROOT/usr/lib/libisl*gdb.py /usr/share/gdb/auto-load/usr/lib
}
