#!/bin/sh
NAME="libisl"
RELEASE="1"
VERSION="0.27"
BUILD_DEPENDS="gmake"
SOURCES="https://libisl.sourceforge.io/isl-$VERSION.tar.xz"
DEPENDS="gmp"
SHA256SUM="6d8babb59e7b672e8cb7870e874f3f7b813b6e00e6af3f8b04f7579965643d5c"
DESCRIPTION="isl is a library for manipulating sets and relations of integer points bounded by linear constraints."

build() {
    kpkgConfigure --prefix=/usr
    make -j$(nproc)
}

package() {
    make DESTDIR=$ROOT install
}
