#!/bin/sh
NAME="libisl"
VERSION="0.24"
SOURCES="https://libisl.sourceforge.io/isl-$VERSION.tar.xz"
SHA256SUM="043105cc544f416b48736fff8caf077fb0663a717d06b1113f16e391ac99ebad  isl-0.24.tar.xz"
DESCRIPTION="isl is a library for manipulating sets and relations of integer points bounded by linear constraints."

build() {
    tar -xvf isl-$VERSION.tar.xz
    cd isl-$VERSION || exit 1
    ./configure --prefix=/usr
    make -j$(nproc)
    make DESTDIR=$ROOT install
    mkdir -pv $ROOT/usr/share/gdb/auto-load/usr/lib
    mv -v $ROOT/usr/lib/libisl*gdb.py /usr/share/gdb/auto-load/usr/lib
}
