#!/bin/sh
NAME="swaybg"
RELEASE="1"
VERSION="1.2.1"
SOURCES="https://github.com/swaywm/swaybg/releases/download/v$VERSION/swaybg-$VERSION.tar.gz"
BUILD_DEPENDS="meson"
DEPENDS="wayland-protocols wayland pixman cairo libpng"
SHA256SUM="6af1fdf0e57b1cc5345febed786b761fea0e170943a82639f94cfaed7df84f8f"
DESCRIPTION="Wallpaper utility for Wayland compositors"

build() {
    meson setup --prefix=/usr build/
    ninja -C build/
}

package() {
    DESTDIR=$ROOT ninja -C build/ install
}
