#!/bin/sh
NAME="linux-pam"
RELEASE="2"
VERSION="1.5.3"
SOURCES="https://github.com/linux-pam/linux-pam/releases/download/v$VERSION/Linux-PAM-$VERSION.tar.xz;pam.d/other;pam.d/system-account;pam.d/system-auth;pam.d/system-password;pam.d/system-session"
SHA256SUM="7ac4b50feee004a9fa88f1dfd2d2fa738a82896763050cd773b3c54b0a818283  Linux-PAM-1.5.3.tar.xz;461e53f138a8e5d1ed20033f8d9363c56f2187ce2a0551d57860140da40e1697  pam.d/other;a8295e4780b323cac83ca08c65c8cd47ca26e516d64ed857fd3f4ac1f1a8ccc4  pam.d/system-account;da912d0b5fe0ee9d70403ca88402974f2c24b6dfeb2c8adc037c72297a859590  pam.d/system-auth;29ef099774837bf3fe01ef6b22fc87ac55bf222a4c0f8544d007f57b6aa4b61a  pam.d/system-password;5fbb7220de9d119e4e5551862ea516134ffc62d1b0695fe063add2774983753d  pam.d/system-session"
DESCRIPTION="Pluggable Authentication Modules for Linux"

prepare() { 
  mkdir pam.d
  
  for i in other system-account system-auth system-password system-session
  do
    cp -f "$i" "pam.d/$i"
  done

  tar -xvf Linux-PAM-$VERSION.tar.gz
  cd Linux-PAM-$VERSION
}

build() {
    cd Linux-PAM-$VERSION
    ./configure --prefix=/usr --enable-securedir=/usr/lib/security
    make
}

package() {
    cd Linux-PAM-$VERSION
    make DESTDIR=$ROOT install
    mkdir -p "$ROOT/etc/pam.d"
    cp -rf pam.d/* "$ROOT/etc/pam.d/" 
}
