#!/bin/sh
NAME="linux-pam"
RELEASE="1"
VERSION="1.5.3"
SOURCES="https://github.com/linux-pam/linux-pam/releases/download/v$VERSION/Linux-PAM-$VERSION.tar.xz"
SHA256SUM="7ac4b50feee004a9fa88f1dfd2d2fa738a82896763050cd773b3c54b0a818283  Linux-PAM-1.5.3.tar.xz"
DESCRIPTION="Pluggable Authentication Modules for Linux"

build() {
    ./configure --prefix=/usr --enable-securedir=/usr/lib/security
    make
}

package() {
    make DESTDIR=$ROOT install
}
