#!/bin/sh
NAME="linux-pam"
RELEASE="6"
VERSION="1.5.3"
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/linux-pam/linux-pam/releases/download/v$VERSION/Linux-PAM-$VERSION.tar.xz pam.d/other pam.d/system-account pam.d/system-auth pam.d/system-password pam.d/system-session pam.d/login"
SHA256SUM="7ac4b50feee004a9fa88f1dfd2d2fa738a82896763050cd773b3c54b0a818283 SKIP SKIP SKIP SKIP SKIP SKIP"
EXTRACT="false"
DESCRIPTION="Pluggable Authentication Modules for Linux"

prepare() { 
  mkdir pam.d
  
  for i in other system-account system-auth system-password system-session login
  do
    cp -f "$i" "pam.d/$i"
  done

  tar -xvf Linux-PAM-$VERSION.tar.xz
  cd Linux-PAM-$VERSION
}

build() {
    cd Linux-PAM-$VERSION
    kpkgConfigure --prefix=/usr --enable-securedir=/usr/lib/security
    make
}

package() {
    cd Linux-PAM-$VERSION
    make DESTDIR=$ROOT install
    mkdir -p "$ROOT/etc/pam.d"
    cp -rf ../pam.d/* "$ROOT/etc/pam.d/" 
}
