#!/bin/sh
NAME="openssl"
RELEASE="1"
VERSION="3.3.1"
BUILD_DEPENDS="gmake"
SOURCES="https://www.openssl.org/source/openssl-$VERSION.tar.gz"
SHA256SUM="777cd596284c883375a2a7a11bf5d2786fc5413255efab20c50d6ffe6d020b7e"
DEPENDS="zlib"
DESCRIPTION="TLS library"

build() {
    if [ "$KPKG_ARCH" != "$(uname -m)" ]; then
	extraArgs="linux-$KPKG_ARCH"
	export CFLAGS=-I/usr/$KPKG_TARGET/usr/include 
	export LDFLAGS=-L/usr/$KPKG_TARGET/lib
	export PKG_CONFIG_PATH=/usr/$KPKG_TARGET/usr/lib/pkgconfig
    fi
    ./config $extraArgs --prefix=/usr --openssldir=/etc/ssl --libdir=lib shared zlib-dynamic
    make -j$(nproc)
}

package() {
    make DESTDIR="$ROOT" install
}

