#!/bin/sh
NAME="openssl"
RELEASE="1"
VERSION="3.3.0"
BUILD_DEPENDS="gmake"
SOURCES="https://www.openssl.org/source/openssl-$VERSION.tar.gz"
SHA256SUM="53e66b043322a606abf0087e7699a0e033a37fa13feb9742df35c3a33b18fb02"
DEPENDS="zlib"
DESCRIPTION="TLS library"

build() {
    if [ "$KPKG_ARCH" != "$(uname -m)" ]; then
	extraArgs="linux-$KPKG_ARCH"
	export CFLAGS=-I/usr/$KPKG_TARGET/usr/include 
	export LDFLAGS=-L/usr/$KPKG_TARGET/lib
	export PKG_CONFIG_PATH=/usr/$KPKG_TARGET/usr/lib/pkgconfig
    fi
    ./config $extraArgs --prefix=/usr --openssldir=/etc/ssl --libdir=lib shared zlib-dynamic
    make -j$(nproc)
}

package() {
    make DESTDIR="$ROOT" install
}

