#!/bin/sh
NAME="openssl"
RELEASE="1"
VERSION="3.2.0"
SOURCES="https://openssl.org/source/openssl-$VERSION.tar.gz"
SHA256SUM="14c826f07c7e433706fb5c69fa9e25dab95684844b4c962a2cf1bf183eb4690e"
DEPENDS="zlib"
DESCRIPTION="TLS library"

build() {
    if [ "$KPKG_ARCH" != "$(uname -m)" ]; then
	extraArgs="linux-$KPKG_ARCH"
	export CFLAGS=-I/usr/$KPKG_TARGET/usr/include 
	export LDFLAGS=-L/usr/$KPKG_TARGET/lib
	export PKG_CONFIG_PATH=/usr/$KPKG_TARGET/usr/lib/pkgconfig
    fi
    ./config $extraArgs --prefix=/usr --openssldir=/etc/ssl --libdir=lib shared zlib-dynamic
    make -j$(nproc)
}

package() {
    make DESTDIR="$ROOT" install
}

