#!/bin/sh
NAME="pycairo"
RELEASE="1"
VERSION="1.24.0"
SOURCES="https://github.com/pygobject/pycairo/releases/download/v$VERSION/pycairo-$VERSION.tar.gz"
DEPENDS="python cairo"
SHA256SUM="1444d52f1bb4cc79a4a0c0fe2ccec4bd78ff885ab01ebe1c0f637d8392bcafb6"
DESCRIPTION="Python bindings for Cairo, a 2D graphics library"

build() {
    meson setup \
        --prefix=/usr \
        --buildtype=release \
        build

    meson compile -C build
}

package() {
    meson install --destdir="$ROOT" -C build
}
