#!/bin/sh
NAME="vala"
RELEASE="1"
VERSION="0.56.14"
BUILD_DEPENDS="gmake"
SOURCES="https://download.gnome.org/sources/vala/0.56/vala-$VERSION.tar.xz"
DEPENDS="glib gobject-introspection"
SHA256SUM="9382c268ca9bdc02aaedc8152a9818bf3935273041f629c56de410e360a3f557"
DESCRIPTION="Programming language commonly used in GNOME applications"

build() {
    kpkgConfigure --disable-valadoc --prefix=/usr
    make
}

package() {
    make install
}
