#!/bin/sh
NAME="nghttp2"
RELEASE="1"
VERSION="1.56.0"
SOURCES="https://github.com/nghttp2/nghttp2/releases/download/v$VERSION/nghttp2-$VERSION.tar.xz"
DEPENDS="zlib python"
SHA256SUM="65eee8021e9d3620589a4a4e91ce9983d802b5229f78f3313770e13f4d2720e9  nghttp2-1.56.0.tar.xz"
DESCRIPTION=""
build() {
    ./configure \
        --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
