#!/bin/sh
NAME="libei"
RELEASE="2"
VERSION="1.4.1"
SOURCES="https://gitlab.freedesktop.org/libinput/libei/-/archive/$VERSION/libei-$VERSION.tar.gz"
DEPENDS="elogind libxkbcommon libevdev python-attr python-jinja2 gdk-pixbuf"
BUILD_DEPENDS="meson"
SHA256SUM="d0e8f18eb3617fbcc3d860bb54a47e17709e94e8e7cb0ae01ae221c67f000872"
DESCRIPTION="Library for Emulated Input"

build() {
    meson setup \
        --prefix=/usr \
        --buildtype=release \
        build/
    ninja -C build/
}

package() {
    DESTDIR=$ROOT ninja -C build/ install
}

postinstall() {
  gdk-pixbuf-query-loaders --update-cache
}
