#!/bin/sh
NAME="libei"
RELEASE="2"
VERSION="1.4.1"
SOURCES="https://gitlab.freedesktop.org/libinput/libei/-/archive/$VERSION/libei-$VERSION.tar.gz"
DEPENDS="elogind libxkbcommon libevdev python-attr python-jinja2 gdk-pixbuf"
BUILD_DEPENDS="meson"
SHA256SUM="680f85d49968dd96dff6e4b97340669d4e04a8b6248fbe223cdf192e8fc9e3e8"
DESCRIPTION="Library for Emulated Input"

build() {
    meson setup \
        --prefix=/usr \
        --buildtype=release \
        build/
    ninja -C build/
}

package() {
    DESTDIR=$ROOT ninja -C build/ install
}

postinstall() {
  gdk-pixbuf-query-loaders --update-cache
}
