#!/bin/sh
NAME="libtool"
RELEASE="1"
VERSION="2.5.3"
BUILD_DEPENDS="gmake"
SOURCES="https://ftp.gnu.org/gnu/libtool/libtool-$VERSION.tar.gz"
DEPENDS="m4"
SHA256SUM="9322bd8f6bc848fda3e385899dd1934957169652acef716d19d19d24053abb95"
DESCRIPTION="The GNU Portable Library Tool"
build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
    rm -rf "$ROOT"/usr/share/info/dir
}
