#!/bin/sh
NAME="runit"
VERSION="2.1.2"
SOURCES="http://smarden.org/runit/runit-$VERSION.tar.gz"
SHA256SUM="6fd0160cb0cf1207de4e66754b6d39750cff14bb0aa66ab49490992c0c47ba18  runit-2.1.2.tar.gz"
DESCRIPTION="The OpenRC init system"

build() {
    cd admin/runit-$VERSION/src || exit 1
    make
    cd .. || exit 1
    mkdir -p $ROOT/usr/bin
    for i in `cat package/commands`; do
       rm -f $ROOT/usr/bin/$i
       cp /tmp/nyaa_srcdir/admin/runit-$VERSION/src/$i $ROOT/usr/bin/$i
    done
}
