#!/bin/sh
NAME="elogind"
RELEASE="1"
VERSION="255.22"
SOURCES="https://github.com/elogind/elogind/archive/refs/tags/v$VERSION.tar.gz realpath.patch"
BUILD_DEPENDS="meson"
DEPENDS="dbus linux-pam python-jinja2 util-linux gperf eudev"
REPLACES="systemd"
SHA256SUM="SKIP SKIP"
DESCRIPTION="systemd-logind, extracted to be a standalone daemon"

prepare() {
  patch -p1 < ../realpath.patch
}

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Dman=false \
    -Ddbuspolicydir=/etc/dbus-1/system.d \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
    mkdir -p $ROOT/usr/lib/pkgconfig $ROOT/usr/include/systemd
    ln -s  libelogind.pc $ROOT/usr/lib/pkgconfig/libsystemd.pc
    ln -sn elogind $ROOT/usr/include/systemd 
}
