#!/bin/sh
NAME="elogind"
RELEASE="1"
VERSION="252.9"
SOURCES="https://github.com/elogind/elogind/archive/refs/tags/v$VERSION.tar.gz realpath.patch"
BUILD_DEPENDS="meson"
DEPENDS="dbus linux-pam python-jinja2 util-linux gperf eudev"
REPLACES="systemd"
SHA256SUM="7af8caa8225a406e77fb99c9f33dba5e1f0a94f0e1277c9d91dcfc016f116d85 feb8948704e98971a936eb69701d14c31b1be3017b9746d81f8ed739ed4189fc"
DESCRIPTION="systemd-logind, extracted to be a standalone daemon"

prepare() {
  patch -p1 < ../realpath.patch
}

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Dman=false \
    -Ddbuspolicydir=/etc/dbus-1/system.d \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
    mkdir -p $ROOT/usr/lib/pkgconfig $ROOT/usr/include/systemd
    ln -s  libelogind.pc $ROOT/usr/lib/pkgconfig/libsystemd.pc
    ln -sn elogind $ROOT/usr/include/systemd 
}
