#!/bin/sh
NAME="squashfs-tools"
RELEASE="1"
VERSION="4.6.1"
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/plougher/squashfs-tools/archive/refs/tags/$VERSION.tar.gz"
DEPENDS=""
SHA256SUM="9c4974e07c61547dae14af4ed1f358b7d04618ae194e54d6be72ee126f0d2f53"
DESCRIPTION="Tools for managing SquashFS"

build() {
    cd squashfs-tools
    make INSTALL_MANPAGES_DIR=""
 }

package() {
    cd squashfs-tools
    rm -f ../generate-manpages/install-manpages.sh
    touch ../generate-manpages/install-manpages.sh
    chmod +x ../generate-manpages/install-manpages.sh
    make INSTALL_MANPAGES_DIR="" INSTALL_PREFIX=$ROOT/usr DESTDIR=$ROOT install
}
