#!/bin/sh
NAME="squashfs-tools"
RELEASE="1"
VERSION="4.6.1"
SOURCES="https://github.com/plougher/squashfs-tools/archive/refs/tags/$VERSION.tar.gz"
DEPENDS=""
SHA256SUM="94201754b36121a9f022a190c75f718441df15402df32c2b520ca331a107511c"
DESCRIPTION="Tools for managing SquashFS"

build() {
    cd squashfs-tools
    make INSTALL_MANPAGES_DIR=""
 }

package() {
    cd squashfs-tools
    rm -f ../generate-manpages/install-manpages.sh
    touch ../generate-manpages/install-manpages.sh
    chmod +x ../generate-manpages/install-manpages.sh
    make INSTALL_MANPAGES_DIR="" INSTALL_PREFIX=$ROOT/usr DESTDIR=$ROOT install
}
