#!/bin/sh
NAME="python-mako"
VERSION="1.2.3"
SOURCES="https://files.pythonhosted.org/packages/source/M/Mako/Mako-$VERSION.tar.gz"
SHA256SUM="7fde96466fcfeedb0eed94f187f20b23d85e4cb41444be0e542e2c8c65c396cd  Mako-1.2.3.tar.gz"
DESCRIPTION="Hyperfast and lightweight templating for the Python platform"
build() {
    [ ! -d "Mako-$VERSION" ] && tar -xvf Mako-$VERSION.tar.gz
    cd Mako-$VERSION || exit 1
    SETUPTOOLS_USE_DISTUTILS=stdlib pip install . --prefix=/usr --root="$ROOT"
}
