#!/bin/sh
NAME="python-mako"
RELEASE="1"
VERSION="1.2.4"
SOURCES="https://files.pythonhosted.org/packages/source/M/Mako/Mako-$VERSION.tar.gz"
SHA256SUM="d60a3903dc3bb01a18ad6a89cdbe2e4eadc69c0bc8ef1e3773ba53d44c3f7a34  Mako-1.2.4.tar.gz"
DESCRIPTION="Hyperfast and lightweight templating for the Python platform"
build() {
}

install() {
    SETUPTOOLS_USE_DISTUTILS=stdlib pip install . --prefix=/usr --root="$ROOT"
}
