#!/bin/sh
NAME="perl-parse-yapp"
RELEASE="1"
VERSION="1.21"
BUILD_DEPENDS="gmake"
SOURCES="https://www.cpan.org/authors/id/W/WB/WBRASWELL/Parse-Yapp-$VERSION.tar.gz"
DEPENDS="perl"
SHA256SUM="3810e998308fba2e0f4f26043035032b027ce51ce5c8a52a8b8e340ca65f13e5"
DESCRIPTION="perl-parse-yapp"

build() {
    perl Makefile.PL
    make
}

package() {
    make DESTDIR=$ROOT install
}
