#!/bin/sh
NAME="libdrm"
RELEASE="1"
VERSION="2.4.120"
SOURCES="https://dri.freedesktop.org/libdrm/libdrm-$VERSION.tar.xz"
BUILD_DEPENDS="meson"
DEPENDS="libpciaccess"
SHA256SUM="3bf55363f76c7250946441ab51d3a6cc0ae518055c0ff017324ab76cdefb327a"
DESCRIPTION="libdrm"

build() {
    meson setup --prefix=/usr --buildtype=release build/
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
