#!/bin/sh
NAME="sqlite"
RELEASE="2"
VERSION="3.44.2"
SOURCES="https://sqlite.org/2023/sqlite-autoconf-3430200.tar.gz"
DEPENDS="ncurses"
SHA256SUM="6d422b6f62c4de2ca80d61860e3a3fb693554d2f75bb1aaca743ccc4d6f609f0"
DESCRIPTION="A small, fast, self-contained, high-reliability, full-featured, SQL database engine"

build() {
    kpkgConfigure --prefix=/usr \
	    	--disable-static \
        --enable-shared
    make
}

package() {
    make DESTDIR=$ROOT install
}
