#!/bin/sh
NAME="sqlite"
RELEASE="2"
VERSION="3.43.1"
SOURCES="https://sqlite.org/2023/sqlite-autoconf-3430100.tar.gz"
DEPENDS="ncurses"
SHA256SUM="39116c94e76630f22d54cd82c3cea308565f1715f716d1b2527f1c9c969ba4d9"
DESCRIPTION="A small, fast, self-contained, high-reliability, full-featured, SQL database engine"

build() {
    ./configure --prefix=/usr \
	    	--disable-static \
        --enable-shared
    make
}

package() {
    make DESTDIR=$ROOT install
}
