#!/bin/sh
NAME="sqlite"
RELEASE="2"
VERSION="3.43.0"
SOURCES="https://sqlite.org/2023/sqlite-autoconf-3430000.tar.gz"
DEPENDS="ncurses"
SHA256SUM="49008dbf3afc04d4edc8ecfc34e4ead196973034293c997adad2f63f01762ae1  sqlite-autoconf-3430000.tar.gz"
DESCRIPTION="A small, fast, self-contained, high-reliability, full-featured, SQL database engine"

build() {
    ./configure --prefix=/usr \
	    	--disable-static \
        --enable-shared
    make
}

package() {
    make DESTDIR=$ROOT install
}
