#!/bin/sh
NAME="pciutils"
RELEASE="1"
VERSION="3.12.0"
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/pciutils/pciutils/archive/refs/tags/v$VERSION.tar.gz"
DEPENDS=""
SHA256SUM="3a76ca02581fed03d0470ba822e72ee06e492442a990062f9638dec90018505f"
DESCRIPTION="pciutils designed to be handle pci activites"

build() {
   make
}

package() {
    make DESTDIR=$ROOT PREFIX=/usr install 
}
