#!/bin/sh
NAME="pciutils"
RELEASE="1"
VERSION="3.10.0"
SOURCES="https://github.com/pciutils/pciutils/archive/refs/tags/v$VERSION.tar.gz"
SHA256SUM="e579d87f1afe2196db7db648857023f80adb500e8194c4488c8b47f9a238c1c6  v3.10.0.tar.gz"
DESCRIPTION="pciutils designed to be handle pci activites"

build() {
   make
}

install() {
    make DESTDIR=$ROOT PREFIX=/usr install 
}
