#!/bin/sh
NAME="libx11"
RELEASE="1"
VERSION="1.8.12"
SOURCES="https://www.x.org/releases/individual/lib/libX11-$VERSION.tar.gz"
SHA256SUM="b7a1a90d881bb7b94df5cf31509e6b03f15c0972d3ac25ab0441f5fbc789650f"
DEPENDS="libxcb xorgproto"
BUILD_DEPENDS="xtrans gmake"
DESCRIPTION="X11 client-side library"

build() {
    kpkgConfigure \
        --prefix=/usr \
        --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
