#!/bin/sh
NAME="libx11"
RELEASE="1"
VERSION="1.8.12"
SOURCES="https://www.x.org/releases/individual/lib/libX11-$VERSION.tar.gz"
SHA256SUM="220fbcf54b6e4d8dc40076ff4ab87954358019982490b33c7802190b62d89ce1"
DEPENDS="libxcb xorgproto"
BUILD_DEPENDS="xtrans gmake"
DESCRIPTION="X11 client-side library"

build() {
    kpkgConfigure \
        --prefix=/usr \
        --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
