#!/bin/sh
NAME="libx11"
RELEASE="1"
VERSION="1.8.6"
SOURCES="https://www.x.org/releases/individual/lib/libX11-$VERSION.tar.gz"
SHA256SUM="5ff0d26c94d82ebb94a944b9f1f55cd01b9713fd461fe93f62f3527ce14ad94e  libX11-1.8.6.tar.gz"
DEPENDS="libxcb xorgproto"
BUILD_DEPENDS="xtrans"
DESCRIPTION="X11 client-side library"

build() {
    ./configure \
        --prefix=/usr
        --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
