#!/bin/sh
NAME="shared-mime-info"
RELEASE="1"
VERSION="2.4"
SOURCES="https://gitlab.freedesktop.org/xdg/shared-mime-info/-/archive/$VERSION/shared-mime-info-$VERSION.tar.gz"
BUILD_DEPENDS="meson"
DEPENDS="glib"
SHA256SUM="531291d0387eb94e16e775d7e73788d06d2b2fdd8cd2ac6b6b15287593b6a2de"
DESCRIPTION="shared-mime-info"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}

postinstall() {
  update-mime-database /usr/share/mime
}
