#!/bin/sh
NAME="shared-mime-info"
VERSION="2.2"
SOURCES="https://gitlab.freedesktop.org/xdg/shared-mime-info/-/archive/$VERSION/shared-mime-info-$VERSION.tar.gz"
SHA256SUM="bcf5d552318136cf7b3ae259975f414fbcdc9ebce000c87cf1f0901ff14e619f  shared-mime-info-2.2.tar.gz"
build() {
    [ ! -d "shared-mime-info-$VERSION" ] && tar -xvf shared-mime-info-$VERSION.tar.gz
    cd shared-mime-info-$VERSION || exit  1
    meson --prefix=/usr build/
    ninja -C build/
    DESTDIR=$ROOT ninja -C build/ install
}
