#!/bin/sh
NAME="shared-mime-info"
RELEASE="1"
VERSION="2.2"
SOURCES="https://gitlab.freedesktop.org/xdg/shared-mime-info/-/archive/$VERSION/shared-mime-info-$VERSION.tar.gz"
BUILD_DEPENDS="meson"
SHA256SUM="bcf5d552318136cf7b3ae259975f414fbcdc9ebce000c87cf1f0901ff14e619f  shared-mime-info-2.2.tar.gz"
DESCRIPTION="shared-mime-info"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
