#!/bin/sh
NAME="gcc"
VERSION="11.2.0"
DESCRIPTION="The GNU C Compiler"

build() {
	mkdir -p $ROOT/source
    cd $ROOT/source || exit 1
    [ ! -f "gcc.tar.xz" ] && wget https://ftp.gnu.org/gnu/gcc/gcc-$VERSION/gcc-$VERSION.tar.xz -O gcc.tar.xz
    tar -xvf gcc.tar.xz
    cd gcc-$VERSION || exit 1
    case $(uname -m) in
        x86_64)
    sed -e '/m64=/s/lib64/lib/' \
        -i.orig gcc/config/i386/t-linux64
    ;;
    esac
    rm -rf build
    mkdir -v build
    cd       build
    make distclean
    ../configure                                       \
        --without-headers                              \
        --enable-initfini-array                        \
        --disable-nls                                  \
        --disable-multilib                             \

    make -j$(nproc)
    make DESTDIR=$ROOT install-strip
    rm -rf $ROOT/source
}
