#!/bin/sh
NAME="gcc"
RELEASE="1"
VERSION="13.1.0"
SOURCES="https://ftp.gnu.org/gnu/gcc/gcc-$VERSION/gcc-$VERSION.tar.xz"
SHA256SUM="61d684f0aa5e76ac6585ad8898a2427aade8979ed5e7f85492286c4dfc13ee86  gcc-13.1.0.tar.xz"
DESCRIPTION="The GNU C Compiler"

build() {
    case $(uname -m) in
        x86_64)
    sed -e '/m64=/s/lib64/lib/' \
        -i.orig gcc/config/i386/t-linux64
    ;;
    esac
    rm -rf build
    mkdir -v build
    cd       build
    make distclean
    ../configure                                       \
        --without-headers                              \
        --enable-initfini-array                        \
        --prefix=/usr                                  \
        --disable-nls                                  \
        --disable-multilib                             \

	make -j$(nproc)
}

install() {
    cd build
    make DESTDIR=$ROOT install
    rm -rf $ROOT/source
}
