#!/bin/sh
NAME="gnome-settings-daemon"
RELEASE="1"
VERSION="48.1"
SOURCES="https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/archive/$VERSION/gnome-settings-daemon-$VERSION.tar.gz"
BUILD_DEPENDS="meson"
DEPENDS="alsa-lib networkmanager colord fontconfig gcr-4 geoclue geocode-glib gnome-desktop lcms2 libcanberra libgweather libnotify libwacom pulseaudio upower wayland gnome-session"
SHA256SUM="e381a367ad4d372a9ca938fee43918db8e443bef20d669f1319de16c27b27f4c"
DESCRIPTION="gnome-settings-daemon"

build() {
    
    rm -r subprojects/gvc
    git clone https://gitlab.gnome.org/GNOME/libgnome-volume-control subprojects/gvc
    cd subprojects/gvc
    git checkout 7a621180b46421e356b33972e3446775a504139c
    cd ../.. 

    if ! command -v systemctl > /dev/null; then
      # Credits to https://www.linuxfromscratch.org/blfs/view/svn/gnome/gnome-settings-daemon.html for these
      sed -e 's/libsystemd/libelogind/' \
        -i plugins/power/test.py
      systemd="false"
    else
      systemd="true" 
    fi

    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Dsystemd=$systemd \
    -Dsmartcard=false \
    -Dcups=false \
    -Dwwan=false \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
