#!/bin/sh
NAME="gtk4"
RELEASE="1"
VERSION="4.13.0"
SOURCES="https://download.gnome.org/sources/gtk/4.13/gtk-$VERSION.tar.xz;https://gitlab.gnome.org/GNOME/gtk/-/commit/c61313cbfe92d5a34f3d9ee92170a7bab95d3d76.patch"
BUILD_DEPENDS="meson gobject-introspection"
DEPENDS="gdk-pixbuf libtiff libepoxy pango graphene adwaita-icon-theme iso-codes libxkbcommon wayland wayland-protocols"
SHA256SUM="0e2e928a271ac5ef9c95d891a2b9a8c46df9598d12efd9ccfa31695e88cab6aa  gtk-4.13.0.tar.xz;13e59950ff0d1c603799bc5b6879e402d73da4758931e724386f3ecf8d33332e  c61313cbfe92d5a34f3d9ee92170a7bab95d3d76.patch"
DESCRIPTION="gtk4"

prepare() {
  tar -xvf gtk-$VERSION.tar.xz
  cd gtk-$VERSION
  patch -p1 < ../c61313cbfe92d5a34f3d9ee92170a7bab95d3d76.patch
}

build() {
  cd gtk-$VERSION
  meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Dx11-backend=false \
    -Dmedia-gstreamer=disabled \
    -Dintrospection=enabled \
    build
    ninja -C build
}

package() {
    cd gtk-$VERSION
    DESTDIR="$ROOT" ninja -C build install
}
