#!/bin/sh
NAME="gtk4"
RELEASE="2"
VERSION="4.13.0"
SOURCES="https://download.gnome.org/sources/gtk/4.13/gtk-$VERSION.tar.xz"
BUILD_DEPENDS="meson gobject-introspection"
DEPENDS="libx11 cantarell-fonts libxcursor libxdamage libxext libxfixes libxi libxinerama libxkbcommon libxrandr libxrender gdk-pixbuf libtiff libepoxy pango graphene adwaita-icon-theme iso-codes libxkbcommon wayland wayland-protocols"
SHA256SUM="0e2e928a271ac5ef9c95d891a2b9a8c46df9598d12efd9ccfa31695e88cab6aa  gtk-4.13.0.tar.xz"
DESCRIPTION="gtk4"

prepare() {
  tar -xvf gtk-$VERSION.tar.xz
  cd gtk-$VERSION
  sed -i 's/can_use_objcopy_for_resources = true/can_use_objcopy_for_resources = false/g' meson.build
}

build() {
  cd gtk-$VERSION
  meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Dx11-backend=true \
    -Dmedia-gstreamer=disabled \
    -Dintrospection=enabled \
    build
    ninja -C build
}

package() {
    cd gtk-$VERSION
    DESTDIR="$ROOT" ninja -C build install
}
