#!/bin/sh
NAME="freeglut"
RELEASE="1"
VERSION="3.6.0"
SOURCES="https://netix.dl.sourceforge.net/project/freeglut/freeglut/$VERSION/freeglut-$VERSION.tar.gz"
BUILD_DEPENDS="cmake glu gmake"
DEPENDS="mesa libxi"
SHA256SUM="9c3d4d6516fbfa0280edc93c77698fb7303e443c1aaaf37d269e3288a6c3ea52"
DESCRIPTION="freeglut"

build() {
    cmake \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_BUILD_TYPE=Release \
      -DFREEGLUT_BUILD_DEMOS=OFF  \
      -DFREEGLUT_BUILD_STATIC_LIBS=OFF  \
      -B build
    make -C build
}

package() {
    make DESTDIR=$ROOT -C build install
}
