#!/bin/sh
NAME="file"
RELEASE="1"
VERSION="5.44"
SOURCES="https://astron.com/pub/file/file-$VERSION.tar.gz"
SHA256SUM="3751c7fba8dbc831cb8d7cc8aff21035459b8ce5155ef8b0880a27d028475f3b  file-5.44.tar.gz"
DESCRIPTION="File tool"
build() {
    ./configure --prefix=/usr
    make
}

install() {
    make DESTDIR=$ROOT install
}
