#!/bin/sh
NAME="file"
RELEASE="1"
VERSION="5.46"
BUILD_DEPENDS="gmake"
SOURCES="https://astron.com/pub/file/file-$VERSION.tar.gz"
DEPENDS=""
SHA256SUM="c9cc77c7c560c543135edc555af609d5619dbef011997e988ce40a3d75d86088"
DESCRIPTION="File tool"
build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
