#!/bin/sh
NAME="crun"
RELEASE="1"
VERSION="1.8.4"
SOURCES="https://github.com/containers/crun/releases/download/$VERSION/crun-$VERSION.tar.xz"
SHA256SUM="0d2475d1dbcfed224f21e740782c7a7c45c53444eb7b84a493764e2a0ee36166  crun-1.8.4.tar.xz"
DESCRIPTION="A fast and lightweight fully featured OCI runtime and C library for running containers"

build() {
    ./configure --disable-systemd --prefix=/usr
    make -j$(nproc)
}

install() {
    make install
}
