#!/bin/sh
NAME="crun"
RELEASE="1"
VERSION="1.8.3"
SOURCES="https://github.com/containers/crun/releases/download/$VERSION/crun-$VERSION.tar.xz"
SHA256SUM="6dc9b2bc1cdcddbc45617866d673acb0a61ee25734fb92b31d6e7ec228bae09c  crun-1.8.3.3.3.tar.xz"
DESCRIPTION="A fast and lightweight fully featured OCI runtime and C library for running containers"

build() {
    ./configure --disable-systemd --prefix=/usr
    make -j$(nproc)
}

install() {
    make install
}
