#!/bin/sh
NAME="gnome-control-center"
RELEASE="1"
VERSION="44.3"
SOURCES="https://gitlab.gnome.org/GNOME/gnome-control-center/-/archive/$VERSION/gnome-control-center-$VERSION.tar.gz"
DEPENDS="accountsservice colord-gtk libgtop udisks libpwquality gnome-settings-daemon gsound gnome-bluetooth ibus libadwaita"
BUILD_DEPENDS="meson"
SHA256SUM="668139f7bb1ab02c85ae9073cc3db09c7a458944e3d6cbb0c9285bac187e7292  gnome-control-center-44.3.tar.gz"
DESCRIPTION="GNOME Control Center"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
