#!/bin/sh
NAME="libice"
RELEASE="1"
VERSION="1.1.2"
SOURCES="https://www.x.org/releases/individual/lib/libICE-$VERSION.tar.xz"
SHA256SUM="974e4ed414225eb3c716985df9709f4da8d22a67a2890066bc6dfc89ad298625"
DEPENDS="xorgproto"
BUILD_DEPENDS="xtrans gmake"
DESCRIPTION="X11 Inter-Client exchange library"

build() {
    kpkgConfigure \
      --prefix=/usr \
      --disable-static 
    make
}

package() {
    make DESTDIR=$ROOT install
}
