#!/bin/sh
NAME="readline"
RELEASE="2"
VERSION="8.3.1"
BUILD_DEPENDS="gmake"
SOURCES="https://ftp.gnu.org/gnu/readline/readline-$VERSION.tar.gz"
DEPENDS="ncurses"
SHA256SUM="SKIP"
DESCRIPTION="GNU readline"

build() {
    kpkgConfigure --prefix=/usr
    make SHLIB_LIBS="-lncurses"
}

package() {
    make DESTDIR=$ROOT SHLIB_LIBS="-lncurses" install
    rm -rf "$ROOT/usr/share/info/dir"
}
