#!/bin/sh
NAME="readline"
RELEASE="1"
VERSION="8.1.2"
SOURCES="https://ftp.gnu.org/gnu/readline/readline-$VERSION.tar.gz"
SHA256SUM="7589a2381a8419e68654a47623ce7dfcb756815c8fee726b98f90bf668af7bc6  readline-8.1.2.tar.gz"
DESCRIPTION="GNU readline"

build() {
    ./configure --prefix=/usr --with-shared 
}

install() {
    make DESTDIR=$ROOT SHLIB_LIBS="-L/tools/lib -lncursesw" install
}
