#!/bin/sh
NAME="binutils"
VERSION="2.38"
SOURCES="https://ftp.gnu.org/gnu/binutils/binutils-$VERSION.tar.xz"
SHA256SUM="e316477a914f567eccc34d5d29785b8b0f5a10208d36bbacedcc39048ecfe024  binutils-2.38.tar.xz"
DESCRIPTION="GNU Binutils"

build() {
    [ ! -f "binutils-$VERSION.tar.xz" ] && wget https://ftp.gnu.org/gnu/binutils/binutils-$VERSION.tar.xz
    [ ! -d "binutils-$VERSION" ] && tar -xvf binutils-$VERSION.tar.xz
    cd binutils-$VERSION || exit 1
    mkdir -v build
    cd       build
    ../configure                   \
        --prefix=/usr              \
        --build=$(../config.guess) \
        --host=x86_64-pc-linux-gnu \
        --disable-nls              \
        --enable-shared            \
        --disable-werror           \
        --enable-64-bit-bfd

    make -j$(nproc)
    make DESTDIR=$ROOT install -j1
    cd ld || exit 1
    make -j$(nproc)
    make DESTDIR=$ROOT install -j1
}
