#!/bin/sh
NAME="binutils"
RELEASE="3"
VERSION="2.43"
BUILD_DEPENDS="gmake"
SOURCES="https://ftp.gnu.org/gnu/binutils/binutils-$VERSION.tar.xz"
DEPENDS="flex perl zlib bison texinfo file"
SHA256SUM="b53606f443ac8f01d1d5fc9c39497f2af322d99e14cea5c0b4b124d630379365"
DESCRIPTION="GNU Binutils"

actual_build() {
    mkdir -v build
    cd       build
    
    if [ "$1" != "$(uname -m)-linux-gnu" ]; then
	    target="--target=$1"
	    sysroot="--with-sysroot=/usr/$1"
    fi
	
    echo $target
    echo $sysroot
    ../configure                   \
        --prefix=/usr              \
	$target			   \
	$sysroot		   \
	--enable-gnu-as		   \
	--enable-gnu-ld		   \
	--enable-gold		   \
	--build=$(../config.guess) \
        --disable-nls              \
        --enable-shared            \
        --disable-werror           \
        --enable-64-bit-bfd

    make -j$(nproc)
}

build_aarch64_linux_gnu_binutils() {
    actual_build "aarch64-linux-gnu"
}

build() {
    actual_build "$KPKG_TARGET"
}

package() {
    cd build
    make DESTDIR=$ROOT install -j1
    rm -f $ROOT/usr/lib/libbfd.la
    rm -rf "$ROOT/usr/share/info/dir"
}
