#!/bin/sh
NAME="binutils"
RELEASE="1"
VERSION="2.39"
SOURCES="https://ftp.gnu.org/gnu/binutils/binutils-$VERSION.tar.xz"
SHA256SUM="645c25f563b8adc0a81dbd6a41cffbf4d37083a382e02d5d3df4f65c09516d00  binutils-2.39.tar.xz"
DESCRIPTION="GNU Binutils"

build() {
    cd binutils-$VERSION || exit 1
    mkdir -v build
    cd       build
    ../configure                   \
        --prefix=/usr              \
        --build=$(../config.guess) \
        --host=x86_64-pc-linux-gnu \
        --disable-nls              \
        --enable-shared            \
        --disable-werror           \
        --enable-64-bit-bfd
    make
    make DESTDIR=$ROOT install -j1
}
