#!/bin/sh
NAME="libxslt"
RELEASE="2"
VERSION="1.1.40"
SOURCES="https://download.gnome.org/sources/libxslt/1.1/libxslt-$VERSION.tar.xz"
BUILD_DEPENDS="pkgconf gmake"
DEPENDS="python libxml2"
SHA256SUM="194715db023035f65fb566402f2ad2b5eab4c29d541f511305c40b29b1f48d13"
DESCRIPTION="XSLT processor based on libxml2"

build() {
    kpkgConfigure --prefix=/usr    \
            --disable-static \
            --with-history   \
            --with-python=/usr/bin/python3
    make
}

package() {
    make DESTDIR=$ROOT install
}
