#!/bin/sh
NAME="libxslt"
RELEASE="1"
VERSION="1.1.38"
SOURCES="https://download.gnome.org/sources/libxslt/1.1/libxslt-$VERSION.tar.xz"
DEPENDS="python libxml2"
SHA256SUM="1f32450425819a09acaff2ab7a5a7f8a2ec7956e505d7beeb45e843d0e1ecab1  libxslt-1.1.38.tar.xz"
DESCRIPTION="XSLT processor based on libxml2"

build() {
    ./configure --prefix=/usr    \
            --disable-static \
            --with-history   \
            --with-python=/usr/bin/python3
    make
}

package() {
    make DESTDIR=$ROOT install
}
