#!/bin/sh
NAME="libxslt"
RELEASE="1"
VERSION="1.1.39"
SOURCES="https://download.gnome.org/sources/libxslt/1.1/libxslt-$VERSION.tar.xz"
DEPENDS="python libxml2"
SHA256SUM="2a20ad621148339b0759c4d4e96719362dee64c9a096dbba625ba053846349f0"
DESCRIPTION="XSLT processor based on libxml2"

build() {
    ./configure --prefix=/usr    \
            --disable-static \
            --with-history   \
            --with-python=/usr/bin/python3
    make
}

package() {
    make DESTDIR=$ROOT install
}
