#!/bin/sh
NAME="mercurial"
RELEASE="1"
VERSION="7.1.2"
SOURCES="https://www.mercurial-scm.org/release/mercurial-$VERSION.tar.gz"
DEPENDS="python"
BUILD_DEPENDS="gmake python-setuptools"
B2SUM="757b114be166029f5b60466d25f37349ceb8253017fad7c29c1ebe69c56a5768114e130a0e55533837254f1df0abdce74a85f771c875801e859f3ad0152fd689"
DESCRIPTION="A free, distributed source control management tool"

build() {
    make build
}

package() {
    make PREFIX=/usr DESTDIR=$ROOT install-bin
}
