#!/bin/sh
NAME="mercurial"
RELEASE="1"
VERSION="6.8.1"
SOURCES="https://www.mercurial-scm.org/release/mercurial-$VERSION.tar.gz"
DEPENDS="python"
BUILD_DEPENDS="gmake python-setuptools"
SHA256SUM="030e8a7a6d590e4eaeb403ee25675615cd80d236f3ab8a0b56dcc84181158b05"
DESCRIPTION="A free, distributed source control management tool"

build() {
    make build
}

package() {
    make PREFIX=/usr DESTDIR=$ROOT install-bin
}
