#!/bin/sh
NAME="mercurial"
RELEASE="1"
VERSION="6.6.1"
SOURCES="https://www.mercurial-scm.org/release/mercurial-$VERSION.tar.gz"
DEPENDS="python"
BUILD_DEPENDS="gmake python-setuptools"
SHA256SUM="a29465a3fe40a3e8d49ba8343134ac2aba286b683ffeb838da0cf6e4521f9695"
DESCRIPTION="A free, distributed source control management tool"

build() {
    make build
}

package() {
    make PREFIX=/usr DESTDIR=$ROOT install-bin
}
