#!/bin/sh
NAME="libinput"
VERSION=1.21.0
SOURCES="https://gitlab.freedesktop.org/libinput/libinput/-/archive/$VERSION/libinput-$VERSION.tar.gz"
SHA256SUM="1b23c180f5b297303ed36f5a549910f5d320b0eb21052eac67a966d4eaa4e01d  libinput-1.21.0.tar.gz;"
DESCRIPTION="Library that handles input devices"

build() {
    tar -xvf libinput-$VERSION.tar.gz
    cd libinput-$VERSION || exit 1
    mkdir build 
    cd    build 
    meson --prefix=/usr \
      --buildtype=release   \
      -Ddebug-gui=false     \
      -Dtests=false         \
      -Dlibwacom=false      \
      ..                    
    ninja
    DESTDIR="$ROOT" ninja install  
}
