#!/bin/sh
NAME="libnotify"
RELEASE="1"
VERSION="0.8.3"
SOURCES="https://gitlab.gnome.org/GNOME/libnotify/-/archive/$VERSION/libnotify-$VERSION.tar.gz"
BUILD_DEPENDS="meson"
DEPENDS="gdk-pixbuf gobject-introspection"
SHA256SUM="5bcfeff21b6669c009c862e25c42556723f7a46c2c3454fce0fd532ebed715a0"
DESCRIPTION="Notification library"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Dtests=false \
    -Dman=false \
    -Dgtk_doc=false \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
