#!/bin/sh
NAME="libnotify"
RELEASE="1"
VERSION="0.8.7"
SOURCES="https://gitlab.gnome.org/GNOME/libnotify/-/archive/$VERSION/libnotify-$VERSION.tar.gz"
BUILD_DEPENDS="meson"
DEPENDS="gdk-pixbuf gobject-introspection"
SHA256SUM="b041ab7e4eb8cd16eafa6ae853274120ee3210aa6913614d9e774e6c45839723"
DESCRIPTION="Notification library"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Dtests=false \
    -Dman=false \
    -Dgtk_doc=false \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
