#!/bin/sh
NAME="newt"
RELEASE="1"
VERSION="0.52.25"
BUILD_DEPENDS="gmake"
SOURCES="https://releases.pagure.org/newt/newt-$VERSION.tar.gz"
DEPENDS="python slang popt"
SHA256SUM="ef0ca9ee27850d1a5c863bb7ff9aa08096c9ed312ece9087b30f3a426828de82"
DESCRIPTION="newt"

build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
