#!/bin/sh
NAME="nyaa"
RELEASE="2"
VERSION="3.4"
SOURCES="https://github.com/kreatolinux/nyaa3/archive/refs/tags/v$VERSION.tar.gz"
SHA256SUM="6815cdfa01157b5a86d9701ea761f16ec6093db1cbe0f9bf7db01854bba67fff  v3.4.tar.gz"
DESCRIPTION="The nyaa package manager"

build() {
        cd nyaa3-$VERSION || exit 1
        nimble install --nimbleDir=/tmp/nyaa_srcdir/deps --depsOnly -Y
        nimble build -d:release --threads:on -d:ssl --nimcache=/tmp/nyaa_srcdir/cache --nimbleDir=/tmp/nyaa_srcdir/deps -Y
        mkdir -p "$ROOT/bin"
        cp out/nyaa "$ROOT/bin/"
        mkdir -p "$ROOT/usr/share/man/man8"
        mkdir "$ROOT/usr/share/man/man5"
        cp -f man/nyaa3.8 "$ROOT/usr/share/man/man8"
        cp -f man/nyaa_run.8 "$ROOT/usr/share/man/man8"
        cp -f man/nyaa.conf.5 "$ROOT/usr/share/man/man5"
}
