#!/bin/sh
NAME="gnutls"
RELEASE="1"
VERSION="3.8.2"
SOURCES="https://www.gnupg.org/ftp/gcrypt/gnutls/v3.8/gnutls-$VERSION.tar.xz"
DEPENDS="libnettle"
SHA256SUM="e765e5016ffa9b9dd243e363a0460d577074444ee2491267db2e96c9c2adef77"
DESCRIPTION="GNU TLS"

build() {
    kpkgConfigure --prefix=/usr --with-included-unistring
    make -j$(nproc)
}

package() {
    make DESTDIR="$ROOT" install
}
