#!/bin/sh
NAME="mpfr"
RELEASE="1"
VERSION="4.2.1"
BUILD_DEPENDS="gmake"
SOURCES="https://ftp.gnu.org/gnu/mpfr/mpfr-$VERSION.tar.xz"
DEPENDS="gmp"
SHA256SUM="SKIP"
DESCRIPTION="GNU mpfr"

build() {
    if [ "$KPKG_ARCH" != "$(uname -m)" ]; then
	extraArgs="--with-sysroot=/usr/$KPKG_TARGET"
    fi
    
    kpkgConfigure $extraArgs
    make -j$(nproc)
}

package() {
    make DESTDIR=$ROOT install
    rm -rf "$ROOT/usr/share/info/dir"
}
