#!/bin/sh
NAME="nspr"
RELEASE="1"
VERSION="4.36"
BUILD_DEPENDS="gmake"
SOURCES="https://archive.mozilla.org/pub/nspr/releases/v$VERSION/src/nspr-$VERSION.tar.gz"
SHA256SUM="55dec317f1401cd2e5dba844d340b930ab7547f818179a4002bce62e6f1c6895"
DESCRIPTION="nspr"

build() {
      
    cd nspr

    if [ "$(uname -m)" = "x86_64" ]; then
      extraArgs="--enable-64bit"
    fi

    kpkgConfigure --prefix=/usr \
                --with-pthreads \
                --with-mozilla $extraArgs
    make
}

package() {
    cd nspr
    make DESTDIR=$ROOT install
}
