#!/bin/sh
NAME="gnome-keyring"
RELEASE="1"
VERSION="48.0"
BUILD_DEPENDS="gmake"
SOURCES="https://download.gnome.org/sources/gnome-keyring/42/gnome-keyring-$VERSION.tar.xz"
DEPENDS="p11-kit gcr-4 gcr-3 dbus linux-pam libxslt openssh"
SHA256SUM="SKIP"
DESCRIPTION="A daemon that keeps passwords and other secrets for users"

build() {
    # From BLFS
    sed -i 's:"/desktop:"/org:' schema/*.xml

    kpkgConfigure --prefix=/usr     \
                --sysconfdir=/etc \
                --disable-static \
                --with-pam-dir=/usr/lib/security \
                --sysconfdir=/etc \
                --localstatedir=/var \
                --libexecdir=/usr/lib \
                --disable-doc
    make
}

package() {
    make DESTDIR=$ROOT install
}
