#!/bin/sh
NAME="xcb-proto"
RELEASE="1"
VERSION="1.16.0"
SOURCES="https://www.x.org/releases/individual/proto/xcb-proto-$VERSION.tar.xz"
SHA256SUM="a75a1848ad2a89a82d841a51be56ce988ff3c63a8d6bf4383ae3219d8d915119"
BUILD_DEPENDS="python libxml2"
DESCRIPTION="XML-XCB protocol descriptions"

build() {
    ./configure \
      --prefix=/usr \
      --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
