#!/bin/sh
NAME="xcb-proto"
RELEASE="1"
VERSION="1.17.0"
SOURCES="https://www.x.org/releases/individual/proto/xcb-proto-$VERSION.tar.xz"
SHA256SUM="2c1bacd2110f4799f74de6ebb714b94cf6f80fb112316b1219480fd22562148c"
BUILD_DEPENDS="python libxml2 gmake"
DESCRIPTION="XML-XCB protocol descriptions"

build() {
    kpkgConfigure \
      --prefix=/usr \
      --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
