#!/bin/sh
NAME="bluez"
RELEASE="1"
VERSION="5.85"
BUILD_DEPENDS="gmake"
SOURCES="https://mirrors.edge.kernel.org/pub/linux/bluetooth/bluez-$VERSION.tar.gz"
DEPENDS="sbc eudev dbus glib libical"
BACKUP="etc/bluetooth/main.conf"
SHA256SUM="7516f167f6aaabff9a48eac1515638fd349ecb884d254b558481b02520e7abe8"
DESCRIPTION="Bluetooth protocol stack for Linux"

build() {
    if command -v systemctl > /dev/null; then
	extraArgs="--with-systemdsystemunitdir=/usr/lib/systemd/system --with-systemduserunitdir=/usr/lib/systemd/user"
    else
	extraArgs="--disable-systemd"
    fi
	
    kpkgConfigure $extraArgs \
	    --prefix=/usr \
	    --with-udevdir=/usr/lib/udev/rules.d \
	    --disable-manpages \
	    --sysconfdir=/etc \
	    --enable-library
    make
}

package() {
    make DESTDIR="$ROOT" install
    install -v -dm755 "$ROOT/etc/bluetooth"
    install -v -m644 src/main.conf "$ROOT/etc/bluetooth/main.conf"
}
