#!/bin/sh
NAME="openrc"
RELEASE="1"
VERSION="0.63"
SOURCES="https://github.com/OpenRC/openrc/archive/refs/tags/$VERSION.tar.gz"
BUILD_DEPENDS="ninja meson"
SHA256SUM="1b661016bd8cd4189be83b441dd7062c967b641fdc00f741e359e22d06857df8"
DESCRIPTION="The OpenRC init system"

build() {
    mkdir build
    cd build
    meson --prefix=/usr       \
          --buildtype=release \
	  -Dpam=false
    ninja
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
