#!/bin/sh
NAME="openrc"
RELEASE="1"
VERSION="0.55.1"
SOURCES="https://github.com/OpenRC/openrc/archive/refs/tags/$VERSION.tar.gz"
BUILD_DEPENDS="ninja meson"
SHA256SUM="102e53825031361e4d96a5c0a7eb192bd64b0a6b227bb0568651efc8f5972952"
DESCRIPTION="The OpenRC init system"

build() {
    mkdir build
    cd build
    meson --prefix=/usr       \
          --buildtype=release \
	  -Dpam=false
    ninja
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
