#!/bin/sh
NAME="autoconf"
RELEASE="1"
VERSION="2.71"
SOURCES="https://ftp.gnu.org/gnu/autoconf/autoconf-2.71.tar.xz"
DEPENDS="m4"
SHA256SUM="f14c83cfebcc9427f2c3cea7258bd90df972d92eb26752da4ddad81c87a0faa4"
DESCRIPTION="GNU Autoconf"
build() {
    ./configure --prefix=/usr 
    make
}

package() {
    make DESTDIR=$ROOT install
}
