#!/bin/sh
NAME="autoconf"
RELEASE="1"
VERSION="2.72"
SOURCES="https://ftp.gnu.org/gnu/autoconf/autoconf-2.72.tar.xz"
DEPENDS="m4"
SHA256SUM="ba885c1319578d6c94d46e9b0dceb4014caafe2490e437a0dbca3f270a223f5a"
DESCRIPTION="GNU Autoconf"
build() {
    kpkgConfigure --prefix=/usr 
    make
}

package() {
    make DESTDIR=$ROOT install
}
