#!/bin/sh
NAME="wget"
RELEASE="2"
VERSION="1.25.0"
BUILD_DEPENDS="gmake"
SOURCES="https://ftp.gnu.org/gnu/wget/wget-$VERSION.tar.gz"
DEPENDS="openssl"
SHA256SUM="766e48423e79359ea31e41db9e5c289675947a7fcf2efdcedb726ac9d0da3784"
DESCRIPTION="Network utility to retrieve files from the Web"
build() {
    kpkgConfigure --prefix=/usr --with-ssl=openssl
    make
}

package() {
    make install
}
