#!/bin/sh
NAME="wget"
RELEASE="2"
VERSION="1.25.0"
BUILD_DEPENDS="gmake"
SOURCES="https://ftp.gnu.org/gnu/wget/wget-$VERSION.tar.gz"
DEPENDS="openssl"
SHA256SUM="SKIP"
DESCRIPTION="Network utility to retrieve files from the Web"
build() {
    kpkgConfigure --prefix=/usr --with-ssl=openssl
    make
}

package() {
    make install
}
