#!/bin/sh
NAME="gnupg"
RELEASE="1"
VERSION="2.4.3"
SOURCES="https://gnupg.org/ftp/gcrypt/gnupg/gnupg-$VERSION.tar.bz2"
DEPENDS="libgpg-error libgcrypt libassuan libksba npth"
SHA256SUM="a271ae6d732f6f4d80c258ad9ee88dd9c94c8fdc33c3e45328c4d7c126bd219d  gnupg-2.4.3.tar.bz2"
DESCRIPTION="GNU Privacy Guard"

build() {
    ./configure --disable-ldap --prefix=/usr
    make -j$(nproc)
}

package() {
    make DESTDIR="$ROOT" install
}
