#!/bin/sh
NAME="libgtop"
RELEASE="1"
VERSION="2.41.2"
SOURCES="https://download.gnome.org/sources/libgtop/2.41/libgtop-$VERSION.tar.xz"
DEPENDS="glib libxau"
BUILD_DEPENDS="gobject-introspection"
SHA256SUM="d9026cd8a48d27cdffd332f8d60a92764b56424e522c420cd13a01f40daf92c3"
DESCRIPTION="libgtop"

build() {
    ./configure --prefix=/usr   \
                --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
