#!/bin/sh
NAME="libgtop"
RELEASE="1"
VERSION="2.41.1"
SOURCES="https://download.gnome.org/sources/libgtop/2.41/libgtop-$VERSION.tar.xz"
DEPENDS="glib libxau"
BUILD_DEPENDS="gobject-introspection gmake"
SHA256SUM="43ea9ad13f7caf98303e64172b191be9b96bab340b019deeec72251ee140fe3b"
DESCRIPTION="libgtop"

build() {
    kpkgConfigure --prefix=/usr   \
                --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
