#!/bin/sh
NAME="mtools"
RELEASE="3"
VERSION="4.0.45"
SOURCES="http://ftp.gnu.org/gnu/mtools/mtools-$VERSION.tar.gz"
BUILD_DEPENDS="gmake"
DEPENDS=""
SHA256SUM="eea170403f48f0cd19b3d940e4bd12630a82601e25f944f47654b13d9d7eb5d4"
DESCRIPTION="A collection of utilities to access MS-DOS disks without mounting them"

build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
