#!/bin/sh
NAME="mtools"
RELEASE="3"
VERSION="4.0.49"
SOURCES="http://ftp.gnu.org/gnu/mtools/mtools-$VERSION.tar.gz"
BUILD_DEPENDS="gmake"
DEPENDS=""
SHA256SUM="10cd1111da87bf2400a380c1639a6cba8bfb937a24f9c51f5f88d393ae5f6f76"
DESCRIPTION="A collection of utilities to access MS-DOS disks without mounting them"

build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
