#!/bin/sh
NAME="mtools"
RELEASE="3"
VERSION="4.0.44"
SOURCES="http://ftp.gnu.org/gnu/mtools/mtools-$VERSION.tar.gz"
BUILD_DEPENDS="gmake"
DEPENDS=""
SHA256SUM="10be76148870f984fa44df297473a4e45184472cdb19a4d05ef17fdb59b5d5a4"
DESCRIPTION="A collection of utilities to access MS-DOS disks without mounting them"

build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
