#!/bin/sh
NAME="libxcursor"
RELEASE="1"
VERSION="1.2.1"
SOURCES="https://www.x.org/releases/individual/lib/libXcursor-$VERSION.tar.xz"
SHA256SUM="46c143731610bafd2070159a844571b287ac26192537d047a39df06155492104  libXcursor-1.2.1.tar.xz"
DEPENDS="libxfixes libxrender"
DESCRIPTION="libxcursor"

build() {
    ./configure \
        --sysconfdir=/etc \
        --prefix=/usr \
        --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
