#!/bin/sh
NAME="libxcursor"
RELEASE="1"
VERSION="1.2.2"
BUILD_DEPENDS="gmake"
SOURCES="https://www.x.org/releases/individual/lib/libXcursor-$VERSION.tar.xz"
SHA256SUM="53d071bd2cc56e517a30998d5e685c8a74556ddada43c6985d14da9a023a88ee"
DEPENDS="libxfixes libxrender"
DESCRIPTION="libxcursor"

build() {
    kpkgConfigure \
        --sysconfdir=/etc \
        --prefix=/usr \
        --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
