#!/bin/sh
NAME="musl"
RELEASE="1"
VERSION="1.2.5"
BUILD_DEPENDS="gmake"
SOURCES="https://musl.libc.org/releases/musl-$VERSION.tar.gz"
DEPENDS=""
SHA256SUM="a9a118bbe84d8764da0ea0d28b3ab3fae8477fc7e4085d90102b8596fc7c75e4"
DESCRIPTION="musl libc"
build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
