#!/bin/sh
NAME="musl"
RELEASE="1"
VERSION="1.2.4"
BUILD_DEPENDS="gmake"
SOURCES="https://musl.libc.org/releases/musl-$VERSION.tar.gz"
DEPENDS=""
SHA256SUM="7a35eae33d5372a7c0da1188de798726f68825513b7ae3ebe97aaaa52114f039"
DESCRIPTION="musl libc"
build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
