#!/bin/sh
NAME="desktop-file-utils"
RELEASE="1"
VERSION="0.28"
SOURCES="https://www.freedesktop.org/software/desktop-file-utils/releases/desktop-file-utils-$VERSION.tar.xz"
BUILD_DEPENDS="meson"
DEPENDS="glib"
SHA256SUM="4401d4e231d842c2de8242395a74a395ca468cd96f5f610d822df33594898a70"
DESCRIPTION="A few command line utilities for working
with desktop entries"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
