#!/bin/sh
NAME="desktop-file-utils"
RELEASE="1"
VERSION="0.28"
SOURCES="https://www.freedesktop.org/software/desktop-file-utils/releases/desktop-file-utils-$VERSION.tar.xz"
BUILD_DEPENDS="meson"
DEPENDS="glib"
SHA256SUM="a0817df39ce385b6621880407c56f1f298168c040c2032cedf88d5b76affe836"
DESCRIPTION="A few command line utilities for working
with desktop entries"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
