#!/bin/sh
NAME="libxt"
RELEASE="1"
VERSION="1.3.1"
BUILD_DEPENDS="gmake"
SOURCES="https://www.x.org/releases/individual/lib/libXt-$VERSION.tar.xz"
SHA256SUM="e0a774b33324f4d4c05b199ea45050f87206586d81655f8bef4dba434d931288"
DEPENDS="libx11 libsm"
DESCRIPTION="X11 library"

build() {
    kpkgConfigure \
        --prefix=/usr \
        --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
