#!/bin/sh
NAME="libxt"
RELEASE="1"
VERSION="1.3.0"
BUILD_DEPENDS="gmake"
SOURCES="https://www.x.org/releases/individual/lib/libXt-$VERSION.tar.xz"
SHA256SUM="52820b3cdb827d08dc90bdfd1b0022a3ad8919b57a39808b12591973b331bf91"
DEPENDS="libx11 libsm"
DESCRIPTION="X11 library"

build() {
    kpkgConfigure \
        --prefix=/usr \
        --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
