#!/bin/sh
NAME="libportal"
RELEASE="1"
VERSION="0.7.1"
SOURCES="https://github.com/flatpak/libportal/releases/download/$VERSION/libportal-$VERSION.tar.xz"
DEPENDS="gtk3 gtk4"
BUILD_DEPENDS="meson gobject-introspection vala gjs"
SHA256SUM="297b90b263fad22190a26b8c7e8ea938fe6b18fb936265e588927179920d3805  libportal-0.7.1.tar.xz"
DESCRIPTION="libportal"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
