#!/bin/sh
NAME="libportal"
RELEASE="1"
VERSION="0.9.1"
SOURCES="https://github.com/flatpak/libportal/releases/download/$VERSION/libportal-$VERSION.tar.xz"
DEPENDS="gtk3 gtk4"
BUILD_DEPENDS="meson gobject-introspection vala gjs"
SHA256SUM="de801ee349ed3c255a9af3c01b1a401fab5b3fc1c35eb2fd7dfb35d4b8194d7f"
DESCRIPTION="libportal"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Ddocs=false \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
