#!/bin/sh
NAME="dmenu-wl"
RELEASE="1"
VERSION="1.0"
SOURCES="git::https://github.com/nyyManni/dmenu-wayland::master"
DEPENDS="wayland cairo pango libxkbcommon glib"
BUILD_DEPENDS="meson pkgconf"
SHA256SUM="SKIP"
DESCRIPTION="An efficient dynamic menu for wayland (wlroots)"

build() {
	meson setup --prefix=/usr build
	ninja -C build
}

package() {
	DESTDIR="$ROOT" ninja -C build install
}
