#!/bin/sh
NAME="linux-firmware"
RELEASE="1"
VERSION="20240811"
BUILD_DEPENDS="gmake"
SOURCES="https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/snapshot/linux-firmware-$VERSION.tar.gz"
DEPENDS="rdfind"
SHA256SUM="b1c672868e36c19d51f943898d0fdb5534759dc649af72fe51b04be47663d153"
DESCRIPTION="Linux firmware files"

package() {
    make install
}
