#!/bin/sh
NAME="linux-firmware"
RELEASE="1"
VERSION="20231030"
SOURCES="https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/snapshot/linux-firmware-$VERSION.tar.gz"
DEPENDS="rdfind"
SHA256SUM="833483257dd3388de2018617c779faaa17139c0a17286b1c513cb569d2122fc4"
DESCRIPTION="Linux firmware files"

package() {
    make install
}
