#!/bin/sh
NAME="efivar"
RELEASE="1"
VERSION="38"
SOURCES="https://github.com/rhboot/efivar/releases/download/$VERSION/efivar-$VERSION.tar.bz2"
DEPENDS=""
SHA256SUM="f018ed6e49c5f1c16d336d9fd7687ce87023276591921db1e49a314ad6515349  efivar-38.tar.bz2"
DESCRIPTION="efivar provides tools and libraries to manipulate EFI variables"

build() {
    make MANDOC="" CFLAGS=-Wno-error=enum-int-mismatch
}

package() {
    make DESTDIR="$ROOT" CFLAGS=-Wno-error=enum-int-mismatch LIBDIR=/usr/lib install || exit 1
}
