#!/bin/sh
NAME="efivar"
RELEASE="1"
VERSION="39"
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/rhboot/efivar/archive/refs/tags/$VERSION.tar.gz"
DEPENDS=""
B2SUM="73ea4b3293cd708923bcd4332a8c7a5a8bbf539d81300c502a764a2ac205ba7cdf1e30b3432c42a101f56c0b6e31af2907a6a38ada69ace3b0d60e90515094cd"
DESCRIPTION="efivar provides tools and libraries to manipulate EFI variables"

build() {
    make MANDOC="" CFLAGS=-Wno-error=enum-int-mismatch
}

package() {
    make DESTDIR="$ROOT" CFLAGS=-Wno-error=enum-int-mismatch LIBDIR=/usr/lib install || exit 1
}
