#!/bin/sh
NAME="rust"
RELEASE="1"
VERSION="1.72.1"
SOURCES="https://static.rust-lang.org/dist/rustc-$VERSION-src.tar.gz"
DEPENDS="llvm"
BUILD_DEPENDS="python"
SHA256SUM="7f48845f6a52cdbb5d63fb0528fd5f520eb443275b55f98e328159f86568f895  rustc-1.72.1-src.tar.gz"
DESCRIPTION="Memory-safe programming language that doesn't use garbage collection"

build() {
  ./configure --set install.prefix="/usr" --set llvm.link-shared=true --llvm-config=/usr/bin/llvm-config 
  ./x.py build
}

package() {
  DESTDIR="$ROOT" ./x.py install
}
