#!/bin/sh
NAME="rust"
RELEASE="1"
VERSION="1.80.1"
SOURCES="https://static.rust-lang.org/dist/rustc-$VERSION-src.tar.gz"
DEPENDS="llvm"
BUILD_DEPENDS="python"
SHA256SUM="2c0b8f643942dcb810cbcc50f292564b1b6e44db5d5f45091153996df95d2dc4"
DESCRIPTION="Memory-safe programming language that doesn't use garbage collection"

build() {
  :
}

package() {
  kpkgConfigure --set install.prefix="/usr" --set llvm.link-shared=true --llvm-config=/usr/bin/llvm-config 
  ./x.py build
  DESTDIR="$ROOT" ./x.py install
}
