#!/bin/sh
NAME="rust"
RELEASE="1"
VERSION="1.91.1"
SOURCES="https://static.rust-lang.org/dist/rustc-$VERSION-src.tar.gz"
DEPENDS="llvm"
BUILD_DEPENDS="python cmake curl"
SHA256SUM="38dce205d39f61571261f0444237a1ce9efecb970e760d8ec4d957af5b445723"
DESCRIPTION="Memory-safe programming language that doesn't use garbage collection"

build() {
  kpkgConfigure --set install.prefix="/usr" --set llvm.link-shared=true --llvm-config=/usr/bin/llvm-config 
  ./x.py build
}

package() {
  DESTDIR="$ROOT" ./x.py install
}
