#!/bin/sh
NAME="libnl"
RELEASE="1"
VERSION="3.8.0"
SOURCES="https://github.com/thom311/libnl/releases/download/libnl3_8_0/libnl-3.8.0.tar.gz"
DEPENDS="flex"
SHA256SUM="bb726c6d7a08b121978d73ff98425bf313fa26a27a331d465e4f1d7ec5b838c6"
DESCRIPTION="A collection of libraries providing APIs to netlink protocol Linux kernel interfaces"

build() {
    kpkgConfigure --prefix=/usr     \
                --sysconfdir=/etc \
                --disable-static
    make
}

package() {
    make DESTDIR="$ROOT" install 
}

