#!/bin/sh
NAME="zig"
RELEASE="2"
VERSION="0.15.2"
SOURCES="https://ziglang.org/download/$VERSION/zig-$VERSION.tar.xz"
DEPENDS="llvm"
BUILD_DEPENDS="cmake"
SHA256SUM="d9b30c7aa983fcff5eed2084d54ae83eaafe7ff3a84d8fb754d854165a6e521c"
DESCRIPTION="A general-purpose programming language and toolchain for maintaining robust, optimal and reusable software."

build() {
    cmake -B build -DCMAKE_BUILD_TYPE=None \
	    -DZIG_SHARED_LLVM=ON	   \
    	    -DCMAKE_INSTALL_PREFIX=/usr
    cmake --build build
}

package() {
    DESTDIR="$ROOT" cmake --install build
}
