#!/bin/sh
NAME="zig"
RELEASE="2"
VERSION="0.11.0"
SOURCES="https://ziglang.org/download/$VERSION/zig-$VERSION.tar.xz"
DEPENDS="llvm"
BUILD_DEPENDS="cmake"
SHA256SUM="ead029cfe474d9bf0413332d0e9d3bdfb5990cadce238f44f35ba32d92169295"
DESCRIPTION="A general-purpose programming language and toolchain for maintaining robust, optimal and reusable software."

build() {
    cmake -B build -DCMAKE_BUILD_TYPE=None \
	    -DZIG_SHARED_LLVM=ON	   \
    	    -DCMAKE_INSTALL_PREFIX=/usr
    cmake --build build
}

package() {
    DESTDIR="$ROOT" cmake --install build
}
