#!/bin/sh
NAME="libgpg-error"
RELEASE="1"
VERSION="1.49"
BUILD_DEPENDS="gmake"
SOURCES="https://gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-$VERSION.tar.bz2"
DEPENDS=""
SHA256SUM="8b79d54639dbf4abc08b5406fb2f37e669a2dec091dd024fb87dd367131c63a9"
DESCRIPTION="A small library that originally defined common error values for all GnuPG components"

build() {
    kpkgConfigure --prefix=/usr
    make -j$(nproc)
}

package() {
    make install
}
