#!/bin/sh
NAME="libgpg-error"
RELEASE="1"
VERSION="1.55"
BUILD_DEPENDS="gmake"
SOURCES="https://gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-$VERSION.tar.bz2"
DEPENDS=""
SHA256SUM="be0f1b2db6b93eed55369cdf79f19f72750c8c7c39fc20b577e724545427e6b2"
DESCRIPTION="A small library that originally defined common error values for all GnuPG components"

build() {
    kpkgConfigure --prefix=/usr
    make -j$(nproc)
}

package() {
    make install
}
