#!/bin/sh
NAME="libgpg-error"
RELEASE="1"
VERSION="1.55"
BUILD_DEPENDS="gmake"
SOURCES="https://gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-$VERSION.tar.bz2"
DEPENDS=""
SHA256SUM="95b178148863f07d45df0cea67e880a79b9ef71f5d230baddc0071128516ef78"
DESCRIPTION="A small library that originally defined common error values for all GnuPG components"

build() {
    kpkgConfigure --prefix=/usr
    make -j$(nproc)
}

package() {
    make install
}
