#!/bin/sh
NAME="ccache"
RELEASE="2"
VERSION="4.9.1"
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/ccache/ccache/archive/refs/tags/v$VERSION.tar.gz"
DEPENDS="cmake gcc libzstd"
SHA256SUM="3ba0c080eee7f5e9763f80457273dda7376eca77433b45929e9aa6f5e5c7f47c"
DESCRIPTION="ccache - a fast compiler cache"
build() {
    mkdir build && cd build || exit 1
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$ROOT/usr -DCMAKE_INSTALL_SYSCONFDIR=$ROOT/etc ..
    make
}

package() {
    cd build
    make install
    mkdir -p "$ROOT/usr/lib/ccache"
    for i in gcc clang cc g++ c++ clang++; do
	ln -s /usr/bin/ccache "$ROOT/usr/lib/ccache/$i"
    done
}
