#!/bin/sh
NAME="ccache"
RELEASE="1"
VERSION="4.8.2"
SOURCES="https://github.com/ccache/ccache/archive/refs/tags/v$VERSION.tar.gz"
DEPENDS="cmake gcc libzstd"
SHA256SUM="3ba679c9e91101bfc3f3c0aab6622d8132f83e2e3c92633dcc61eef810e92ce0  v4.8.2.tar.gz"
DESCRIPTION="ccache - a fast compiler cache"
build() {
    mkdir build && cd build || exit 1
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$ROOT/usr -DCMAKE_INSTALL_SYSCONFDIR=$ROOT/etc ..
    make
}

package() {
    cd build
    make install
}
