#!/bin/sh
NAME="ccache"
RELEASE="2"
VERSION="4.12.1"
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/ccache/ccache/archive/refs/tags/v$VERSION.tar.gz"
DEPENDS="cmake gcc libzstd"
SHA256SUM="7250b1d6b9f598049d0a3802b3195c580d7c0b1e9a708d8a9bfbfaf12cbc5fcd"
DESCRIPTION="ccache - a fast compiler cache"
build() {
    mkdir build && cd build || exit 1
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$ROOT/usr -DCMAKE_INSTALL_SYSCONFDIR=$ROOT/etc ..
    make
}

package() {
    cd build
    make install
    mkdir -p "$ROOT/usr/lib/ccache"
    for i in gcc clang cc g++ c++ clang++; do
	ln -s /usr/bin/ccache "$ROOT/usr/lib/ccache/$i"
    done
}
