#!/bin/sh
NAME="noto-fonts"
RELEASE="1"
VERSION="23.9.1"
SOURCES="https://github.com/notofonts/notofonts.github.io/archive/refs/tags/noto-monthly-release-$VERSION.tar.gz"
DEPENDS="fontconfig"
SHA256SUM="90335582faf06c61511f0a2a9f7f1ffaafd160c79fe8115b4c4fb5ef7992d526"
DESCRIPTION="Google Noto fonts"

package() {
    install -Dm644 fonts/*/hinted/ttf/*.tt[fc] -t "$DESTDIR/usr/share/fonts/noto"
}

postinstall() {
    fc-cache -fv
}
