#!/bin/sh
NAME="attr"
RELEASE="1"
VERSION="2.5.2"
SOURCES="https://download.savannah.gnu.org/releases/attr/attr-$VERSION.tar.gz"
BUILD_DEPENDS="gmake"
SHA256SUM="SKIP"
DESCRIPTION="attr library"
build() {
    kpkgConfigure --prefix=/usr --disable-static
    make
}

package() {
    make install 
}
