#!/bin/sh
NAME="attr"
RELEASE="1"
VERSION="2.5.1"
SOURCES="https://download.savannah.gnu.org/releases/attr/attr-$VERSION.tar.gz"
DEPENDS=""
SHA256SUM="bae1c6949b258a0d68001367ce0c741cebdacdd3b62965d17e5eb23cd78adaf8"
DESCRIPTION="attr library"
build() {
    ./configure --prefix=/usr --disable-static
    make
}

package() {
    make install 
}
