#!/bin/sh
NAME="sudo"
VERSION="1_9_12p1"
SOURCES="https://github.com/sudo-project/sudo/archive/refs/tags/SUDO_$VERSION.tar.gz"
SHA256SUM=""
DESCRIPTION="Utility to execute a command as another user"
build() {
    tar -xvf SUDO_$VERSION.tar.gz
    cd sudo-SUDO_$VERSION || exit 1
    ./configure --prefix=/usr
    make
    make install
}
