#!/bin/sh
NAME="jansson"
RELEASE="1"
VERSION="2.14.1"
SOURCES="https://github.com/akheron/jansson/releases/download/v$VERSION/jansson-$VERSION.tar.gz"
BUILD_DEPENDS="llvm gmake"
SHA256SUM="2521cd51a9641d7a4e457f7215a4cd5bb176f690bc11715ddeec483e85d9e2b3"
DESCRIPTION="C library for encoding, decoding and manipulating JSON data"

build() {
    export CC=clang
    kpkgConfigure --prefix=/usr                   \
                --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
