#!/bin/sh
NAME="jansson"
RELEASE="1"
VERSION="2.14"
SOURCES="https://github.com/akheron/jansson/releases/download/v$VERSION/jansson-$VERSION.tar.gz"
SHA256SUM="5798d010e41cf8d76b66236cfb2f2543c8d082181d16bc3085ab49538d4b9929  jansson-2.14.tar.gz"
DESCRIPTION="C library for encoding, decoding and manipulating JSON data"

build() {
    ./configure --prefix=/usr                   \
                --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
