#!/bin/sh
NAME="pcre"
RELEASE="1"
VERSION="8.45"
SOURCES="https://netcologne.dl.sourceforge.net/project/pcre/pcre/$VERSION/pcre-$VERSION.zip"
SHA256SUM="5b709aa45ea3b8bb73052947200ad187f651a2049158fb5bbfed329e4322a977"
DESCRIPTION="Perl Compatible Regular Expression libraries"

build() {
    kpkgConfigure --prefix=/usr
}

package() {
    make DESTDIR=$ROOT install
}
