#!/bin/sh
NAME="seatd"
RELEASE="1"
VERSION=0.7.0
SOURCES="https://git.sr.ht/~kennylevinsen/seatd/archive/$VERSION.tar.gz"
SHA256SUM="210ddf8efa1149cde4dd35908bef8e9e63c2edaa0cdb5435f2e6db277fafff3c  0.7.0.tar.gz"
DESCRIPTION="Seat daemon."

build() {
    mkdir build 
    cd    build 
    meson --prefix=/usr \
      --buildtype=release   \
      ..                    
    ninja
}

install() {
    DESTDIR="$ROOT" ninja install  
}
