#!/bin/sh
NAME="seatd"
RELEASE="1"
VERSION=0.9.0
SOURCES="https://git.sr.ht/~kennylevinsen/seatd/archive/$VERSION.tar.gz"
BUILD_DEPENDS="meson"
DEPENDS=""
SHA256SUM="SKIP"
DESCRIPTION="Seat daemon."

build() {
    mkdir build 
    cd    build 
    meson --prefix=/usr \
      --buildtype=release   \
      ..                    
    ninja
}

package() {
    DESTDIR="$ROOT" ninja -C build install  
}
