#!/bin/sh
NAME="elfutils"
RELEASE="1"
VERSION="0.190"
SOURCES="https://sourceware.org/elfutils/ftp/$VERSION/elfutils-$VERSION.tar.bz2"
DEPENDS="zlib"
SHA256SUM="8e00a3a9b5f04bc1dc273ae86281d2d26ed412020b391ffcc23198f10231d692"
DESCRIPTION="elfutils"
build() {
    ./configure --prefix=/usr \
        --disable-debuginfod \
        --disable-libdebuginfod
    make
}

package() {
    make DESTDIR=$ROOT install
}
