#!/bin/sh
NAME="procps-ng"
RELEASE="1"
VERSION="4.0.5"
SOURCES="https://gitlab.com/procps-ng/procps/-/archive/v$VERSION/procps-v$VERSION.tar.gz"
BUILD_DEPENDS="autoconf automake libtool gmake"
DEPENDS="gettext"
SHA256SUM="3214fab0f817d169f2c117842ba635bafb1cd6090273e311a8b5c6fc393ddb9d"
DESCRIPTION="procps"

build() {
    ./autogen.sh
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
