#!/bin/sh
NAME="procps-ng"
RELEASE="1"
VERSION="4.0.3"
SOURCES="https://gitlab.com/procps-ng/procps/-/archive/v$VERSION/procps-v$VERSION.tar.gz"
SHA256SUM="14cc21219c45d196772274ea3f194f6d668b6cc667fbde9ee6d8039121b73fa6  procps-v4.0.3.tar.gz"
DESCRIPTION="procps"
build() {
    ./autogen.sh
    ./configure --prefix=/usr
    make
}

install() {
    make DESTDIR=$ROOT install
}
