#!/bin/sh
NAME="procps-ng"
RELEASE="1"
VERSION="4.0.5"
SOURCES="https://gitlab.com/procps-ng/procps/-/archive/v$VERSION/procps-v$VERSION.tar.gz"
BUILD_DEPENDS="autoconf automake libtool gmake"
DEPENDS="gettext"
SHA256SUM="2c6d7ed9f2acde1d4dd4602c6172fe56eff86953fe8639bd633dbd22cc18f5db"
DESCRIPTION="procps"

build() {
    ./autogen.sh
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
