#!/bin/sh
NAME="libvorbis"
RELEASE="1"
VERSION="1.3.7"
SOURCES="https://ftp.osuosl.org/pub/xiph/releases/vorbis/libvorbis-$VERSION.tar.xz"
SHA256SUM="b33cc4934322bcbf6efcbacf49e3ca01aadbea4114ec9589d1b1e9d20f72954b  libvorbis-1.3.7.tar.xz"
DESCRIPTION="Reference implementation for Ogg Vorbis"

build() {
    ./configure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
