#!/bin/sh
NAME="libwebp"
RELEASE="1"
VERSION="1.3.2"
SOURCES="https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-$VERSION.tar.gz"
DEPENDS="libjpeg-turbo libpng libtiff"
SHA256SUM="2a499607df669e40258e53d0ade8035ba4ec0175244869d1025d460562aa09b4"
DESCRIPTION="libwebp"

build() {
  
  # Flags are from BLFS
  kpkgConfigure --prefix=/usr           \
            --enable-libwebpmux     \
            --enable-libwebpdemux   \
            --enable-libwebpdecoder \
            --enable-libwebpextras  \
            --enable-swap-16bit-csp \
            --disable-static        
    make
}

package() {
    make DESTDIR=$ROOT install
}
