#!/bin/sh
NAME="libwebp"
RELEASE="1"
VERSION="1.6.0"
BUILD_DEPENDS="gmake"
SOURCES="https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-$VERSION.tar.gz"
DEPENDS="libjpeg-turbo libpng libtiff"
SHA256SUM="e4ab7009bf0629fd11982d4c2aa83964cf244cffba7347ecd39019a9e38c4564"
DESCRIPTION="libwebp"

build() {
  
  # Flags are from BLFS
  kpkgConfigure --prefix=/usr           \
            --enable-libwebpmux     \
            --enable-libwebpdemux   \
            --enable-libwebpdecoder \
            --enable-libwebpextras  \
            --enable-swap-16bit-csp \
            --disable-static        
    make
}

package() {
    make DESTDIR=$ROOT install
}
