#!/bin/sh
NAME="libwebp"
RELEASE="1"
VERSION="1.6.0"
BUILD_DEPENDS="gmake"
SOURCES="https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-$VERSION.tar.gz"
DEPENDS="libjpeg-turbo libpng libtiff"
SHA256SUM="61f873ec69e3be1b99535634340d5bde750b2e4447caa1db9f61be3fd49ab1e5"
DESCRIPTION="libwebp"

build() {
  
  # Flags are from BLFS
  kpkgConfigure --prefix=/usr           \
            --enable-libwebpmux     \
            --enable-libwebpdemux   \
            --enable-libwebpdecoder \
            --enable-libwebpextras  \
            --enable-swap-16bit-csp \
            --disable-static        
    make
}

package() {
    make DESTDIR=$ROOT install
}
