#!/bin/sh
NAME="freetype"
RELEASE="2"
VERSION="2.14.1"
SOURCES="https://download-mirror.savannah.gnu.org/releases/freetype/freetype-$VERSION.tar.gz"
BUILD_DEPENDS="ninja meson"
DEPENDS="libpng"
SHA256SUM="174d9e53402e1bf9ec7277e22ec199ba3e55a6be2c0740cb18c0ee9850fc8c34"
DESCRIPTION="FriBidi is an implementation of Unicode Bidirectional Algorithm"


build() {
    meson \
        --prefix=/usr \
        -Dharfbuzz=disabled \
        -Dbzip2=disabled \
        . output
    ninja -C output
}

package() {
        DESTDIR=$ROOT ninja -C output install
}
