#!/bin/sh
NAME="freetype"
RELEASE="2"
VERSION="2.14.1"
SOURCES="https://download-mirror.savannah.gnu.org/releases/freetype/freetype-$VERSION.tar.gz"
BUILD_DEPENDS="ninja meson"
DEPENDS="libpng"
SHA256SUM="5c3a8e78f7b24c20b25b54ee575d6daa40007a5f4eea2845861c3409b3021747"
DESCRIPTION="FriBidi is an implementation of Unicode Bidirectional Algorithm"


build() {
    meson \
        --prefix=/usr \
        -Dharfbuzz=disabled \
        -Dbzip2=disabled \
        . output
    ninja -C output
}

package() {
        DESTDIR=$ROOT ninja -C output install
}
