#!/bin/sh
NAME="freetype"
RELEASE="2"
VERSION="2.12.1"
SOURCES="https://download-mirror.savannah.gnu.org/releases/freetype/freetype-$VERSION.tar.gz"
SHA256SUM="efe71fd4b8246f1b0b1b9bfca13cfff1c9ad85930340c27df469733bbb620938  freetype-2.12.1.tar.gz"
DESCRIPTION="FriBidi is an implementation of Unicode Bidirectional Algorithm"


build() {
    meson \
        --prefix=/usr \
        -Dharfbuzz=disabled \
        . output
    ninja -C output
}

install() {
        DESTDIR=$ROOT ninja -C output install
}
