#!/bin/sh
NAME="kreainit"
VERSION="1.2"
DESCRIPTION="Kreato's init system"

build() {
    wget https://git.kreatea.space/kreato-linux/kreainit/archive/kreainit-v$VERSION.tar.gz
    tar -xvf kreainit-v$VERSION.tar.gz
    cd kreainit-v$VERSION || exit 1
    make DESTDIR="$ROOT" install
}

