#!/bin/sh
NAME="bison"
RELEASE="1"
VERSION="3.8.2"
SOURCES="https://ftp.gnu.org/gnu/bison/bison-$VERSION.tar.xz"
DEPENDS="m4"
SHA256SUM="9bba0214ccf7f1079c5d59210045227bcf619519840ebfa80cd3849cff5a5bf2"
DESCRIPTION="a general-purpose parser generator"

build() {
    kpkgConfigure --prefix=/usr
}

package() {
    make DESTDIR=$ROOT install
    [ -d "$ROOT/usr/share/info/dir" ] && rm -rf "$ROOT/usr/share/info/dir"
}
