#!/bin/sh
NAME="libevent"
RELEASE="1"
VERSION="2.1.12"
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/libevent/libevent/releases/download/release-$VERSION-stable/libevent-$VERSION-stable.tar.gz"
DEPENDS="openssl"
SHA256SUM="92e6de1be9ec176428fd2367677e61ceffc2ee1cb119035037a27d346b0403bb"
DESCRIPTION="Event notification library"

build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
