#!/bin/sh
NAME="sysctl-configs"
RELEASE="1"
VERSION="0.1"
SOURCES="99-JomOS.conf"
DEPENDS="procps-ng"
SHA256SUM="052f12eef5d9ced324900dc239686a4ec30c85e4dbb14cf0e1bd09da47a6fedc"
DESCRIPTION="Kernel configurations optimized for performance"

prepare() {
    :
}

package() {
    mkdir -p $ROOT/etc/sysctl.d
    cp -f 99-JomOS.conf $ROOT/etc/sysctl.d
}

postinstall() {
    sysctl --system
}
