#!/bin/sh
NAME="sysctl-configs"
RELEASE="1"
VERSION="0.1"
SOURCES="99-Desktop.conf"
DEPENDS="procps-ng"
SHA256SUM="SKIP"
DESCRIPTION="Kernel configurations optimized for performance"

prepare() {
    :
}

package() {
    mkdir -p $ROOT/etc/sysctl.d
    cp -f 99-Desktop.conf $ROOT/etc/sysctl.d
}

postinstall() {
    sysctl --system
}
