#!/bin/sh
NAME="opus"
RELEASE="1"
VERSION="1.6.1"
BUILD_DEPENDS="gmake"
SOURCES="https://downloads.xiph.org/releases/opus/opus-$VERSION.tar.gz"
SHA256SUM="6ffcb593207be92584df15b32466ed64bbec99109f007c82205f0194572411a1"
DESCRIPTION="Lossy audio compression format"

build() {
    kpkgConfigure --prefix=/usr                   \
                --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
