#!/bin/sh
NAME="opus"
RELEASE="1"
VERSION="1.5.2"
BUILD_DEPENDS="gmake"
SOURCES="https://downloads.xiph.org/releases/opus/opus-$VERSION.tar.gz"
SHA256SUM="65c1d2f78b9f2fb20082c38cbe47c951ad5839345876e46941612ee87f9a7ce1"
DESCRIPTION="Lossy audio compression format"

build() {
    kpkgConfigure --prefix=/usr                   \
                --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
