#!/bin/sh
NAME="opus"
RELEASE="1"
VERSION="1.3.1"
SOURCES="https://archive.mozilla.org/pub/opus/opus-$VERSION.tar.gz"
DEPENDS=""
SHA256SUM="65b58e1e25b2a114157014736a3d9dfeaad8d41be1c8179866f144a2fb44ff9d  opus-1.3.1.tar.gz"
DESCRIPTION="Lossy audio compression format"

build() {
    ./configure --prefix=/usr                   \
                --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
