#!/bin/sh
NAME="glib-networking"
RELEASE="1"
VERSION="2.80.1"
SOURCES="https://download.gnome.org/sources/glib-networking/2.78/glib-networking-$VERSION.tar.xz"
BUILD_DEPENDS="meson"
DEPENDS="glib gnutls gsettings-desktop-schemas ca-certificates"
SHA256SUM="SKIP"
DESCRIPTION="Network extensions for GLib"

build() {
    meson setup \
    --prefix=/usr \
    -Dlibproxy=disabled \
    --buildtype=release \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
