#!/bin/sh
NAME="npth"
RELEASE="1"
VERSION="1.8"
BUILD_DEPENDS="gmake"
SOURCES="https://gnupg.org/ftp/gcrypt/npth/npth-$VERSION.tar.bz2"
DEPENDS=""
SHA256SUM="8bd24b4f23a3065d6e5b26e98aba9ce783ea4fd781069c1b35d149694e90ca3e"
DESCRIPTION="A library to provide the GNU Pth API"

build() {
    kpkgConfigure --prefix=/usr
    make -j$(nproc)
}

package() {
    make install
}
