#!/bin/sh
NAME="npth"
RELEASE="1"
VERSION="1.7"
BUILD_DEPENDS="gmake"
SOURCES="https://gnupg.org/ftp/gcrypt/npth/npth-$VERSION.tar.bz2"
DEPENDS=""
SHA256SUM="8589f56937b75ce33b28d312fccbf302b3b71ec3f3945fde6aaa74027914ad05"
DESCRIPTION="A library to provide the GNU Pth API"

build() {
    kpkgConfigure --prefix=/usr
    make -j$(nproc)
}

package() {
    make install
}
