#!/bin/sh
NAME="go"
RELEASE="2"
VERSION="1.23.0"
SOURCES="https://go.dev/dl/go$VERSION.src.tar.gz"
BUILD_DEPENDS="wget bash gmake"
DEPENDS="git"
SHA256SUM="42b7a8e80d805daa03022ed3fde4321d4c3bf2c990a144165d01eeecd6f699c6"
DESCRIPTION="Go is a statically typed, compiled programming language designed at Google"

build() {
    if ! command -v go > /dev/null; then
        echo "go: go not found to bootstrap, downloading binary to bootstrap..."
        # We get the architecture by hand since
        # kpkg doesn't currently offer any variable to do this.
        ARCH=""
        case $(uname -m)
        in
            "x86_64")
                ARCH="amd64"
            ;;
            *)
                ARCH="$(uname -m)"
            ;;
        esac
	cd ..
        wget https://go.dev/dl/go$VERSION.linux-$ARCH.tar.gz
        mkdir go-bin
	tar -xvf go$VERSION.linux-$ARCH.tar.gz -C go-bin
        export PATH=$PATH:$PWD/go-bin/go/bin
    	cd -
    fi
    cd src || exit 1
    export GOENV="/opt/kpkg/srcdir/go/env" 
    export GOCACHE="/opt/kpkg/srcdir/go-build"
    export GOROOT_FINAL=/usr/local/go
    go env -w  GOCACHE="/opt/kpkg/srcdir/go-build"
    ./make.bash -v
}

package() {
    mkdir -p "$ROOT"/bin
    mkdir -p "$ROOT"/usr/local/go
    cp -r . "$ROOT"/usr/local/go
    ln -s /usr/local/go/bin/go "$ROOT/bin/go"
    ln -s /usr/local/go/bin/gofmt "$ROOT/bin/gofmt"
    mkdir -p /opt/kpkg/srcdir/go
}
