#!/bin/sh
NAME="go"
RELEASE="1"
VERSION="1.20"
SOURCES="https://go.dev/dl/go$VERSION.src.tar.gz;https://go.dev/dl/go1.4.src.tar.gz"
SHA256SUM="3a29ff0421beaf6329292b8a46311c9fbf06c800077ceddef5fb7f8d5b1ace33  go1.20.src.tar.gz;3ae9f67e45a5ca7004b28808da8b1367d328a371d641ddbe636c0fb0ae0ffdae  go1.4.src.tar.gz"
DESCRIPTION="Go is a statically typed, compiled programming language designed at Google"

prepare() {
    tar -zxf go$VERSION.src.tar.gz
    mkdir go1.4
    tar -zxf go1.4.src.tar.gz -C ./go1.4
}

build() {
    # bootstrap go1.4
    cd go1.4/go/src || exit 1

    export GOROOT_BOOTSTRAP
    GOROOT_BOOTSTRAP=$(realpath ..)

    CGO_ENABLED=0 TMPDIR=/tmp CFLAGS="-Wno-error=sizeof-array-div -Wno-error=implicit-fallthrough -Wno-error=use-after-free -Wno-error=shift-negative-value" ./make.bash
    # done bootstrapping go

    cd ../../../go/src || exit 1
    GOROOT_FINAL=/usr/local/go ./make.bash
}

install() {
    mkdir -p "$ROOT"/bin
    cd .. || exit 1
    cp -r ./bin "$ROOT"
    mkdir -p "$ROOT"/usr/local/go
    cp -r . "$ROOT"/usr/local/go
    mkdir -p /tmp/nyaa_srcdir/go
    GOENV=/tmp/nyaa_srcdir/go/env "$ROOT"/bin/go env -w GOROOT=/usr/local/go
}
