#!/bin/sh
NAME="diffutils"
RELEASE="1"
VERSION="3.9"
SOURCES="https://ftp.gnu.org/gnu/diffutils/diffutils-$VERSION.tar.xz"
DEPENDS=""
SHA256SUM="d80d3be90a201868de83d78dad3413ad88160cc53bcc36eb9eaf7c20dbf023f1"
DESCRIPTION="GNU diffutils"

build() {
    mkdir -v build
    cd       build
    .kpkgConfigure                   \
        --prefix=/usr              \
        --build=$(../config.guess) \
        --host=x86_64-pc-linux-gnu \
        --disable-nls              \
        --enable-shared            \
        --disable-werror           \
        --enable-64-bit-bfd
    make
}

package() {
    cd build
    make DESTDIR=$ROOT install -j1
}
