#!/bin/sh
NAME="diffutils"
RELEASE="1"
VERSION="3.10"
BUILD_DEPENDS="gmake"
SOURCES="https://ftp.gnu.org/gnu/diffutils/diffutils-$VERSION.tar.xz"
DEPENDS=""
SHA256SUM="90e5e93cc724e4ebe12ede80df1634063c7a855692685919bfe60b556c9bd09e"
DESCRIPTION="GNU diffutils"

build() {
    mkdir -v build
    cd       build
    KPKG_CONFIGURE_PATH=../configure kpkgConfigure \
        --build=$(../config.guess) \
        --disable-nls              \
        --enable-shared            \
        --disable-werror           \
        --enable-64-bit-bfd
    make
}

package() {
    cd build
    make DESTDIR=$ROOT install -j1
}
