#!/bin/sh
NAME="bubblewrap"
RELEASE="2"
VERSION="0.10.0"
SOURCES="https://github.com/containers/bubblewrap/releases/download/v0.10.0/bubblewrap-0.10.0.tar.xz"
BUILD_DEPENDS="meson pkgconf bash"
DEPENDS="libcap"
SHA256SUM="65d92cf44a63a51e1b7771f70c05013dce5bd6b0b2841c4b4be54b0c45565471"
DESCRIPTION="Low-level unprivileged sandboxing tool used by Flatpak and similar projects"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
