#!/bin/sh
NAME="bubblewrap"
RELEASE="2"
VERSION="0.11.0"
SOURCES="https://github.com/containers/bubblewrap/releases/download/v0.11.0/bubblewrap-0.11.0.tar.xz"
BUILD_DEPENDS="meson pkgconf bash"
DEPENDS="libcap"
SHA256SUM="988fd6b232dafa04b8b8198723efeaccdb3c6aa9c1c7936219d5791a8b7a8646"
DESCRIPTION="Low-level unprivileged sandboxing tool used by Flatpak and similar projects"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
