#!/bin/sh
NAME="gsed"
RELEASE="1"
VERSION="4.9"
SOURCES="https://ftp.gnu.org/gnu/sed/sed-$VERSION.tar.xz"
SHA256SUM="6e226b732e1cd739464ad6862bd1a1aba42d7982922da7a53519631d24975181  sed-4.9.tar.xz"
DESCRIPTION="GNU sed"

build() {
    ./configure --prefix=/usr
}

install() {
    make DESTDIR=$ROOT install
}
