#!/bin/sh
NAME="gsed"
RELEASE="1"
VERSION="4.9"
SOURCES="https://ftp.gnu.org/gnu/sed/sed-$VERSION.tar.xz"
BUILD_DEPENDS="gettext gmake"
DEPENDS=""
SHA256SUM="6e226b732e1cd739464ad6862bd1a1aba42d7982922da7a53519631d24975181"
DESCRIPTION="GNU sed"

build() {
    kpkgConfigure --prefix=/usr
}

package() {
    make DESTDIR=$ROOT install
}
