#!/bin/sh
NAME="jetbrains-mono"
RELEASE="1"
VERSION="2.304"
SOURCES="https://github.com/JetBrains/JetBrainsMono/releases/download/v$VERSION/JetBrainsMono-$VERSION.zip"
DEPENDS="fontconfig"
SHA256SUM="6f6376c6ed2960ea8a963cd7387ec9d76e3f629125bc33d1fdcd7eb7012f7bbf  JetBrainsMono-2.304.zip"
DESCRIPTION="Free and open-source typeface for developers"

build() {
    : 
}

package() {
    mkdir -p $DESTDIR/usr/share/fonts/jetbrains-mono
    mv fonts/ttf/* $DESTDIR/usr/share/fonts/jetbrains-mono/
}

postinstall() {
    fc-cache -fv
}
