#!/bin/sh
NAME="vulkan-loader"
RELEASE="1"
VERSION="1.3.287"
SOURCES="https://github.com/KhronosGroup/Vulkan-Loader/archive/refs/tags/v$VERSION.tar.gz"
DEPENDS="cmake ninja"
BUILD_DEPENDS="vulkan-headers wayland libxcb libx11 libxrandr"
SHA256SUM="8501325eb301c9cbd147acf439ad243dc6b4b417c08adc413cdeb4e188537fb0"
DESCRIPTION="Vulkan ICD loader"

build() {
    cmake -B build \
        -DVULKAN_HEADERS_INSTALL_DIR=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DCMAKE_INSTALL_SYSCONFDIR=/etc \
        -DCMAKE_INSTALL_DATADIR=/share \
        -DCMAKE_SKIP_RPATH=True \
        -DBUILD_TESTS=OFF \
        -DBUILD_WSI_XCB_SUPPORT=ON \
        -DBUILD_WSI_XLIB_SUPPORT=ON \
        -DBUILD_WSI_WAYLAND_SUPPORT=ON \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -G Ninja
    ninja -C build -j$(nproc)
}

package() {    
    DESTDIR="$ROOT" ninja -C build install
}


