#!/bin/sh
NAME="cracklib"
RELEASE="1"
VERSION="2.9.11"
SOURCES="https://github.com/cracklib/cracklib/releases/download/v$VERSION/cracklib-$VERSION.tar.gz"
DEPENDS="autoconf automake"
SHA256SUM="6213b986a5209fc0d4ca93734e349b8f66b36bfe9a3fae6eead14a15d82a68dc"
DESCRIPTION="cracklib"

build() {
    autoreconf -v -f -i
    ./configure --prefix=/usr --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
