#!/bin/sh
NAME="cracklib"
RELEASE="1"
VERSION="2.10.3"
SOURCES="https://github.com/cracklib/cracklib/releases/download/v$VERSION/cracklib-$VERSION.tar.gz"
BUILD_DEPENDS="autoconf automake libtool gmake"
SHA256SUM="877b823198eb29aa1778b16a70cad05f7b54b164b3bf7ab656fc326c393f4c85"
DESCRIPTION="cracklib"

build() {
    autoreconf -v -f -i
    kpkgConfigure --prefix=/usr --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
