#!/bin/sh
NAME="pcre2"
RELEASE="1"
VERSION="10.47"
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/PCRE2Project/pcre2/releases/download/pcre2-$VERSION/pcre2-$VERSION.tar.gz"
SHA256SUM="c08ae2388ef333e8403e670ad70c0a11f1eed021fd88308d7e02f596fcd9dc16"
DESCRIPTION="Perl Compatible Regular Expression libraries"

build() {
    kpkgConfigure --prefix=/usr
}

package() {
    make DESTDIR=$ROOT install
}
