#!/bin/sh
NAME="which"
RELEASE="1"
VERSION="2.23"
BUILD_DEPENDS="gmake"
SOURCES="https://ftp.gnu.org/gnu/which/which-$VERSION.tar.gz"
SHA256SUM="SKIP"
DESCRIPTION="GNU Which"
build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
