#!/bin/sh
NAME="which"
RELEASE="1"
VERSION="2.21"
SOURCES="https://ftp.gnu.org/gnu/which/which-$VERSION.tar.gz"
SHA256SUM="f4a245b94124b377d8b49646bf421f9155d36aa7614b6ebf83705d3ffc76eaad"
DESCRIPTION="GNU Which"
build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
