#!/bin/sh
NAME="findutils"
RELEASE="1"
VERSION="4.10.0"
BUILD_DEPENDS="gmake"
SOURCES="https://ftp.gnu.org/gnu/findutils/findutils-$VERSION.tar.xz"
SHA256SUM="1387e0b67ff247d2abde998f90dfbf70c1491391a59ddfecb8ae698789f0a4f5"
DESCRIPTION="GNU findutils"

build() {
    mkdir -v build
    cd       build
    KPKG_CONFIGURE_PATH="../configure" kpkgConfigure                   \
        --build=$(../config.guess) \
        --disable-nls              \
        --enable-shared            \
        --disable-werror           \
        --enable-64-bit-bfd
    make
}

package() {
    cd build
    make DESTDIR=$ROOT install -j1
}
