#!/bin/sh
NAME="pigz"
RELEASE="1"
VERSION="2.8"
SOURCES="https://zlib.net/pigz/pigz-$VERSION.tar.gz"
BUILD_DEPENDS=""
DEPENDS=""
SHA256SUM="eb872b4f0e1f0ebe59c9f7bd8c506c4204893ba6a8492de31df416f0d5170fd0"
DESCRIPTION="Parallel gzip"
build() {
    make
}

package() {
    env install -vDm 0755 pigz "$ROOT/usr/bin/pigz"
    env install -vDm 0755 unpigz "$ROOT/usr/bin/unpigz"
    ln -s "pigz" "$ROOT/usr/bin/gzip"
    ln -s "unpigz" "$ROOT/usr/bin/gunzip"
}
