#!/bin/sh
NAME="python-jinja2"
RELEASE="2"
VERSION="3.1.2"
SOURCES="https://files.pythonhosted.org/packages/source/J/Jinja2/Jinja2-$VERSION.tar.gz"
DEPENDS="python"
BUILD_DEPENDS="python-setuptools"
SHA256SUM="31351a702a408a9e7595a8fc6150fc3f43bb6bf7e319770cbc0db9df9437e852"
DESCRIPTION="fast, expressive, extensible templating engine"

package() {
    pip install . --prefix=/usr --root="$ROOT"
}
