#!/bin/sh
NAME="rhash"
RELEASE="1"
VERSION="1.4.5"
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/rhash/RHash/archive/refs/tags/v$VERSION.tar.gz"
SHA256SUM="6db837e7bbaa7c72c5fd43ca5af04b1d370c5ce32367b9f6a1f7b49b2338c09a"
DESCRIPTION="Great utility for computing hash sums"

build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
    
    # install libs
    make -C librhash DESTDIR="$ROOT" install-lib-headers install-lib-shared install-so-link
}
