#!/bin/sh
NAME="rhash"
RELEASE="1"
VERSION="1.4.6"
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/rhash/RHash/archive/refs/tags/v$VERSION.tar.gz"
SHA256SUM="9f6019cfeeae8ace7067ad22da4e4f857bb2cfa6c2deaa2258f55b2227ec937a"
DESCRIPTION="Great utility for computing hash sums"

build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
    
    # install libs
    make -C librhash DESTDIR="$ROOT" install-lib-headers install-lib-shared install-so-link
}
