#!/bin/sh
NAME="gsound"
RELEASE="1"
VERSION="1.0.3"
SOURCES="https://gitlab.gnome.org/GNOME/gsound/-/archive/$VERSION/gsound-$VERSION.tar.gz"
BUILD_DEPENDS="meson vala gobject-introspection"
DEPENDS="libcanberra"
SHA256SUM="ebee33c77f43bcae87406c20e051acaff08e86f8960c35b92911e243fddc7a0b"
DESCRIPTION="A small library for playing system sounds"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
