#!/bin/sh
NAME="mari"
RELEASE="1"
VERSION="0.1"
SOURCES="git::https://github.com/kreatolinux/src::master"
SHA256SUM=""
DESCRIPTION="The minimal HTTP server (but not really) that runs Kreato Linux's binary repository"

build() {
        nimble install httpbeast --nimbleDir=/tmp/kpkg/srcdir/deps -Y
	nim c -d:release -o="out/mari" "src/mari/mari.nim" --NimblePath=/tmp/kpkg/srcdir/deps/pkgs --nimcache=/tmp/kpkg/srcdir/cache
}

install() {
        mkdir -p "$ROOT/usr/bin"
        cp out/mari "$ROOT/usr/bin/"
}
