#!/bin/sh
NAME="mari"
RELEASE="2"
VERSION="4.1.3"
SOURCES="https://github.com/kreatolinux/src/archive/refs/tags/v$VERSION.tar.gz"
SHA256SUM="155793dc39784c8bb4a84e6112adaf5d4d43a52add350abfc0e571c2bd602933  v4.1.3.tar.gz"
DESCRIPTION="Kreato Linux's binary repository server"

build() {
        nimble install httpbeast -y --nimbleDir=/tmp/kpkg/srcdir/deps
        nim c -d:release -o="out/mari" --NimblePath=/tmp/kpkg/srcdir/deps/pkgs --nimcache=/tmp/kpkg/srcdir/cache "src/mari/mari.nim"
}

install() {
        mkdir -p "$ROOT/bin"
        cp out/mari "$ROOT/bin/"
}
