#!/bin/sh
NAME="mold"
RELEASE="1"
VERSION="2.3.3"
SOURCES="https://github.com/rui314/mold/archive/refs/tags/v$VERSION.tar.gz"
DEPENDS="cmake"
SHA256SUM="dcba90d5ee852ececb3a1a70110bb2d385079dcd1aa103e970296683c642f856"
DESCRIPTION="A Modern Linker"

build() {
    mkdir build
    cd build
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=c++ -DCMAKE_INSTALL_PREFIX=/usr ..
    cmake --build . -j $(nproc)
}

package() {
	cmake --install build
}
