#!/bin/sh
NAME="mold"
RELEASE="1"
VERSION="2.4.0"
SOURCES="https://github.com/rui314/mold/archive/refs/tags/v$VERSION.tar.gz"
DEPENDS="cmake"
SHA256SUM="be65f3d785d32ece7b3204ecaa57810847fdd25c232cf704cbfff2dafb1ac107"
DESCRIPTION="A Modern Linker"

build() {
    mkdir build
    cd build
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=c++ -DCMAKE_INSTALL_PREFIX=/usr ..
    cmake --build . -j $(nproc)
}

package() {
	cmake --install build
}
