#!/bin/sh
NAME="mold"
RELEASE="1"
VERSION="1.8.0"
SOURCES="https://github.com/rui314/mold/archive/refs/tags/v$VERSION.tar.gz"
SHA256SUM="7210225478796c2528aae30320232a5a3b93a640292575a8c55aa2b140041b5c  v1.8.0.tar.gz"
DESCRIPTION="A Modern Linker"

build() {
    cd mold-$VERSION || exit 1
    mkdir build
    cd build
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=c++ -DCMAKE_INSTALL_PREFIX=/usr ..
    cmake --build . -j $(nproc)
    cmake --install .
}
