#!/bin/sh
NAME="libtasn"
VERSION="4.18.0"
DESCRIPTION="GNU libtasn"

build() {
    [ ! -f "libtasn1-$VERSION.tar.gz" ] && wget https://ftp.gnu.org/gnu/libtasn1/libtasn1-$VERSION.tar.gz
    tar -xf libtasn1-$VERSION.tar.gz
    cd libtasn1-$VERSION
    ./configure
    make -j$(nproc)
    make DESTDIR=$ROOT install
}
