#!/bin/sh
NAME="keyutils"
RELEASE="1"
VERSION="1.6.3"
SOURCES="https://git.kernel.org/pub/scm/linux/kernel/git/dhowells/keyutils.git/snapshot/keyutils-$VERSION.tar.gz"
DEPENDS="krb5"
SHA256SUM="a61d5706136ae4c05bd48f86186bcfdbd88dd8bd5107e3e195c924cfc1b39bb4"
DESCRIPTION="keyutils"

build() {
    make
}

package() {
    make DESTDIR=$ROOT install
}
