#!/bin/sh
NAME="python"
RELEASE="4"
VERSION="3.14.0"
BUILD_DEPENDS="gmake"
SOURCES="https://www.python.org/ftp/python/$VERSION/Python-$VERSION.tar.xz"
DEPENDS="openssl zlib libxcrypt bzip2 libffi"
SHA256SUM="2299dae542d395ce3883aca00d3c910307cd68e0b2f7336098c8e7b7eee9f3e9"
NO_CHKUPD=true
DESCRIPTION="General-Purpose Programming language"

build() {
    kpkgConfigure \
        --prefix=/usr
        #--disable-static \
        #--enable-shared \
        #--without-ensurepip \
        #--without-static-libpython \
        #--with-system-expat
    make
}

package() {
    make DESTDIR="$ROOT" install || exit 1
    ln -s "python3" "$ROOT/usr/bin/python"
    find "$ROOT" -type f -name "*.pyc" -delete
    find "$ROOT" -type d -name "__pycache__" -exec rm -rf {} +
}
