#!/bin/sh
NAME="python"
RELEASE="3"
VERSION="3.12.0"
SOURCES="https://www.python.org/ftp/python/$VERSION/Python-$VERSION.tar.xz"
DEPENDS="openssl zlib libxcrypt bzip2"
SHA256SUM="795c34f44df45a0e9b9710c8c71c15c671871524cd412ca14def212e8ccb155d"
DESCRIPTION="General-Purpose Programming language"

build() {
    ./configure --disable-static --enable-shared --with-ensurepip=install --prefix=/usr --enable-optimizations
    make
}

package() {
    make DESTDIR="$ROOT" install || exit 1
    ln -s "python3" "$ROOT/usr/bin/python"
    ln -s "pip3" "$ROOT/usr/bin/pip"
}
