#!/bin/sh
NAME="python"
RELEASE="3"
VERSION="3.12.3"
BUILD_DEPENDS="gmake"
SOURCES="https://www.python.org/ftp/python/$VERSION/Python-$VERSION.tar.xz"
DEPENDS="openssl zlib libxcrypt bzip2 libffi"
SHA256SUM="56bfef1fdfc1221ce6720e43a661e3eb41785dd914ce99698d8c7896af4bdaa1"
DESCRIPTION="General-Purpose Programming language"

build() {
    kpkgConfigure --disable-static --with-ensurepip=install --enable-shared --prefix=/usr --enable-optimizations
    make
}

package() {
    make DESTDIR="$ROOT" install || exit 1
    ln -s "python3" "$ROOT/usr/bin/python"
}
