#!/bin/sh
NAME="wpa_supplicant"
RELEASE="3"
VERSION="2.10"
SOURCES="https://w1.fi/releases/wpa_supplicant-$VERSION.tar.gz"
DEPENDS="openssl dbus libnl libxml2 readline pkgconf"
SHA256SUM="20df7ae5154b3830355f8ab4269123a87affdea59fe74fe9292a91d0d7e17b2f"
DESCRIPTION="WPA client"

build() {
    cat > wpa_supplicant/.config << "EOF"
CONFIG_BACKEND=file
CONFIG_CTRL_IFACE=y
CONFIG_DEBUG_FILE=y
CONFIG_DEBUG_SYSLOG=y
CONFIG_DEBUG_SYSLOG_FACILITY=LOG_DAEMON
CONFIG_DRIVER_NL80211=y
CONFIG_DRIVER_WEXT=y
CONFIG_DRIVER_WIRED=y
CONFIG_EAP_GTC=y
CONFIG_EAP_LEAP=y
CONFIG_EAP_MD5=y
CONFIG_EAP_MSCHAPV2=y
CONFIG_EAP_OTP=y
CONFIG_EAP_PEAP=y
CONFIG_EAP_TLS=y
CONFIG_EAP_TTLS=y
CONFIG_IEEE8021X_EAPOL=y
CONFIG_IPV6=y
CONFIG_LIBNL32=y
CONFIG_PEERKEY=y
CONFIG_PKCS12=y
CONFIG_CTRL_IFACE_DBUS=y
CONFIG_CTRL_IFACE_DBUS_NEW=y
CONFIG_CTRL_IFACE_DBUS_INTRO=y
CONFIG_READLINE=y
CONFIG_SMARTCARD=y
CONFIG_WPS=y
CFLAGS += -I/usr/include/libnl3
EOF
    cd wpa_supplicant/
    make BINDIR=/usr/sbin LIBDIR=/usr/lib -j$(nproc)
}

package() {
    cd wpa_supplicant
    make BINDIR=/usr/sbin LIBDIR=/usr/lib DESTDIR=$ROOT install
    # from blfs
    mkdir $ROOT/usr/share/dbus-1/system-services
    install -v -m644 dbus/fi.w1.wpa_supplicant1.service \
                 $ROOT/usr/share/dbus-1/system-services/
    install -v -d -m755 $ROOT/etc/dbus-1/system.d
    install -v -m644 dbus/dbus-wpa_supplicant.conf \
                 $ROOT/etc/dbus-1/system.d/wpa_supplicant.conf
    if command -v systemctl > /dev/null; then
      mkdir -p $ROOT/usr/lib/systemd/system
      install -v -m644 systemd/*.service $ROOT/usr/lib/systemd/system/
    fi
}

