#!/bin/sh
NAME="wpa_supplicant"
VERSION="2.10"
DESCRIPTION="WPA client"

build() {
    [ ! -f "wpa_supplicant-$VERSION.tar.gz" ] && down https://w1.fi/releases/wpa_supplicant-$VERSION.tar.gz
    tar -xf wpa_supplicant-$VERSION.tar.gz
    cd wpa_supplicant-$VERSION
    cat > wpa_supplicant/.config << "EOF"
CONFIG_BACKEND=file
CONFIG_CTRL_IFACE=y
CONFIG_DEBUG_FILE=y
CONFIG_DEBUG_SYSLOG=y
CONFIG_DEBUG_SYSLOG_FACILITY=LOG_DAEMON
CONFIG_DRIVER_NL80211=y
CONFIG_DRIVER_WEXT=y
CONFIG_DRIVER_WIRED=y
CONFIG_EAP_GTC=y
CONFIG_EAP_LEAP=y
CONFIG_EAP_MD5=y
CONFIG_EAP_MSCHAPV2=y
CONFIG_EAP_OTP=y
CONFIG_EAP_PEAP=y
CONFIG_EAP_TLS=y
CONFIG_EAP_TTLS=y
CONFIG_IEEE8021X_EAPOL=y
CONFIG_IPV6=y
CONFIG_LIBNL32=y
CONFIG_PEERKEY=y
CONFIG_PKCS12=y
CONFIG_READLINE=y
CONFIG_SMARTCARD=y
CONFIG_WPS=y
CFLAGS += -I/usr/include/libnl3
EOF
    cd wpa_supplicant/
    make BINDIR=/usr/sbin LIBDIR=/usr/lib -j$(nproc)
    install -v -m755 wpa_{cli,passphrase,supplicant} /usr/sbin/ 
    install -v -m644 doc/docbook/wpa_supplicant.conf.5 /usr/share/man/man5/
    install -v -m644 doc/docbook/wpa_{cli,passphrase,supplicant}.8 /usr/share/man/man8/

}

