#!/bin/sh
NAME="busybox"
RELEASE="5"
VERSION="1.36.1"
SOURCES="https://www.busybox.net/downloads/busybox-$VERSION.tar.bz2 ln-relative-symlinks.patch"
SHA256SUM="b8cc24c9574d809e7279c3be349795c5d5ceb6fdf19ca709f80cde50e47de314 9dd4c0567e98a745d48414197f7ad711f8ede97452486159d86926ae12a95d04"
DEPENDS_BUSYBOX="grep ncurses attr xz-utils shadow gtar bzip2"
EXTRACT="false"
DESCRIPTION="The Swiss Army Knife of Embedded Linux"

prepare() {
    tar -xvf busybox-$VERSION.tar.bz2
    cd busybox-$VERSION/coreutils
    
    # Got the patch from http://lists.busybox.net/pipermail/busybox/2016-June/084276.html
    patch -p1 < ../../ln-relative-symlinks.patch
}

build() {
    cd busybox-$VERSION
    make -j$(nproc) defconfig
    make -j$(nproc) busybox
}

package_busybox_standalone() {
    cd busybox-$VERSION
    mkdir -p $ROOT/bin
    cp busybox $ROOT/bin
}

package() {
    package_busybox_standalone
    "$ROOT/bin/busybox" --list | while read APPLET; do
        case $APPLET in
            # Dependencies will cover these commands.
            # We don't outright disable these just in case someone needs them.
            "clear" | "egrep" | "fgrep" | "grep" | "strings" | "setfattr" | "xz" | "su" | "nologin" | "chpasswd" | "groups" | "login" | "tar" | "bzip2" | "bzcat" | "lzcat" | "unxz")
                continue
            ;;
            *)
                echo "Linking /bin/busybox to /bin/$APPLET"
                ln -s /bin/busybox "$ROOT/bin/$APPLET"
            ;;
        esac
    done
}

