#!/bin/sh
NAME="busybox"
RELEASE="3"
VERSION="1.36.1"
SOURCES="https://www.busybox.net/downloads/busybox-$VERSION.tar.bz2;ln-relative-symlinks.patch"
SHA256SUM="b8cc24c9574d809e7279c3be349795c5d5ceb6fdf19ca709f80cde50e47de314;9dd4c0567e98a745d48414197f7ad711f8ede97452486159d86926ae12a95d04"
DESCRIPTION="The Swiss Army Knife of Embedded Linux"

prepare() {
    tar -xvf busybox-$VERSION.tar.bz2
    cd busybox-$VERSION/coreutils
    
    # Got the patch from http://lists.busybox.net/pipermail/busybox/2016-June/084276.html
    patch -p1 < ../../ln-relative-symlinks.patch
}

build() {
    cd busybox-$VERSION
    make -j$(nproc) defconfig
    make -j$(nproc)
}

package() {
    cd busybox-$VERSION
    make install
    mkdir -p $ROOT/bin $ROOT/sbin $ROOT/usr/bin $ROOT/usr/sbin
    cp -rf _install/bin/* $ROOT/bin/
    cp -rf _install/sbin/* $ROOT/sbin/
    cp -rf _install/usr/bin/* $ROOT/usr/bin/
    cp -rf _install/usr/sbin/* $ROOT/usr/bin/
}
