#!/bin/sh
NAME="mtdev"
VERSION="1.1.6"
DESCRIPTION="The mtdev package contains Multitouch Protocol Translation Library which is used to transform all variants of kernel MT (Multitouch) events to the slotted type B protocol."

build() {
    down https://bitmath.org/code/mtdev/mtdev-$VERSION.tar.bz2 
    tar -xvf mtdev-$VERSION.tar.bz2
    cd mtdev-$VERSION || exit 1
    ./configure --prefix=/usr --disable-static
    make
    make DESTDIR="$ROOT" install
}
