#!/bin/sh
NAME="mtdev"
RELEASE="1"
VERSION="1.1.7"
BUILD_DEPENDS="gmake"
SOURCES="https://bitmath.org/code/mtdev/mtdev-$VERSION.tar.bz2"
DEPENDS=""
SHA256SUM="SKIP"
DESCRIPTION="The mtdev package contains Multitouch Protocol Translation Library which is used to transform all variants of kernel MT (Multitouch) events to the slotted type B protocol."

build() {
    kpkgConfigure --prefix=/usr --disable-static
    make
}

package() {
    make DESTDIR="$ROOT" install
}
