#!/bin/sh
NAME="kpkg"
RELEASE="4"
VERSION="5.1.0"
SOURCES="https://github.com/kreatolinux/src/archive/refs/tags/v$VERSION.tar.gz"
BUILD_DEPENDS="nim"
DEPENDS="libarchive shadow openssl git fakeroot"
SHA256SUM="064b65cbeb999f90085a759f73bcb316f8223bce99f7b542baaf7ab7b6199a52  v5.1.0.tar.gz"
DESCRIPTION="Kreato Linux's Package Manager"

build() {
        nimble install cligen libsha -y
        nim c -d:release --threads:on -d:ssl -o="out/kpkg" "kpkg/kpkg.nim"
}

package() {
        mkdir -p "$ROOT/bin"
        cp out/kpkg "$ROOT/bin/"
        mkdir -p "$ROOT/usr/share/man/man8"
        mkdir "$ROOT/usr/share/man/man5"
        cp -f man/kpkg.8 "$ROOT/usr/share/man/man8"
        cp -f man/kpkg_run.8 "$ROOT/usr/share/man/man8"
}
