#!/bin/sh
NAME="kpkg"
RELEASE="4"
VERSION="4.2.0"
SOURCES="https://github.com/kreatolinux/src/archive/refs/tags/v$VERSION.tar.gz"
SHA256SUM="c26ae5419d0d07405d28f1caf43d11d40f9d884739b1e4741d73c77658536aca  v4.2.0.tar.gz"
DESCRIPTION="Kreato Linux's Package Manager"

build() {
        nimble install cligen libsha -y
        nim c -d:release --threads:on -d:ssl -o="out/kpkg" "src/kpkg/kpkg.nim"
}

install() {
        mkdir -p "$ROOT/bin"
        cp out/kpkg "$ROOT/bin/"
        mkdir -p "$ROOT/usr/share/man/man8"
        mkdir "$ROOT/usr/share/man/man5"
        cp -f man/kpkg.8 "$ROOT/usr/share/man/man8"
        cp -f man/kpkg_run.8 "$ROOT/usr/share/man/man8"
}
