#!/bin/sh
NAME="kpkg"
RELEASE="2"
VERSION="4.0.3"
SOURCES="https://github.com/kreatolinux/src/archive/refs/tags/v$VERSION.tar.gz"
SHA256SUM="90337e928d1b88e8e14549a438f5ffa09b85ce23dedf9e604fd5893c42c84163  v4.0.3.tar.gz"
DESCRIPTION="Kreato Linux's Package Manager"

build() {
        nimble install cligen libsha -y --nimbleDir=/tmp/kpkg/srcdir/deps
        nim c -d:release --threads:on -d:ssl -o="out/kpkg" --NimblePath=/tmp/kpkg/srcdir/deps/pkgs --nimcache=/tmp/kpkg/srcdir/cache "src/kpkg/kpkg.nim"
}

install() {
        mkdir -p "$ROOT/bin"
        cp out/kpkg "$ROOT/bin/"
        mkdir -p "$ROOT/usr/share/man/man8"
        mkdir "$ROOT/usr/share/man/man5"
        cp -f man/kpkg.8 "$ROOT/usr/share/man/man8"
        cp -f man/kpkg_run.8 "$ROOT/usr/share/man/man8"
}
