#!/bin/sh
NAME="libressl"
RELEASE="1"
VERSION="3.8.4"
BUILD_DEPENDS="gmake"
SOURCES="https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-$VERSION.tar.gz"
SHA256SUM="c0cef9cfe174ac366ce482f542fddb07721e7fa0caface34b49a8720fa37fe7d"
DESCRIPTION="TLS library"

build() {
    kpkgConfigure
    make -j$(nproc)
}

package() {
    make DESTDIR="$ROOT" install
}

