#!/bin/sh
NAME="iptables"
RELEASE="1"
VERSION="1.8.11"
SOURCES="https://www.netfilter.org/projects/iptables/files/iptables-$VERSION.tar.xz"
BUILD_DEPENDS="gmake"
B2SUM="82daca3940e253f6fda7cf5b3332488c31391ff66c0112c0cae2645ab61918f81e6028ea2b1e1385f21e4c5ff8cd64cba31072a2417a2ab696fe1c6b5464cea1"
DESCRIPTION="Userspace program to configure the Linux packet filtering ruleset"

build() {
    kpkgConfigure --disable-nftables
    make
}

package() {
    make DESTDIR=$ROOT install
}

