#!/bin/sh
NAME="lvm2"
RELEASE="1"
VERSION="2.03.35"
BUILD_DEPENDS="gmake"
SOURCES="https://mirrors.kernel.org/sourceware/lvm2/LVM2.$VERSION.tgz"
DEPENDS="libaio util-linux"
SHA256SUM="ebf28b3427535e2b5abd9991cd839b61622a0dbfb8c86df0f7af1f69dcaa8371"
DESCRIPTION="Logical Volume Manager"
REPO_DIR="/etc/nyaa"

build() {
    kpkgConfigure --enable-pkgconfig --prefix=/usr
    make -j$(nproc)
}

package() {
    make DESTDIR="$ROOT" install
}
