#!/bin/sh
NAME="lvm2"
RELEASE="1"
VERSION="2.03.21"
SOURCES="https://mirrors.kernel.org/sourceware/lvm2/LVM2.$VERSION.tgz"
SHA256SUM="1e261921d621998adc37960c615de784c6145c7f737a80b781f3108fbec67a7e  LVM2.2.03.21.tgz"
DESCRIPTION="Logical Volume Manager"
REPO_DIR="/etc/nyaa"

build() {
    ./configure --enable-pkgconfig --prefix=/usr
    make -j$(nproc)
}

install() {
    make DESTDIR="$ROOT" install
}
