#!/bin/sh
NAME="libxdmcp"
RELEASE="1"
VERSION="1.1.5"
BUILD_DEPENDS="gmake"
SOURCES="https://www.x.org/releases/individual/lib/libXdmcp-$VERSION.tar.xz"
SHA256SUM="d8a5222828c3adab70adf69a5583f1d32eb5ece04304f7f8392b6a353aa2228c"
DEPENDS="xorgproto"
DESCRIPTION="X Display Manager Control Protocol library"

build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
