#!/bin/sh
NAME="nasm"
RELEASE="1"
VERSION="2.15.05"
SOURCES="https://www.nasm.us/pub/nasm/releasebuilds/$VERSION/nasm-$VERSION.tar.xz"
SHA256SUM="3caf6729c1073bf96629b57cee31eeb54f4f8129b01902c73428836550b30a3f  nasm-2.15.05.tar.xz"
DESCRIPTION="Assembler designed for portability and modularity."

build() {
    ./configure --prefix=/usr
    make
}

install() {
    make DESTDIR="$ROOT" install
}
