#!/bin/sh
NAME="nasm"
RELEASE="1"
VERSION="2.16.02"
BUILD_DEPENDS="gmake"
SOURCES="https://www.nasm.us/pub/nasm/releasebuilds/$VERSION/nasm-$VERSION.tar.xz"
DEPENDS=""
SHA256SUM="1e1b942ea88f22edae89659e15be26fa027eae0747f51413540f52d4eac4790d"
DESCRIPTION="Assembler designed for portability and modularity."

build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR="$ROOT" install
}
