#!/bin/sh
NAME="nasm"
RELEASE="1"
VERSION="2.16.01"
SOURCES="https://www.nasm.us/pub/nasm/releasebuilds/$VERSION/nasm-$VERSION.tar.xz"
SHA256SUM="c77745f4802375efeee2ec5c0ad6b7f037ea9c87c92b149a9637ff099f162558  nasm-2.16.01.tar.xz"
DESCRIPTION="Assembler designed for portability and modularity."

build() {
    ./configure --prefix=/usr
    make
}

install() {
    make DESTDIR="$ROOT" install
}
