#!/bin/sh
NAME="gdbm"
RELEASE="1"
VERSION="1.26"
BUILD_DEPENDS="gmake"
SOURCES="https://ftp.gnu.org/gnu/gdbm/gdbm-$VERSION.tar.gz"
SHA256SUM="695e9827fdf763513f133910bc7e6cfdb9187943a4fec943e57449723d2b8dbf"
DESCRIPTION="A library of database functions that use extendible hashing"

build() {
    kpkgConfigure --prefix=/usr    \
                --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
