#!/bin/sh
NAME="flac"
RELEASE="1"
VERSION="1.4.3"
SOURCES="https://ftp.osuosl.org/pub/xiph/releases/flac/flac-$VERSION.tar.xz"
SHA256SUM="6c58e69cd22348f441b861092b825e591d0b822e106de6eb0ee4d05d27205b70  flac-1.4.3.tar.xz"
DESCRIPTION="Free Lossless Audio Codec"

build() {
    ./configure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
