#!/bin/sh
NAME="flac"
RELEASE="2"
VERSION="1.5.0"
BUILD_DEPENDS="cmake"
DEPENDS="libogg"
SOURCES="https://ftp.osuosl.org/pub/xiph/releases/flac/flac-$VERSION.tar.xz"
SHA256SUM="f2c1c76592a82ffff8413ba3c4a1299b6c7ab06c734dee03fd88630485c2b920"
DESCRIPTION="Free Lossless Audio Codec"

build() {
    cmake -B build \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DBUILD_DOCS=0
    
    cmake --build build
}

package() {
    cmake --install build
}
