#!/bin/sh
NAME="wireplumber"
RELEASE="1"
VERSION="0.5.3"
SOURCES="https://gitlab.freedesktop.org/pipewire/wireplumber/-/archive/$VERSION/wireplumber-$VERSION.tar.gz"
DEPENDS="pipewire"
REPLACES="pipewire-session-manager"
BUILD_DEPENDS="meson python-setuptools"
SHA256SUM="626cfaf090efb5359454a30c9b288e068ea04289b341dc4d5c7064fd6b1427b4"
DESCRIPTION="Session / policy manager implementation for PipeWire"

build() {
    meson setup --prefix=/usr \
      --buildtype=release \
    build                    
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install  
}
