#!/bin/sh
NAME="lcms2"
RELEASE="1"
VERSION="2.17"
SOURCES="https://github.com/mm2/Little-CMS/releases/download/lcms$VERSION/lcms2-$VERSION.tar.gz"
BUILD_DEPENDS="meson"
DEPENDS="libjpeg-turbo"
SHA256SUM="d11af569e42a1baa1650d20ad61d12e41af4fead4aa7964a01f93b08b53ab074"
DESCRIPTION="A free, open source, CMM engine"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Djpeg=enabled \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
