#!/bin/sh
NAME="libxcb"
RELEASE="1"
VERSION="1.16.1"
SOURCES="https://www.x.org/releases/individual/lib/libxcb-$VERSION.tar.xz"
SHA256SUM="f24d187154c8e027b358fc7cb6588e35e33e6a92f11c668fe77396a7ae66e311"
DEPENDS="xcb-proto libxdmcp libxau"
BUILD_DEPENDS="python xorgproto libxslt"
DESCRIPTION="X11 client-side library"

build() {
    kpkgConfigure \
        --prefix=/usr \
        --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
