#!/bin/sh
NAME="libxext"
RELEASE="1"
VERSION="1.3.6"
SOURCES="https://www.x.org/releases/individual/lib/libXext-$VERSION.tar.gz"
SHA256SUM="1a0ac5cd792a55d5d465ced8dbf403ed016c8e6d14380c0ea3646c4415496e3d"
DEPENDS="libx11"
BUILD_DEPENDS="xorgproto gmake"
DESCRIPTION="libxext"

build() {
    kpkgConfigure \
        --sysconfdir=/etc \
        --prefix=/usr \
        --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
