#!/bin/sh
NAME="libxext"
RELEASE="1"
VERSION="1.3.5"
SOURCES="https://www.x.org/releases/individual/lib/libXext-$VERSION.tar.gz"
SHA256SUM="1a3dcda154f803be0285b46c9338515804b874b5ccc7a2b769ab7fd76f1035bd"
DEPENDS="libx11"
BUILD_DEPENDS="xorgproto gmake"
DESCRIPTION="libxext"

build() {
    kpkgConfigure \
        --sysconfdir=/etc \
        --prefix=/usr \
        --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
