#!/bin/sh
NAME="xorg-util-macros"
RELEASE="1"
VERSION="1.20.0"
SOURCES="https://www.x.org/archive/individual/util/util-macros-$VERSION.tar.xz"
SHA256SUM="0b86b262dbe971edb4ff233bc370dfad9f241d09f078a3f6d5b7f4b8ea4430db"
DESCRIPTION="xorg-util-macros"

build() {
    ./configure \
        --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
