#!/bin/sh
NAME="upower"
RELEASE="1"
VERSION="1.91.0"
SOURCES="https://gitlab.freedesktop.org/upower/upower/-/archive/v$VERSION/upower-v$VERSION.tar.gz"
BUILD_DEPENDS="meson"
DEPENDS="libgudev eudev gobject-introspection"
SHA256SUM="0b4808827bdc742e8bc65cc12e035dc9b526a246eae18e2509841a7e891eab9e"
DESCRIPTION="Power management support for DeviceKit"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Dgtk-doc=false \
    -Dman=false \
    -Dintrospection=enabled \
    -Dsystemdsystemunitdir=/usr/lib/systemd/system \
    -Dudevrulesdir=/usr/lib/udev/rules.d \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
