#!/bin/sh
NAME="libgweather"
RELEASE="1"
VERSION="4.3.2"
SOURCES="https://github.com/GNOME/libgweather/archive/refs/tags/$VERSION.tar.gz"
DEPENDS="pygobject geocode-glib glib libsoup json-glib"
BUILD_DEPENDS="meson vala"
SHA256SUM="16bdaa00720b9464e1a27bcbf151771b6c7d2438680a027c960d7f10f3974225  4.3.2.tar.gz"
DESCRIPTION="libgweather"

build() {
    meson setup --prefix=/usr \
                --buildtype=release \
                -Dintrospection=true \
                -Dgtk_doc=false \
                -Denable_vala=true \
                build/
    meson compile -C build 
}

package() {
    meson install --destdir "$ROOT" -C build/
}
