#!/bin/sh
NAME="libgweather"
RELEASE="1"
VERSION="4.4.0"
SOURCES="https://gitlab.gnome.org/GNOME/libgweather/-/archive/$VERSION/libgweather-$VERSION.tar.gz"
DEPENDS="geocode-glib glib libsoup json-glib"
BUILD_DEPENDS="meson vala pygobject gobject-introspection"
SHA256SUM="9a7dabd9252f547fabfc277154025c2a9098bc3b6f2473dcead055689a969d1f"
DESCRIPTION="libgweather"

build() {
    meson setup --prefix=/usr \
                --buildtype=release \
                -Dintrospection=true \
                -Dgtk_doc=false \
                -Denable_vala=true \
                build/
    meson compile -C build 
}

package() {
    meson install --destdir "$ROOT" -C build/
}
