#!/bin/sh
NAME="xtrans"
RELEASE="1"
VERSION="1.6.0"
BUILD_DEPENDS="gmake"
SOURCES="https://www.x.org/releases/individual/lib/xtrans-$VERSION.tar.xz"
SHA256SUM="SKIP"
DESCRIPTION="X transport library"

build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
