#!/bin/sh
NAME="xtrans"
RELEASE="1"
VERSION="1.5.1"
BUILD_DEPENDS="gmake"
SOURCES="https://www.x.org/releases/individual/lib/xtrans-$VERSION.tar.xz"
SHA256SUM="dea80fbd8c3c941495b4b1d2785cb652815d016849a0d2ef90d1140de916993e"
DESCRIPTION="X transport library"

build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
