#!/bin/sh
NAME="meson"
RELEASE="1"
VERSION="1.3.0"
SOURCES="https://github.com/mesonbuild/meson/releases/download/$VERSION/meson-$VERSION.tar.gz"
DEPENDS="python samurai"
SHA256SUM="4ba253ef60e454e23234696119cbafa082a0aead0bd3bbf6991295054795f5dc"
DESCRIPTION="Next generation build system"

package() {
    pip install . --root=$ROOT
    #install -vDm644 data/shell-completions/bash/meson "$ROOT/usr/share/bash-completion/completions/meson"
    #install -vDm644 data/shell-completions/zsh/_meson "$ROOT/usr/share/zsh/site-functions/_meson"
}
