#!/bin/sh
NAME="meson"
RELEASE="1"
VERSION=1.2.1
SOURCES="https://github.com/mesonbuild/meson/releases/download/$VERSION/meson-$VERSION.tar.gz"
DEPENDS="python samurai"
SHA256SUM="b1db3a153087549497ee52b1c938d2134e0338214fe14f7efd16fecd57b639f5"
DESCRIPTION="Next generation build system"

build() {
	:
}

package() {
    SETUPTOOLS_USE_DISTUTILS=stdlib pip install . --root=$ROOT
    #install -vDm644 data/shell-completions/bash/meson "$ROOT/usr/share/bash-completion/completions/meson"
    #install -vDm644 data/shell-completions/zsh/_meson "$ROOT/usr/share/zsh/site-functions/_meson"
}
