#!/bin/sh
NAME="meson"
RELEASE="1"
VERSION="1.6.1"
SOURCES="https://github.com/mesonbuild/meson/releases/download/$VERSION/meson-$VERSION.tar.gz"
BUILD_DEPENDS="python-pip"
DEPENDS="python samurai"
B2SUM="7ccdb3bf3f701fc787fabf91413db8301a8658b89e08c1d712711bd35845dc2468211e4b666cf46ad68ad9462e62b12b62d60c3767a2804f9b695b4390bb8235"
DESCRIPTION="Next generation build system"

package() {
    pip install . --root=$ROOT
    #install -vDm644 data/shell-completions/bash/meson "$ROOT/usr/share/bash-completion/completions/meson"
    #install -vDm644 data/shell-completions/zsh/_meson "$ROOT/usr/share/zsh/site-functions/_meson"
}
