#!/bin/sh
NAME="webkitgtk"
RELEASE="1"
VERSION="2.42.0"
SOURCES="https://webkitgtk.org/releases/webkitgtk-$VERSION.tar.xz"
DEPENDS="libxt xdg-dbus-proxy bubblewrap cairo harfbuzz gst-plugins-base gtk3 gtk4 icu lcms2 libgudev libsecret libsoup libtasn libwebp mesa openjpeg sqlite wpebackend-fdo wayland libx11 libxcomposite libxml2 libxslt"
BUILD_DEPENDS="cmake unifdef ninja ruby gst-plugins-bad gobject-introspection wayland-protocols"
SHA256SUM="828f95935861fae583fb8f2ae58cf64c63c178ae2b7c2d6f73070813ad64ed1b  webkitgtk-2.42.0.tar.xz"
DESCRIPTION="webkit"

build_webkitgtk4() {
  # Got flags from BLFS
  cmake -B build -DCMAKE_BUILD_TYPE=Release  \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_SKIP_RPATH=ON       \
      -DPORT=GTK                  \
      -DLIB_INSTALL_DIR=/usr/lib  \
      -DUSE_LIBHYPHEN=OFF         \
      -DENABLE_GAMEPAD=OFF        \
      -DENABLE_MINIBROWSER=ON     \
      -DENABLE_SPELLCHECK=OFF     \
      -DENABLE_DOCUMENTATION=OFF  \
      -DUSE_AVIF=OFF              \
      -DUSE_WOFF2=OFF             \
      -DUSE_GTK4=ON               \
      -DUSE_JPEGXL=OFF            \
      -DUSE_WPE_RENDERER=ON       \
      -DENABLE_JOURNALD_LOG=OFF   \
      -DENABLE_BUBBLEWRAP_SANDBOX=ON \
      -Wno-dev -G Ninja
    ninja -C build
}

build_webkitgtk3() {
  # Got flags from BLFS
  cmake -B build -DCMAKE_BUILD_TYPE=Release  \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_SKIP_RPATH=ON       \
      -DPORT=GTK                  \
      -DLIB_INSTALL_DIR=/usr/lib  \
      -DUSE_LIBHYPHEN=OFF         \
      -DENABLE_GAMEPAD=OFF        \
      -DENABLE_MINIBROWSER=ON     \
      -DENABLE_SPELLCHECK=OFF     \
      -DENABLE_DOCUMENTATION=OFF  \
      -DUSE_AVIF=OFF              \
      -DUSE_WOFF2=OFF             \
      -DUSE_GTK4=OFF              \
      -DUSE_JPEGXL=OFF            \
      -DUSE_WPE_RENDERER=ON       \
      -DENABLE_JOURNALD_LOG=OFF   \
      -DENABLE_BUBBLEWRAP_SANDBOX=ON \
      -Wno-dev -G Ninja
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
