#!/bin/sh
NAME="libpng"
RELEASE="1"
VERSION="1.6.41"
SOURCES="https://github.com/glennrp/libpng/archive/refs/tags/v$VERSION.tar.gz"
DEPENDS=""
SHA256SUM="d236ef40d8733b5a1f5dfd3f8386a7741a0bdd896b6677be0a9cec9747296f4c"
DESCRIPTION="PNG library"

build() {
    kpkgConfigure --prefix=/usr    \
            --disable-static
    make
}

package() {
    make DESTDIR="$ROOT" install
}
