#!/bin/sh
NAME="libpng"
RELEASE="1"
VERSION="1.6.39"
SOURCES="https://github.com/glennrp/libpng/archive/refs/tags/v$VERSION.tar.gz"
SHA256SUM="a00e9d2f2f664186e4202db9299397f851aea71b36a35e74910b8820e380d441  v1.6.39.tar.gz"
DESCRIPTION="PNG library"

build() {
    ./configure --prefix=/usr    \
            --disable-static
    make
}

install() {
    make DESTDIR="$ROOT" install
}
