#!/bin/sh
NAME="libpng"
RELEASE="1"
VERSION="1.6.53"
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/glennrp/libpng/archive/refs/tags/v$VERSION.tar.gz"
DEPENDS=""
SHA256SUM="b20cee717e11416d2f96ccc7d184f63730ca8cb2f03bfd0c4ed77fbc909c0bff"
DESCRIPTION="PNG library"

build() {
    kpkgConfigure --prefix=/usr    \
            --disable-static
    make
}

package() {
    make DESTDIR="$ROOT" install
}
