#!/bin/sh
NAME="graphene"
RELEASE="1"
VERSION="1.10.8"
SOURCES="https://download.gnome.org/sources/graphene/1.10/graphene-$VERSION.tar.xz"
BUILD_DEPENDS="meson"
DEPENDS="glib gobject-introspection"
SHA256SUM="a37bb0e78a419dcbeaa9c7027bcff52f5ec2367c25ec859da31dfde2928f279a  graphene-1.10.8.tar.xz"
DESCRIPTION="graphene"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
