#!/bin/sh
NAME="p11-kit"
RELEASE="1"
VERSION="0.25.2"
SOURCES="https://github.com/p11-glue/p11-kit/releases/download/$VERSION/p11-kit-$VERSION.tar.xz"
DEPENDS="libtasn libffi pkgconf"
SHA256SUM="44be0f5797464ca5b36c68c8fb9152c2d34e91f6ba910ad3945dd7cdd2557cc3"
DESCRIPTION="A way to load and enumerate PKCS#11 modules"

build() {
    ./configure --prefix=/usr     \
            --sysconfdir=/etc \
            --with-trust-paths=/etc/pki/anchors
    make
}

package() {
    make DESTDIR=$ROOT install
}
