#!/bin/sh
NAME="hicolor-icon-theme"
RELEASE="1"
VERSION="0.17"
SOURCES="https://icon-theme.freedesktop.org/releases/hicolor-icon-theme-$VERSION.tar.xz"
SHA256SUM="317484352271d18cbbcfac3868eab798d67fff1b8402e740baa6ff41d588a9d8"
DESCRIPTION="hicolor-icon-theme"

build() {
    ./configure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
