#!/bin/sh
NAME="podman"
RELEASE="1"
VERSION="4.9.0"
SOURCES="https://github.com/containers/podman/archive/refs/tags/v$VERSION.tar.gz"
BUILD_DEPENDS="go"
DEPENDS="libseccomp gpgme btrfs-progs conmon crun lvm2"
SHA256SUM="c24337dede3575eeeae98bb6126b803769e885b6db12b9b76f5548caf0da4b43"
DESCRIPTION="A tool for managing OCI containers and pods"

build() {
    make BUILDTAGS="seccomp" -j$(nproc)
}

package() {
    sed -i 's/-sfr/-sf/g' Makefile
    make install
}
