#!/bin/sh
NAME="gmp"
RELEASE="1"
VERSION="6.3.0"
BUILD_DEPENDS="gmake"
SOURCES="https://ftp.gnu.org/gnu/gmp/gmp-$VERSION.tar.xz"
DEPENDS="m4"
SHA256SUM="SKIP"
DESCRIPTION="GNU gmp"

build() {
    kpkgConfigure
    make -j$(nproc)
}

check() {
    make check
}

package() {
    make DESTDIR=$ROOT install
    rm -rf "$ROOT/usr/share/info/dir"
}

