#!/bin/sh
NAME="gmp"
RELEASE="1"
VERSION="6.3.0"
BUILD_DEPENDS="gmake"
SOURCES="https://ftp.gnu.org/gnu/gmp/gmp-$VERSION.tar.xz"
DEPENDS="m4"
SHA256SUM="a3c2b80201b89e68616f4ad30bc66aee4927c3ce50e33929ca819d5c43538898"
DESCRIPTION="GNU gmp"

build() {
    if ! kpkgConfigure; then
        cat config.log
        exit 1
    fi
    make -j$(nproc)
}

check() {
    make check
}

package() {
    make DESTDIR=$ROOT install
    rm -rf "$ROOT/usr/share/info/dir"
}

