#!/bin/sh
NAME="flex"
RELEASE="1"
VERSION="2.6.4"
SOURCES="https://github.com/westes/flex/releases/download/v$VERSION/flex-$VERSION.tar.gz"
DEPENDS="m4"
SHA256SUM="e87aae032bf07c26f85ac0ed3250998c37621d95f8bd748b31f15b33c45ee995"
DESCRIPTION="The Fast Lexical Analyzer - scanner generator for lexing in C and C++"

build() {
    kpkgConfigure --prefix=/usr 
    make -j$(nproc)
}

package() {
    make DESTDIR=$ROOT install
}

