#!/bin/sh
NAME="flex"
VERSION="2.6.4"
SOURCES="https://github.com/westes/flex/releases/download/v$VERSION/flex-$VERSION.tar.gz"
SHA256SUM="e87aae032bf07c26f85ac0ed3250998c37621d95f8bd748b31f15b33c45ee995  flex-2.6.4.tar.gz"
DESCRIPTION="The Fast Lexical Analyzer - scanner generator for lexing in C and C++"

build() {
    tar -xf flex-$VERSION.tar.gz
    cd flex-$VERSION
    ./configure
    make -j$(nproc)
    make DESTDIR=$ROOT install
}

