#!/bin/sh
NAME="linux-headers"
VERSION="5.19.12"
SOURCES="https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-$VERSION.tar.xz"
SHA256SUM="c436a548c7312ce6fc5a3472cbead895eef8f52841fbe7c71fd8e48bdfe2b0ba  linux-5.19.12.tar.xz"
DESCRIPTION="Linux development headers"

build() {
    tar -xvf linux-$VERSION.tar.xz
    cd linux-$VERSION
    make mrproper
    make headers
    find usr/include -name '.*' -delete
    rm usr/include/Makefile
    mkdir -p $ROOT/usr
    cp -rv usr/include $ROOT/usr/include
}
