#!/bin/sh
NAME="perl"
VERSION="5.36.0"
SOURCES="https://www.cpan.org/src/5.0/perl-$VERSION.tar.gz"
SHA256SUM="e26085af8ac396f62add8a533c3a0ea8c8497d836f0689347ac5abd7b7a4e00a  perl-5.36.0.tar.gz"
DESCRIPTION="Perl"

build() {
    tar -xvf perl-$VERSION.tar.gz
    cd perl-$VERSION
    sh Configure -des -Dprefix=/usr -Dlibs=-lm -Uloclibpth -Ulocincpth
    make -j$(nproc --all)
    make DESTDIR=$ROOT install
}
