#!/bin/sh
NAME="perl"
RELEASE="2"
VERSION="5.40.2"
BUILD_DEPENDS="gmake"
SOURCES="https://www.cpan.org/src/5.0/perl-$VERSION.tar.gz"
SHA256SUM="10d4647cfbb543a7f9ae3e5f6851ec49305232ea7621aed24c7cfbb0bef4b70d"
DESCRIPTION="Perl"

build() {
	VERSION_MAJORANDMINOR=$(echo $VERSION | cut -d. -f1-2) # 5.40
    # Credit: https://www.linuxfromscratch.org/lfs/view/development/chapter08/perl.html
    sh Configure -des                                         \
             -Dprefix=/usr                                \
             -Dvendorprefix=/usr                          \
             -Dprivlib=/usr/lib/perl5/$VERSION_MAJORANDMINOR/core_perl      \
             -Darchlib=/usr/lib/perl5/$VERSION_MAJORANDMINOR/core_perl      \
             -Dsitelib=/usr/lib/perl5/$VERSION_MAJORANDMINOR/site_perl      \
             -Dsitearch=/usr/lib/perl5/$VERSION_MAJORANDMINOR/site_perl     \
             -Dvendorlib=/usr/lib/perl5/$VERSION_MAJORANDMINOR/vendor_perl  \
             -Dvendorarch=/usr/lib/perl5/$VERSION_MAJORANDMINOR/vendor_perl \
             -Dman1dir=/usr/share/man/man1                \
             -Dman3dir=/usr/share/man/man3                \
             -Dpager="/usr/bin/less -isR"                 \
             -Duseshrplib                                 \
             -Dusethreads
    make -j$(nproc --all)
}

#check() {
#	make -j$(nproc --all) test
#}

package() {
    make DESTDIR=$ROOT install
	cd $ROOT
	tree
}
