#!/bin/sh
NAME="rootdo"
VERSION="1.4.2"
SOURCES="https://codeberg.org/sw1tchbl4d3/rdo/archive/$VERSION.tar.gz"
SHA256SUM="e62f8b502b5e706d9dd4d22d1db96f78d98cfd05b04178b327897660149ab260  1.4.2.tar.gz"
DESCRIPTION="simple sudo/doas alternative"
build() {
    tar -xvf $VERSION.tar.gz
    cd rdo || exit  1
    make
    mkdir -p $ROOT/usr/bin /etc/
    cp rdo /usr/bin/rdo
    chown root:root /usr/bin/rdo
    chmod 755 /usr/bin/rdo
    chmod u+s /usr/bin/rdo
    cp rdo_sample.conf /etc/rdo.conf
    chmod 600 /etc/rdo.conf
    ln -s /usr/bin/rdo /usr/bin/rootdo
}
