#!/bin/sh
NAME="fribidi"
RELEASE="1"
VERSION="1.0.15"
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/fribidi/fribidi/releases/download/v$VERSION/fribidi-$VERSION.tar.xz" 
DEPENDS=""
SHA256SUM="0bbc7ff633bfa208ae32d7e369cf5a7d20d5d2557a0b067c9aa98bcbf9967587"
DESCRIPTION="FriBidi is an implementation of Unicode Bidirectional Algorithm"

build() {
    kpkgConfigure --prefix=/usr 
    make
}

package() {
    make DESTDIR="$ROOT" install
}
