#!/bin/sh
NAME="fribidi"
RELEASE="1"
VERSION="1.0.13"
SOURCES="https://github.com/fribidi/fribidi/releases/download/v$VERSION/fribidi-$VERSION.tar.xz" 
SHA256SUM="7fa16c80c81bd622f7b198d31356da139cc318a63fc7761217af4130903f54a2  fribidi-1.0.13.tar.xz"
DESCRIPTION="FriBidi is an implementation of Unicode Bidirectional Algorithm"

build() {
    ./configure --prefix=/usr 
    make
}

install() {
    make DESTDIR="$ROOT" install
}
