#!/bin/sh
NAME="fribidi"
RELEASE="1"
VERSION="1.0.12"
SOURCES="https://github.com/fribidi/fribidi/releases/download/v$VERSION/fribidi-$VERSION.tar.xz" 
SHA256SUM=";"
DESCRIPTION="FriBidi is an implementation of Unicode Bidirectional Algorithm"

build() {
    cd fribidi-$VERSION || exit 1
    ./configure --prefix=/usr 
    make
    make DESTDIR="$ROOT" install
}
