#!/bin/sh
NAME="ostree"
RELEASE="2"
VERSION="2024.1"
SOURCES="https://github.com/ostreedev/ostree/releases/download/v$VERSION/libostree-$VERSION.tar.xz"
DEPENDS="xz-utils fuse e2fsprogs gpgme libarchive curl glib libsoup"
SHA256SUM="152327fe804512d4f896fb9b9e9cdc84ad9b4c0b205b8625472147d5a28164af"
DESCRIPTION="Operating system and container binary deployment and upgrades"

build() {

    if ! command -v systemctl > /dev/null; then
        extraArgs="--without-libsystemd"
    fi

    kpkgConfigure $extraArgs --disable-man --with-curl --with-gpgme --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
