#!/bin/sh
NAME="appstream"
RELEASE="1"
VERSION="1.0.0"
SOURCES="https://github.com/ximion/appstream/archive/refs/tags/v$VERSION.tar.gz disable-docs.patch"
BUILD_DEPENDS="meson ninja"
DEPENDS="glib itstool libxslt libxml2 libxmlb curl gobject-introspection libyaml"
OPTDEPENDS="systemd: For systemd support"
SHA256SUM="e964fea8b4b7efac7976dc13da856421ddec4299acb5012a7c059f03eabcbeae 30a67dd92c943f97576dc0c1c314dbcc2392c88eeb6ed04895a0b5f2c515d9aa"
DESCRIPTION="appstream"

prepare() {
    tar -xvf v$VERSION.tar.gz
    cd appstream-$VERSION
    patch -p1 < ../disable-docs.patch
}

build() {
    cd appstream-$VERSION
    
    if command -v systemctl > /dev/null; then
      systemdSupport="true"
    else 
      systemdSupport="false"
    fi
    
    meson setup \
    --prefix=/usr \
    -Dsystemd=$systemdSupport \
    -Dstemming=false \
    -Ddocs=false \
    -Dapidocs=false \
    -Dinstall-docs=false \
    build
    ninja -C build
}

package() {
    cd appstream-$VERSION
    DESTDIR="$ROOT" ninja -C build install
}
