#!/bin/sh
NAME="appstream"
RELEASE="1"
VERSION="1.1.1"
SOURCES="https://github.com/ximion/appstream/archive/refs/tags/v$VERSION.tar.gz"
BUILD_DEPENDS="meson"
DEPENDS="glib itstool libxslt libxml2 libxmlb curl gobject-introspection libfyaml gperf"
OPTDEPENDS="systemd: For systemd support"
SHA256SUM="dd7222519b5d855124fa803ce82a7cbf090ac6b2e44a5bc515e729b1f20a63ae"
DESCRIPTION="Tools and libraries to work with AppStream metadata"

build() {
    
    # https://github.com/ximion/appstream/issues/523
    # We won't want manpages, so we will just remove the line that adds docs 
    # as a subdir.
    grep -v "subdir('docs/')" meson.build > meson.build.new
    mv meson.build.new meson.build

    if command -v systemctl > /dev/null; then
      systemdSupport="true"
    else 
      systemdSupport="false"
    fi
    
    meson setup \
    --prefix=/usr \
    -Dsystemd=$systemdSupport \
    -Dstemming=false \
    -Ddocs=false \
    -Dapidocs=false \
    -Dinstall-docs=false \
    build
    meson compile -C build
}

package() {
    meson install --destdir="$ROOT" -C build
}
