#!/bin/sh
NAME="appstream"
RELEASE="1"
VERSION="0.16.3"
SOURCES="https://github.com/ximion/appstream/archive/refs/tags/v$VERSION.tar.gz;disable-docs.patch"
BUILD_DEPENDS="meson ninja"
DEPENDS="glib itstool libxslt libxml2 libxmlb curl gobject-introspection libyaml"
OPTDEPENDS="systemd: For systemd support"
SHA256SUM="4470a27474dc3cc4938552fbf0394b6a65d8a2055d4f4418df086d65d8f2ba29  v0.16.3.tar.gz;30a67dd92c943f97576dc0c1c314dbcc2392c88eeb6ed04895a0b5f2c515d9aa  disable-docs.patch"
DESCRIPTION="appstream"

prepare() {
    tar -xvf v$VERSION.tar.gz
    cd appstream-$VERSION
    patch -p1 < ../disable-docs.patch
}

build() {
    cd appstream-$VERSION
    
    if command -v systemctl > /dev/null; then
      systemdSupport="true"
    else 
      systemdSupport="false"
    fi
    
    meson setup \
    --prefix=/usr \
    -Dsystemd=$systemdSupport \
    -Dstemming=false \
    -Ddocs=false \
    -Dapidocs=false \
    -Dinstall-docs=false \
    build
    ninja -C build
}

package() {
    cd appstream-$VERSION
    DESTDIR="$ROOT" ninja -C build install
}
