#!/bin/sh
NAME="libxmlb"
RELEASE="1"
VERSION="0.3.12"
SOURCES="https://github.com/hughsie/libxmlb/releases/download/$VERSION/libxmlb-$VERSION.tar.xz"
BUILD_DEPENDS="meson ninja"
DEPENDS="glib"
SHA256SUM="b1e61f64dadc67e458430bb35a9f1b25170aafcf5674a52012ae38a2212227b3  libxmlb-0.3.12.tar.xz"
DESCRIPTION="A library to help create and query binary XML blobs"

build() {
    meson \
    --prefix=/usr \
    -Dman=false \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
