#!/bin/sh
NAME="libxmlb"
RELEASE="1"
VERSION="0.3.24"
SOURCES="https://github.com/hughsie/libxmlb/releases/download/$VERSION/libxmlb-$VERSION.tar.xz"
BUILD_DEPENDS="meson ninja"
DEPENDS="glib gobject-introspection"
SHA256SUM="0a3ec258b12dbf10e5fe840b2421c84137eb7cc1b09c3de6210f3f7d51733733"
DESCRIPTION="A library to help create and query binary XML blobs"

build() {
    meson setup \
    --prefix=/usr \
    -Dgtkdoc=false \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
