#!/bin/sh
NAME="bemenu"
RELEASE="1"
VERSION="0.6.15"
SOURCES="https://github.com/Cloudef/bemenu/releases/download/$VERSION/bemenu-$VERSION.tar.gz"
DEPENDS="wayland wayland-protocols cairo pango libxkbcommon"
BUILD_DEPENDS="gmake pkgconf"
SHA256SUM="7fcd32d97be477b1813e6b9b1a69fcf9d7c9a958e6c3ddfbd69a46fd66f606f4  bemenu-0.6.15.tar.gz"
DESCRIPTION="Dynamic menu library and client program inspired by dmenu"

build() {
    make clients wayland 
}

package() {
    make PREFIX=/usr DESTDIR=$ROOT install
}
