#!/bin/sh
NAME="startup-notification"
RELEASE="1"
VERSION="0.12"
BUILD_DEPENDS="gmake"
SOURCES="https://www.freedesktop.org/software/startup-notification/releases/startup-notification-$VERSION.tar.gz"
DEPENDS="libx11 libxcb xcb-util"
SHA256SUM="3c391f7e930c583095045cd2d10eb73a64f085c7fde9d260f2652c7cb3cfbe4a"
DESCRIPTION="startup-notification"

build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
