#!/bin/sh
NAME="efibootmgr"
VERSION="18"
SOURCES="https://github.com/rhboot/efibootmgr/archive/$VERSION/efibootmgr-$VERSION.tar.gz"
SHA256SUM="442867d12f8525034a404fc8af3036dba8e1fc970998af2486c3b940dfad0874  efibootmgr-18.tar.gz"
DESCRIPTION="efibootmgr provides tools and libraries to manipulate EFI variables"

build() {
    tar -xvf efibootmgr-$VERSION.tar.gz
    cd efibootmgr-$VERSION || exit 1
    sed -e '/-Werror/d' -i Make.defaults   
    sed -e '/extern int efi_set_verbose/d' -i src/efibootmgr.c
    make EFI_LOADER=grubx64.efi EFIDIR=KLX
    make DESTDIR="$ROOT" EFIDIR=KLX install
}
