#!/bin/sh
NAME="jsoncpp"
RELEASE="1"
VERSION="1.9.6"
SOURCES="https://github.com/open-source-parsers/jsoncpp/archive/refs/tags/$VERSION.tar.gz"
BUILD_DEPENDS="meson"
SHA256SUM="f93b6dd7ce796b13d02c108bc9f79812245a82e577581c4c9aabe57075c90ea2"
DESCRIPTION="A C++ library for interacting with JSON"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
