#!/bin/sh
NAME="jsoncpp"
RELEASE="1"
VERSION="1.9.5"
SOURCES="https://github.com/open-source-parsers/jsoncpp/archive/refs/tags/$VERSION.tar.gz"
BUILD_DEPENDS="meson"
SHA256SUM="f409856e5920c18d0c2fb85276e24ee607d2a09b5e7d5f0a371368903c275da2"
DESCRIPTION="A C++ library for interacting with JSON"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
