#!/bin/sh
NAME="harfbuzz"
RELEASE="2"
VERSION="8.0.1"
SOURCES="https://github.com/harfbuzz/harfbuzz/releases/download/$VERSION/harfbuzz-$VERSION.tar.xz" 
SHA256SUM="c1ce780acd385569f25b9a29603d1d5bc71e6940e55bfdd4f7266fad50e42620  harfbuzz-8.0.1.tar.xz"
DESCRIPTION="FriBidi is an implementation of Unicode Bidirectional Algorithm"


build() {
    meson \
        --prefix=/usr \
        . output
    ninja -C output
}

install() {
        DESTDIR=$ROOT ninja -C output install
}
