#!/bin/sh
NAME="harfbuzz"
RELEASE="2"
VERSION="8.0.0"
SOURCES="https://github.com/harfbuzz/harfbuzz/releases/download/$VERSION/harfbuzz-$VERSION.tar.xz" 
SHA256SUM="1f98b5e3d06a344fe667d7e8210094ced458791499839bddde98c167ce6a7c79  harfbuzz-8.0.0.tar.xz"
DESCRIPTION="FriBidi is an implementation of Unicode Bidirectional Algorithm"


build() {
    meson \
        --prefix=/usr \
        . output
    ninja -C output
}

install() {
        DESTDIR=$ROOT ninja -C output install
}
