#!/bin/sh
NAME="gcr-4"
RELEASE="1"
VERSION="4.1.0"
SOURCES="https://download.gnome.org/sources/gcr/4.1/gcr-$VERSION.tar.xz"
DEPENDS="glib gtk4 libgcrypt p11-kit gnupg libsecret openssh libxslt"
BUILD_DEPENDS="meson gobject-introspection"
SHA256SUM="9ceaad29284ba919b9216e2888c18ec67240c2c93b3a4856bc5488bbc1f3a383"
DESCRIPTION="A library for displaying certificates and crypto UI"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Dgtk_doc=false \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
