#!/bin/sh
NAME="gtk+"
VERSION="3.24.34"
SOURCES="https://download.gnome.org/sources/gtk+/3.24/gtk+-$VERSION.tar.xz"
SHA256SUM="dbc69f90ddc821b8d1441f00374dc1da4323a2eafa9078e61edbe5eeefa852ec  gtk+-3.24.34.tar.xz"
DESCRIPTIONS="Contains libraries for GUI applications"
build() {
    [ ! -d "gtk+-$VERSION" ] && tar -xvf gtk+-$VERSION.tar.gz
    cd gtk+-$VERSION || exit  1
    ./configure --prefix=/usr --enable-wayland-backend
    make
    make DESTDIR=$ROOT install
}
