#!/bin/sh
NAME="libgusb"
RELEASE="2"
VERSION="0.4.8"
SOURCES="https://github.com/hughsie/libgusb/releases/download/$VERSION/libgusb-$VERSION.tar.xz"
BUILD_DEPENDS="meson gobject-introspection vala"
DEPENDS="json-glib libusb"
SHA256SUM="77aec51de289afe3bf5f8a1a36ae989d1a59748391097242949daccda9569ede"
DESCRIPTION="GObject bindings for libusb"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Ddocs=false \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
