#!/bin/sh
NAME="libgusb"
RELEASE="2"
VERSION="0.4.9"
SOURCES="https://github.com/hughsie/libgusb/releases/download/$VERSION/libgusb-$VERSION.tar.xz"
BUILD_DEPENDS="meson gobject-introspection vala"
DEPENDS="json-glib libusb"
SHA256SUM="9df5ef301d6a4b361002aa52cce1165a87a89744055879bdbab31e7e86f1e846"
DESCRIPTION="GObject bindings for libusb"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Ddocs=false \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
