#!/bin/sh
NAME="pixman"
RELEASE="1"
VERSION="0.42.2"
SOURCES="https://www.cairographics.org/releases/pixman-$VERSION.tar.gz"
BUILD_DEPENDS="meson"
SHA256SUM="ea1480efada2fd948bc75366f7c349e1c96d3297d09a3fe62626e38e234a625e  pixman-0.42.2.tar.gz"
DESCRIPTION="A library that provides low-level pixel manipulation features such as image compositing and trapezoid rasterization"

build() {
    mkdir build
    cd build
    meson --prefix=/usr --buildtype=release
    ninja
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
