#!/bin/sh
NAME="grim"
RELEASE="1"
VERSION="1.4.1"
SOURCES="https://git.sr.ht/~emersion/grim/refs/download/v1.4.1/grim-1.4.1.tar.gz"
SHA256SUM="93dbbc6608ae541a209c82d7e3cf1035d93844b99d2e40592d0b355f088d9ac5  grim-1.4.1.tar.gz"
DESCRIPTION="Grabs images from a Wayland compositor"
build() {                                                                                                              
    meson --prefix=/usr build/                                                                                         
    ninja -C build/                                                                                                    
}

install() {
    DESTDIR=$ROOT ninja -C build/ install                                                                              
}                                                                                                                      
