#!/bin/sh
NAME="libpciaccess"
RELEASE="1"
VERSION="0.17"
SOURCES="https://x.org/releases/individual/lib/libpciaccess-$VERSION.tar.gz"
SHA256SUM="bf6985a77d2ecb00e2c79da3edfb26b909178ffca3f2e9d14ed0620259ab733b  libpciaccess-0.17.tar.gz"
DESCRIPTION="libpciaccess"
build() {
    ./configure --prefix=/usr
    make
}

install() {
    make DESTDIR=$ROOT install
}
