#!/bin/sh
NAME="libpciaccess"
RELEASE="1"
VERSION="0.18.1"
BUILD_DEPENDS="gmake"
SOURCES="https://x.org/releases/individual/lib/libpciaccess-$VERSION.tar.gz"
DEPENDS=""
SHA256SUM="SKIP"
DESCRIPTION="libpciaccess"
build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
