#!/bin/sh
NAME="libxau"
RELEASE="1"
VERSION="1.0.12"
BUILD_DEPENDS="gmake"
SOURCES="https://www.x.org/releases/individual/lib/libXau-$VERSION.tar.xz"
SHA256SUM="74d0e4dfa3d39ad8939e99bda37f5967aba528211076828464d2777d477fc0fb"
DEPENDS="xorgproto"
DESCRIPTION="X11 authentication library"

build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
