#!/bin/sh
NAME="libxau"
RELEASE="1"
VERSION="1.0.11"
SOURCES="https://www.x.org/releases/individual/lib/libXau-$VERSION.tar.xz"
SHA256SUM="f3fa3282f5570c3f6bd620244438dbfbdd580fc80f02f549587a0f8ab329bbeb  libXau-1.0.11.tar.xz"
DEPENDS="xorgproto"
DESCRIPTION="X11 authentication library"

build() {
    ./configure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
