#!/bin/sh
NAME="src"
RELEASE="6"
VERSION="7.2.1"
SOURCES="https://github.com/kreatolinux/src/releases/download/v$VERSION/src-v$VERSION-dist.tar.gz"
BUILD_DEPENDS="nim"
DEPENDS="libarchive shadow openssl git"
DEPENDS_KPKG+="bubblewrap sqlite"
B2SUM="786a02f742015903c6c6fd852552d272912f4740e15847618a86e217f71f5419d25e1031afee585313896444934eb04b903a685b1448b755d56f701afe9be2ce"
DESCRIPTION="Kreato Linux source tree metapackage"

build_kpkg() {
        nimble install cligen fuzzy nimcrypto norm -y
        nim c --deepcopy:on -d:release -d:useDist --passL:-larchive --threads:on -d:ver="$VERSION" -d:ssl -o="out/kpkg" "kpkg/kpkg.nim"
}

package_kpkg() {
        mkdir -p "$ROOT/bin"
        cp out/kpkg "$ROOT/bin/"
        mkdir -p "$ROOT/usr/share/man/man8"
        mkdir "$ROOT/usr/share/man/man5"
        cp -f man/kpkg.8 "$ROOT/usr/share/man/man8"
        cp -f man/kpkg_run.8 "$ROOT/usr/share/man/man8"
}

build_jumpstart() {
        nimble install cligen fusion -y
        nim c -d:release --threads:on -o="out/jumpstart" "jumpstart/jumpstart.nim"
        nim c -d:release --threads:on -o="out/jumpctl" "jumpstart/jumpctl.nim"
}

package_jumpstart() {
        mkdir -p "$ROOT/bin"
        cp out/jumpctl "$ROOT/bin/"
        cp out/jumpstart "$ROOT/bin"
}

package_mari() {
        mkdir -p "$ROOT/bin"
        cp out/mari "$ROOT/bin/"
}

