#!/bin/sh
NAME="src"
RELEASE="4"
VERSION="6.2.3"
SOURCES="https://github.com/kreatolinux/src/releases/download/v$VERSION/src-v$VERSION-dist.tar.gz"
BUILD_DEPENDS="nim"
DEPENDS="libarchive shadow openssl git fakeroot"
SHA256SUM="46ad54697c28d5cd455500a6488063997c25799b57907039bef758a865ac9e99"
DESCRIPTION="Kreato Linux source tree metapackage"

build_kpkg() {
        nimble install cligen fuzzy libsha -y
        nim c -d:release -d:useDist --passL:-larchive --threads:on -d:ver="$VERSION" -d:ssl -o="out/kpkg" "kpkg/kpkg.nim"
}

package_kpkg() {
        mkdir -p "$ROOT/bin"
        cp out/kpkg "$ROOT/bin/"
        mkdir -p "$ROOT/usr/share/man/man8"
        mkdir "$ROOT/usr/share/man/man5"
        cp -f man/kpkg.8 "$ROOT/usr/share/man/man8"
        cp -f man/kpkg_run.8 "$ROOT/usr/share/man/man8"
}

build_jumpstart() {
        nimble install cligen fusion -y
        nim c -d:release --threads:on -o="out/jumpstart" "jumpstart/jumpstart.nim"
        nim c -d:release --threads:on -o="out/jumpctl" "jumpstart/jumpctl.nim"
}

package_jumpstart() {
        mkdir -p "$ROOT/bin"
        cp out/jumpctl "$ROOT/bin/"
        cp out/jumpstart "$ROOT/bin"
}

package_mari() {
        mkdir -p "$ROOT/bin"
        cp out/mari "$ROOT/bin/"
}

