#!/bin/sh
NAME="src"
RELEASE="4"
VERSION="5.3.3"
SOURCES="https://github.com/kreatolinux/src/archive/refs/tags/v$VERSION.tar.gz"
BUILD_DEPENDS="nim"
DEPENDS="libarchive shadow openssl git fakeroot"
SHA256SUM="ab86d9a87a511f98ec8bffccc8b7c5cda6e1ce4643728b4e0d94798bf2851608  v5.3.3.tar.gz"
DESCRIPTION="Kreato Linux source tree metapackage"

build_kpkg() {
        nimble install cligen libsha -y
        nim c -d:release --threads:on -d:ver="$VERSION" -d:ssl -o="out/kpkg" "kpkg/kpkg.nim"
}

package_kpkg() {
        mkdir -p "$ROOT/bin"
        cp out/kpkg "$ROOT/bin/"
        mkdir -p "$ROOT/usr/share/man/man8"
        mkdir "$ROOT/usr/share/man/man5"
        cp -f man/kpkg.8 "$ROOT/usr/share/man/man8"
        cp -f man/kpkg_run.8 "$ROOT/usr/share/man/man8"
}

build_jumpstart() {
        nimble install cligen fusion -y
        nim c -d:release --threads:on -o="out/jumpstart" "jumpstart/jumpstart.nim"
        nim c -d:release --threads:on -o="out/jumpctl" "jumpstart/jumpctl.nim"
}

package_jumpstart() {
        mkdir -p "$ROOT/bin"
        cp out/jumpctl "$ROOT/bin/"
        cp out/jumpstart "$ROOT/bin"
}

build_mari() {
        nimble install httpbeast -y
        nim c -d:release -o="out/mari" "mari/mari.nim"
}

package_mari() {
        mkdir -p "$ROOT/bin"
        cp out/mari "$ROOT/bin/"
}

