#!/bin/sh
NAME="dhcpcd"
RELEASE="1"
VERSION="10.0.4"
SOURCES="https://github.com/NetworkConfiguration/dhcpcd/releases/download/v$VERSION/dhcpcd-$VERSION.tar.xz"
DEPENDS="libudev"
SHA256SUM="ced5bbde8da3726eac77b9e77e4f31a89c9849d811ef8a2c749664fc5f55a718"
DESCRIPTION="DHCP client"

build() {
    ./configure --prefix=/usr                \
            --sysconfdir=/etc            \
            --libexecdir=/usr/lib/dhcpcd \
            --dbdir=/var/lib/dhcpcd      \
            --runstatedir=/run           \
            --privsepuser=dhcpcd
    make
    make -j$(nproc)
}

package() {
    make DESTDIR=$ROOT install
    mkdir "$ROOT/bin/"
printf '
    #!/bin/sh
    echo "dhcpcd:x:981:981:dhcpcd privilege separation:/:/usr/bin/nologin" >> /etc/passwd
    echo "dhcpcd:x:981:" >> /etc/group
    ' > "$ROOT/bin/install-dhcpcd-groups"
    chmod +x "$ROOT/bin/install-dhcpcd-groups"
    echo "dhcpcd: please run install-dhcpcd-groups to install groups"
}
