#!/bin/sh
NAME="dhcpcd"
RELEASE="1"
VERSION="10.3.0"
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/NetworkConfiguration/dhcpcd/releases/download/v$VERSION/dhcpcd-$VERSION.tar.xz"
DEPENDS="eudev"
SHA256SUM="06e4c1aaf958523f3fd1c57258c613c6c7ae56b8f1d678fa7943495d5ea6aeb5"
DESCRIPTION="DHCP client"

build() {
    kpkgConfigure --prefix=/usr                \
            --sysconfdir=/etc            \
            --libexecdir=/usr/lib/dhcpcd \
            --dbdir=/var/lib/dhcpcd      \
            --runstatedir=/run           \
            --privsepuser=dhcpcd
    make
    make -j$(nproc)
}

package() {
    make DESTDIR=$ROOT install
    mkdir "$ROOT/bin/"
printf '
    #!/bin/sh
    echo "dhcpcd:x:981:981:dhcpcd privilege separation:/:/usr/bin/nologin" >> /etc/passwd
    echo "dhcpcd:x:981:" >> /etc/group
    ' > "$ROOT/bin/install-dhcpcd-groups"
    chmod +x "$ROOT/bin/install-dhcpcd-groups"
    echo "dhcpcd: please run install-dhcpcd-groups to install groups"
}
