#!/bin/sh
NAME="libuv"
RELEASE="1"
VERSION="1.47.0"
SOURCES="https://dist.libuv.org/dist/v$VERSION/libuv-v$VERSION.tar.gz"
DEPENDS="automake libtool"
SHA256SUM="20c37a4ca77a2107879473c6c8fa0dc1350e80045df98bfbe78f7cd6d7dd2965"
DESCRIPTION="The libuv package is a multi-platform support library with a focus on asynchronous I/O."

build() {
    sh autogen.sh
    kpkgConfigure --prefix=/usr --disable-static
    make -j$(nproc)
}

package() {
    make DESTDIR=$ROOT install
}

