#!/bin/sh
NAME="libuv"
RELEASE="1"
VERSION="1.46.0"
SOURCES="https://dist.libuv.org/dist/v$VERSION/libuv-v$VERSION.tar.gz"
DEPENDS="automake libtool"
SHA256SUM="111f83958b9fdc65f1489195d25f342b9f7a3e683140c60e62c00fbaccddddce"
DESCRIPTION="The libuv package is a multi-platform support library with a focus on asynchronous I/O."

build() {
    sh autogen.sh
    ./configure --prefix=/usr --disable-static
    make -j$(nproc)
}

package() {
    make DESTDIR=$ROOT install
}

