#!/bin/sh
NAME="libaio"
RELEASE="1"
VERSION="0.3.113"
SOURCES="https://pagure.io/libaio/archive/libaio-$VERSION/libaio-$VERSION.tar.gz"
SHA256SUM="1c561c20670c5c09cc8437a622008c0693c6a7816c1f30332da3796953b2f454  libaio-0.3.113.tar.gz"
DESCRIPTION="Asynchronous I/O library"

build() {
    make -j$(nproc)
}

install() {
    make install
}
