#!/bin/sh
NAME="linux"
RELEASE="4"
VERSION="6.4"
SOURCES="https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-$VERSION.tar.xz;https://github.com/projg2/fedora-kernel-config-for-gentoo/raw/6.3.1-gentoo/kernel-x86_64-fedora.config;https://github.com/kreatolinux/kpkg-repo/raw/master/linux/settings.config"
SHA256SUM="8fa0588f0c2ceca44cac77a0e39ba48c9f00a6b9dc69761c02a5d3efac8da7f3  linux-6.4.tar.xz;eb895fb6e72c78c5df522e44e14bf48fe1a462ee7a8100518dfc1d36566c26e3  kernel-x86_64-fedora.config;39856275c2fb6930fd5f48a607a9e18f297833a37dd1a2db757dc95f01975266  settings.config"
DESCRIPTION="The Linux kernel"

prepare() {
	tar -xvf linux-$VERSION.tar.xz
	cd linux-$VERSION
	./scripts/kconfig/merge_config.sh -m ../kernel-x86_64-fedora.config ../settings.config || exit 1 
	make olddefconfig
}

build() {
     cd linux-$VERSION
     make -j$(nproc) || exit 1
}

install() {
    cd linux-$VERSION
    export INSTALL_MOD_PATH=$DESTDIR
    export INSTALL_PATH=$DESTDIR/boot
    mkdir -p "$INSTALL_PATH"
    make install
    make modules_install
}
