#!/bin/sh
NAME="linux"
RELEASE="4"
VERSION="6.4.7"
SOURCES="https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-$VERSION.tar.xz;https://github.com/projg2/fedora-kernel-config-for-gentoo/raw/6.3.7-gentoo/kernel-x86_64-fedora.config;https://github.com/kreatolinux/kpkg-repo/raw/master/linux/settings.config"
SHA256SUM="de143cb61dcaa756c05f56ff35144316d810615819518a33e34754f064c4a7d8  linux-6.4.7.tar.xz;b9726d36fb1243b96c1519f6b29b344621e43bf969ceccc8ced38f2532ac5217  kernel-x86_64-fedora.config;39856275c2fb6930fd5f48a607a9e18f297833a37dd1a2db757dc95f01975266  settings.config"
DESCRIPTION="The Linux kernel"

prepare() {
	tar -xvf linux-$VERSION.tar.xz
	cd linux-$VERSION
	./scripts/kconfig/merge_config.sh -m ../kernel-x86_64-fedora.config ../settings.config || exit 1 
	make olddefconfig
}

build() {
     cd linux-$VERSION
     make -j$(nproc) || exit 1
}

install() {
    cd linux-$VERSION
    export INSTALL_MOD_PATH=$DESTDIR
    export INSTALL_PATH=$DESTDIR/boot
    mkdir -p "$INSTALL_PATH"
    make install
    make modules_install
}
