#!/bin/sh
NAME="cmake"
VERSION="3.25.1"
RELEASE="1"
SOURCES="https://cmake.org/files/v3.25/cmake-$VERSION.tar.gz"
SHA256SUM="1c511d09516af493694ed9baf13c55947a36389674d657a2d5e0ccedc6b291d8  cmake-3.25.1.tar.gz"
DESCRIPTION="CMake package contains a modern toolset used for generating Makefiles."

build() {
    tar -xf cmake-$VERSION.tar.gz
    cd cmake-$VERSION
    sed -i '/"lib64"/s/64//' Modules/GNUInstallDirs.cmake
    ./bootstrap --prefix=/usr        \
                --system-libs        \
                --mandir=/share/man  \
                --no-system-jsoncpp  \
                --no-system-librhash \
                --docdir=/share/doc/cmake-$VERSION
    make -j$(nproc)
    make DESTDIR=$ROOT install
}

