#!/bin/sh
NAME="cmake"
VERSION="3.23"
SOURCES="https://cmake.org/files/v$VERSION/cmake-$VERSION.0.tar.gz"
SHA256SUM="5ab0a12f702f44013be7e19534cd9094d65cc9fe7b2cd0f8c9e5318e0fe4ac82  cmake-3.23.0.tar.gz"
DESCRIPTION="CMake package contains a modern toolset used for generating Makefiles."

build() {
    tar -xf cmake-$VERSION.0.tar.gz
    cd cmake-$VERSION.0
    sed -i '/"lib64"/s/64//' Modules/GNUInstallDirs.cmake
    ./bootstrap --prefix=/usr        \
                --system-libs        \
                --mandir=/share/man  \
                --no-system-jsoncpp  \
                --no-system-librhash \
                --docdir=/share/doc/cmake-$VERSION.0
    make -j$(nproc)
    make DESTDIR=$ROOT install
}

