#!/bin/sh
NAME="mesa"
RELEASE="3"
VERSION="25.2.7"
SOURCES="https://archive.mesa3d.org/mesa-$VERSION.tar.xz"
DEPENDS="libelf libxxf86vm libglvnd eudev llvm flex libxshmfence libxdamage"
BUILD_DEPENDS="libdrm libx11 libxrandr meson libelf python-mako wayland-protocols wayland"
SHA256SUM="b40232a642011820211aab5a9cdf754e106b0bce15044bc4496b0ac9615892ad"
DESCRIPTION="The 3D Graphics Library"
build() {
    meson \
      --buildtype=release     \
      --prefix=/usr           \
      -Dplatforms=wayland,x11 \
      -Dgallium-drivers=auto  \
      -Dvulkan-drivers=""     \
      -Degl=enabled           \
      -Dgles1=disabled        \
      -Dglvnd=true            \
      -Dgles2=enabled         \
      -Dglx=dri               \
      -Dvalgrind=disabled     \
      -Dlibunwind=disabled    \
      build/
    ninja -C build/
}

package() {
    DESTDIR=$ROOT ninja -C build/ install
}
