#!/bin/sh
NAME="mesa"
RELEASE="2"
VERSION="23.1.5"
SOURCES="https://archive.mesa3d.org/mesa-$VERSION.tar.xz"
DEPENDS="libelf libxxf86vm libglvnd libudev llvm flex libxshmfence libxdamage"
BUILD_DEPENDS="libdrm libx11 libxrandr meson libelf python-mako wayland-protocols wayland"
SHA256SUM="3cf88576fdebf24fc4047067936131c90cb6541c27365996b79b661dec1fb153  mesa-23.1.5.tar.xz"
DESCRIPTION="The 3D Graphics Library"
build() {
    meson \
      --buildtype=release     \
      --prefix=/usr           \
      -Dplatforms=wayland,x11 \
      -Dgallium-drivers=auto  \
      -Dvulkan-drivers=""     \
      -Degl=enabled           \
      -Dgles1=disabled        \
      -Dglvnd=true            \
      -Dgles2=enabled         \
      -Dglx=dri               \
      -Dvalgrind=disabled     \
      -Dlibunwind=disabled    \
      build/
    ninja -C build/
}

package() {
    DESTDIR=$ROOT ninja -C build/ install
}
