#!/bin/sh
NAME="mesa"
RELEASE="1"
VERSION="22.3.2"
SOURCES="https://archive.mesa3d.org/mesa-$VERSION.tar.xz"
SHA256SUM="c15df758a8795f53e57f2a228eb4593c22b16dffd9b38f83901f76cd9533140b  mesa-22.3.2.tar.xz"
DESCRIPTION="The 3D Graphics Library"
build() {
    cd mesa-$VERSION || exit  1
    export PYTHONPATH=$(realpath /usr/lib/python*/site-packages):$(python -c "import sys; print(':'.join(sys.path))")
    meson --buildtype=release  --prefix=/usr   \
      -Dplatforms=wayland \
      -Dgallium-drivers=auto  \
      -Dvulkan-drivers=""     \
      -Dglx=disabled          \
      -Dvalgrind=disabled     \
      -Dlibunwind=disabled    \
      build/
    ninja -C build/
    DESTDIR=$ROOT ninja -C build/ install
}
