#!/bin/sh
NAME="libbytesize"
RELEASE="1"
VERSION="2.11"
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/storaged-project/libbytesize/releases/download/$VERSION/libbytesize-$VERSION.tar.gz"
DEPENDS="python"
SHA256SUM="1f6ce157750ed1201ce83edd3c23d997a615c7da30f9a0e5bb44635f66768d81"
DESCRIPTION="libbytesize"

build() {
    kpkgConfigure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
