#!/bin/sh
NAME="libtirpc"
RELEASE="1"
VERSION="1.3.6"
BUILD_DEPENDS="gmake"
SOURCES="https://netix.dl.sourceforge.net/project/libtirpc/libtirpc/$VERSION/libtirpc-$VERSION.tar.bz2"
SHA256SUM="bbd26a8f0df5690a62a47f6aa30f797f3ef8d02560d1bc449a83066b5a1d3508"
DESCRIPTION="libtirpc"
build() {
    kpkgConfigure --prefix=/usr                   \
                --disable-gssapi \
                --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
