#!/bin/sh
NAME="libtirpc"
RELEASE="1"
VERSION="1.3.7"
BUILD_DEPENDS="gmake"
SOURCES="https://netix.dl.sourceforge.net/project/libtirpc/libtirpc/$VERSION/libtirpc-$VERSION.tar.bz2"
SHA256SUM="b47d3ac19d3549e54a05d0019a6c400674da716123858cfdb6d3bdd70a66c702"
DESCRIPTION="libtirpc"
build() {
    kpkgConfigure --prefix=/usr                   \
                --disable-gssapi \
                --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
