#!/bin/sh
NAME="libtirpc"
RELEASE="1"
VERSION="1.3.3"
SOURCES="https://netix.dl.sourceforge.net/project/libtirpc/libtirpc/$VERSION/libtirpc-$VERSION.tar.bz2"
SHA256SUM="6474e98851d9f6f33871957ddee9714fdcd9d8a5ee9abb5a98d63ea2e60e12f3  libtirpc-1.3.3.tar.bz2"
DESCRIPTION="libtirpc"
build() {
    ./configure --prefix=/usr                   \
                --disable-gssapi \
                --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
