#!/bin/sh
NAME="fish"
RELEASE="1"
VERSION="4.0.2"
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/fish-shell/fish-shell/releases/download/$VERSION/fish-$VERSION.tar.xz"
DEPENDS="cmake ncurses pcre gettext"
SHA256SUM="614c9f5643cd0799df391395fa6bbc3649427bb839722ce3b114d3bbc1a3b250"
DESCRIPTION="The user-friendly command line shell."

build() {
	cmake -S . -B build \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_SYSCONFDIR=/etc \
		-DCMAKE_BUILD_TYPE=Release \
		-DBUILD_DOCS=False \
		-Wno-dev
	cmake --build build
}

package() {
	cmake --install build
}

postinstall() {
    grep -q "/bin/fish" /etc/shells || echo "/bin/fish" >> /etc/shells
    grep -q "/usr/bin/fish" /etc/shells || echo "/usr/bin/fish" >> /etc/shells
}

postremove() {
    grep -q "/usr/bin/fish" /etc/shells && sed -i "s#/usr/bin/fish##g" /etc/shells
    grep -q "/bin/fish" /etc/shells && sed -i "s#/bin/fish##g" /etc/shells
    sed -i '/^[[:space:]]*$/d' /etc/shells 
}

