#!/bin/sh
NAME="fish"
RELEASE="1"
VERSION="3.6.1"
SOURCES="https://github.com/fish-shell/fish-shell/releases/download/$VERSION/fish-$VERSION.tar.xz"
DEPENDS="cmake ncurses pcre gettext"
SHA256SUM="55402bb47ca6739d8aba25e41780905b5ce1bce0a5e0dd17dca908b5bc0b49b2"
DESCRIPTION="The user-friendly command line shell."

build() {
    export CXXFLAGS="-ltinfow $CXXFLAGS"
	cmake -S . -B build \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_SYSCONFDIR=/etc \
		-DCMAKE_BUILD_TYPE=Release \
		-DBUILD_DOCS=False \
		-Wno-dev
	cmake --build build
}

package() {
	cmake --install build
}

postinstall() {
    grep -q "/bin/fish" /etc/shells || echo "/bin/fish" >> /etc/shells
    grep -q "/usr/bin/fish" /etc/shells || echo "/usr/bin/fish" >> /etc/shells
}

postremove() {
    grep -q "/usr/bin/fish" /etc/shells && sed -i "s#/usr/bin/fish##g" /etc/shells
    grep -q "/bin/fish" /etc/shells && sed -i "s#/bin/fish##g" /etc/shells
    sed -i '/^[[:space:]]*$/d' /etc/shells 
}

