#!/bin/sh
NAME="fish"
RELEASE="1"
VERSION="3.6.1"
SOURCES="https://github.com/fish-shell/fish-shell/releases/download/$VERSION/fish-$VERSION.tar.xz"
SHA256SUM="55402bb47ca6739d8aba25e41780905b5ce1bce0a5e0dd17dca908b5bc0b49b2  fish-3.6.1.tar.xz"
DESCRIPTION="The user-friendly command line shell."

build() {
	cmake -S . -B build \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_SYSCONFDIR=/etc \
		-DCMAKE_BUILD_TYPE=Release \
		-DBUILD_DOCS=False \
		-Wno-dev
	cmake --build build
}

install() {
	cmake --install build
}
