#!/bin/sh
NAME="libwpe"
RELEASE="1"
VERSION="1.16.0"
SOURCES="https://wpewebkit.org/releases/libwpe-$VERSION.tar.xz"
BUILD_DEPENDS="meson"
DEPENDS="libxkbcommon mesa"
SHA256SUM="c7f3a3c6b3d006790d486dc7cceda2b6d2e329de07f33bc47dfc53f00f334b2a"
DESCRIPTION="libwpe"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
