#!/bin/sh
NAME="gdm"
RELEASE="1"
VERSION="45.0.1"
SOURCES="https://gitlab.gnome.org/GNOME/gdm/-/archive/$VERSION/gdm-$VERSION.tar.gz"
DEPENDS="accountsservice dconf dbus libcanberra linux-pam gnome-session elogind"
BUILD_DEPENDS="meson"
SHA256SUM="4b160687d6de338e880d065df52909f37a70710ea4dbf321e65a2e9251d8dfb2"
DESCRIPTION="GNOME Display Manager"

build() {
    
    # Thanks to BLFS
    if ! command -v systemctl > /dev/null; then
      extraArgs="-Dsystemd-journal=false -Dsystemdsystemunitdir=/tmp -Dsystemduserunitdir=/tmp"
      sed -i -r '/(^| )systemd_dep/d' meson.build
      sed -e 's@systemd@elogind@'                                \
          -e '/elogind/isession  required       pam_loginuid.so' \
          -i data/pam-lfs/gdm-launch-environment.pam
    fi

    meson setup $extraArgs      \
    --prefix=/usr               \
    --buildtype=release         \
    -Dgdm-xsession=true         \
    -Drun-dir=/run/gdm          \
    -Ddefault-pam-config=lfs    \
    -Ddbus-sys="/usr/share/dbus-1/system.d" \
    -Ddefault-path="/usr/bin:/usr/local/bin:/usr/local/sbin:/bin" \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}

postinstall() {
  # from blfs
  groupadd -g 21 gdm
  useradd -c "GDM Daemon Owner" -d /var/lib/gdm -u 21 \
          -g gdm -s /bin/false gdm
  passwd -ql gdm
}
