#!/bin/sh
NAME="lame"
RELEASE="1"
VERSION="3.100"
SOURCES="https://netix.dl.sourceforge.net/project/lame/lame/$VERSION/lame-$VERSION.tar.gz"
DEPENDS="ncurses"
BUILD_DEPENDS="nasm"
SHA256SUM="ddfe36cab873794038ae2c1210557ad34857a4b6bdc515785d1da9e175b1da1e"
DESCRIPTION="A MP3 encoder"

build() {
    kpkgConfigure --prefix=/usr \
                --enable-shared \
                --enable-mp3rtp
    make
}

package() {
    make DESTDIR=$ROOT install
}
