#!/bin/sh
NAME="bash"
RELEASE="1"
VERSION="5.3.3"
SOURCES="https://ftp.gnu.org/gnu/bash/bash-$VERSION.tar.gz"
DEPENDS="ncurses"
BUILD_DEPENDS="gmake"
SHA256SUM="13720965b5f4fc3a0d4b61dd37e7565c741da9a5be24edc2ae00182fc1b3588c"
DESCRIPTION="The GNU bash shell"

build() {
    kpkgConfigure --prefix=/usr                 \
                --build=$(support/config.guess) \
                --without-bash-malloc
    make
}

package() {
    make DESTDIR=$ROOT install
    rm -rf "$ROOT/usr/share/info/dir"
}

postinstall() {
    grep -q "/bin/bash" /etc/shells || echo "/bin/bash" >> /etc/shells
    grep -q "/usr/bin/bash" /etc/shells || echo "/usr/bin/bash" >> /etc/shells
    grep -q "/bin/sh" /etc/shells || echo "/bin/sh" >> /etc/shells
    grep -q "/usr/bin/sh" /etc/shells || echo "/usr/bin/sh" >> /etc/shells
}

postremove() {
    grep -q "/usr/bin/bash" /etc/shells && sed -i "s#/usr/bin/bash##g" /etc/shells
    grep -q "/bin/bash" /etc/shells && sed -i "s#/bin/bash##g" /etc/shells
    grep -q "/usr/bin/sh" /etc/shells && sed -i "s#/usr/bin/sh##g" /etc/shells
    grep -q "/bin/sh" /etc/shells && sed -i "s#/bin/sh##g" /etc/shells
    sed -i '/^[[:space:]]*$/d' /etc/shells 
}
