#!/bin/sh
NAME="librsvg"
RELEASE="1"
VERSION="2.58.1"
SOURCES="https://gitlab.gnome.org/GNOME/librsvg/-/archive/$VERSION/librsvg-$VERSION.tar.gz"
DEPENDS="cairo freetype gdk-pixbuf glib harfbuzz libxml2 pango"
BUILD_DEPENDS="rust vala gobject-introspection gmake"
SHA256SUM="723cd48a5c98ca3b88dcf436f4e56991d21df159900f8ae7ac31cbfa2f7dccdc"
DESCRIPTION="SVG rendering library"

build() {
    ./autogen.sh \
      --prefix=/usr \
      --disable-static \
      --enable-vala
    make
}

package() {
    make DESTDIR=$ROOT install
}

postinstall() {
  gdk-pixbuf-query-loaders --update-cache
}
