#!/bin/sh
NAME="xdg-dbus-proxy"
RELEASE="1"
VERSION="0.1.6"
SOURCES="https://github.com/flatpak/xdg-dbus-proxy/releases/download/$VERSION/xdg-dbus-proxy-$VERSION.tar.xz"
BUILD_DEPENDS="meson"
DEPENDS="glib"
SHA256SUM="131bf59fce7c7ee7ecbc5d9106d6750f4f597bfe609966573240f7e4952973a1"
DESCRIPTION="xdg-dbus-proxy"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Dman=disabled \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
