#!/bin/sh
NAME="rest"
RELEASE="1"
VERSION="0.9.1"
SOURCES="https://download.gnome.org/sources/rest/0.9/rest-$VERSION.tar.xz"
BUILD_DEPENDS="meson"
DEPENDS="gobject-introspection json-glib libsoup make-ca"
SHA256SUM="9266a5c10ece383e193dfb7ffb07b509cc1f51521ab8dad76af96ed14212c2e3"
DESCRIPTION="rest"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Dgtk_doc=false	\
    -Dexamples=false	\
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
