#!/bin/sh
NAME="libadwaita"
RELEASE="1"
VERSION="1.4.2"
SOURCES="https://gitlab.gnome.org/GNOME/libadwaita/-/archive/$VERSION/libadwaita-$VERSION.tar.gz"
DEPENDS="gtk4"
BUILD_DEPENDS="meson vala sassc"
SHA256SUM="47ce895ce87c0a66a1e700b6d778520c14339cfc88af7bd30f6b401d782214f1"
DESCRIPTION="GNOME ui stuff"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Dgtk_doc=false \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
