#!/bin/sh
NAME="libadwaita"
RELEASE="1"
VERSION="1.8.2"
SOURCES="https://gitlab.gnome.org/GNOME/libadwaita/-/archive/$VERSION/libadwaita-$VERSION.tar.gz"
DEPENDS="gtk4"
BUILD_DEPENDS="meson vala sassc"
SHA256SUM="4d1c92c1a955c9947c5788773733523ae927b742191ea5f881ad358188391771"
DESCRIPTION="GNOME ui stuff"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Dgtk_doc=false \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
