#!/bin/sh
NAME="libadwaita"
RELEASE="1"
VERSION="1.8.2"
SOURCES="https://gitlab.gnome.org/GNOME/libadwaita/-/archive/$VERSION/libadwaita-$VERSION.tar.gz"
DEPENDS="gtk4"
BUILD_DEPENDS="meson vala sassc"
SHA256SUM="be965cecb7b61380bc139c2df09d6176701015881326deb036f1d602a4fe0061"
DESCRIPTION="GNOME ui stuff"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Dgtk_doc=false \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
