#!/bin/sh
NAME="vulkan-headers"
RELEASE="1"
VERSION="1.3.286"
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/KhronosGroup/Vulkan-Headers/archive/refs/tags/v$VERSION.tar.gz"
DEPENDS="cmake ninja"
SHA256SUM="a82a6982efe5e603e23505ca19b469e8f3d876fc677c46b7bfb6177f517bf8fe"
DESCRIPTION="Vulkan headers"

build() {
    cmake -B build \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -G Ninja
    ninja -C build -j$(nproc)
}

package() {    
    DESTDIR="$ROOT" ninja -C build install
}


