#!/bin/sh
NAME="vulkan-headers"
RELEASE="1"
VERSION="1.3.300"
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/KhronosGroup/Vulkan-Headers/archive/refs/tags/v$VERSION.tar.gz"
DEPENDS="cmake ninja"
SHA256SUM="9a0542fb2233e39179fcc9aba8b0dd9deee4a19a2d7adb89449144b2e3d80e93"
DESCRIPTION="Vulkan headers"

build() {
    cmake -B build \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -G Ninja
    ninja -C build -j$(nproc)
}

package() {    
    DESTDIR="$ROOT" ninja -C build install
}


