#!/bin/sh
NAME="vulkan-headers"
RELEASE="1"
VERSION="1.3.288"
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/KhronosGroup/Vulkan-Headers/archive/refs/tags/v$VERSION.tar.gz"
DEPENDS="cmake ninja"
SHA256SUM="6f21dd9efe65fb7aeba6beaef2d274a0a31d32b4f494637b0d1a49853cf20ca6"
DESCRIPTION="Vulkan headers"

build() {
    cmake -B build \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -G Ninja
    ninja -C build -j$(nproc)
}

package() {    
    DESTDIR="$ROOT" ninja -C build install
}


