#!/bin/sh
NAME="fuse"
RELEASE="1"
VERSION="3.13.1"
SOURCES="https://github.com/libfuse/libfuse/releases/download/fuse-$VERSION/fuse-$VERSION.tar.xz"
SHA256SUM="6cd0759944c9aeb3d078b24a97b8a5cd5d49a0b8b7f15f85f32ac0c8a662fb6e  fuse-3.13.1.tar.xz"
DESCRIPTION="Filesystem in Userspace"
build() {
    meson --prefix=/usr build/
    ninja -C build/
}

install() {
    DESTDIR=$ROOT ninja -C build/ install
}
