#!/bin/sh
NAME="udisks"
RELEASE="1"
VERSION="2.10.0"
SOURCES="https://github.com/storaged-project/udisks/releases/download/udisks-$VERSION/udisks-$VERSION.tar.bz2"
DEPENDS="libatasmart libblockdev elogind libgudev libxslt polkit"
BUILD_DEPENDS="gobject-introspection"
SHA256SUM="4f5a7a592526f7f32795a1f2211c67b9a649ab40386752f9a71ebaa2fc2090bc  udisks-2.10.0.tar.bz2"
DESCRIPTION="udisks"

build() {
    # from BLFS
    ./configure --prefix=/usr  \
            --sysconfdir=/etc  \
            --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
