#!/bin/sh
NAME="libxrender"
RELEASE="1"
VERSION="0.9.12"
SOURCES="https://www.x.org/releases/individual/lib/libXrender-$VERSION.tar.xz"
SHA256SUM="b832128da48b39c8d608224481743403ad1691bf4e554e4be9c174df171d1b97"
DEPENDS="libx11"
BUILD_DEPENDS="xorgproto gmake"
DESCRIPTION="libxrender"

build() {
    kpkgConfigure \
        --prefix=/usr \
        --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
