#!/bin/sh
NAME="libseccomp"
RELEASE="1"
VERSION="2.6.0"
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/seccomp/libseccomp/releases/download/v$VERSION/libseccomp-$VERSION.tar.gz"
DEPENDS="gperf"
SHA256SUM="83b6085232d1588c379dc9b9cae47bb37407cf262e6e74993c61ba72d2a784dc"
DESCRIPTION="An easy to use, platform independent, interface to the Linux Kernel's syscall filtering mechanism"

build() {
    kpkgConfigure --prefix=/usr
    make -j$(nproc)
}

package() {
    make install
}
