#!/bin/sh
NAME="libseccomp"
RELEASE="1"
VERSION="2.5.4"
SOURCES="https://github.com/seccomp/libseccomp/releases/download/v$VERSION/libseccomp-$VERSION.tar.gz"
SHA256SUM="d82902400405cf0068574ef3dc1fe5f5926207543ba1ae6f8e7a1576351dcbdb  libseccomp-2.5.4.tar.gz"
DESCRIPTION="An easy to use, platform independent, interface to the Linux Kernel's syscall filtering mechanism"

build() {
    ./configure --prefix=/usr
    make -j$(nproc)
}

install() {
    make install
}
