#!/bin/sh
NAME="libvpx"
RELEASE="1"
VERSION="1.14.1"
SOURCES="https://github.com/webmproject/libvpx/archive/v$VERSION/libvpx-$VERSION.tar.gz"
BUILD_DEPENDS="nasm diffutils gmake"
SHA256SUM="901747254d80a7937c933d03bd7c5d41e8e6c883e0665fadcb172542167c7977"
DESCRIPTION="Reference implementation of the VP8 Codec"

build() {
    kpkgConfigure --prefix=/usr                   \
                --disable-static                \
                --enable-shared
    make
}

package() {
    make DESTDIR=$ROOT install
}
