#!/bin/sh
NAME="libvpx"
RELEASE="1"
VERSION="1.15.2"
SOURCES="https://github.com/webmproject/libvpx/archive/v$VERSION/libvpx-$VERSION.tar.gz"
BUILD_DEPENDS="nasm diffutils gmake"
SHA256SUM="e935eded7d81631a538bfae703fd1e293aad1c7fd3407ba00440c95105d2011e"
DESCRIPTION="Reference implementation of the VP8 Codec"

build() {
    kpkgConfigure --prefix=/usr                   \
                --disable-static                \
                --enable-shared
    make
}

package() {
    make DESTDIR=$ROOT install
}
