#!/bin/sh
NAME="libvpx"
RELEASE="1"
VERSION="1.13.0"
SOURCES="https://github.com/webmproject/libvpx/archive/v$VERSION/libvpx-$VERSION.tar.gz"
BUILD_DEPENDS="nasm"
SHA256SUM="cb2a393c9c1fae7aba76b950bb0ad393ba105409fe1a147ccd61b0aaa1501066"
DESCRIPTION="Reference implementation of the VP8 Codec"

build() {
    ./configure --prefix=/usr                   \
                --disable-static                \
                --enable-shared                 \
    make
}

package() {
    make DESTDIR=$ROOT install
}
