#!/bin/sh
NAME="js115"
RELEASE="1"
NO_CHKUPD="true"
VERSION="115.6.0"
SOURCES="https://archive.mozilla.org/pub/firefox/releases/$VERSIONesr/source/firefox-$VERSIONesr.source.tar.xz patches/D190288.1705253813.diff"
DEPENDS="readline zlib icu"
BUILD_DEPENDS="rust python llvm which"
SHA256SUM="66d7e6e5129ac8e6fe83e24227dc7bb8dc42650bc53b21838e614de80d22bc66 6b2ceafcc2b64f52e8e38449ab95fd3970493d4e00ffe377f22287ca1f7e6759"
DESCRIPTION="Spidermonkey JavaScript and WebAssembly Engine"

prepare() {
  bsdtar -xf firefox-"$VERSION"esr.source.tar.xz
  cd firefox-$VERSION
  patch -p1 < ../D190288.1705253813.diff
}

build() {
  # Thanks to BLFS for configure arguments: https://www.linuxfromscratch.org/blfs/view/svn/general/js102.html
  mkdir firefox-$VERSION/obj
  cd firefox-$VERSION/obj
  # Add CC=clang so it overrides the cc set by the user in the configuration file as it may cause problems.
  CC=clang CXX=clang++ sh ../js/src/configure \
                          --prefix=/usr \
                          --with-intl-api          \
                          --with-system-zlib       \
                          --with-system-icu        \
                          --disable-jemalloc       \
                          --disable-debug-symbols  \
                          --enable-readline
  make -j$(nproc)
}

package() {
  cd firefox-$VERSION/obj
  make install
}
