#!/bin/sh                                                                      
NAME="openssh"
RELEASE="1"
VERSION="9.4p1"
SOURCES="https://ftp.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-$VERSION.tar.gz"
DEPENDS="shadow"
SHA256SUM="3608fd9088db2163ceb3e600c85ab79d0de3d221e59192ea1923e23263866a85  openssh-9.4p1.tar.gz"
DESCRIPTION="ssh tools"                                                        
build() {                                                                      
    ./configure --prefix=/usr                                                  
    make                                                                       
}

package() {
    make DESTDIR="$ROOT" install                                                               
}
