#!/bin/sh                                                                      
NAME="openssh"
RELEASE="2"
VERSION="9.5p1"
SOURCES="https://ftp.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-$VERSION.tar.gz"
DEPENDS="shadow zlib"
SHA256SUM="f026e7b79ba7fb540f75182af96dc8a8f1db395f922bbc9f6ca603672686086b"
DESCRIPTION="ssh tools"                                                        
build() {                                                                      
    kpkgConfigure --without-zlib-version-check --prefix=/usr                                                  
    make                                                                       
}

package() {
    make DESTDIR="$ROOT" install                                                               
}
