#!/bin/sh                                                                      
NAME="openssh"
RELEASE="2"
VERSION="9.6p1"
SOURCES="https://ftp.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-$VERSION.tar.gz"
DEPENDS="shadow zlib"
SHA256SUM="910211c07255a8c5ad654391b40ee59800710dd8119dd5362de09385aa7a777c"
DESCRIPTION="ssh tools"                                                        
build() {                                                                      
    kpkgConfigure --without-zlib-version-check --prefix=/usr                                                  
    make                                                                       
}

package() {
    make DESTDIR="$ROOT" install                                                               
}
