#!/bin/sh
NAME="kmod"
RELEASE="1"
VERSION="30"
SOURCES="https://www.kernel.org/pub/linux/utils/kernel/kmod/kmod-$VERSION.tar.xz"
DESCRIPTION="Contains utilities for loading kernel modules"
build() {
    [ ! -d "kmod-$VERSION" ] && tar -xvf kmod-$VERSION.tar.xz
    cd kmod-$VERSION || exit  1
    ./configure --prefix=/usr
    make
    make DESTDIR=$ROOT install
    ln -s /usr/bin/kmod $ROOT/usr/bin/depmod
}
