#!/bin/sh
NAME="kmod"
RELEASE="3"
VERSION="34.2"
SOURCES="https://www.kernel.org/pub/linux/utils/kernel/kmod/kmod-$VERSION.tar.xz"
DEPENDS="zlib"
BUILD_DEPENDS="pkgconf gmake"
SHA256SUM="5a5d5073070cc7e0c7a7a3c6ec2a0e1780850c8b47b3e3892226b93ffcb9cb54"
DESCRIPTION="Contains utilities for loading kernel modules"

build() {
    kpkgConfigure --with-zlib --prefix=/usr --disable-manpages
    make
}

package() {
    make DESTDIR=$ROOT install
    [ -f "$ROOT/usr/bin/depmod" ] || ln -s /usr/bin/kmod $ROOT/usr/bin/depmod
    [ -f "$ROOT/usr/bin/rmmod" ] || ln -s /usr/bin/kmod $ROOT/usr/bin/rmmod
    [ -f "$ROOT/usr/bin/lsmod" ] || ln -s /usr/bin/kmod $ROOT/usr/bin/lsmod
    [ -f "$ROOT/usr/bin/insmod" ] || ln -s /usr/bin/kmod $ROOT/usr/bin/insmod
    [ -f "$ROOT/usr/bin/modprobe" ] || ln -s /usr/bin/kmod $ROOT/usr/bin/modprobe
}
