#!/bin/sh
NAME="kmod"
RELEASE="3"
VERSION="31"
SOURCES="https://www.kernel.org/pub/linux/utils/kernel/kmod/kmod-$VERSION.tar.xz"
DEPENDS="zlib"
BUILD_DEPENDS="pkgconf gmake"
SHA256SUM="f5a6949043cc72c001b728d8c218609c5a15f3c33d75614b78c79418fcf00d80"
DESCRIPTION="Contains utilities for loading kernel modules"

build() {
    kpkgConfigure --with-zlib --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
    [ -f "$ROOT/usr/bin/depmod" ] || ln -s /usr/bin/kmod $ROOT/usr/bin/depmod
    [ -f "$ROOT/usr/bin/rmmod" ] || ln -s /usr/bin/kmod $ROOT/usr/bin/rmmod
    [ -f "$ROOT/usr/bin/lsmod" ] || ln -s /usr/bin/kmod $ROOT/usr/bin/lsmod
    [ -f "$ROOT/usr/bin/insmod" ] || ln -s /usr/bin/kmod $ROOT/usr/bin/insmod
    [ -f "$ROOT/usr/bin/modprobe" ] || ln -s /usr/bin/kmod $ROOT/usr/bin/modprobe
}
