#!/bin/sh
NAME="nautilus"
RELEASE="1"
VERSION="49.2"
SOURCES="https://gitlab.gnome.org/GNOME/nautilus/-/archive/$VERSION/nautilus-$VERSION.tar.gz"
DEPENDS="bubblewrap dconf libgexiv2 gdk-pixbuf gnome-autoar gnome-desktop gst-plugins-base libnotify libadwaita libportal libseccomp tracker3 desktop-file-utils adwaita-icon-theme"
BUILD_DEPENDS="meson vala gobject-introspection"
SHA256SUM="c3cf323dbb2ae5b638a4548d44b5886601a9b05fcf933f66636953b4503091d8"
DESCRIPTION="File manager of GNOME"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Dcloudproviders=false \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}

postinstall() {
  glib-compile-schemas /usr/share/glib-2.0/schemas
}
