#!/bin/sh
NAME="foot"
RELEASE="1"
VERSION="1.15.0"
SOURCES="https://codeberg.org/dnkl/foot/archive/1.15.0.tar.gz"
SHA256SUM="5b6fcec57cedca350c36fa46534bd7724ed414cc292516b74567d070b7062f07  1.15.0.tar.gz"
DESCRIPTION="A fast, lightweight and minimalistic Wayland terminal emulator"
build() {
    meson --prefix=/usr build/
    ninja -C build/
}

install() {
    git config --global --add safe.directory /tmp/kpkg/srcdir/foot/subprojects/fcft
    DESTDIR=$ROOT ninja -C build/ install
}
