#!/bin/sh
NAME="foot"
RELEASE="1"
VERSION="1.18.0"
SOURCES="https://codeberg.org/dnkl/foot/archive/1.18.0.tar.gz"
BUILD_DEPENDS="meson"
DEPENDS="wayland-protocols wayland fontconfig libxkbcommon pixman freetype"
SHA256SUM="9d9f0efe4bca0bbf201482d6e7bb946a12a4b164d2e73dae75a2f2404e1e85ff"
DESCRIPTION="A fast, lightweight and minimalistic Wayland terminal emulator"
build() {
    meson --prefix=/usr build/
    ninja -C build/
}

package() {
    git config --global --add safe.directory /tmp/kpkg/srcdir/foot/subprojects/fcft
    DESTDIR=$ROOT ninja -C build/ install
}
