#!/bin/sh
NAME="foot"
RELEASE="1"
VERSION="1.25.0"
SOURCES="https://codeberg.org/dnkl/foot/archive/$VERSION.tar.gz"
BUILD_DEPENDS="meson"
DEPENDS="wayland-protocols wayland fontconfig libxkbcommon pixman freetype"
SHA256SUM="442a42d576ec72dd50f2d3faea8a664230a47bac79dc1eb6e7c9125ee76c130f"
DESCRIPTION="A fast, lightweight and minimalistic Wayland terminal emulator"
build() {
    export CFLAGS="${CFLAGS} -Wno-error=deprecated-declarations"
    meson --prefix=/usr build/
    ninja -C build/
}

package() {
    git config --global --add safe.directory /tmp/kpkg/srcdir/foot/subprojects/fcft
    DESTDIR=$ROOT ninja -C build/ install
}
