#!/bin/sh
NAME="yaml"
RELEASE="1"
VERSION="0.2.5"
SOURCES="https://pyyaml.org/download/libyaml/yaml-$VERSION.tar.gz"
SHA256SUM="c642ae9b75fee120b2d96c712538bd2cf283228d2337df2cf2988e3c02678ef4  yaml-0.2.5.tar.gz"
DESCRIPTION="C library for YAML"
build() {
    ./configure --prefix=/usr
    make
}

install() {
    make DESTDIR=$ROOT install
}
