#!/bin/sh
NAME="curl"
RELEASE="1"
VERSION="8.6.0"
SOURCES="https://curl.haxx.se/download/curl-$VERSION.tar.xz"
DEPENDS="nghttp2 zlib nghttp2"
SHA256SUM="3ccd55d91af9516539df80625f818c734dc6f2ecf9bada33c76765e99121db15"
DESCRIPTION="command line tool and library for transferring data with URLs"

build() {
    # Taken from Kiss Linux repo, License here https://github.com/kisslinux/repo/blob/master/LICENSE
    kpkgConfigure \
        --prefix=/usr \
        --disable-manual \
        --disable-ldap \
        --disable-ares \
        --without-librtmp \
        --without-libpsl \
        --without-libidn2 \
        --without-brotli \
        --without-zstd   \
        --with-openssl   \
        --with-nghttp2   \
        --with-ca-path=/etc/ssl/certs

    make
}

package() {
    make DESTDIR=$ROOT install
}
