#!/bin/sh
NAME="curl"
RELEASE="1"
VERSION="8.1.2"
SOURCES="https://curl.haxx.se/download/curl-$VERSION.tar.xz"
SHA256SUM="31b1118eb8bfd43cd95d9a3f146f814ff874f6ed3999b29d94f4d1e7dbac5ef6  curl-8.1.2.tar.xz"
DESCRIPTION=""
build() {
    # Taken from Kiss Linux repo, License here https://github.com/kisslinux/repo/blob/master/LICENSE
    ./configure \
        --prefix=/usr \
        --disable-manual \
        --disable-ldap \
        --disable-ares \
        --without-librtmp \
        --without-libpsl \
        --without-libidn2 \
        --without-brotli \
        --without-zstd   \
        --with-openssl   \
        --with-nghttp2   \
        --with-ca-path=/etc/ssl/certs

    make
}

install() {
    make DESTDIR=$ROOT install
}
