#!/bin/sh
NAME="dash"
RELEASE="1"
VERSION="0.5.13"
SOURCES="https://git.kernel.org/pub/scm/utils/dash/dash.git/snapshot/dash-$VERSION.tar.gz"
BUILD_DEPENDS="autoconf automake gmake"
SHA256SUM="e1dddd60704f68764f453ee43c50248dd97d6d7ebe59182896ff82113550942a"
DESCRIPTION="Small and fast POSIX-compliant shell"
build() {
    autoreconf -v -f -i
    kpkgConfigure --prefix=/usr --bindir=/usr/bin
    make
}

package() {
    make DESTDIR=$ROOT install
}
