#!/bin/sh
NAME="xmlto"
RELEASE="1"
VERSION="0.0.28"
BUILD_DEPENDS="gmake"
SOURCES="https://releases.pagure.org/xmlto/xmlto-$VERSION.tar.gz"
SHA256SUM="2f986b7c9a0e9ac6728147668e776d405465284e13c74d4146c9cbc51fd8aad3"
DEPENDS="libxslt docbook-xml docbook-xsl links"
DESCRIPTION="Convert xml to many other formats"

build() {
    export CFLAGS="$CFLAGS -Wno-implicit-int"
    LINKS="/usr/bin/links" kpkgConfigure
    make
}

package() {
    make DESTDIR=$ROOT install
}
