#!/bin/sh
NAME="xmlto"
RELEASE="1"
VERSION="0.0.29"
BUILD_DEPENDS="gmake"
SOURCES="https://releases.pagure.org/xmlto/xmlto-$VERSION.tar.gz"
SHA256SUM="40504db68718385a4eaa9154a28f59e51e59d006d1aa14f5bc9d6fded1d6017a"
DEPENDS="libxslt docbook-xml docbook-xsl links"
DESCRIPTION="Convert xml to many other formats"

build() {
    export CFLAGS="$CFLAGS -Wno-implicit-int"
    LINKS="/usr/bin/links" kpkgConfigure
    make
}

package() {
    make DESTDIR=$ROOT install
}
