#!/bin/sh
NAME="zlib"
VERSION="1.2.13"
DESCRIPTION="zlib is a software library used for data compression."
SOURCES="https://zlib.net/zlib-$VERSION.tar.gz"
SHA256SUM="b3a24de97a8fdbc835b9833169501030b8977031bcb54b3b3ac13740f846ab30  zlib-1.2.13.tar.gz"

build() {
    tar -xvf zlib-$VERSION.tar.gz
    cd zlib-$VERSION
    ./configure --prefix=/usr
    make
    make DESTDIR=$ROOT install
}
