#!/bin/sh
NAME="zlib"
RELEASE="1"
VERSION="1.3"
DESCRIPTION="zlib is a software library used for data compression."
SOURCES="https://zlib.net/zlib-$VERSION.tar.gz"
DEPENDS=""
SHA256SUM="ff0ba4c292013dbc27530b3a81e1f9a813cd39de01ca5e0f8bf355702efa593e"

build() {
    if [ "$KPKG_ARCH" != "$(uname -m)" ]; then
	export CROSS_PREFIX="$KPKG_TARGET-"
    fi
    ./configure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
