#!/bin/sh
NAME="libudev"
RELEASE="1"
VERSION="1.0.3"
SOURCES="https://github.com/illiliti/libudev-zero/archive/refs/tags/$VERSION.tar.gz"
BUILD_DEPENDS="gmake"
SHA256SUM="0bd89b657d62d019598e6c7ed726ff8fed80e8ba092a83b484d66afb80b77da5"
DESCRIPTION="libudev, without dependencies"

build() {
    make
}

package() {
    make DESTDIR=$ROOT PREFIX=/usr install
}
