#!/bin/sh
NAME="cryptsetup"
RELEASE="1"
VERSION="2.8.1"
BUILD_DEPENDS="gmake"
SOURCES="https://mirrors.edge.kernel.org/pub/linux/utils/cryptsetup/v2.6/cryptsetup-$VERSION.tar.xz"
DEPENDS="json-c lvm2 popt"
SHA256SUM="SKIP"
DESCRIPTION="cryptsetup"

build() {
    kpkgConfigure --disable-asciidoc --prefix=/usr --disable-ssh-token
    make
}

package() {
    make DESTDIR=$ROOT install
}
