#!/bin/sh
NAME="cryptsetup"
RELEASE="1"
VERSION="2.6.1"
SOURCES="https://mirrors.edge.kernel.org/pub/linux/utils/cryptsetup/v2.6/cryptsetup-$VERSION.tar.xz"
DEPENDS="json-c lvm2 popt"
SHA256SUM="410ded65a1072ab9c8e41added37b9729c087fef4d2db02bb4ef529ad6da4693  cryptsetup-2.6.1.tar.xz"
DESCRIPTION="cryptsetup"

build() {
    ./configure --prefix=/usr --disable-ssh-token
    make
}

package() {
    make DESTDIR=$ROOT install
}
