#!/bin/sh
NAME="xdg-desktop-portal"
RELEASE="1"
VERSION="1.18.0"
SOURCES="https://github.com/flatpak/xdg-desktop-portal/releases/download/$VERSION/xdg-desktop-portal-$VERSION.tar.xz"
DEPENDS="glib flatpak bubblewrap geoclue gdk-pixbuf fuse pipewire json-glib"
BUILD_DEPENDS="meson"
OPTDEPENDS="xdg-desktop-portal-gtk: GTK backend ;; xdg-desktop-portal-gnome: GNOME backend ;; xdg-desktop-portal-wlr: wlroots backend"
SHA256SUM="5ea35a6420a98b598c83355fc19feaea8ba999149641bf84079b0c572b00f5bd  xdg-desktop-portal-1.18.0.tar.xz"
DESCRIPTION="A portal frontend service for Flatpak and possibly other desktop containment frameworks"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Ddocbook-docs=disabled \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
