#!/bin/sh
NAME="xdg-desktop-portal"
RELEASE="1"
VERSION="1.20.3"
SOURCES="https://github.com/flatpak/xdg-desktop-portal/releases/download/$VERSION/xdg-desktop-portal-$VERSION.tar.xz"
DEPENDS="glib flatpak bubblewrap geoclue gdk-pixbuf fuse pipewire json-glib"
BUILD_DEPENDS="meson"
OPTDEPENDS="xdg-desktop-portal-gtk: GTK backend ;; xdg-desktop-portal-gnome: GNOME backend ;; xdg-desktop-portal-wlr: wlroots backend"
SHA256SUM="dfac239c5476aafd117a9a10131a2f0b142f72106c52fc03859938e00545f440"
DESCRIPTION="A portal frontend service for Flatpak and possibly other desktop containment frameworks"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Ddocbook-docs=disabled \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
