#!/bin/sh
NAME="dmidecode"
RELEASE="1"
VERSION="3.6"
BUILD_DEPENDS="gmake"
SOURCES="https://download.savannah.gnu.org/releases/dmidecode/dmidecode-$VERSION.tar.xz"
SHA256SUM="e40c65f3ec3dafe31ad8349a4ef1a97122d38f65004ed66575e1a8d575dd8bae"
DESCRIPTION="Desktop Management Interface table related utilities"

build() {
    make
    make strip
}

package() {
    make prefix=/usr DESTDIR=$ROOT install
}
