#!/bin/sh
NAME="libarchive"
RELEASE="4"
VERSION="3.7.0"
SOURCES="https://github.com/libarchive/libarchive/releases/download/v$VERSION/libarchive-$VERSION.tar.xz"
SHA256SUM="44729a0cc3b0b0be6742a9873d25e85e240c9318f5f5ebf2cca6bc84d7b91b07  libarchive-3.7.0.tar.xz"
DESCRIPTION="Multi-format archive and compression library"

build() {
    cd libarchive-$VERSION
    # Taken from BLFS r11.2-232 
    sed '/linux\/fs\.h/d' -i libarchive/archive_read_disk_posix.c
    ./configure --prefix=/usr --disable-static
    make -j$(nproc)
}

install() {
    cd libarchive-$VERSION
    make DESTDIR=$ROOT install
    sed -i '/Libs.private: /s|$| -liconv|' "$ROOT/usr/lib/pkgconfig/libarchive.pc"
    sed -i '/Requires.private:/d'          "$ROOT/usr/lib/pkgconfig/libarchive.pc"
}

