#!/bin/sh
NAME="libarchive"
RELEASE="4"
VERSION="3.8.4"
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/libarchive/libarchive/releases/download/v$VERSION/libarchive-$VERSION.tar.xz"
DEPENDS="openssl expat bzip2 xz-utils zlib libzstd linux-headers"
SHA256SUM="c7b847b57feacf5e182f4d14dd6cae545ac6843d55cb725f58e107cdf1c9ad73"
DESCRIPTION="Multi-format archive and compression library"

build() {
    cd libarchive-$VERSION
    # Taken from BLFS r11.2-232 
    sed '/linux\/fs\.h/d' -i libarchive/archive_read_disk_posix.c
    kpkgConfigure --prefix=/usr --disable-static --without-xml2
    make -j$(nproc)
}

package() {
    cd libarchive-$VERSION
    make DESTDIR=$ROOT install
    sed -i '/Libs.private: /s|$| -liconv|' "$ROOT/usr/lib/pkgconfig/libarchive.pc"
    sed -i '/Requires.private:/d'          "$ROOT/usr/lib/pkgconfig/libarchive.pc"
}

