#!/bin/sh
NAME="libjpeg-turbo"
RELEASE="1"
VERSION="3.0.0"
SOURCES="https://downloads.sourceforge.net/project/libjpeg-turbo/3.0.0/libjpeg-turbo-3.0.0.tar.gz"
SHA256SUM="c77c65fcce3d33417b2e90432e7a0eb05f59a7fff884022a9d931775d583bfaa  libjpeg-turbo-3.0.0.tar.gz"
DESCRIPTION="library for jpeg"

build() {
	mkdir build
	cmake \
	-DCMAKE_INSTALL_PREFIX=/usr  \
	-DCMAKE_INSTALL_LIBDIR=/usr/lib \
	-DENABLE_STATIC=OFF \
	-G Ninja \
	-B build
	ninja -C build
}

install() {
	DESTDIR="$ROOT" ninja -C build install 

}
