#!/bin/sh
NAME="libjpeg-turbo"
RELEASE="1"
VERSION="3.1.2"
SOURCES="https://downloads.sourceforge.net/project/libjpeg-turbo/3.0.1/libjpeg-turbo-3.0.1.tar.gz"
BUILD_DEPENDS="cmake ninja"
DEPENDS=""
SHA256SUM="22429507714ae147b3acacd299e82099fce5d9f456882fc28e252e4579ba2a75"
DESCRIPTION="library for jpeg"

build() {
	mkdir build
	cmake \
	-DCMAKE_INSTALL_PREFIX=/usr  \
	-DCMAKE_INSTALL_LIBDIR=/usr/lib \
	-DENABLE_STATIC=OFF \
	-G Ninja \
	-B build
	ninja -C build
}

package() {
	DESTDIR="$ROOT" ninja -C build install 

}
