#!/bin/sh
NAME="libwacom"
RELEASE="1"
VERSION="2.12.2"
SOURCES="https://github.com/linuxwacom/libwacom/releases/download/libwacom-$VERSION/libwacom-$VERSION.tar.xz"
BUILD_DEPENDS="meson"
DEPENDS="libgudev libxml2 libevdev"
SHA256SUM="c8319c40c70edd05d1839c0d3f449c23bdc90cd1f0d819bd0c1ec7c00b117700"
DESCRIPTION="Library for Wacom tablets"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Dtests=disabled \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
