#!/bin/sh
NAME="libwacom"
RELEASE="1"
VERSION="2.17.0"
SOURCES="https://github.com/linuxwacom/libwacom/releases/download/libwacom-$VERSION/libwacom-$VERSION.tar.xz"
BUILD_DEPENDS="meson"
DEPENDS="libgudev libxml2 libevdev"
SHA256SUM="acd18121441bbc00fc5c881fca08a33319ab814b798eac8d0be6354923f8fb08"
DESCRIPTION="Library for Wacom tablets"

build() {
    meson setup \
    --prefix=/usr \
    --buildtype=release \
    -Dtests=disabled \
    build
    ninja -C build
}

package() {
    DESTDIR="$ROOT" ninja -C build install
}
