#!/bin/sh
NAME="shadow"
RELEASE="3"
VERSION="4.14.2"
SOURCES="https://github.com/shadow-maint/shadow/releases/download/4.14.2/shadow-4.14.2.tar.xz"
DEPENDS="libxcrypt linux-pam libbsd"
SHA256SUM="25df30589d2e31aaff14576d03f980bb578e6d446891da6d24de1e5a09a38949"
DESCRIPTION="Shadow utils"

build() {
    kpkgConfigure  --disable-static \
                 --sysconfdir=/etc \
                 --with-libpam
    make
}

package() {
    make exec_prefix=/usr DESTDIR=$ROOT install
    sed -i 's/account.*/account         include         system-account/g' "$ROOT/etc/pam.d/su"
    rm -f $ROOT/etc/pam.d/login
  }

postinstall() {
   pwconv
}
