#!/bin/sh
NAME="shadow"
RELEASE="3"
VERSION="4.14.3"
SOURCES="https://github.com/shadow-maint/shadow/releases/download/4.14.3/shadow-4.14.3.tar.xz"
BUILD_DEPENDS="pkgconf gmake"
DEPENDS="libxcrypt linux-pam libbsd"
SHA256SUM="6969279236fe3152768573a38c9f83cb9ca109851a5a990aec1fc672ac2cfcd2"
DESCRIPTION="Shadow utils"

build() {
    kpkgConfigure  --disable-static \
                 --sysconfdir=/etc \
                 --with-libpam
    make
}

package() {
    make exec_prefix=/usr DESTDIR=$ROOT install
    sed -i 's/account.*/account         include         system-account/g' "$ROOT/etc/pam.d/su"
    rm -f $ROOT/etc/pam.d/login
  }

postinstall() {
   pwconv
}
