#!/bin/sh
NAME="shadow"
RELEASE="3"
VERSION="4.15.1"
SOURCES="https://github.com/shadow-maint/shadow/releases/download/4.15.1/shadow-4.15.1.tar.xz"
BUILD_DEPENDS="pkgconf gmake"
DEPENDS="libxcrypt linux-pam libbsd"
SHA256SUM="bb5f70639a0581f9d626f227ce45b31ac137daa7c451c0f672ce14f2731a96ee"
DESCRIPTION="Shadow utils"

build() {
    kpkgConfigure  --disable-static \
                 --sysconfdir=/etc \
                 --with-libpam
    make
}

package() {
    make exec_prefix=/usr DESTDIR=$ROOT install
    sed -i 's/account.*/account         include         system-account/g' "$ROOT/etc/pam.d/su"
    rm -f $ROOT/etc/pam.d/login
  }

postinstall() {
   pwconv
}
