#!/bin/sh
NAME="itstool"
RELEASE="1"
VERSION="2.0.7"
SOURCES="https://files.itstool.org/itstool/itstool-$VERSION.tar.bz2"
DEPENDS="python"
SHA256SUM="6b9a7cd29a12bb95598f5750e8763cee78836a1a207f85b74d8b3275b27e87ca  itstool-2.0.7.tar.bz2"
DESCRIPTION="Tool for translating XML documents with PO files"

build() {
    ./configure --prefix=/usr
    make
}

package() {
    make DESTDIR=$ROOT install
}
