#!/bin/sh
NAME="jp2a"
VERSION="1.0.7"
SOURCES="https://github.com/cslarsen/jp2a/archive/refs/tags/v$VERSION.tar.gz"
SHA256SUM="e509d8bbf9434afde5c342568b21d11831a61d9942ca8cb1633d4295b7bc5059  v1.0.7.tar.gz"
DESCRIPTION="Converts jpg images to ASCII"
build() {
    [ ! -d "jp2a-$VERSION" ] && tar -xvf v$VERSION.tar.gz
    cd jp2a-$VERSION || exit  1
    autoreconf -vi
    ./configure --prefix=/usr
    make
    make DESTDIR=$ROOT install
}
