#!/bin/sh
NAME="docbook-xsl"
RELEASE="1"
VERSION="1.79.2"
SOURCES="https://github.com/docbook/xslt10-stylesheets/releases/download/release/$VERSION/docbook-xsl-$VERSION.tar.bz2"
SHA256SUM="316524ea444e53208a2fb90eeb676af755da96e1417835ba5f5eb719c81fa371"
DEPENDS="libxml2 libxslt docbook-xml"
DESCRIPTION="XML stylesheets for Docbook-xml transformations"

# Huge thanks to BLFS that had this batshit insane installation process figured out

package() {

    install -v -m755 -d $DESTDIR/usr/share/xml/docbook/xsl-stylesheets-$VERSION

    cp -v -R VERSION assembly common eclipse epub epub3 extensions fo       \
            highlighting html htmlhelp images javahelp lib manpages params  \
            profiling roundtrip slides template tests tools webhelp website \
            xhtml xhtml-1_1 xhtml5                                          \
        $DESTDIR/usr/share/xml/docbook/xsl-stylesheets-$VERSION

    ln -s VERSION $DESTDIR/usr/share/xml/docbook/xsl-stylesheets-$VERSION/VERSION.xsl

    install -v -m644 -D README \
                        $DESTDIR/usr/share/doc/docbook-xsl-$VERSION/README.txt
    install -v -m644    RELEASE-NOTES* NEWS* \
                        $DESTDIR/usr/share/doc/docbook-xsl-$VERSION
    rm -f $DESTDIR/etc/xml/docbook
}

postinstall() {
    if [ ! -d /etc/xml ]; then install -v -m755 -d /etc/xml; fi &&
if [ ! -f /etc/xml/catalog ]; then
    xmlcatalog --noout --create /etc/xml/catalog
fi &&

xmlcatalog --noout --add "rewriteSystem" \
           "http://docbook.sourceforge.net/release/xsl/1.79.2" \
           "/usr/share/xml/docbook/xsl-stylesheets-1.79.2" \
    /etc/xml/catalog &&

xmlcatalog --noout --add "rewriteURI" \
           "http://docbook.sourceforge.net/release/xsl/1.79.2" \
           "/usr/share/xml/docbook/xsl-stylesheets-1.79.2" \
    /etc/xml/catalog &&

xmlcatalog --noout --add "rewriteSystem" \
           "http://docbook.sourceforge.net/release/xsl/current" \
           "/usr/share/xml/docbook/xsl-stylesheets-1.79.2" \
    /etc/xml/catalog &&

xmlcatalog --noout --add "rewriteURI" \
           "http://docbook.sourceforge.net/release/xsl/current" \
           "/usr/share/xml/docbook/xsl-stylesheets-1.79.2" \
    /etc/xml/catalog
}
