name: Update Sums on Renovate PRs

on:
  workflow_call:
    inputs:
      runfiles:
        description: "Whitespace-separated list of run file paths to update"
        required: false
        type: string

jobs:
  update-sums:
    if: github.event_name == 'workflow_call' || contains(github.head_ref, 'renovate/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Determine target runfiles
        id: files
        run: |
          set -euo pipefail
          TARGETS="${{ inputs.runfiles }}"
          echo "targets<<EOF" >> $GITHUB_OUTPUT
          printf "%s\n" $TARGETS >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update sums (targeted)
        if: steps.files.outputs.targets != ''
        run: |
          while IFS= read -r f; do
            [ -z "$f" ] && continue
            echo "Updating sums for $f"
            node scripts/update-sums.mjs "${f%$'\r'}" || echo "update-sums failed for $f"
          done << 'EOF'
          ${{ steps.files.outputs.targets }}
          EOF
      
      - name: Update sums (fallback all)
        if: steps.files.outputs.targets == ''
        run: |
          node scripts/update-sums.mjs || echo "update-sums failed"

      - name: Commit and push changes
        run: |
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -am "chore: update checksums after version bump" || true
            BRANCH="${{ github.head_ref || github.ref_name }}"
            git push origin "HEAD:${BRANCH}"
          fi


