#!/bin/sh
NAME="libblockdev"
RELEASE="2"
VERSION="3.4.0"
BUILD_DEPENDS="gmake"
SOURCES="https://github.com/storaged-project/libblockdev/releases/download/$VERSION-1/libblockdev-$VERSION.tar.gz"
DEPENDS="glib keyutils cryptsetup lvm2 e2fsprogs eudev util-linux libbytesize gobject-introspection libnvme"
SHA256SUM="SKIP"
DESCRIPTION="libblockdev"

build() {
    # from BLFS
    kpkgConfigure --prefix=/usr  \
            --sysconfdir=/etc  \
            --with-python3     \
            --without-escrow   \
            --without-gtk-doc  \
            --without-lvm_dbus \
            --without-nvdimm   \
            --without-tools
    make
}

package() {
    make DESTDIR=$ROOT install
}
