#!/bin/sh
NAME="nss"
RELEASE="1"
VERSION="3.96.1"
SOURCES="https://archive.mozilla.org/pub/security/nss/releases/NSS_3_96_1_RTM/src/nss-3.96.1.tar.gz bundle.sh certdata2pem.py"
BUILD_DEPENDS="python"
EXTRACT="false"
DEPENDS="nspr sqlite p11-kit zlib"
DEPENDS_CA_CERTIFICATES_MOZILLA+="ca-certificates-utils"
SHA256SUM="c51e89f6fbb06163f4302e368eeb672d748b52d583948bdb15ef1b069237a496 SKIP SKIP"
DESCRIPTION="network stuff"

prepare() {
  bsdtar -xf nss-$VERSION.tar.gz
  cd nss-$VERSION
  mkdir -p certs
  cd certs
  for i in certdata.txt nssckbi.h; do
    ln -srf ../nss/lib/ckfw/builtins/$i $i
  done
}



build() {
  cd nss-$VERSION/certs
  
  # Scripts from Arch Linux: https://gitlab.archlinux.org/archlinux/packaging/packages/nss/-/tree/3.98-1?ref_type=tags
  python ../../certdata2pem.py || exit 1
  
  cd ..
  sh ../bundle.sh || exit 1

  cd nss
  if [ "$(uname -m)" = "x86_64" ]; then
    export USE_64=1
  else
    export USE_64=0
  fi

  # Taken from BLFS
  make -j$(nproc) BUILD_OPT=1                  \
    NSPR_INCLUDE_DIR=/usr/include/nspr  \
    USE_SYSTEM_ZLIB=1                   \
    ZLIB_LIBS=-lz                       \
    NSS_ENABLE_WERROR=0                 \
    NSS_USE_SYSTEM_SQLITE=1             \
    USE_64=$USE_64
}

package() {
  
   cd nss-$VERSION
    
   DIST=$(basename dist/Linux*.OBJ)
   # From https://gitlab.archlinux.org/archlinux/packaging/packages/nss/-/commit/314bb55c3ab50a9951993c885e6d5df56f5b13a6
   nsprver="$(pkg-config --modversion nspr)"
   libdir=/usr/lib includedir=/usr/include/nss

  sed nss/pkg/pkg-config/nss.pc.in \
    -e "s,%prefix%,/usr,g" \
    -e "s,%exec_prefix%,\${prefix},g" \
    -e "s,%libdir%,$libdir,g" \
    -e "s,%includedir%,$includedir,g" \
    -e "s,%NSPR_VERSION%,$nsprver,g" \
    -e "s,%NSS_VERSION%,$VERSION,g" |
    install -Dm644 /dev/stdin "$DESTDIR$libdir/pkgconfig/nss.pc"

  ln -s nss.pc "$DESTDIR$libdir/pkgconfig/mozilla-nss.pc"

  install -Dt "$DESTDIR$libdir" dist/$DIST/lib/*.so

  { read vmajor; read vminor; read vpatch; } \
    < <(awk '/#define.*NSS_V(MAJOR|MINOR|PATCH)/ {print $3}' nss/lib/nss/nss.h)

  sed nss/pkg/pkg-config/nss-config.in \
    -e "s,@prefix@,/usr,g" \
    -e "s,@exec_prefix@,/usr,g" \
    -e "s,@libdir@,$libdir,g" \
    -e "s,@includedir@,$includedir,g" \
    -e "s,@MOD_MAJOR_VERSION@,$vmajor,g" \
    -e "s,@MOD_MINOR_VERSION@,$vminor,g" \
    -e "s,@MOD_PATCH_VERSION@,$vpatch,g" |
    install -D /dev/stdin "$DESTDIR/usr/bin/nss-config"
    
  cd dist/$DIST/bin
  for i in *util shlibsign signtool signver ssltap; do
    install -Dt "$DESTDIR/usr/bin" \
        "$i"
  done
  cd -

  install -Dt "$DESTDIR$includedir" -m644 dist/public/nss/*.h

  # Replace built-in trust with p11-kit connection
  ln -s pkcs11/p11-kit-trust.so "$DESTDIR$libdir/p11-kit-trust.so"
  ln -sf p11-kit-trust.so "$DESTDIR$libdir/libnssckbi.so"
}

package_ca_certificates_mozilla() {
    cd nss-$VERSION
    install -Dm644 ca-bundle.trust.p11-kit \
        "$DESTDIR/usr/share/ca-certificates/trust-source/mozilla.trust.p11-kit"
}
