#!/bin/sh
NAME="vivaldi"
RELEASE="1"
VERSION="6.2.3105.48-1"
SOURCES="https://downloads.vivaldi.com/stable/vivaldi-stable_$VERSION_amd64.deb"
DEPENDS="alsa-lib desktop-file-utils gtk3 hicolor-icon-theme libnotify cups nss"
SHA256SUM="2ecc9e5fe9cf94eb4c096bf566ee3a399ef2326f5f7aac8647bdec680c0cd525  vivaldi-stable_6.2.3105.48-1_amd64.deb"
DESCRIPTION="An advanced browser made with the power user in mind"

prepare() {
    bsdtar -xf *.deb
} 

build() {
    :
}

package() {
    tar -xf "data.tar.xz"
    mv etc $ROOT
    mv usr $ROOT
    mv opt $ROOT
   
    # From the vivaldi PKGBUILD 
    # https://gitlab.archlinux.org/archlinux/packaging/packages/vivaldi/-/blob/main/PKGBUILD?ref_type=heads

    # install icons
    for res in 16 22 24 32 48 64 128 256; do
        install -Dm644 "$ROOT/opt/vivaldi/product_logo_${res}.png" \
            "$ROOT/usr/share/icons/hicolor/${res}x${res}/apps/vivaldi.png"
    done

    # install global icon in case hicolor theme gets bypassed
    install -Dm644 "$ROOT/opt/vivaldi/product_logo_256.png" \
        "$ROOT/usr/share/pixmaps/vivaldi.png"

}
