#!/bin/sh
NAME="vivaldi"
RELEASE="1"
VERSION="6.2.3105.54-1"
SOURCES="https://downloads.vivaldi.com/stable/vivaldi-stable_$VERSION_amd64.deb"
DEPENDS="alsa-lib liberation-fonts desktop-file-utils gtk3 hicolor-icon-theme libnotify cups nss"
SHA256SUM="cf9fe5f783058691d12ef6d4752c05492b779f6d663d92736a762e81779c2c59"
DESCRIPTION="An advanced browser made with the power user in mind"

prepare() {
    bsdtar -xf *.deb
} 

package() {
    tar -xf "data.tar.xz"
    mv etc $ROOT
    mv usr $ROOT
    mv opt $ROOT
   
    # From the vivaldi PKGBUILD 
    # https://gitlab.archlinux.org/archlinux/packaging/packages/vivaldi/-/blob/main/PKGBUILD?ref_type=heads

    # install icons
    for res in 16 22 24 32 48 64 128 256; do
        install -Dm644 "$ROOT/opt/vivaldi/product_logo_${res}.png" \
            "$ROOT/usr/share/icons/hicolor/${res}x${res}/apps/vivaldi.png"
    done

    # install global icon in case hicolor theme gets bypassed
    install -Dm644 "$ROOT/opt/vivaldi/product_logo_256.png" \
        "$ROOT/usr/share/pixmaps/vivaldi.png"

}
