#!/bin/sh
NAME="sbc"
RELEASE="1"
VERSION="2.1"
BUILD_DEPENDS="gmake"
SOURCES="https://www.kernel.org/pub/linux/bluetooth/sbc-$VERSION.tar.xz"
SHA256SUM="426633cabd7c798236443516dfa8335b47e004b0ef37ff107e0c7ead3299fcc2"
DESCRIPTION="Bluetooth low-complexity, subband codec (SBC) library"

build() {
    kpkgConfigure --prefix=/usr    \
                --disable-static \
                --disable-tester
    make
}

package() {
    make DESTDIR=$ROOT install
}
