#!/bin/sh
NAME="hwdata"
RELEASE="1"
VERSION="0.388"
SOURCES="https://github.com/vcrhonek/hwdata/archive/refs/tags/v$VERSION.tar.gz"
BUILD_DEPENDS="gmake"
DEPENDS=""
SHA256SUM="a1b4a2bd227f491d30e88feaef9407443b43d9ee42237ef1789d06e11f09d86e"
DESCRIPTION="hwdata contains various hardware identification and configuration data, such as the pci.ids and usb.ids databases."

build() {
    kpkgConfigure --prefix=/usr
    sed -i 's/-T//g' -i Makefile
}

package() {
    make DESTDIR=$ROOT install
}
