#!/bin/sh
NAME="hwdata"
RELEASE="1"
VERSION="0.376"
SOURCES="https://github.com/vcrhonek/hwdata/archive/refs/tags/v$VERSION.tar.gz"
BUILD_DEPENDS="gmake"
DEPENDS=""
SHA256SUM="48d85dbf05650b2c382ffaadeb601cac1650f5a34ee5c452df8021af988ea090"
DESCRIPTION="hwdata contains various hardware identification and configuration data, such as the pci.ids and usb.ids databases."

build() {
    ./configure --prefix=/usr
    sed -i 's/-T//g' -i Makefile
}

package() {
    make DESTDIR=$ROOT install
}
