#!/bin/sh
NAME="libxdamage"
RELEASE="1"
VERSION="1.1.6"
SOURCES="https://www.x.org/releases/individual/lib/libXdamage-$VERSION.tar.xz"
SHA256SUM="52733c1f5262fca35f64e7d5060c6fcd81a880ba8e1e65c9621cf0727afb5d11"
DEPENDS="libxfixes"
BUILD_DEPENDS="xorgproto"
DESCRIPTION="libxdamage"

build() {
    ./configure \
        --sysconfdir=/etc \
        --prefix=/usr \
        --disable-static
    make
}

package() {
    make DESTDIR=$ROOT install
}
